### ISSUE TITLE
CMD_TCPCMDS_ADD aren't executed

### ISSUE THREAD

**Issue by tomcao** [linux-test-project/ltp#100]
I try to run the network test, it happened that CMD_TCPCMDS_ADD (addtional TCP/IP commands tests) is not executed.
In /opt/ltp/testscripts/networktests.sh:

```
 92 if [ $(($CMD&$CMD_TCPCMDS_ADD)) -ne 0 ]; then
 93     echo "Entered tcp cmds addition"
 94     cat  ${LTPROOT}/runtest/tcp_cmds_addition >> $CMDFILE
 95 fi
```
The value of $(($CMD&$CMD_TCPCMDS_ADD) is always 0, so these tests are not written to $CMDFILE, which make the addtional tests are not executed.

**Comment by metan-ucw** [comment]
The file has been removed in fddb4f3. Use latest LTP where the network testcases could be executed via ```runltp``` just like any other tests.

**Comment by tomcao** [comment]
@metan-ucw Thanks in advance.
