### ISSUE TITLE
io_uring02 failed: EOPNOTSUPP

### ISSUE THREAD

**Issue by mathslimin** [linux-test-project/ltp#1007]
tst_test.c:1526: TINFO: Timeout per run is 0h 02m 30s
io_uring02.c:213: TBROK: io_uring_setup() failed: EOPNOTSUPP (95)

Summary:
passed   0
failed   0
broken   1
skipped  0
warnings 0

**Comment by pevik** [comment]
`EOPNOTSUPP` should endup as `TCONF` => trivial fix.

**Comment by coolgw** [comment]
Test on latest upstream, the test result is good, so could we close this issue?
/home/ltp/testcases/kernel/syscalls/io_uring # ./io_uring02
tst_test.c:1558: TINFO: Timeout per run is 0h 00m 30s
io_uring02.c:192: TINFO: IOSQE_ASYNC is supported
io_uring02.c:205: TPASS: Write outside chroot failed as expected: ENOENT (2)

Summary:
passed   1
failed   0
broken   0
skipped  0
warnings 0

**Comment by metan-ucw** [comment]
@coolgw not really, the test should be fixed to be able to handle EOPNOTSUPP from the io_uring().

**Comment by pevik** [comment]
@coolgw `safe_io_uring_init()` is the right place to add check for `errno == EOPNOTSUPP` and quit with `TCONF` instead of `TBROK` (see the meaning in https://github.com/linux-test-project/ltp/wiki/C-Test-API#12-basic-test-interface).

**Comment by coolgw** [comment]
Thanks @metan-ucw @pevik , i will have a look on it.

**Comment by coolgw** [comment]
patch email done.
