### ISSUE TITLE
io_uring make fail

### ISSUE THREAD

**Issue by mathslimin** [linux-test-project/ltp#1008]
cd testcases/kernel/syscalls/io_uring/
make
../../../../include/mk/env_pre.mk:92: /tmp/hulk/ltp/include/mk/features.mk: No such file or directory
make: *** No rule to make target '/tmp/hulk/ltp/include/mk/features.mk'.  Stop

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp#quick-guide-to-running-the-tests
```
$ make autotools
$ ./configure
```
It's actually the first instruction in our doc.
