### ISSUE TITLE
hello, I meet a problem:make test failed about testing ltp.The fs_bind test is failed. What is the reason? Is there any way to modify it？Thanks

### ISSUE THREAD

**Issue by Wjjoye** [linux-test-project/ltp#1011]
hello, I meet a problem:make test failed about testing ltp.The fs_bind test is failed. What is the reason? Is there any way to modify it？Thanks
Here is the print information：
......
COMMAND:    /opt/ltp/bin/ltp-pan   -e -S   -a 1734     -n 1734 -p -f /tmp/ltp-PS7vkh2NHY/alltests -l /opt/ltp/results/sprd.result  -C /opt/ltp/output/LTP_RUN_ON-sprd.result.failed -T /opt/ltp/output/LTP_RUN_ON-sprd.result.tconf
INFO: Restricted to fs_bind_cloneNS06.sh
LOG File: /opt/ltp/results/sprd.result
FAILED COMMAND File: /opt/ltp/output/LTP_RUN_ON-sprd.result.failed
TCONF COMMAND File: /opt/ltp/output/LTP_RUN_ON-sprd.result.tconf
Running tests.......
<<<test_start>>>
tag=fs_bind_cloneNS06_sh stime=1675727480
cmdline="fs_bind_cloneNS06.sh"
contacts=""
analysis=exit
<<<test_output>>>
incrementing stop
fs_bind_cloneNS06 1 TINFO: timeout per run is 0h 5m 0s
fs_bind_cloneNS06 1 TPASS: mount --bind sandbox sandbox passed as expected
fs_bind_cloneNS06 1 TPASS: mount --make-private sandbox passed as expected
fs_bind_cloneNS06 1 TINFO: cloneNS: namespace with shared point bind mounted within the same directory
fs_bind_cloneNS06 1 TPASS: mount --bind dir1 dir1 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --make-rshared dir1 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --rbind dir1 dir2 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --make-rslave dir2 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --make-rshared dir2 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --rbind dir2 dir3 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --make-rslave dir3 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --make-rshared dir3 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --rbind dir3 dir4 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --make-rslave dir4 passed as expected
fs_bind_cloneNS06 1 TPASS: mount --rbind disk1 dir1/x passed as expected
fs_bind_cloneNS06 1 TPASS: Check propagation dir1/x dir2/x dir3/x dir4/x
fs_bind_cloneNS06 1 TPASS: mount --rbind disk2 dir2/x/a passed as expected
fs_bind_cloneNS06 1 TPASS: Check no propagation dir1/x/a dir2/x/a
fs_bind_cloneNS06 1 TPASS: Check propagation dir2/x/a dir3/x/a dir4/x/a
fs_bind_cloneNS06 1 TFAIL: Check propagation in mnt namespace dir1/x dir2/x dir3/x dir4/x:
fs_bind_cloneNS06 1 TFAIL: "dir1/x" "dir2/x" differ:\n
fs_bind_cloneNS06 1 TPASS: Check no propagation in mnt namespace dir1/x/a dir2/x/a
fs_bind_cloneNS06 1 TPASS: Check propagation in mnt namespace disk2 dir2/x/a dir3/x/a dir4/x/a
fs_bind_cloneNS06 1 TPASS: ns_exec 1909 mnt mount --rbind /tmp/ltp-PS7vkh2NHY/LTP_fs_bind_cloneNS06.SSC9x4yabh/sandbox/disk3 /tmp/ltp-PS7vkh2NHY/LTP_fs_bind_cloneNS06.SSC9x4yabh/sandbox/dir3/x/b passed as expected
fs_bind_cloneNS06 1 TPASS: Check no propagation in mnt namespace dir1/x/b dir3/x/b
fs_bind_cloneNS06 1 TPASS: Check no propagation in mnt namespace dir2/x/b dir3/x/b
fs_bind_cloneNS06 1 TPASS: Check propagation in mnt namespace dir3/x/b dir4/x/b
fs_bind_cloneNS06 1 TPASS: ns_exec 1909 mnt mount --rbind /tmp/ltp-PS7vkh2NHY/LTP_fs_bind_cloneNS06.SSC9x4yabh/sandbox/disk4 /tmp/ltp-PS7vkh2NHY/LTP_fs_bind_cloneNS06.SSC9x4yabh/sandbox/dir4/x/c passed as expected
fs_bind_cloneNS06 1 TPASS: Check no propagation in mnt namespace dir1/x/c dir4/x/c
fs_bind_cloneNS06 1 TPASS: Check no propagation in mnt namespace dir2/x/c dir4/x/c
fs_bind_cloneNS06 1 TPASS: Check no propagation in mnt namespace dir3/x/c dir4/x/c
fs_bind_cloneNS06 1 TPASS: Check no propagation dir1/x/b dir3/x/b
fs_bind_cloneNS06 1 TPASS: Check no propagation dir2/x/b dir3/x/b
fs_bind_cloneNS06 1 TPASS: Check propagation dir3/x/b dir4/x/b
fs_bind_cloneNS06 1 TPASS: Check propagation disk3 dir3/x/b
fs_bind_cloneNS06 1 TPASS: Check no propagation disk4 dir4/x/c
fs_bind_cloneNS06 1 TPASS: Check propagation dir1/x/c dir2/x/c dir3/x/c dir4/x/c
fs_bind_cloneNS06 1 TPASS: umount dir3/x/b passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir3/x/a passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir2/x/a passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir2/x passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir1/x passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir4 passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir3 passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir2 passed as expected
fs_bind_cloneNS06 1 TPASS: umount dir1 passed as expected

Summary:
passed   42
failed   2
broken   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=1 termination_type=exited termination_id=1 corefile=no
cutime=36 cstime=58
<<<test_end>>>
INFO: ltp-pan reported some tests FAIL
LTP Version: 20220121

       ###############################################################

            Done executing testcases.
            LTP Version:  20220121
       ###############################################################

fs_bind_cloneNS06 1 TFAIL: Check propagation in mnt namespace dir1/x dir2/x dir3/x dir4/x:
fs_bind_cloneNS06 1 TFAIL: "dir1/x" "dir2/x" differ:\n

Can you help me look at this failure.

fs_bind_move09.sh、fs_bind_rbind21.sh、fs_bind_rbind35.sh、fs_bind_rbind36.sh、fs_bind_rbind39.sh、fs_bind_cloneNS06.sh are are similar errors

**Comment by Wjjoye** [comment]
Hello, is there any progress in the analysis of this issue?

**Comment by Wjjoye** [comment]
Hello, is there any progress in the analysis of this issue?

**Comment by metan-ucw** [comment]
The failure looks like the kernel failed to propagate changes to rbind mount, no idea why you have to debug the failure yourself to figure that out.

**Comment by Wjjoye** [comment]
@metan-ucw 
Can this error be ignored? Can we not pay attention to it? Can we not test this kind of case?
