### ISSUE TITLE
Add scheduller thread starvation reproducer?

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#1023]
https://lwn.net/ml/linux-kernel/9fd2c37a05713c206dcbd5866f67ce779f315e9e.camel@gmx.de/

**Comment by coolgw** [comment]
https://patchwork.ozlabs.org/project/ltp/patch/20230321110337.22970-1-wegao@suse.com/

**Comment by Martchus** [comment]
Looks like this has already been implemented via 6ac00ddcd4.

**Comment by coolgw** [comment]
> https://patchwork.ozlabs.org/project/ltp/patch/20230321110337.22970-1-wegao@suse.com/

https://patchwork.ozlabs.org/project/ltp/patch/20230507142209.17815-1-wegao@suse.com/  v2 accept in LTP.

**Comment by pevik** [comment]
Wei, please next time add to your git commit message

```
Implements: https://github.com/linux-test-project/ltp/issues/1023
```

This will close the ticket automatically after patchset is merged.
