### ISSUE TITLE
Syscall：Failed to acquire device

### ISSUE THREAD

**Issue by Bad916** [linux-test-project/ltp#1025]
When testing syscall, there is a low probability of “Failed to acquire device”occurring.
![image](https://user-images.githubusercontent.com/39617479/226894290-419a46f5-2f38-4d56-8631-fa4444709fcc.png)

**Comment by xuyang0410** [comment]
Whic system do you use?  Can you attach the "ls /dev/loop*" and "ls /dev/block/loop*" output?

**Comment by Bad916** [comment]
> Which system do you use? Can you attach the "ls /dev/loop*" and "ls /dev/block/loop*" output?

1.We're using Android 13，linux kernel 5.15
2.ls: /dev/loop: /dev/loop-control
3.
![image](https://user-images.githubusercontent.com/39617479/227503845-b171608a-7818-4539-8bf7-b718d2246eaa.png)

**Comment by Bad916** [comment]
![image](https://user-images.githubusercontent.com/39617479/227508009-93f4b7ea-59d4-4563-bb39-e12837047846.png)
But this is not a matter of stable recurrence，it’s occasionality matter

**Comment by xuyang0410** [comment]
From the above log, /dev/block/loop40 exists and I guess it is not a  symbolic link.  It looks strange. Edward Liaw is planning to change ltp tst_device logic for loop device on android. He may know this failure's reason. @edliaw

**Comment by pevik** [comment]
There is a patchset trying to fix it: https://patchwork.ozlabs.org/project/ltp/list/?series=347760&state=*

Also, for AOSP it's better to use their fork https://android.googlesource.com/platform/external/ltp/
(noted at https://github.com/linux-test-project/ltp/wiki/Supported-kernel,-libc,-toolchain-versions#14-supported-libc).

**Comment by Bad916** [comment]
> There is a patchset trying to fix it: https://patchwork.ozlabs.org/project/ltp/list/?series=347760&state=*
> 
> Also, for AOSP it's better to use their fork https://android.googlesource.com/platform/external/ltp/ (noted at https://github.com/linux-test-project/ltp/wiki/Supported-kernel,-libc,-toolchain-versions#14-supported-libc).

Thanks，and could you tell me when will this patchset be merged into the master？

**Comment by pevik** [comment]
Merged 42ce90d8c5d80f0e629388204bbd54b108d423f2 (and 3 patches before), closing.
If the problem persists, feel free to open, but beware only @edliaw will be able to do anything about it.
