### ISSUE TITLE
asapi_02 case fails on older firewalld (1.2.1)

### ISSUE THREAD

**Issue by xuyang0410** [linux-test-project/ltp#1026]
When I update firewalld version to 1.2.1, then asapi02 case fails as below:

asapi_02    1  TBROK  :  asapi_02.c:176: ICMP6_FILTER_SETPASS s 20 f 20: recv all timed out
asapi_02    2  TBROK  :  asapi_02.c:176: ICMP6_FILTER_SETPASS s 20 f 21: recv all timed out
asapi_02    3  TBROK  :  asapi_02.c:176: ICMP6_FILTER_SETBLOCK s 20 f 20: recv all timed out
asapi_02    4  TBROK  :  asapi_02.c:176: ICMP6_FILTER_SETBLOCK s 20 f 21: recv all timed out
asapi_02    5  TBROK  :  asapi_02.c:176: ICMP6_FILTER_PASSALL s 20: recv all timed out
asapi_02    6  TBROK  :  asapi_02.c:176: ICMP6_FILTER_PASSALL s 20: recv all timed out
asapi_02    7  TBROK  :  asapi_02.c:176: ICMP6_FILTER_BLOCKALL s 20: recv all timed out
asapi_02    8  TBROK  :  asapi_02.c:176: ICMP6_FILTER_BLOCKALL s 20: recv all timed out

Even I looks  [firewalld github](https://github.com/firewalld/firewalld/tree/v1.2.1) , but I can't figure out the reason. Does anybody give some advise?

**Comment by pevik** [comment]
Hard to tell what have changed, something by default on? Best would be to see from strace what exactly is being blocked and ask firewalld folks (they will want to know your previous version).
Also, they might ask you to update / test the latest version.
Test itself *could* have a bug (unlikely, but uses the old API, fails when running as root).

**Comment by xuyang0410** [comment]
Oh , thanks. I don't get some useful info from strace output. I  will submit a issue for firewalld forks.

**Comment by xuyang0410** [comment]
Oh, I have found the introduced commit [fix(nftables): drop invalid packets before zone dispatch](https://github.com/firewalld/firewalld/commit/dc972aedcae5ac05b53c5e903e55f4525e47c492)  and fix commit [fix(nftables): allow loopback packets before conntrack checks](https://github.com/firewalld/firewalld/commit/bc767151d6c36d610cebe756c52b0caf882d99b7).  But I am not understand why asapi_02  create invalid packet.

**Comment by pevik** [comment]
```
$ git tag --contains dc972aedcae5ac05b53c5e903e55f4525e47c492 # regression
v1.2.1
v1.2.2
v1.2.3

$ git tag --contains bc767151d6c36d610cebe756c52b0caf882d99b7 # fix
v1.3.0
```
I have no idea why asapi_02 create invalid packet, but I'd just filter out the test on older distros (with old firewalld). I'd even consider to backport bc767151d6c36d610cebe756c52b0caf882d99b7 to the distro.

**Comment by pevik** [comment]
I dared to rename the ticket, because although v1.2.1 is still quite new, given there are 3 more releases, I'd not call it newer.

**Comment by xuyang0410** [comment]
Since it is a firewalld issue instead of ltp issue, I think backport the fixed patch to distro is ok.  Also, I have send two patches to clean up this case with new api.
