### ISSUE TITLE
fcntl06 testcase is failing on RHEL

### ISSUE THREAD

**Issue by mahi657** [linux-test-project/ltp#1029]
fcntl06 test case is failing with below error on RHEL9 kernel(5.14*). 

**fcntl06     1  TCONF  :  fcntl06.c:109: system doesn't have LINUX_LOCK_FILE_REGION support**

I see in the test case file, there are restrictions mentioned for this feature,

RESTRICTIONS
Currently Linux kernel doesn't implement R_GETLK/R_SETLK facility, but this facility seems to be present in other standard flavours of Unix. Currently this program has all the testing done under "#ifdef LINUX_FILE_REGION_LOCK", when Linux implements the regions locking then, this testcase should be recompiled accordingly with the "ifdef" removed.

I didn't find this CONFIG_LOCK_FILE_REGION parameter in /boot/config-$(uname -r) file.
Is FILE_REGION_LOCK support available on any linux kernel by default?

**Comment by xuyang0410** [comment]
I found a twenty year old email that mentioned this R_GETLK/R_SETLK exists in IRIX  [Re: [LTP] fcntl06](https://sourceforge.net/p/ltp/mailman/message/7574937/). It never exist on linux. I guess we can removet this case.

**Comment by mahi657** [comment]
Thanks for the reply!
I will exclude this test case for now. 
Can we also remove this test case from upcoming LTP releases?

**Comment by xuyang0410** [comment]
I have sent a patch [syscalls/fcntl06: Remove R_GETLK/R_SETLK test case](https://patchwork.ozlabs.org/project/ltp/patch/1681092133-28614-1-git-send-email-xuyang2018.jy@fujitsu.com/) to remove this case.

**Comment by mahi657** [comment]
Thank You!
