### ISSUE TITLE
aio tests requires libaio and it's development packages for SLES15.4

### ISSUE THREAD

**Issue by priyama2** [linux-test-project/ltp#1030]
When ltp, aio are executed the test looks for libaio related packages, when still libaio packages are already available inside test environment.
Test Output: 

test requires libaio and it's development packages

-bash-4.4# rpm -qa  | grep libaio
libaio1-debuginfo-0.3.109-1.25.ppc64le
libaio-debugsource-0.3.109-1.25.ppc64le
libaio1-0.3.109-1.25.ppc64le
libaio-devel-0.3.109-1.25.ppc64le
-bash-4.4# uname -r
5.14.21-150400.22-default
-bash-4.4#

**Comment by pevik** [comment]
IMHO this report is invalid:
1. LTP does not depend on libaio-devel
2. libaio-devel is part of the distro

**Comment by pevik** [comment]
Could you be more specific what's wrong? Which test is failing?
BTW the issue subject is misleading.

**Comment by priyama2** [comment]
ltp-aiodio.part1 
-  aiocp testcase is failing


the test log is as follows:
http://9.3.111.30/LOGS/ltp-aiodio.part1

**Comment by pevik** [comment]
I don't see the content of the logs (connection timeouted). If it's sensitive, feel free to post it to my work email (see git log), otherwise post it here.

**Comment by priyama2** [comment]
Hi Petr,
Updating the logs of aio-stress here as follows:
Running tests.......
<<<test_start>>>
tag=ADS1000 stime=1682418318
cmdline="aio-stress -o2 -r4k -f1"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1137: TCONF: test requires libaio and its development packages
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=32 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=ADS1001 stime=1682418318
cmdline="aio-stress -o2 -r8k -f1"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1137: TCONF: test requires libaio and its development packages
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=32 corefile=no
cutime=0 cstime=0
<<<test_end>>>

But libaio rpm is there at system
libaio1-0.3.109-1.25.ppc64le
libaio-debugsource-0.3.109-1.25.ppc64le
libaio1-debuginfo-0.3.109-1.25.ppc64le
libaio-devel-0.3.109-1.25.ppc64le

**Comment by metan-ucw** [comment]
You have to re-run configure script and recompile LTP after installing previously missing devel libraries.
