### ISSUE TITLE
use fcntl07 with error

### ISSUE THREAD

**Issue by miyang111222** [linux-test-project/ltp#1032]
in testcases/kernel/syscalls/fcntl 
do ./fcntl07 with errror : exec(fcntl07, fcntl07, -T, 6) failed.  Errno No such file or directory [2]
do ./fcntl07 -T 0 or ./fcntl07 -T 1 or ./fcntl07 -T 2 is ok
do ./fcntl07 -T 3 will exit in 
	if (t_opt)
		exit(test_open(t_opt));
how to fix this question?

**Comment by metan-ucw** [comment]
See [README.md](https://github.com/linux-test-project/ltp/blob/master/README.md)
