### ISSUE TITLE
cgroup_fj_stress.sh, cn_pec.sh and memcg_failcnt.sh test cases are resulting in TBROK

### ISSUE THREAD

**Issue by mahi657** [linux-test-project/ltp#1035]
cgroup_fj_stress.sh, cn_pec.sh and memcg_failcnt.sh test cases are resulting in TBROK.

cgroup_fj_stress 1 TBROK: Test didn't report any results
cn_pec 1 TBROK: Test didn't report any results
memcg_failcnt 1 TBROK: Test didn't report any results

This issue is similar to #1033. 

After changing the test function parameter and test function itself to "do_test" from test, the tests are passing.

cgroup_fj_stress 1 TPASS: All done!
cn_pec 1 TPASS: All events detected
memcg_failcnt 3 TPASS: memory.failcnt is 37, > 0 as expected

**Comment by metan-ucw** [comment]
Can you send a patch to our mailing list?

**Comment by mahi657** [comment]
I have sent the patch to mailing list
