### ISSUE TITLE
tst_cgroup.c:802: TBROK: 'files' controller is unknown to LTP

### ISSUE THREAD

**Issue by LaberIScn** [linux-test-project/ltp#1038]
#tst_cgroup.c:802: TBROK: 'files' controller is unknown to LTP
##Description:Controller module below test cases are getting failed
`cgroup_regression_test 1 TINFO: timeout per run is 0h 5m 0s
cgroup_regression_test 1 TPASS: no kernel bug was found
cgroup_regression_test 2 TPASS: notify_on_release is inherited
cgroup_regression_test 3 TPASS: no kernel bug was found
cgroup_regression_test 4 TCONF: CONFIG_LOCKDEP is not enabled
cgroup_regression_test 5 TINFO: The '/tmp/ltp-GL3tjU1tdu/LTP_cgroup_regression_test.WEyFQGfolQ/cgroup' is not mounted, skipping umount
cgroup_regression_test 5 TPASS: no kernel bug was found
cgroup_regression_test 6 TPASS: no kernel bug was found
tst_cgroup.c:802: TBROK: 'files' controller is unknown to LTP
cgroup_regression_test 7 TBROK: 'tst_cgctl require' exited`
##Config 
LTP Version: 20230127

**Comment by metan-ucw** [comment]
Feel free to reopen with the requested information provided.
