### ISSUE TITLE
swapon01 doesn't take EPERM into account

### ISSUE THREAD

**Issue by richiejp** [linux-test-project/ltp#1091]
Test fails when swapon returns EPERM. This is the correct behavior when we don't have privs.

**Comment by pevik** [comment]
Well, `EPERM` is on other filesystems as well, tested on btrfs and ext4. I guess we would need root for the permission anyway.

> 
> ```
> .needs_root = 1,
> .mntpoint = MNTPOINT,
> .mount_device = 1,
> ```
 How about use `.all_filesystems = 1`. `tmpfs` is already detected on root, but I'd maybe check add for EPERM in libswap.c:59 => `TCONF`, just for sure.

**Comment by Martchus** [comment]
Does it really make sense to use `.all_filesystems = 1`? This would run the test on multiple filesystems but it suppose we just need *one* that works.

**Comment by pevik** [comment]
FYI working on this, more fixes are needed, eg. in tst_ioctl.c

**Comment by Martchus** [comment]
Ok, then I'll leave it to you. (By the way, is there some way to assign oneself to tickets. This would allow us to avoid having multiple people work on the same ticket in parallel.)

**Comment by metan-ucw** [comment]
Also I'm not sure that all_filesystems would work here, since unless user has passed a real block device, we would end up with a block device in a file on a tmpfs, that probably still does not work with swap. There is more problems with LTP tests with /tmp on tmpfs, the only proper solution is to pass `TMPDIR` env variable to LTP that points to a real filesystem.

**Comment by metan-ucw** [comment]
Also I guess that all that is actually needed is to add '.needs_root = 1,' to swapon01.c

**Comment by pevik** [comment]
@Martchus @richiejp Feel free to do it as you started on it. The cleanup I do is not relevant to this.

**Comment by Martchus** [comment]
Supposedly using `.needs_root = 1` is the simplest approach, indeed. I created a patch: https://patchwork.ozlabs.org/project/ltp/patch/20231011152900.4274-1-mkittler@suse.de/
