### ISSUE TITLE
failed: errno=EACCES(13): Permission denied

### ISSUE THREAD

**Issue by Ankita-020696** [linux-test-project/ltp#1099]
Hi,
I am facing permission issue with most of the tests from syscalls suite. Tried chown and chmod to fix but no help.

How do I fix this?

Thanks

**Comment by pevik** [comment]
With so sparse info we can hardly help you (why don't you post part of the output?). You can try run under root.

**Comment by Ankita-020696** [comment]
> With so sparse info we can hardly help you (why don't you post part of the output?). You can try run under root.

Hi,
I am running as a root stll there is a issue.
PFA
![Screenshot from 2023-11-16 15-41-18](https://github.com/linux-test-project/ltp/assets/59390480/12671cd2-5d88-4537-a832-14c25b178c1c)

Thanks

**Comment by metan-ucw** [comment]
There is no real information added in the last comment. You have to describe your environment, e.g. distribution/LTP version/etc and upload the logs of the failures.

**Comment by Ankita-020696** [comment]
> There is no real information added in the last comment. You have to describe your environment, e.g. distribution/LTP version/etc and upload the logs of the failures.

Sorry for delay it was issue with my system.

Thanks
