### ISSUE TITLE
Not able to find option to run ltp test for a specific filesystem

### ISSUE THREAD

**Issue by shivania2** [linux-test-project/ltp#1101]
I have mounted a filesystem on /mnt directory and wanted to run ltp test on the /mnt directory. I have explored the options provided in help and code also but didnot find any way to run ltp test on specific directory.

Is it possible to run ltp test for a filesystem mounted on /mnt directory?

**Comment by pevik** [comment]
```
export TMPDIR="/mnt"
```
Documented in our wiki: https://github.com/linux-test-project/ltp/wiki/User-Guidelines#1-library-environment-variables

**Comment by pevik** [comment]
NOTE: many tests use [`.all_filesystems = 1`](https://github.com/linux-test-project/ltp/wiki/C-Test-API#115-testing-with-a-block-device) or [`TST_ALL_FILESYSTEMS=1`](https://github.com/linux-test-project/ltp/wiki/Shell-Test-API#12-library-environment-variables-and-functions-for-shell), these test on loop device formatted with these filesystems: ext2, ext3, ext4, xfs, btrfs, vfat, exfat, ntfs, tmpfs ([the current list](https://github.com/linux-test-project/ltp/blob/master/lib/tst_supported_fs_types.c#L21-L30)).

**Comment by shivania2** [comment]
I wanted to test tarfs filesystem. We have made internal changes for it

**Comment by pevik** [comment]
If you add it also to the array https://github.com/linux-test-project/ltp/blob/master/lib/tst_supported_fs_types.c#L21-L30 you'll get covered the tests which use [.all_filesystems = 1](https://github.com/linux-test-project/ltp/wiki/C-Test-API#115-testing-with-a-block-device) or [TST_ALL_FILESYSTEMS=1](https://github.com/linux-test-project/ltp/wiki/Shell-Test-API#12-library-environment-variables-and-functions-for-shell) (otherwise they will not use `tarfs`.

**Comment by shivania2** [comment]
Ok. I will try this

**Comment by shivania2** [comment]
I have added the tarfs to array https://github.com/linux-test-project/ltp/blob/master/lib/tst_supported_fs_types.c#L21-L30. But while executing LTP test getting following error
`LTP_RUN_ON-2023_11_18-22h_27m_40s.output:217384:tst_supported_fs_types.c:91: TINFO: Kernel supports tarfs
LTP_RUN_ON-2023_11_18-22h_27m_40s.output:217385:tst_supported_fs_types.c:52: TINFO: mkfs.tarfs does not exist` . Any idea how to resolve this issue

**Comment by pevik** [comment]
If tarfs does not have `mkfs.tarfs` (I don't know myself), you should skip it for it similar way tmpfs skips it at least in lib/tst_supported_fs_types.c and lib/tst_mkfs.c.

**Comment by shivania2** [comment]
Thank You. I will add this change
