### ISSUE TITLE
pthread_barrier_destroy_2-1 should be dropped

### ISSUE THREAD

**Issue by jackiehjm** [linux-test-project/ltp#112]
After glibc-2.23, the algorithm of pthread_barrier is changed by: 

commit b02840bacdefde318d2ad2f920e50785b9b25d69 
Author: Torvald Riegel <triegel@redhat.com> 
Date: Wed Jun 24 14:37:32 2015 +0200 

    New pthread_barrier algorithm to fulfill barrier destruction requirements. 

    The previous barrier implementation did not fulfill the POSIX requirements 
    for when a barrier can be destroyed. Specifically, it was possible that 
    threads that haven't noticed yet that their round is complete still access 
    the barrier's memory, and that those accesses can happen after the barrier 
    has been legally destroyed. 
    The new algorithm does not have this issue, and it avoids using a lock 
    internally. 

After the change: 

+ /* Destroying a barrier is only allowed if no thread is blocked on it. 
+ Thus, there is no unfinished round, and all modifications to IN will 
+ have happened before us (either because the calling thread took part 
+ in the most recent round and thus synchronized-with all other threads 
+ entering, or the program ensured this through other synchronization). 
+ We must wait until all threads that entered so far have confirmed that 
+ they have exited as well. To get the notification, pretend that we have 
+ reached the reset threshold. */ 

But the test pthread_barrier_destroy_2-1 is to test destroying the barrier while child is waiting/blocked, it will return EBUSY before glibc-2.23, but after, it will never return if there is thread blocked. 

So I think the test is invalid anymore.

**Comment by metan-ucw** [comment]
Looks like glibc no longer implements recommended practice to return `EBUSY`. And the test possibly invokes undefined behaviour now. But it may be possibly useful on other POSIX platforms, I would expect BSD to follow the recommended practice.

I will try to figure out how to disable/rewrite the test so that it's skipped on newer glibc.

**Comment by jackiehjm** [comment]
Good to know that, thanks!

**Comment by richiejp** [comment]
Hi, I have posted a patch for review on the mailing list, which you can also see here: https://github.com/linux-test-project/ltp/compare/master...richiejp:posix_cond_barrier

**Comment by SamuelZOU** [comment]
I tested this case in glibc-2.28, but it still failed. In this version of glibc, the pthread_barrier_destroy() should have no return value of EBUSY.
