### ISSUE TITLE
Build failure while trying to build from source

### ISSUE THREAD

**Issue by DaanDeMeyer** [linux-test-project/ltp#1121]
```
In file included from /usr/include/linux/fs.h:19,
                 from /usr/include/linux/io_uring.h:11,
                 from ../include/lapi/io_uring.h:21,
                 from tst_fd.c:20:
/usr/include/sys/mount.h:35:3: error: expected identifier before numeric constant
   35 |   MS_RDONLY = 1,                /* Mount read-only.  */
      |   ^~~~~~~~~
```

**Comment by pevik** [comment]
Thanks, although we talked about it 2 days ago (https://lore.kernel.org/ltp/20240116003219.GD2535088@pevik/), Cyril added just one part of the fix: 12867c0d6428891e175e9abecbe466066a0e9720. I'm adding a rest tonight (wait for CI test):

https://github.com/pevik/ltp/commit/dcb038e34a68f7a287eac189c1b39399776e40f4
https://github.com/pevik/ltp/actions/runs/7561031650

@metan-ucw FYI

**Comment by pevik** [comment]
Actually closed by 9793c892d4d230ef0b78ea3dac9c78e6a4b48f2f.

**Comment by ai1urus** [comment]
Hi @pevik , i'm still encountering this compile error with 4.19 kernel and the latest master branch.
`GEN ltp-version.h
In file included from /usr/include/linux/io_uring.h:11:0,
                 from ../include/lapi/io_uring.h:21,
                 from tst_fd.c:21:
/usr/include/sys/mount.h:35:3: error: expected identifier before numeric constant
   MS_RDONLY = 1,  /* Mount read-only.  */
   ^
make[1]: *** [tst_fd.o] Error 1`

**Comment by ai1urus** [comment]
> Hi @pevik , i'm still encountering this compile error with 4.19 kernel and the latest master branch.
> 
> GEN ltp-version.h In file included from /usr/include/linux/io_uring.h:11:0, from ../include/lapi/io_uring.h:21, from tst_fd.c:21: /usr/include/sys/mount.h:35:3: error: expected identifier before numeric constant MS_RDONLY = 1, /* Mount read-only. */ ^ make[1]: *** [tst_fd.o] Error 1

Redefinition of MS_XXX macro. Just need to:
1. update glibc to latest version, or
2. wrap the enum definition in /usr/include/sys/mount.h like
`#ifndef MS_RDONLY
enum
{
  MS_RDONLY = 1,
  ...
}
#endif`

**Comment by ai1urus** [comment]
> Hi @pevik , i'm still encountering this compile error with 4.19 kernel and the latest master branch.
> 
> GEN ltp-version.h In file included from /usr/include/linux/io_uring.h:11:0, from ../include/lapi/io_uring.h:21, from tst_fd.c:21: /usr/include/sys/mount.h:35:3: error: expected identifier before numeric constant MS_RDONLY = 1, /* Mount read-only. */ ^ make[1]: *** [tst_fd.o] Error 1

Redefinition of MS_XXX macro. Just need to:

1. update glibc to latest version

or

2. wrap the enum definition in /usr/include/sys/mount.h like

```
#ifndef MS_RDONLY
enum {
  MS_RDONLY = 1,
  ...
}
#endif
```

**Comment by metan-ucw** [comment]
This kind of problems was fixed in glibc in:

commit 774058d72942249f71d74e7f2b639f77184160a6
Author: Adhemerval Zanella <adhemerval.zanella@linaro.org>
Date:   Wed Aug 10 14:24:47 2022 -0300

    linux: Fix sys/mount.h usage with kernel headers


However there is a workaround in the kernel as well, the linux/io_uring.h includes linux/fs.h and the linux/fs.h contains:

commit e262e32d6bde0f77fb0c95d977482fc872c51996
Author: David Howells <dhowells@redhat.com>
Date:   Thu Nov 1 23:07:23 2018 +0000

    vfs: Suppress MS_* flag defs within the kernel unless explicitly enabled


So if you are unlucky and have old kernel (4.19 is from 2018) and slightly older glibc you may hit this problem.
