### ISSUE TITLE
fsx-linux: fname filename input option needed back

### ISSUE THREAD

**Issue by AYUSHJAIN951** [linux-test-project/ltp#1128]
With the rewrite of fsx-linux test, https://github.com/linux-test-project/ltp/commit/134b08362ed77ab8af515820c85e6e3836879967
option for filename input was removed
can it be pulled back in the testcase?
eg: FSX035 fsx-linux -N 10000 $TMPDIR/junkfile   --was changed to-->  FSX038 fsx-linux -N 10000

**Comment by AYUSHJAIN951** [comment]
@pevik @acerv ping

**Comment by acerv** [comment]
Hi, can you please explain what's the reason behind the request?
In the example I only see $TMPDIR usage missing, which can be defined before running the test, for example: `TMPDIR=myfolder fsx-linux -N 10000`

**Comment by metan-ucw** [comment]
@AYUSHJAIN951 the I/O stress tests were finally integrated into LTP properly which means, as @acerv pointed out that the directory all LTP testcases use as a base to create directories and files i.e. `$TMPDIR` is used by the test internally. And the only change should be that instead of passing the `$TMPDIR` as a test parameter it's now used by the test library directly.

**Comment by AYUSHJAIN951** [comment]
need for the ask is to run the testcase over differnet mountpoints ,so directing the mount point files as tempdir
and as your suggestion on `$TMPDIR`
```
root@x:~/ltp/testcases/kernel/fs/fsx-linux# TMPDIR=/tmp/ayush ./fsx-linux -N 10000
tst_test.c:1741: TINFO: LTP version: 20240129-16-g2a50d18cc
tst_test.c:1625: TINFO: Timeout per run is 0h 30m 30s
fsx-linux.c:320: TPASS: All file operations succeed

Summary:
passed   1
failed   0
broken   0
skipped  0
warnings 0
root@x:~/ltp/testcases/kernel/fs/fsx-linux# ls /tmp/ayush/
root@x:~/ltp/testcases/kernel/fs/fsx-linux#
```
unable to get results at the given directory, here either we are looking at a bug or am i missing something else

**Comment by metan-ucw** [comment]
Well of course the test cleans up after it's done. If you want to see the file you have to look while the test is running...

**Comment by pevik** [comment]
@AYUSHJAIN951 FYI we have `$LTP_NO_CLEANUP` to keep the files for shell API. I'm not sure if it's really useful, but maybe we could add it to the C API.
