### ISSUE TITLE
kirk executable not present in the container

### ISSUE THREAD

**Issue by mahi657** [linux-test-project/ltp#1129]
Hi,

I build a ltp container using the existing containerfile and base os as tumbleweed.

`podman build -t tumbleweed/ltp --build-arg PREFIX=registry.opensuse.org/opensuse/ --build-arg DISTRO_NAME=tumbleweed --build-arg DISTRO_RELEASE=20240124 .`

and the image was successfully created.
```

+ useradd ltp
--> cb63801bb9b
[2/2] STEP 7/12: COPY --from=build $LTPROOT $LTPROOT
--> aa211019148
[2/2] STEP 8/12: ENV LTPROOT=$LTPROOT
--> f12260aa66e
[2/2] STEP 9/12: ENV PATH=$LTPROOT/testcases/bin:$LTPROOT/bin:$PATH
--> a04752698b7
[2/2] STEP 10/12: RUN mkdir -p $KIRKROOT
--> 7e19a493c52
[2/2] STEP 11/12: COPY --from=build /build/tools/kirk $KIRKROOT
--> 48d63404f4c
[2/2] STEP 12/12: USER ltp
[2/2] COMMIT tumbleweed/ltp
--> 92c7f2cdb04
Successfully tagged localhost/tumbleweed/ltp:latest
92c7f2cdb04c23d4377c1edf6fa2115abf506172ff9e4220591c2052325e45e0
```

But on running the container with the above image, I don't see kirk executable under /opt/kirk/

```
ltp@b47f9caacd78:/opt/kirk> ls
ltp@b47f9caacd78:/opt/kirk> 
ltp@b47f9caacd78:/opt/kirk> 
```

Can someone please help me?

**Comment by pevik** [comment]
In LTP git root you run:
```
$ git submodule update --init
$ cd tools/kirk/
$ make install
```

**Comment by mahi657** [comment]
Thank You @pevik , I was able to install and build kirk. Few additional steps I followed, setting profile and adding python3 to runtime script.

**Comment by Avinesh** [comment]
@pevik , I think we can close this one.
