### ISSUE TITLE
test_robind 1 TBROK: mkfs.f2fs /dev/block/loop44 failed

### ISSUE THREAD

**Issue by Bad916** [linux-test-project/ltp#1142]
<<<test_start>>>
tag=test_robind01 stime=1709808628
cmdline="test_robind.sh -c "growfiles -W gf01 -b -e 1 -u -i 0 -L 5 -w -C 1 -l -I r -T 10 glseek20 glseek20.2""
contacts=""
analysis=exit
<<<test_output>>>
test_robind 1 TINFO: Formatting /dev/block/loop44 with f2fs extra opts=''
Th[0] 
    F2FS-tools: mkfs.f2fs Ver: 1.16.0 (2023-04-11)

Th[0] Info: Disable heap-based policy
Th[0] Info: Debug level = 0
Th[0] Info: Trim is enabled
Th[0] Info: not exist /proc/version!
Th[0] Info: Segments per section = 1
Th[0] Info: Sections per zone = 1
Th[0] Info: sector size = 512
Th[0] Info: total sectors = 1228800 (600 MB)
Th[0] Info: zone aligned segment0 blkaddr: 512
Th[0] Info: format version with
  "5.15.123-android13-8-o-g86531b42bd11"
Th[0] Info: [/dev/block/loop44] Discarding device
Th[0] Info: This device doesn't support BLKSECDISCARD
Th[0] Info: Discarded 600 MB
Th[0] Info: Overprovision ratio = 7.490%
Th[0] Info: Overprovision segments = 22 (GC reserved = 20)
Th[0] 	Error: Could not conduct fsync!!!
test_robind 1 TBROK: mkfs.f2fs /dev/block/loop44 failed

**Comment by metan-ucw** [comment]
Well there is a failure during the run of mkfs.f2fs I do not think that there is anything wrong with LTP.
