### ISSUE TITLE
splice07 fails on kernels <5.10

### ISSUE THREAD

**Issue by edliaw** [linux-test-project/ltp#1156]
splice07 seems to depend on https://github.com/torvalds/linux/commit/36e2c7421f02a22f71c9283e55fdb672a9eb58e7 ("fs: don't allow splice read/write without explicit ops") to pass.  I've compiled a list of failing combinations on 5.4, but I'm not sure what's the right approach to modifying the test:

|in_fd|out_fd|error|
|-----|------|-----|
|TST_FD_PIPE_READ |TST_FD_EPOLL     |hangs|
|TST_FD_PIPE_READ |TST_FD_EVENTFD   |hangs|
|TST_FD_PIPE_READ |TST_FD_SIGNALFD  |hangs|
|TST_FD_PIPE_READ |TST_FD_TIMERFD   |hangs|
|TST_FD_PIPE_READ |TST_FD_PIDFD     |hangs|
|TST_FD_PIPE_READ |TST_FD_PERF_EVENT|hangs|
|TST_FD_PIPE_READ |TST_FD_IO_URING  |hangs|
|TST_FD_PIPE_READ |TST_FD_BPF_MAP   |hangs|
|TST_FD_PIPE_READ |TST_FD_FSOPEN    |hangs|
|TST_FD_PIPE_READ |TST_FD_FSPICK    |hangs|
|TST_FD_INOTIFY   |TST_FD_PIPE_WRITE|hangs|
|TST_FD_DIR       |TST_FD_PIPE_WRITE|EISDIR|
|TST_FD_PERF_EVENT|TST_FD_PIPE_WRITE|ENODATA|
|TST_FD_FSOPEN    |TST_FD_PIPE_WRITE|ENODATA|
|TST_FD_FSPICK    |TST_FD_PIPE_WRITE|ENODATA|

Should it just be gated by kernel version or is there a preferred way to modify it so that it is backwards compatible?

**Comment by pevik** [comment]
Thanks for a detailed table.

@metan-ucw @mdoucha know more than me. AFAIK we noticed at least incorrect errno `EISDIR`  (obviously there is also  `ENODATA`) and hang on `TST_FD_EPOLL` (I did not know about the following hangs), although AFAIK we did not reported it to the kernel mainline ML (lore).

> splice07 seems to depend on https://github.com/torvalds/linux/commit/36e2c7421f02a22f71c9283e55fdb672a9eb58e7 ("fs: don't allow splice read/write without explicit ops") to pass.

Yes (https://lore.kernel.org/ltp/ZbO-Pl9S7KH2cKkb@yuki/).

FYI before the latest release we whitelisted 2 cases: (c04218579773e3c7017a87d8bb121771e3e0f09c, e5970b2e64c3add251bed820f93443322b1eda05) and had a plan to add tests which actually test
splice() on /dev/zero and /proc/self/maps for kernels between v4.4 and v5.3 where it was working (https://lore.kernel.org/ltp/20240126132046.GA508599@pevik/).

**Comment by mdoucha** [comment]
The right approach would be to fix the kernel since all these failures are kernel bugs (maybe except for inotify -> writable pipe). It does not make sense to modify the test, not even to add a kernel version check.

**Comment by pevik** [comment]
> The right approach would be to fix the kernel since all these failures are kernel bugs (maybe except for inotify -> writable pipe). It does not make sense to modify the test, not even to add a kernel version check.

5.10 got fixed by [36e2c7421f02 ("fs: don't allow splice read/write without explicit ops")](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=36e2c7421f02a22f71c9283e55fdb672a9eb58e7). I managed to backport necessary commits on the top of 5.5, but I was not sure if I did not introduce any regression, thus I did not post it.

I was thinking to backport necessary changes to 5.4 LTS kernel, but that would require quite a lot of work (much more commits to backport because the code changed a lot). That is the reason why nobody thought about backporting the code (also some would consider it as a new feature not a fix).

**Comment by pevik** [comment]
For a record another wrong attempt to whitelist splice07 on kernel < 5.10:
https://patchwork.ozlabs.org/project/ltp/patch/20251214060640.41555-1-changwei.zou@canonical.com/

FYI hopefully we will have "Do not work around kernel bugs" ground rules documented:
https://patchwork.ozlabs.org/project/ltp/patch/20251215124404.16395-2-chrubis@suse.cz/
