### ISSUE TITLE
about :opclock_settime/speculative /4-4.c

### ISSUE THREAD

**Issue by chenguanxi12138** [linux-test-project/ltp#1158]
When I run the use case clock_settime_speculative_4-4.run-test on my embedded device，I get the following output：
Caught signal
Caught signal
Caught signal
FAIL:  Didn't catch timer after TIMERINTERVAL.
Caught 0 < 2 signals
Implementation does not repeat signals on clock reset
Caught signal

Is this a bug？or is the implementation of my system's timer not as expected

**Comment by metan-ucw** [comment]
No idea. However notice the `speculative` in the test name, the test tries to assert something that is not required by POSIX and may not be implemented as the test expects. You would have to read the kernel timer source code to understand if the test assertions are valid for the implementation you run the test on.
