### ISSUE TITLE
writev03 FAIL in linux 4.4.32

### ISSUE THREAD

**Issue by journey-wang** [linux-test-project/ltp#116]
writev03    0  TINFO  :  Enter block 1
writev03    1  TFAIL  :  writev03.c:145: Got EFAULT
writev03    0  TINFO  :  Exit block 1
writev03    0  TINFO  :  Enter block 2
writev03    2  TFAIL  :  writev03.c:167: Got EFAULT
writev03    0  TINFO  :  Exit block 2
writev03    0  TINFO  :  Enter block 3
writev03    3  TFAIL  :  writev03.c:191: Got EFAULT
writev03    0  TINFO  :  Exit block 3

**Comment by jstancek** [comment]
This should be already fixed via:
db19194527060a962955a7db54a2f5710e69bec9
9a62652bb67a9d5279de6dbbf2576c8aba33eeeb
b3671b7fa9444c2a9ad71f48817c7ef4afaa148b

**Comment by journey-wang** [comment]
Thanks
