### ISSUE TITLE
utimensat01 failed in linux 4.4.32

### ISSUE THREAD

**Issue by journey-wang** [linux-test-project/ltp#117]
Testing immutable append-only file, owned by self

***** Testing times==NULL case *****
Pathname test
Owner=nobody; perms=-rw-------; EFAs=Immutable,Append_Only,Extents
./utimensat01 -q /tmp/ltp-k5Jun7qhjX/utimensat_tests/utimensat.test_file
EXPECTED: EACCES
RESULT:   EPERM
utimensat01 67 TFAIL : FAILED test 67

**Comment by jstancek** [comment]
8cc1e10d725c9104c0fc2a31527be8b1d9baa252 comes to mind, if that kernel patch been backported to your kernel.

Can you provide more info about your LTP/distro/arch/kernel?
Is it upstream kernel?

**Comment by journey-wang** [comment]
Thanks
