### ISSUE TITLE
ioprio set level failed，need update ioprio.h file

### ISSUE THREAD

**Issue by yangchenguang94** [linux-test-project/ltp#1192]
```
tst_test.c:1558: TINFO: Timeout per run is 0h 00m 30s
ioprio_set03.c:39: TFAIL: ioprio_set IOPRIO_CLASS_BE prio 8 should not work
ioprio_set03.c:47: TINFO: tested illegal priority with class NONE
ioprio_set03.c:50: TPASS: returned correct error for wrong prio: EINVAL (22)
```
kernel update : https://github.com/torvalds/linux/commit/01584c1e233740519d0e11aa20daa323d26bf598

**Comment by metan-ucw** [comment]
This should have been fixed in LTP in 6b7f448fe392845a097a82bd311907a748da3e52

**Comment by yangchenguang94** [comment]
> This should have been fixed in LTP in [6b7f448](https://github.com/linux-test-project/ltp/commit/6b7f448fe392845a097a82bd311907a748da3e52)

I tested it not be fixed，So mabye we should update ioprio.h function IOPRIO_PRIO_VALUE

**Comment by metan-ucw** [comment]
The IOPRIO_PRIO_VALUE comes from the system headers, so possibly your headers are too old and does not match the kernel you are running.

**Comment by yangchenguang94** [comment]
> The IOPRIO_PRIO_NUM comes from the system headers, so possibly your headers are too old and does not match the kernel you are running.IOPRIO_PRIO_NUM 来自系统标头，因此您的标头可能太旧并且与您正在运行的内核不匹配。

kernel headers defined https://github.com/torvalds/linux/blob/master/include/uapi/linux/ioprio.h#L42
```
#define IOPRIO_LEVEL_NR_BITS            3
#define IOPRIO_NR_LEVELS                (1 << IOPRIO_LEVEL_NR_BITS)
```
LTP headers defined
```
#ifdef IOPRIO_NR_LEVELS
# define IOPRIO_PRIO_NUM		IOPRIO_NR_LEVELS
#else
# define IOPRIO_PRIO_NUM		8
#endif
```
The IOPRIO_PRIO_NUM is the same

**Comment by metan-ucw** [comment]
You are right, I was under an impression that the reason why we started using the kernel header was that the number of levels has changed, but that does not seem to be true, looks like the number of levels was always 8 and the valid values are from 0 to 7.

However the commit you pointed out in the first comment went into v6.4 as well as the commits that caused the problem. However the bug you pointed out did not make it into any official kernel release. So unless you have a custom kernel with a subset of patches that went into the mainline you will never hit the bug.

I have no idea why the test fails for you.

**Comment by yangchenguang94** [comment]
> You are right, I was under an impression that the reason why we started using the kernel header was that the number of levels has changed, but that does not seem to be true, looks like the number of levels was always 8 and the valid values are from 0 to 7.
> 
> However the commit you pointed out in the first comment went into v6.4 as well as the commits that caused the problem. However the bug you pointed out did not make it into any official kernel release. So unless you have a custom kernel with a subset of patches that went into the mainline you will never hit the bug.
> 
> I have no idea why the test fails for you.

Sure，I used kernel v6.6. It should be solved later.
