### ISSUE TITLE
There doesn't appear to be any way to make install-strip

### ISSUE THREAD

**Issue by steven-joruk** [linux-test-project/ltp#120]
I may be being stupid but I can't see how to create stripped binaries with ltp's build system. STRIP is set correctly even with a cross compiler, but the top level Makefile has no install-strip target and the default install target doesn't strip.

**Comment by metan-ucw** [comment]
Looks like it wasn't implemented at all, probably not needed by anybody until now.

I guess that we can add install-strip target if you really need it, feel free to send a patch as well.

**Comment by steven-jackson** [comment]
I'm happy with my work around for now, thanks. I'll send a patch in the new year if nobody else has gotten around to it.
