### ISSUE TITLE
cross-compile with uClibc toolchain

### ISSUE THREAD

**Issue by wbx-github** [linux-test-project/ltp#13]
Hi, 

I get a compile error when cross-compiling with a uClibc based toolchain.
Buildroot has a fix included, which works for me.
Any idea why it is not yet included?

--- ltp-full-20140422.orig/testcases/realtime/lib/libstats.c    2014-04-23 10:37:00.000000000 +0200
+++ ltp-full-20140422/testcases/realtime/lib/libstats.c 2014-06-27 10:55:59.401744516 +0200
@@ -46,6 +46,11 @@
 #include <libstats.h>
 #include <librttest.h>

+#ifdef **UCLIBC**
+/\* 10^x = 10^(log e^x) = (e^x)^log10 = e^(x \* log 10) _/
+#define exp10(x) (exp((x) \* log(10)))
+#endif /_ **UCLIBC** */
+
 int save_stats = 0;

 /\* static helper functions */

best regards
 Waldemar

**Comment by pevik** [comment]
For a record `exp10()` has been added in v1.0.27: https://cgit.openadk.org/cgi/cgit/uclibc-ng.git/commit/?id=ea38f4d89c9698895b1cf53a5946429dc1d8bbaa
