### ISSUE TITLE
realtime: ./run.sh fails without -l argument

### ISSUE THREAD

**Issue by vedangp** [linux-test-project/ltp#131]
I am getting the following error if I try to run `./run.sh -t all`:

./run.sh: line 87: 0 +  : syntax error: operand expected (error token is "+  ")

If I try to run `./run.sh -t all -l 1` it runs successfully. The problem is the number of loops is not initialized to a default value.

**Comment by vedangpatel1** [comment]
submitted pull request #132  for this issue

**Comment by pevik** [comment]
Fixed in 97a3ce2.
