### ISSUE TITLE
testcases/kernel/fs/ftest/ftest02.c fails in ILP32 mode, bug in test

### ISSUE THREAD

**Issue by sellcey** [linux-test-project/ltp#135]
While testing ILP32 mode on aarch64, testcases/kernel/fs/ftest/ftest02.c was failing.  The problem is on line 271:

val = lseek(fd, -(sizeof(crmsg) - 1), 1);

it should be

val = lseek(fd, -((off_t) sizeof(crmsg) - 1), 1);

The problem is that sizeof returns type size_t (unsigned) and if off_t (which is signed) is larger, the conversion of the 32 bit unsigned size_t to 64 bit signed off_t results in a large positive number instead of a negative number.  Adding the (off_t) type conversion before we negate the value returned by sizeof fixes it.

I found this on ILP32 aarch64 mode which is still being developed but the problem should be reproducible on x86_64 with the '-mx32' ILP32 flag. (-m32 mode will not show the problem).

**Comment by jstancek** [comment]
Would you care to send a patch to mailing list?

**Comment by sellcey** [comment]
On Mon, 2017-02-27 at 23:59 -0800, Jan Stancek wrote:
> Would you care to send a patch to mailing list?

Can I just send the patch to the ltp mailing list or do I need to check
it in to the githup repository and ask that it be pulled?  I have not
submitted patches to any github hosted projects before.

**Comment by pevik** [comment]
Please, just send the patch to mailing list (using `git format-patch` and `git send-email`). Vast majority of developers prefer mailing list.

**Comment by sellcey** [comment]
On Tue, 2017-02-28 at 13:03 -0800, Petr Vorel wrote:
> Please, just send the patch to mailing list (using git format-patch
> and git send-email). Vast majority of developers prefer mailing list.

I sent a patch, but I forgot to put the issue number (#135) in it.
The patch is at:

http://lists.linux.it/pipermail/ltp/2017-February/003814.html

I also found another problem when compiling on x86_64 with the -mx32
flag and submitted a patch for that:

http://lists.linux.it/pipermail/ltp/2017-February/003813.html

Steve Ellcey
