### ISSUE TITLE
cron test fails on ubuntu 16.04

### ISSUE THREAD

**Issue by sellcey** [linux-test-project/ltp#136]
The cron test script testcases/commands/cron/cron_tests.sh looks in /var/log/messages and /var/log/cron to check for logging of cron activity but my Ubuntu 16.04 system puts it in /var/log/syslog.

% grep REPLACE /var/log/syslog | grep crontab
Feb 27 13:52:29 crb6 crontab[25636]: (ubuntu) REPLACE (ubuntu)

**Comment by pevik** [comment]
I'm going to post a fix in mailing list.

**Comment by pevik** [comment]
Fix merged.

**Comment by metan-ucw** [comment]
@sellcey can you check that the test works for you now?

**Comment by sellcey** [comment]
On Wed, 2017-03-22 at 08:44 -0700, Cyril Hrubis wrote:
> @sellcey can you check that the test works for you now?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Hi Cyril,

I think the log checking code is OK now but I did get this cron
related failure:

<<<test_start>>>
tag=cron_allow01 stime=1490244644
cmdline="cron_allow01"
contacts=""
analysis=exit
<<<test_output>>>
This script contains bashism that needs to be fixed!
No passwd entry for user 'ca_user1'
No passwd entry for user 'ca_user2'
userdel: user 'ca_user1' does not exist
userdel: user 'ca_user2' does not exist
This script contains bashism that needs to be fixed!
TEST: /var/spool/cron/allow should only allow those in the file to
run cron jobs.
(1) TEST THAT PERSON IN /var/spool/cron/allow IS ABLE TO RUN JOB.
backup crontab....
no crontab for ca_user1
sleeping for 130 seconds....
Cron allowed user to execute test job, TEST PASSED
restore old crontab...
This script contains bashism that needs to be fixed!
(2) TEST THAT PERSON NOT IN /var/spool/cron/allow IS NOT ABLE TO RUN
JOB.
backup crontab....
no crontab for ca_user2
sleeping for 130 seconds....
Cron allowed user to execute test job, TEST FAILED
restore old crontab...
<<<execution_status>>>
initiation_status="ok"
duration=262 termination_type=exited termination_id=1 corefile=no
cutime=8 cstime=20
<<<test_end>>>
<<<test_start>>>
tag=cron_dirs_checks01 stime=1490244906
cmdline="cron_dirs_checks01"
contacts=""
analysis=exit
<<<test_output>>>
Checking /etc/cron.d
PASS: /etc/cron.d
Checking /etc/cron.daily
PASS: /etc/cron.daily
Checking /etc/cron.hourly
PASS: /etc/cron.hourly
Checking /etc/cron.monthly
PASS: /etc/cron.monthly
Checking /etc/cron.weekly
PASS: /etc/cron.weekly
Checking /var/spool/cron
PASS: /var/spool/cron
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>

**Comment by metan-ucw** [comment]
The cron tests have been removed in 0fc9b8624bea8acfdb408bf5ff4916b1453e3daa.
