### ISSUE TITLE
Read-only system detection

### ISSUE THREAD

**Issue by Vertigo0709** [linux-test-project/ltp#137]
This question comes in my mind for a while, but I'm not really sure which is the clearest sign / check point to conclude a system is read-only ? (except some folders (/tmp, /run ...) on tmpfs, any other places is read-only)
(Also see some issues on our pages, people are testing on read-only systems)
I normally met a number of failed LTP cases, due to the permission. The most often cases are useradd, userdel (because /etc/passwd is not writable)

Is it the right approach if I only the the write-ability of that files and then return 32 ?
(something like
 if ( access( /etc/passwd, W_OK )) { /* writable */ }
)

Thanks in advance.

**Comment by metan-ucw** [comment]
Hmm, I guess that we can do the check post mortem, i.e. if useradd had failed, we can always look if /etc/passwd is writeable and report TCONF if it is.

**Comment by Vertigo0709** [comment]
Thanks @metan-ucw ,

I'm trying with it (on prot_hsymlinks testcase), something just like
```
static void test_user_cmd(const char *user_cmd)
{
  char cmd[MAX_CMD_LEN];
  snprintf(cmd, MAX_CMD_LEN, "%s %s", user_cmd, users[TEST_USER].name);
  if (system(cmd) != 0) {
    if (access("/etc/passwd", W_OK)) {
      tst_brkm(TCONF, NULL,
      "/etc/passwd is not accessible");
    } else {
      tst_brkm(TBROK, cleanup, "Failed to run cmd: %s %s",
      user_cmd, users[TEST_USER].name);
    }
  }
}
```
and it can works. (I temporarily used "NULL" instead of "cleanup" to avoid test_user_cmd("userdel -r") in cleanup, and causing the loop, but I guess it's better to check "access("/etc/passwd", W_OK)" also in cleanup to decide to call userdel or not)
```
root@mx6q:~# ./prot_hsymlinks
useradd: cannot lock /etc/passwd; try again later.
prot_hsymlinks    1  TCONF  :  prot_hsymlinks.c:321: /etc/passwd is not accessible
prot_hsymlinks    2  TCONF  :  prot_hsymlinks.c:321: Remaining cases not appropriate for configuration
```

Just something I've read in "doc/test-writing-guidelines.txt"

> 3.2 access()
> ~~~~~~~~~~~
> 
> If 'access(some_file, W_OK)' is executed by root, it will return success even
> if the file doesn't have write permission bits set (the same holds for R_OK
> too). For sysfs files you can use 'open()' as a workaround to check file
> read/write permissions. It might not work for other filesystems, for these you
> have to use 'stat()', 'lstat()' or 'fstat()'.

But seems that in case of mounted folders, access() is still applicable ?

**Comment by yaneurabeya** [comment]
You should test writability using eaccess instead of access: https://lists.gnu.org/archive/html/bug-bash/2010-07/msg00071.html . eaccess(2) can give incorrect answers for root.

**Comment by Vertigo0709** [comment]
Thanks @yaneurabeya for your information, I'll try with eaccess instead of access.
