### ISSUE TITLE
Invalid autoconf test for Open POSIX test suite

### ISSUE THREAD

**Issue by tpetazzoni** [linux-test-project/ltp#143]
The ```configure.ac``` script contains:

```
AC_ARG_WITH([open-posix-testsuite],
  [AC_HELP_STRING([--with-open-posix-testsuite],
    [compile and install the open posix testsuite (default=no)])],
  [with_open_posix_testsuite=yes]
)
```

However, the ```with_open_posix_testsuite=yes``` part is bogus, because this part of the code is executed whenever a value is passed, NOT when the value is "option enabled". The end result is that if you pass ```--without-open-posix-testsuite```, the Open POSIX testsuite gets built!

So, it should be changed to:

```
 [with_open_posix_testsuite=$withval],
 [with_open_posix_testsuite=yes]
```

This means: if the option is passed, take its value (yes or no), and if the option is not passed, assume the user wants the Open POSIX testsuite.

**Comment by metan-ucw** [comment]
The default was not to build open posix testsuite unless user enabled it for years, it probably shouldn't be enabled by default without any discussion. Since now this breaks out-of-tree build for example.
