### ISSUE TITLE
CentOS7 getxattr04 fail.

### ISSUE THREAD

**Issue by gaochong2016** [linux-test-project/ltp#148]
Is this should be a "expected fail" ?
Firstly do setup(): setxattr() a small size;
Then do verify_getxattr(): setxattr() big size and remove it;
At last in loop_getxattr(): getxattr() small size,  result is fail,  error=ENODATA
If change to getxattr big size , then PASS.

**Comment by metan-ucw** [comment]
The getxattr04 is an regression test for a bug fixed in linux kernel in https://github.com/torvalds/linux/commit/5a93790d4e2df73e30c965ec6e49be82fc3ccfce if the test fail you are running kernel that misses this fix.
