### ISSUE TITLE
which01 fails on debian/ubuntu

### ISSUE THREAD

**Issue by dannf** [linux-test-project/ltp#151]
The which01 test currently fails on Debian & Ubuntu:

`which01 3 TFAIL : 'which -a pname' failed, not expected.`

This test appears to assume that which(1) will return a full qualified path even if the $PATH contains relative directory components (e.g. ./bin). This appears to be true on Fedora, but Debian will output relative paths, as show below:

```
cd /tmp
mkdir foo
touch foo/bar
chmod +x foo/bar
PATH=$PATH:./foo which bar

```
On Debian this will return `./foo/bar` - on Fedora this would output `/tmp/foo/bar`. AFAICT, there is no standard that specifies one as being more correct than the other.

**Comment by metan-ucw** [comment]
Hmm `which` does not seem to be covered by POSIX or any other standard (while `command -v` that does the same job is required to produce absolute path).

The difference here seems to be that `which` on Debian comes from debianutils package while which on other distros usually comes from the which package.

I guess that we should fix the test here.

**Comment by yaneurabeya** [comment]
Sidenote: the fact that `which` isn't guaranteed to be consistent/existent is part of the reason why some of the tests/code in the LTP tree use the `command` POSIX shell (built-in).
