### ISSUE TITLE
memcg_lib.sh: integer expression expected

### ISSUE THREAD

**Issue by pavlinux** [linux-test-project/ltp#152]
/opt/ltp/testcases/bin/memcg_lib.sh: line 81: [: 18446744073692774399: integer expression expected

**Comment by pavlinux** [comment]
/bin/sh --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by pavlinux** [comment]
```diff
--- a/testcases/kernel/controllers/memcg/functional/memcg_lib.sh
+++ b/testcases/kernel/controllers/memcg/functional/memcg_lib.sh
@@ -78,7 +78,7 @@ TST_CLEANUP=cleanup
 shmmax_setup()
 {
        shmmax=`cat /proc/sys/kernel/shmmax`
-       if [ $shmmax -lt $HUGEPAGESIZE ]; then
+       if [ $shmmax < $HUGEPAGESIZE ]; then
                ROD echo "$HUGEPAGESIZE" \> /proc/sys/kernel/shmmax
        fi
 }```

**Comment by pavlinux** [comment]
And second. if HUGEPAGESIZE == 0, then it will been echoed to /proc/sys/kernel/shmmax

WTF? Minimal values must be: (_PHYS_PAGES / 2) * PAGE_SIZE;

**Comment by pavlinux** [comment]
And third.  shmmax=`cat /proc/sys/kernel/shmmax` must be global (in file) variable. 
For later usage in shmmax_cleanup()

**Comment by pavlinux** [comment]
```patch
--- a/testcases/kernel/controllers/memcg/functional/memcg_lib.sh
+++ b/testcases/kernel/controllers/memcg/functional/memcg_lib.sh
@@ -35,7 +35,7 @@ if [ $? -ne 0 ]; then
 fi
 
 HUGEPAGESIZE=$(awk '/Hugepagesize/ {print $2}' /proc/meminfo)
-[ -z $HUGEPAGESIZE ] && HUGEPAGESIZE=0
+[ -z $HUGEPAGESIZE ] && HUGEPAGESIZE=$(($(getconf _PHYS_PAGES)/$(getconf PAGE_SIZE)))
 HUGEPAGESIZE=$(( $HUGEPAGESIZE * 1024 ))
 orig_memory_use_hierarchy=""
 
@@ -75,10 +75,11 @@ cleanup()
 }
 TST_CLEANUP=cleanup
 
+shmmax=`cat /proc/sys/kernel/shmmax`
+
 shmmax_setup()
 {
-   shmmax=`cat /proc/sys/kernel/shmmax`
-   if [ $shmmax -lt $HUGEPAGESIZE ]; then
+ if [ $shmmax < $HUGEPAGESIZE ]; then
                ROD echo "$HUGEPAGESIZE" \> /proc/sys/kernel/shmmax
        fi
 }

**Comment by yaneurabeya** [comment]
`]` with `<` is not POSIX compliant. It needs to be converted back to `-lt` (or it will break dash, etc).

**Comment by MofX** [comment]
I guess this can be closed.
The comparison was changed already in 578f4cd9015519ff614e387fe60a0d9da4a335ae
