### ISSUE TITLE
ltp/utils/ffsb-6.0-rc2/parser.c:119]: (error) Buffer is accessed out of bounds

### ISSUE THREAD

**Issue by dcb314** [linux-test-project/ltp#155]
Source code is

    memcpy(unit, "\0", 3);

Maybe better code

    memset(unit, 0, 3);

**Comment by metan-ucw** [comment]
This change looks good. Can you provide a signed patch?

**Comment by dcb314** [comment]
>This change looks good. 

Thanks.

>Can you provide a signed patch?

Sorry no.
