### ISSUE TITLE
ltp/testcases/kernel/fs/dmapi/hole.c: 2* wierd coding ?

### ISSUE THREAD

**Issue by dcb314** [linux-test-project/ltp#156]
1.

ltp/testcases/kernel/fs/dmapi/hole.c:1216]: (error) Expression '(off=lseek(fd,500000-(sizeof("0123456789")-1),SEEK_SET))!=off' depends on order of evaluation of side effects

Source code is

           ((off =
              lseek(fd, TMP_FILELEN - DUMMY_STRLEN, SEEK_SET)) != off)

2.

ltp/testcases/kernel/fs/dmapi/hole.c:1209]: (error) Expression '(off=lseek(fd,i,SEEK_SET))!=off' depends on order of evaluation of side effects

Duplicate.

**Comment by metan-ucw** [comment]
This code is even skipped from a compilation. Maybe it's time to remove the whole dmapi directory.
