### ISSUE TITLE
"Cannot alloc memory" on memcg_stress test

### ISSUE THREAD

**Issue by Revaj** [linux-test-project/ltp#159]
Hi,

I have an issue with the testcase of memcg_stress. 

When I execute this test, sometimes I received the message:
bash: fork: Cannot allocate memory

After that message, the script it seems exit out and when I try to use the terminal, almost every command I launched  send me the same message. It seems my machine is empty of memory (only a reboot can help it)

Also I send the top command before to execute the test, and then when I executed the same test, the only process active on that moment using the cpu resources is kswapd. 

I'm using the sles 12.2 distribution with kernel 4.4

**Comment by metan-ucw** [comment]
First of all, what LTP version do you have?

What this test does is to allocates a memory and keeps faulting it in a loop for a given time. Now the amount of memory to allocate is (after dropping kernel caches) free RAM + half of free SWAP, which may be problematic in a case that you have large SWAP compared to RAM as the machine may end up dead by swapping although it should be able recover after some time once the test has exited.

**Comment by Revaj** [comment]
Hi, the version I use is 20160920

About the swap memory, we don't have a swap partition enabled, so the SwapTotal/SwapFree memory is zero. Is required to enable a swap partition for at least this test case?

**Comment by metan-ucw** [comment]
Ah, that explains it, the test does not work without swap. There was a discussion about that http://lists.linux.it/pipermail/ltp/2015-November/000466.html unfortunately we do not have a solution yet.

**Comment by Revaj** [comment]
Ok then, we will skip the test case for the moment. Thanks!
