### ISSUE TITLE
Pass foreign to AM_INIT_AUTOMAKE

### ISSUE THREAD

**Issue by rossburton** [linux-test-project/ltp#16]
If I grab the git repo and run autoreconf, I get this error:

Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './ChangeLog' not found

As LTP doesn't use GNU standards you'll want to tell automake this by having in configure.ac:

AM_INIT_AUTOMAKE([foreign])

As a sidenote, you could replace include/mk/automake.mk with just "autoreconf" for the bootstrap.  After that

**Comment by pevik** [comment]
NOTE: d96efcf34 commit is not referencing it (it just mention number of bug as part of kernel dump)

**Comment by pevik** [comment]
As we removed ffsb in 29f51a85b122c08744d759286b9b54de95ec89aa, can we close the ticket?
