### ISSUE TITLE
general_mail_tests.sh fails because a mismatch on the results

### ISSUE THREAD

**Issue by Revaj** [linux-test-project/ltp#164]
Hi!

I run on a machine with suse12.2 distribution and LTP 2016092 this test case and is failing on the tests 02 and 03. 

This is the output when I execute this test:

>mail_tests::setup    0  TINFO  :  INIT: Removing all mails for mail_test and root
mail_tests::mail01    0  TINFO  :  Test #1: mail root@localhost will send mail to root
mail_tests::mail01    0  TINFO  :  Test #1: user on local machine.
mail_tests::mail01    1  TPASS  :  Test #1: Mail was sent to root & was received
mail_tests::mail02    0  TINFO  :  Test #2: mail user@bad-domain will result in failure
mail_tests::mail02    0  TINFO  :  Test #2: to deliver the mail. Mailer daemon should
mail_tests::mail02    0  TINFO  :  Test #2: report this failure.
Heirloom mailx version 12.5 7/5/10.  Type ? for help.
Heirloom mailx version 12.5 7/5/10.  Type ? for help.
"/var/mail/root": 1 message 1 new
\>N  1 MAILER-DAEMON@linu Tue Jun 13 16:35   75/2569  Undelivered Mail Returned
mail_tests::mail02    2  TFAIL  :  ltpapicmd.c:156: Test #2: Mailer-Deamon failed to report delivery failure. Reason:
mail_tests::mail03    0  TINFO  :  Test #3: mail non_existent_user@localhost will fail
mail_tests::mail03    0  TINFO  :  Test #3: to deliver the mail. Mailer daemon should
mail_tests::mail03    0  TINFO  :  Test #3: report this failure.
Heirloom mailx version 12.5 7/5/10.  Type ? for help.
Heirloom mailx version 12.5 7/5/10.  Type ? for help.
"/var/mail/root": 1 message 1 new
\>N  1 MAILER-DAEMON@linu Tue Jun 13 16:35   73/2403  Undelivered Mail Returned
mail_tests::mail03    3  TFAIL  :  ltpapicmd.c:156: Test #3: Mailer-Daemon failed to report delivery failure. Reason:
mail_tests::mail04    0  TINFO  :  Test #4: Test that mail -c user@domain will
mail_tests::mail04    0  TINFO  :  Test #4: carbon copy user@domain
mail_tests::mail04    4  TPASS  :  Test #4: Mail was carbon copied to user mail_test
mail_tests::mail05    0  TINFO  :  Test #5: Test that mail -b user@domain will
mail_tests::mail05    0  TINFO  :  Test #5: blind carbon copy user@domain
mail_tests::mail05    5  TPASS  :  Test #5: Mail was carbon copied to user mail_test
mail_tests::cleanup    0  TINFO  :  Test CLEAN: Removing temporary files from /tmp
mail_tests::cleanup    0  TINFO  :  Test CLEAN: Removing temporary user mail_test
You have mail in /var/mail/root

I deeply investigated on both tests and it seems there is an issue on the code:
```bash
isHeirloomMail=0
checkHeirloomMail()
{
        if [ $# -eq 1 -a -f $1 ] && grep "Heirloom" $1; then
                isHeirloomMail=1
        fi
}
```

This function is verifying if the tst_mail.res exists and also contains the word "Heirloom". This is the tst_mail.res produced by the test:

> Heirloom mailx version 12.5 7/5/10.  Type ? for help.
"/var/mail/root": 1 message 1 new
\>N  1 MAILER-DAEMON@linu Tue Jun 13 16:53   75/2569  Undelivered Mail Returned

But then, the test uses isHeirloomMail to check which output is expected for the tst_mail.res. It seems the purpose of this is to verify which mail I'm using (mail or mailx) and based on this, uses the correct awks for the output. But since the test is mistaking mailx with mail, then it fails because the output is not the expected.

PD: The test is located on /ltp/testcases/commands/mail

**Comment by richiejp** [comment]
It also says in one of the comments:
```
In this testcase, mail will get "Returnedmail:", while mailx will get "UndeliveredMailReturned:".
```
but then just awks for `UndeliveredMail`. Meanwhile the actual output is `Undelivered Mail Returned`.

**Comment by metan-ucw** [comment]
The mail tests were removed in 8706428afa502e6bd6dfe19b7fd09466d599387c.
