### ISSUE TITLE
mtest06 fails with exit code 1 and no output

### ISSUE THREAD

**Issue by jstancek** [linux-test-project/ltp#165]
I'm seeing a very rare failure in mtest06, where it exits with retcode 1, but provides no output.
```
<<<test_start>>>
tag=mtest06 stime=1496802587
cmdline="mmap1 -x 0.05"
contacts=""
analysis=exit
<<<test_output>>>
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=1 corefile=no
cutime=1 cstime=0
<<<test_end>>>
```

**Comment by jstancek** [comment]
Exit code 1 suggests an _exit(TFAIL) from sig_handler_mapped(). Which somehow gets triggered, while both threads race. Maybe something like ... ?
```
read_mem               map_write_unmap
-----------------------------------------------------------
                       munmap
SIGSEGV
sig_handler
longjmp(jmpbuf, 1);
setjmp(jmpbuf) == 1
read_lock = 0;
SIGSEGV
                       while (read_lock) sched_yield();
                       mmap
                       change handler
do_signal()
sig_handler_mapped()
```

**Comment by veruu** [comment]
Hi, I do have a solution to avoid this race condition, but since I started working with this testcase I'd like to rewrite it to use new API as well (which would hopefully simplify things). I'll send the patches as I finish rewriting the test.
