### ISSUE TITLE
chdir03.c, fchdir03 test working path length of 100 chars is too short

### ISSUE THREAD

**Issue by bentsi** [linux-test-project/ltp#181]
100 characters are not enough for the path. 
`char good_dir[100];`
affected:
- fchdir03.c
- chdir03.c

**Comment by richiejp** [comment]
We should probably use `SAFE_ASPRINTF`

**Comment by metan-ucw** [comment]
@richiejp I'm about to rewrite these mess so that we don't need the good_dir[] in the first place.

**Comment by metan-ucw** [comment]
This is fixed by the two commits that referenced this issue.
