### ISSUE TITLE
add_key02 returns EINVAL for kernel 3.14

### ISSUE THREAD

**Issue by IslamHelmy** [linux-test-project/ltp#182]
I have an issue when running add_key02 test case that the system returns an error code of **EINVAL** to this test case in case of **user,and Logon** keytype , i am not sure whether the problem is with the kernel version itself (3.14) or with the test cases itself so Any help regarding that ? please see also the log for execution below

xxx@yyy:/opt/ltp/testcases/bin# ./add_key02
tst_test.c:898: INFO: Timeout per run is 0h 05m 00s
add_key02.c:84: CONF: kernel doesn't support key type 'asymmetric'
add_key02.c:84: CONF: kernel doesn't support key type 'cifs.idmap'
add_key02.c:84: CONF: kernel doesn't support key type 'cifs.spnego'
add_key02.c:84: CONF: kernel doesn't support key type 'pkcs7_test'
add_key02.c:84: CONF: kernel doesn't support key type 'rxrpc'
add_key02.c:84: CONF: kernel doesn't support key type 'rxrpc_s'
**add_key02.c:99: FAIL: unexpected error with key type 'user': EINVAL
add_key02.c:99: FAIL: unexpected error with key type 'logon': EINVAL**

**Comment by richiejp** [comment]
The kernel has a bug, it should return `EFAULT`.

It was fixed in the commit: "KEYS: fix dereferencing NULL payload with nonzero length"
