### ISSUE TITLE
ltp-pan not found issue

### ISSUE THREAD

**Issue by bushranagma** [linux-test-project/ltp#191]
while running ltp on raspberry pi3 board getting error ltp-pan not found ...
Is raspberry device is compatible to ltp ?
Kindly help

**Comment by metan-ucw** [comment]
The ltp-pan missing means that LTP was not installed correctly, double check your compilation/installation steps.

**Comment by metan-ucw** [comment]
Closing since we didn't get any response for about 2 months. Feel free to reopen with additional information.
