### ISSUE TITLE
Test case setrlimit02 failed on x86, OK for x86-64

### ISSUE THREAD

**Issue by DengkeDu** [linux-test-project/ltp#193]
On x86, kernel is 4.10, in directory /opt/ltp/testcases/bin, run:

> gdb ./setrlimit02

The log:

> GNU
 gdb (GDB) 8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i586-poky-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./setrlimit02...done.
(gdb) run
Starting program: /opt/ltp/testcases/bin/setrlimit02 
Program received signal SIGSEGV, Segmentation fault.
__setrlimit (resource=RLIMIT_NOFILE, rlim=0xffffffff) at /usr/src/debug/glibc/2.25.90-r0/git/sysdeps/unix/sysv/linux/setrlimit.c:39
39	  if (rlim->rlim_cur == RLIM_INFINITY)

On x86-64, run:

> gdb ./setrlimit02

The log:

> GNU gdb (GDB) 8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-poky-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./setrlimit02...done.
(gdb) run
Starting program: /opt/ltp/testcases/bin/setrlimit02 
setrlimit02    1  TPASS  :  expected failure - errno = 14 : Bad address
setrlimit02    2  TPASS  :  expected failure - errno = 22 : Invalid argument
setrlimit02    3  TPASS  :  expected failure - errno = 1 : Operation not permitted
[Inferior 1 (process 1270) exited normally]

**Comment by metan-ucw** [comment]
Hmm, the first part of the trace shows segfault in glibc looks like you are hitting the #ifdef __NR_prlimit64 branch in glibc that has to convert struct rlimit to struct rlim64 in which case it's OK that the test segfaults. I guess that we should remove the invalid address case, or modify the test to cope with segfault and you can safely ignore the failure for the time being.
