### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by hardiksingh-rathore** [linux-test-project/ltp#203]
As networkstress.sh and networktest.sh merged into network.sh then please update the guide in ltp-full-20170516/testcases/network/stress/README.

**Comment by pevik** [comment]
Patch fixing this, waiting in mailing list:
http://lists.linux.it/pipermail/ltp/2017-September/005719.html

**Comment by hardiksingh-rathore** [comment]
Hi Pevik,
Thanks for the patch.
