### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by shankarapailoor** [linux-test-project/ltp#224]
I am seeing an errror when compiling ltp. I followed the instructions on the github page and I see the following error: 

ima_boot_aggregate.c: In function 'main':
ima_boot_aggregate.c:121:76: error: macro "tst_brkm" requires 4 arguments, but only 2 given
ima_boot_aggregate.c:121:2: error: 'tst_brkm' undeclared (first use in this function)
ima_boot_aggregate.c:121:2: note: each undeclared identifier is reported only once for each function it appears 
in

**Comment by metan-ucw** [comment]
Should be fixed in abd6ee637ee6
