### ISSUE TITLE
Cross-compiling failing after libnuma update

### ISSUE THREAD

**Issue by alexchu-cpe** [linux-test-project/ltp#232]
Hi,
Configure won't work with cross compiling after this commit:
##########################################
commit bf3441268245ad3ba2c18da15f9cd1c6bf627a73
Author: Petr Vorel <pvorel@suse.cz>
Date:   Mon Oct 16 13:13:17 2017 +0200
    numa: Check for API >= v2 with autoconf
    instead of more verbose check in C code.
    Signed-off-by: Petr Vorel <pvorel@suse.cz>
##########################################

Tested with Linaro arm toolchain:
https://www.linaro.org/downloads/

This logic means configure will always fail when you are trying to cross compile, regardless of toolchain:
In configure, around line 5815
##########################################
        if test "$cross_compiling" = yes; then :
  { { $as_echo "$as_me:${as_lineno-$LINENO}: error: in \`$ac_pwd':" >&5
$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
as_fn_error $? "cannot run test program while cross compiling
See \`config.log' for more details" "$LINENO" 5; }
else
  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */

#include <numa.h>

int
main ()
{

#if LIBNUMA_API_VERSION < 2
exit(1);
#endif

  ;
  return 0;
}
_ACEOF
##########################################

**Comment by pevik** [comment]
Hi, thanks for a report. Can you please post relevant part of `config.log` + parameters you passed to `configure` script? Or you can post whole `config.log`, if it's easier for you.

**Comment by alexchu-cpe** [comment]
Added path to toolchain to my path and executed:
make distclean

make autotools
./configure  --host=arm-linux-gnueabihf

[config.log](https://github.com/linux-test-project/ltp/files/1468018/config.log)

**Comment by alexchu-cpe** [comment]
Woops, misclicked the 'close and comment' button :)

**Comment by pevik** [comment]
Confirm, that my commit broke it with linaro arm toolchain (tested on
https://releases.linaro.org/components/toolchain/binaries/latest/arm-linux-gnueabihf/gcc-linaro-7.1.1-2017.08-x86_64_arm-linux-gnueabihf.tar.xz). I'll have look on it.
