### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by margrz** [linux-test-project/ltp#236]
Hello,
I would like to cross compile LTP. In the following way:
```
make autotools
export CC=arm-linux-gnueabihf-gcc
./configure --build=x86_64-linux --host=arm-linux-gnueabihf
```
For version LTP 20160126 everything is ok. But for  LTP 20170929 i get error:

> configure: error: cannot run test program while cross compiling

How to resolve this problem?
Thanks.

**Comment by pevik** [comment]
Closing this as it's a duplicity of #232. I'll try to solve it ASAP.
