### ISSUE TITLE
FAILING_CPUACCT.SH_100_100

### ISSUE THREAD

**Issue by PhongThanVuong** [linux-test-project/ltp#237]
I had run the test case “./cpuacct.sh 100 100” on my ARM board.
Afterward,  I have gotten a problem as bellow:
 
1 TINFO: Creating 100 subgroups each with 100 processes
[69402.212655] imx2_wdt_interrupt: pretimer
[69402.212777] The following is the list of last 50 interrupts for each CPU
[69402.212868] [69402.145532]: irqnumber 1023 cpuid 0
[69402.212960] [69402.145727]: irqnumber 99 cpuid 0
 
And my ARM board restarted immediately.
I think the test case had made my board run out of CPU power(CPU overloading ), so the watchdog timer has identified this problem and restarted the board.
To resolve this problem, I have added a delay with 1 millisecond in “do_test()” function of cpuacct.sh file as below, it will help to release CPU resources
for i in `seq 1 $max`; do
                        for j in `seq 1 $nbprocess`; do
                                    cpuacct_task $testpath/subgroup_$i/tasks &
                                    sleep 0.001
                        done
            done
 
But I worry that the solution makes the test case loss its meaning, whether the test case is a type of stress test or not!
 
Could you please confirm that the solution (adding sleep function) is a right way?

**Comment by metan-ucw** [comment]
No it's not. And BTW adding sleep() in order to fix a test is 99% time mistake.
