### ISSUE TITLE
TFAIL_memcg_usage_in_bytes_test.sh

### ISSUE THREAD

**Issue by PhongThanVuong** [linux-test-project/ltp#239]
There is an issue as below when I ran “./memcg_usage_in_bytes_test.sh” on my ARM board
 
mx6q:/opt/ltp/testcases/bin# ./memcg_usage_in_bytes_test.sh
memcg_usage_in_bytes_test 1 TINFO: Starting test 1
memcg_usage_in_bytes_test 1 TINFO: Running memcg_process --mmap-anon -s 4194304
memcg_usage_in_bytes_test 1 TINFO: Warming up pid: 19889
memcg_usage_in_bytes_test 1 TINFO: Process is still here after warm up: 19889
memcg_usage_in_bytes_test 1 TPASS: memory.usage_in_bytes is 4194304 as expected
memcg_usage_in_bytes_test 2 TINFO: Starting test 2
memcg_usage_in_bytes_test 2 TINFO: Running memcg_process --mmap-anon -s 4194304
memcg_usage_in_bytes_test 2 TINFO: Warming up pid: 19909
memcg_usage_in_bytes_test 2 TINFO: Process is still here after warm up: 19909
memcg_usage_in_bytes_test 2 TFAIL: memory.memsw.usage_in_bytes is 4325376, 4194304 expected
 
It is a dangling falling, sometimes the test result is pass and sometimes is fail
 
My kernel is 
root@mx6q:/dev/shm# uname -a
Linux mx6q 3.14.79-01214-g76b5fd377784 #1 SMP PREEMPT Wed Nov 15 17:06:37 CET 2017 armv7l GNU/Linux

**Comment by chengyli** [comment]
I saw similar error after upgrade kernel to 4.14.11 on centos, the using the Jan 10's ltp commit `b54a54e5881a0f9438ce4a862dee724130a9874f`

```
$ uname -r
4.14.11-1.el7.elrepo.x86_64

memcg_usage_in_bytes_test 1 TINFO: Starting test 1
/opt/ltp/testcases/bin/memcg_lib.sh: line 514: echo: write error: Device or resource busy
memcg_usage_in_bytes_test 1 TINFO: set /dev/memcg/memory.use_hierarchy to 0 failed
memcg_usage_in_bytes_test 1 TINFO: Running memcg_process --mmap-anon -s 4194304
memcg_usage_in_bytes_test 1 TINFO: Warming up pid: 15967
memcg_usage_in_bytes_test 1 TINFO: Process is still here after warm up: 15967
memcg_usage_in_bytes_test 1 TFAIL: memory.usage_in_bytes is 4325376, 4194304 expected
memcg_usage_in_bytes_test 2 TINFO: Starting test 2
/opt/ltp/testcases/bin/memcg_lib.sh: line 514: echo: write error: Device or resource busy
memcg_usage_in_bytes_test 2 TINFO: set /dev/memcg/memory.use_hierarchy to 0 failed
memcg_usage_in_bytes_test 2 TINFO: Running memcg_process --mmap-anon -s 4194304
memcg_usage_in_bytes_test 2 TINFO: Warming up pid: 15987
memcg_usage_in_bytes_test 2 TINFO: Process is still here after warm up: 15987
memcg_usage_in_bytes_test 2 TFAIL: memory.memsw.usage_in_bytes is 4325376, 4194304 expected
```

**Comment by pevik** [comment]
This reports the same error as #93 (see https://github.com/linux-test-project/ltp/issues/93#issuecomment-296889774)
