### ISSUE TITLE
cgroup_fj_stress_debug_4_4_each 1 TBROK: mkdir /sys/kernel/debug/ltp failed

### ISSUE THREAD

**Issue by AnnKong** [linux-test-project/ltp#241]
There is an issue when I ran “./cgroup_fj_stress.sh debug 4 4 each” on my x86 board

Euler:/tmp/4.1-11-22/bin/ltp/testcases/bin # ./cgroup_fj_stress.sh debug 4 4 each
cgroup_fj_stress_debug_4_4_each 1 TINFO: Subsystem debug is mounted at /sys/kernel/debug
cgroup_fj_stress_debug_4_4_each 1 TINFO: Creating subgroups ...
mkdir: cannot create directory `/sys/kernel/debug/ltp': Operation not permitted
cgroup_fj_stress_debug_4_4_each 1 TBROK: mkdir /sys/kernel/debug/ltp failed
cgroup_fj_stress_debug_4_4_each 1 TINFO: Removing all ltp subgroups...
find: `/sys/kernel/debug/ltp/': No such file or directory

My kernel is
Euler:/tmp # uname -r
4.1.46-0.1-default

mount
udev on /dev type tmpfs (rw,relatime,nr_inodes=0,mode=755)
tmpfs on /dev/shm type tmpfs (rw,relatime)
/dev/sda2 on / type ext3 (rw,relatime,errors=continue,barrier=1,data=ordered)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
/dev/sda1 on /boot type ext3 (rw,relatime,errors=continue,barrier=1,data=ordered)
/dev/sda7 on /data type ext3 (rw,relatime,errors=continue,barrier=1,data=ordered)
/dev/sda6 on /euler type ext3 (rw,relatime,errors=continue,barrier=1,data=ordered)
/dev/sda3 on /os2 type ext3 (rw,relatime,errors=continue,barrier=1,data=ordered)
/dev/sda5 on /var/log type ext3 (rw,relatime,errors=continue,barrier=1,data=ordered)

**Comment by metan-ucw** [comment]
It's kind of strange to get EPERM here (I suppose that run the testcase as root).

Does `/sys/kernel/debug/` exist on your computer?

What happens when you try to do the `mkdir /sys/kernel/debug/ltp/` by hand?

**Comment by metan-ucw** [comment]
Feel free to reopen if you have further information on the issue.
