### ISSUE TITLE
Does it support for Android

### ISSUE THREAD

**Issue by sky8336** [linux-test-project/ltp#245]
I built it on android and ran it. I am not sure is there something need to be modified for android X86_64. The message I got:
cached = 27, uncached = 349, threshold 97
read ffffffff9bc00081 = ff   (score=0/1000)
read ffffffff9bc00082 = ff   (score=0/1000)
read ffffffff9bc00083 = ff   (score=0/1000)
read ffffffff9bc00085 = ff   (score=0/1000)
read ffffffff9bc00086 = ff   (score=0/1000)
read ffffffff9bc00087 = ff   (score=0/1000)
read ffffffff9bc00088 = ff   (score=0/1000)
read ffffffff9bc00089 = ff   (score=0/1000)
read ffffffff9bc0008a = ff   (score=0/1000)
read ffffffff9bc0008b = ff   (score=0/1000)
read ffffffff9bc0008c = ff   (score=0/1000)
read ffffffff9bc0008d = ff   (score=0/1000)
read ffffffff9bc0008e = ff   (score=0/1000)
NOT VULNERABLE ON
See uname --help
uname: Unknown option i
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 92
model name      : Intel(R) Atom(TM) Processor E3900 @ 1.90GHz
stepping        : 9
microcode       : 0x2c
cpu MHz         : 2400.000
cache size      : 1024 KB
physical id     : 0

**Comment by pevik** [comment]
What exactly did you run?

**Comment by metan-ucw** [comment]
Also some of the older Atoms are supposedly not affected by meltdown, however E3900 looks new enough.

**Comment by richiejp** [comment]
The test has at least one constant value in it which may need adjusting for slower CPUs. Although I guess it could just be because the CPU's pipeline is not deep enough to fully perform the speculation. Hopefully @paboldin can help.

**Comment by paboldin** [comment]
@sky8336 this is not the thread for paboldin/meltdown support. Please refer to the original project, this is linux-test-project page.

Atoms could be invulnerable to this specific bug. If you are willing to play with it please context me on https://github.com/paboldin/meltdown

**Comment by pevik** [comment]
Closed as it's not related to LTP. Feel free to reopen it, if you think it's LTP issue.
