### ISSUE TITLE
ext4_uninit_groups: TCONF : 'ffsb' not found

### ISSUE THREAD

**Issue by tuyenhv** [linux-test-project/ltp#247]
Hi,
When I ran fs_ext4 tests by: 
# ./runltp -z /dev/sdb1 -f fs_ext4
(tests need a big block device(5G-10G), I created /dev/sdb1)
The result of test for ext4_uninit_groups is TCONF: 'ffsb' not found

The reason that in the ext4_uninit_groups_test.sh file, it checks the ffsb exist or not by using "tst_check_cmds ffsb". The ffsb is located in ${LTPROOT}/bin.
In the runltp file, we just append PATH to ${LTPROOT}/testcases/bin.
Some files were installed to ${LTPROOT}/bin.

So, I think it is better if we set PATH like below in the runltp file:
export PATH="${PATH}:${LTPROOT}/testcases/bin:${LTPROOT}/bin"

Best regards,
Tuyen

**Comment by metan-ucw** [comment]
Sounds good. Can you create patch for runltp and runltplite.sh?
