### ISSUE TITLE
ustat and arm64

### ISSUE THREAD

**Issue by freddy77** [linux-test-project/ltp#25]
Hi,
  on arm64 ustat is not available (as deprecated) however is still tested as LTP. Can it be disabled in someway?

This problem was discovered by Wang Weidong, cfr http://lists.infradead.org/pipermail/linux-arm-kernel/2014-December/312572.html.

Regards,
  Frediano

**Comment by metan-ucw** [comment]
The  best solution would be to add a check for ENOSYS errno into the ustat01.c and ustat02.c source code and issue TCONF (test not suitable for current configuration) message rather than TFAIL. That way this would be fixed for all possible future architectures.

i.e.

```
i f (TEST_RETURN == -1) {
        if (errno == ENOSYS)
                tst_brkm(TCONF, "ustat not supported");
        ...
}
```

**Comment by freddy77** [comment]
https://github.com/linux-test-project/ltp/pull/26
