### ISSUE TITLE
Where is the code to read '/root/.rhosts'?

### ISSUE THREAD

**Issue by jongwook-lee** [linux-test-project/ltp#256]
I am trying to apply LTP, especially network part, on my embeded system that i am developing.
As the guide on LTP, RHOST should be pre-defined in /root/.rhosts file.
I want to change that path to other place( e.g. /ets/.rhosts), but I don't know where it is to process for .rhosts file.

If anybody know that, please help me.

**Comment by pevik** [comment]
Place of global rhost file should be defined in docs or source code of rhost client you use.

I'd recommend you to use network namespaces or ssh based testing as it's described in docs as there are better tested and easier to setup than RSH:
https://github.com/linux-test-project/ltp/tree/master/testcases/network#ltp-network-tests

Please, make sure you use the latest release or current head (master branch).

**Comment by jongwook-lee** [comment]
@pevik, thank you for your comment :)
