### ISSUE TITLE
Write tests for membarrier()

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#265]
There are currently no test for membarrier() syscall in LTP.

See: http://man7.org/linux/man-pages/man2/membarrier.2.html

Basic test that just queries supported barriers with MEMBARRIER_CMD_QUERY should be easy enough. Testing actual barriers implementation would likely be very complicated task.

**Comment by rafaeldtinoco** [comment]
I'm working on this. I have proposed Shuah a modification in their membarrier() basic tests but, at the end, it looks exactly like a LTP test should look (at least the initial interface test) and I'll propose it here.

**Comment by rafaeldtinoco** [comment]
http://lists.linux.it/pipermail/ltp/2018-September/009455.html
