### ISSUE TITLE
Write test for statx()

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#267]
See:

http://man7.org/linux/man-pages/man2/statx.2.html

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a528d35e8bfcc521d7cb70aaf03e1bd296c8493f

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/diff/samples/statx/test-statx.c?id=a528d35e8bfcc521d7cb70aaf03e1bd296c8493f

https://lwn.net/Articles/707602/

**Comment by tarunkumar3096** [comment]
Hi cyril,
      I have submitted patch for statx syscall test code, Kindly review it.
      http://lists.linux.it/pipermail/ltp/2018-July/008715.html

     I am now working on left out flags ATTR_STATX_NOAUTOMOUNT, AT_STATX_FORCE_SYNC, 
     AT_STATX_DONT_SYNC in statx.
    
     

Regards,
     Tarun T U

**Comment by metan-ucw** [comment]
I'm aware, I will look into it ASAP.

**Comment by rafaeldtinoco** [comment]
Should this be closed after:

commit d2678e53ae6cf5e4cd6411bd5ed24ba8519b3a3c
Author: Cyril Hrubis <chrubis@suse.cz>
Date: Tue Sep 4 12:48:10 2018 +0200

syscalls/statx01: Add new test.

commit 4480be56e114e563421469d62b84b0bb68aa04b0
Author: vaishnavid <vaishnavi.d@zilogic.com>
Date: Mon Sep 3 12:17:13 2018 +0000

syscalls/statx02: Add new test.

commit b98fbdcc138439680432a76b06d95ad23b5936be
Author: vaishnavid <vaishnavi.d@zilogic.com>
Date: Mon Sep 3 12:17:53 2018 +0000

syscalls/statx03: Add new test.

commit 5ffb23e2c051c718814515527275e92a8d3155e0
Author: vaishnavid <vaishnavi.d@zilogic.com>
Date: Mon Sep 3 12:18:28 2018 +0000

syscalls/statx04: Add new test.

commit 37fa79858e5ac4d1b88929690e4d2f503b7926d6
Author: Cyril Hrubis <chrubis@suse.cz>
Date: Mon Sep 10 12:59:13 2018 +0200

syscalls/statx05: Add new test.

and related fixes for those ?

**Comment by metan-ucw** [comment]
There are still a few in-flight statx tests (timestamps, AT_NO_AUTOMOUNT, and SYNC_FLAG), let's close this one once these are merged.

**Comment by nareshkamboju** [comment]
Just for the record,
LTP: statx04 STATX_ATTR_COMPRESSED flag is not set for ext2

    * The test fails for ext2 filesystem mounted by kernel ext2 driver,
      which is confirmed to be kernel bug that will be fixed later on
ref:
https://bugs.linaro.org/show_bug.cgi?id=4012

**Comment by metan-ucw** [comment]
We recently added a test for STATX_ATTR_VERITY in 681f89d97b195a72b6c796890402b4a29630cc22 with that the coverage should be reasonably complete. Let's close this now.
