### ISSUE TITLE
Query-LTP network test supports infiniband interface testing

### ISSUE THREAD

**Issue by pshrotre** [linux-test-project/ltp#27]
Hello Team,
          I am getting failures during LTP network stress at udp,tcp,icmp for infiniband interfaces on Linux servers. I have added 20 byte ib addresses for these interfaces in ltp_network_stress still can observe above failures.
          Is LTP supports infiniband interfaces or any hints how i can derive and add infini adresses during LTP network stress ? Your comment can help me to go further on issue.

Regrads,
-Prajakta

**Comment by metan-ucw** [comment]
Sorry I have no idea. Thinking about a best course of action, perhaps you should report the failures on the LTP mailing list they may be or may not to be specific to you setup.
