### ISSUE TITLE
Write tests for init_module(), finit_module(), and delete_module()

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#273]
LTP can build kernel modules so we can as well try to build a dummy kernel module for the test and load it to the kernel.

**Comment by Prachi9974830195** [comment]
Hi metan-ucw,

Did anyone has already worked on it?

Thanks,
Prachi

**Comment by metan-ucw** [comment]
This has been actually fixed in #380, let's close this one as well.

Sorry I'm not that good at updating the tickets, will try to update them more often.
