### ISSUE TITLE
Write test for fremovexattr()

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#276]
We already have a test for removexattr() so this should be simple enough.

**Comment by rafaeldtinoco** [comment]
Related to Issue: #272 & #274

**Comment by rafaeldtinoco** [comment]
I'm working on this.

**Comment by rafaeldtinoco** [comment]
**SYSCALLS**

> removexattr	- removes ext attr from "filename"
> lremovexattr	- if "filename" is a symlink, then attr is removed from the link
> fremovexattr	- identical to removexattr but with file descriptor

**FLAGS**

**RETURN**

> 	SUCCESS =  0 returned
> 	FAILURE = -1 returned, errno is set
> 
> 	errno = ENOATTR		named attr does not exist
> 	errno = ENOTSUP		ext attr are not supported by fs (or disabled)
> 

**TESTS**

```
removexattr
./testcases/kernel/syscalls/removexattr/removexattr01.c - tests xattr removal from a file
./testcases/kernel/syscalls/removexattr/removexattr02.c - tests errors (enodata, enoent, efault)

lremovexattr
:TODO:  ./testcases/kernel/syscalls/lremovexattr/lremovexattr01.c - tests if xattr is removed only from symlink
:TODO:  ./testcases/kernel/syscalls/lremovexattr/lremovexattr02.c - tests errors on symlink only

fremovexattr (fremovexattr could be added to removexattrXX tests as 2nd round with filedes)
:TODO:	./testcases/kernel/syscalls/fremovexattr/fremovexattr01.c - same as removexattr01 (with file desc)
:TODO:	./testcases/kernel/syscalls/fremovexattr/fremovexattr02.c - same as removexattr02 (with file desc)
```

**Comment by rafaeldtinoco** [comment]
Sending patch on the mailing list. Proposing through here to check CI output.
