### ISSUE TITLE
Write sync() and syncfs() tests

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#294]
We need a very basic tests for sync() and syncfs().

For sync() the basic test may do something as:

* dirty large amount of pages by writing into a file
* call sync()
* check that amount of Dirty pages in /proc/meminfo is close to 0

The test for syncfs() would be similar.

**Comment by ngie-eign** [comment]
This would work, but needs retries potentially, in the event the system's under load and the number of pages goes up between when the syscall is called and completes. It also is likely done asynchronously via the VM/swapper system, so the time in-between calls might be variable.

Calling sync on a test filesystem though and verifying that the number of outstanding writes approaches zero via the device-specific sysfs node seems incredibly doable, however: https://unix.stackexchange.com/a/48241 .

**Comment by b49020** [comment]
Hi @metan-ucw @ngie-eign,

I am looking to implement these `sync()` and `syncfs()` tests. So I would like to discuss implementation approach here first.

> Calling sync on a test filesystem though and verifying that the number of outstanding writes approaches zero via the device-specific sysfs node seems incredibly doable, however: https://unix.stackexchange.com/a/48241 .

It seems that `in_flight` (9th column) in `/sys/block/<device>/stat`[1] doesn't indicate the IO requests that are in queue and not issued to device driver. But it rather shows those requests which are issued to device driver and currently under process.

We should rather rely on `write sectors` (7th column) in `/sys/block/<device>/stat`[1] which could provide info regarding actual amount of data written on device. So I would like to propose following approach:

```
# In this case I have used emmc based filesystem
$ cat /sys/block/mmcblk0/stat
   65748      179  7706403   130234    19225    68540 19204104 45878023        0   127832 46939228     2133        0 15267840  1019107
$ dd if=/dev/urandom of=emmc/data oflag=nonblock bs=1K count=32K
$ sync -f emmc/data
$ cat /sys/block/mmcblk0/stat
   65748      179  7706403   130234    19303    68550 19269832 45888176        0   128108 46949220     2133        0 15267840  1019107
# Here we can observe the difference in write sectors corresponds to actual size of data file (including some metadata also).
```
Please feel free to correct me if I missed something.

[1] https://www.kernel.org/doc/Documentation/block/stat.txt

Regards,
Sumit

**Comment by metan-ucw** [comment]
Sounds reasonable. We would have to add a functionality to get the path to the stat file for the test device (the one we get with the .needs_device) flag but that should be reasonably easy to solve.

**Comment by b49020** [comment]
Thanks @metan-ucw for your comments.

BTW, I am new to LTP development process. So I would like to know regarding how to send new patches for LTP project? Is it via github PR or via mailing list?

**Comment by metan-ucw** [comment]
Mailing list is preferred solution as that will reach wider audience, but PR will work as well.

**Comment by b49020** [comment]
Ok will use mailing list.

**Comment by metan-ucw** [comment]
This has been solved in:

b88b3785d15f4c1e75824eef0dfbb54067190482
3b52d81b5ff5c3bf4e592e4358c1ac51d2e42ad7
46e99a3910338d37e3831b9e2505c04a695f9c88
058afc78a9d545bfb4d5869f44ae7e08fce61c6b
7c7ecaeb0179c4b69e6f6c1255656c4231669950
