### ISSUE TITLE
cpuset failed

### ISSUE THREAD

**Issue by persistance** [linux-test-project/ltp#325]
#When i preform the ./runltp -f controllers -s cpuset_base_ops, the following occurs:
![image](https://user-images.githubusercontent.com/12888761/40759025-c2d3ce16-64c2-11e8-87ee-99859350f581.png)
I don't know why I don't have permission to create a file. All test cases starting with "cpu_set" failed for this reason

**Comment by metan-ucw** [comment]
See issue #320, in short the test is outdated and there is patch I will apply hopefully soon.
