### ISSUE TITLE
On the mac virtualbox virtual machine centos7 runs ltp, the virtual machine down

### ISSUE THREAD

**Issue by lnsyyj** [linux-test-project/ltp#328]
`[root@cephL ltp]# ./runltp -f syscalls
INFO: creating /opt/ltp/output directory
INFO: creating /opt/ltp/results directory
Checking for required user/group ids

'nobody' user id and group found.
'bin' user id and group found.
'daemon' user id and group found.
Users group found.
Sys group found.
Required users/groups exist.
If some fields are empty or look unusual you may have an old version.
Compare to the current minimal requirements in Documentation/Changes.

/etc/centos-release
/etc/os-release
/etc/redhat-release
/etc/system-release
CentOS Linux release 7.4.1708 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core) 

uname:
Linux cephL.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

/proc/cmdline
BOOT_IMAGE=/vmlinuz-3.10.0-693.el7.x86_64 root=/dev/mapper/centos-root ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=en_US.UTF-8

Gnu C                  gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Gnu make               3.82
util-linux             linux 2.23.2
mount                  linux 2.23.2(libmount 2.23.0: selinux, debug, assert)
modutils               20
e2fsprogs              1.42.9
Linux C Library        > libc.2.17
Dynamic linker (ldd)   2.17
Procps                 3.3.10
Net-tools              2.10-alpha
iproute2               iproute2-ss130716
iputils                iputils-s20160308
Kbd                    1.15.5
Sh-utils               8.22
Modules Loaded         xt_CHECKSUM ipt_MASQUERADE nf_nat_masquerade_ipv4 tun devlink ip6t_rpfilter ipt_REJECT nf_reject_ipv4 ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_security iptable_raw ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter intel_powerclamp snd_intel8x0 iosf_mbi crc32_pclmul snd_ac97_codec ac97_bus ghash_clmulni_intel snd_seq snd_seq_device ppdev snd_pcm aesni_intel lrw gf128mul glue_helper ablk_helper cryptd pcspkr snd_timer snd i2c_piix4 soundcore sg i2c_core parport_pc parport video nfsd auth_rpcgss nfs_acl lockd grace sunrpc ip_tables xfs libcrc32c sd_mod crc_t10dif sr_mod cdrom crct10dif_generic ata_generic pata_acpi ahci libahci ata_piix libata crct10dif_pclmul crct10dif_common e1000 crc32c_intel serio_raw dm_mirror dm_region_hash dm_log dm_mod

free reports:
              total        used        free      shared  buff/cache   available
Mem:        3881880      674224     1415348       14388     1792308     2888008
Swap:       4063228           0     4063228

/proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
stepping	: 4
cpu MHz		: 2899.998
cache size	: 3072 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch rdseed
bogomips	: 5799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

no big block device was specified on commandline.
Tests which require a big block device are disabled.
You can specify it with option -z
COMMAND:    /opt/ltp/bin/ltp-pan   -e -S   -a 24119     -n 24119 -p -f /tmp/ltp-ZL3g6YaAGb/alltests -l /opt/ltp/results/LTP_RUN_ON-2018_06_02-09h_17m_58s.log  -C /opt/ltp/output/LTP_RUN_ON-2018_06_02-09h_17m_58s.failed -T /opt/ltp/output/LTP_RUN_ON-2018_06_02-09h_17m_58s.tconf
LOG File: /opt/ltp/results/LTP_RUN_ON-2018_06_02-09h_17m_58s.log
FAILED COMMAND File: /opt/ltp/output/LTP_RUN_ON-2018_06_02-09h_17m_58s.failed
TCONF COMMAND File: /opt/ltp/output/LTP_RUN_ON-2018_06_02-09h_17m_58s.tconf
Running tests.......
<<<test_start>>>
tag=abort01 stime=1527945479
cmdline="abort01"
contacts=""
analysis=exit
<<<test_output>>>
abort01     0  TINFO  :  Adjusting RLIMIT_CORE to 1048576
abort01     1  TPASS  :  abort dumped core
abort01     2  TPASS  :  abort raised SIGIOT
abort01     3  TPASS  :  abort dumped core
abort01     4  TPASS  :  abort raised SIGIOT
abort01     5  TPASS  :  abort dumped core
abort01     6  TPASS  :  abort raised SIGIOT
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=accept01 stime=1527945479
cmdline="accept01"
contacts=""
analysis=exit
<<<test_output>>>
accept01    1  TPASS  :  bad file descriptor successful
accept01    2  TPASS  :  bad file descriptor successful
accept01    3  TPASS  :  invalid socket buffer successful
accept01    4  TPASS  :  invalid salen successful
accept01    5  TPASS  :  invalid salen successful
accept01    6  TPASS  :  no queued connections successful
accept01    7  TPASS  :  UDP accept successful
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=accept4_01 stime=1527945479
cmdline="accept4_01"
contacts=""
analysis=exit
<<<test_output>>>
accept04_01    1  TPASS  :  Test passed
accept04_01    2  TPASS  :  Test passed
accept04_01    3  TPASS  :  Test passed
accept04_01    4  TPASS  :  Test passed
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=access01 stime=1527945479
cmdline="access01"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1015: INFO: Timeout per run is 0h 05m 00s
access01.c:262: PASS: access(accessfile_rwx, F_OK) as root
access01.c:262: PASS: access(accessfile_rwx, F_OK) as nobody
access01.c:262: PASS: access(accessfile_rwx, X_OK) as root
access01.c:262: PASS: access(accessfile_rwx, X_OK) as nobody
access01.c:262: PASS: access(accessfile_rwx, W_OK) as root
access01.c:262: PASS: access(accessfile_rwx, W_OK) as nobody
access01.c:262: PASS: access(accessfile_rwx, R_OK) as root
access01.c:262: PASS: access(accessfile_rwx, R_OK) as nobody
access01.c:262: PASS: access(accessfile_rwx, R_OK|W_OK) as root
access01.c:262: PASS: access(accessfile_rwx, R_OK|W_OK) as nobody
access01.c:262: PASS: access(accessfile_rwx, R_OK|X_OK) as root
access01.c:262: PASS: access(accessfile_rwx, R_OK|X_OK) as nobody
access01.c:262: PASS: access(accessfile_rwx, W_OK|X_OK) as root
access01.c:262: PASS: access(accessfile_rwx, W_OK|X_OK) as nobody
access01.c:262: PASS: access(accessfile_rwx, R_OK|W_OK|X_OK) as root
access01.c:262: PASS: access(accessfile_rwx, R_OK|W_OK|X_OK) as nobody
access01.c:262: PASS: access(accessfile_x, X_OK) as root
access01.c:262: PASS: access(accessfile_x, X_OK) as nobody
access01.c:262: PASS: access(accessfile_w, W_OK) as root
access01.c:262: PASS: access(accessfile_w, W_OK) as nobody
access01.c:262: PASS: access(accessfile_r, R_OK) as root
access01.c:262: PASS: access(accessfile_r, R_OK) as nobody
access01.c:282: PASS: access(accessfile_r, X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_r, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_r, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_w, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_w, X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_w, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_x, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_x, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_r, W_OK|X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_r, W_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_r, R_OK|X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_r, R_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_r, R_OK|W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_r, R_OK|W_OK|X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_r, R_OK|W_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_w, W_OK|X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_w, W_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_w, R_OK|X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_w, R_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_w, R_OK|W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_w, R_OK|W_OK|X_OK) as root: EACCES
access01.c:282: PASS: access(accessfile_w, R_OK|W_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_x, W_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_x, R_OK|X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_x, R_OK|W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessfile_x, R_OK|W_OK|X_OK) as nobody: EACCES
access01.c:262: PASS: access(accessfile_r, W_OK) as root
access01.c:262: PASS: access(accessfile_r, R_OK|W_OK) as root
access01.c:262: PASS: access(accessfile_w, R_OK) as root
access01.c:262: PASS: access(accessfile_w, R_OK|W_OK) as root
access01.c:262: PASS: access(accessfile_x, R_OK) as root
access01.c:262: PASS: access(accessfile_x, W_OK) as root
access01.c:262: PASS: access(accessfile_x, R_OK|W_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_r, F_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_r, R_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_r, W_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_w, F_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_w, R_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_w, W_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_x, F_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_x, R_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_x, W_OK) as root
access01.c:262: PASS: access(accessdir_r/accessfile_x, X_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_r, F_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_r, R_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_r, W_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_w, F_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_w, R_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_w, W_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_x, F_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_x, R_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_x, W_OK) as root
access01.c:262: PASS: access(accessdir_w/accessfile_x, X_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_r, F_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_r, F_OK) as nobody
access01.c:262: PASS: access(accessdir_x/accessfile_r, R_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_r, R_OK) as nobody
access01.c:262: PASS: access(accessdir_x/accessfile_r, W_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_w, F_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_w, F_OK) as nobody
access01.c:262: PASS: access(accessdir_x/accessfile_w, R_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_w, W_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_w, W_OK) as nobody
access01.c:262: PASS: access(accessdir_x/accessfile_x, F_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_x, F_OK) as nobody
access01.c:262: PASS: access(accessdir_x/accessfile_x, R_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_x, W_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_x, X_OK) as root
access01.c:262: PASS: access(accessdir_x/accessfile_x, X_OK) as nobody
access01.c:262: PASS: access(accessdir_rw/accessfile_r, F_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_r, R_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_r, W_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_w, F_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_w, R_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_w, W_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_x, F_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_x, R_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_x, W_OK) as root
access01.c:262: PASS: access(accessdir_rw/accessfile_x, X_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_r, F_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_r, F_OK) as nobody
access01.c:262: PASS: access(accessdir_rx/accessfile_r, R_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_r, R_OK) as nobody
access01.c:262: PASS: access(accessdir_rx/accessfile_r, W_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_w, F_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_w, F_OK) as nobody
access01.c:262: PASS: access(accessdir_rx/accessfile_w, R_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_w, W_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_w, W_OK) as nobody
access01.c:262: PASS: access(accessdir_rx/accessfile_x, F_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_x, F_OK) as nobody
access01.c:262: PASS: access(accessdir_rx/accessfile_x, R_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_x, W_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_x, X_OK) as root
access01.c:262: PASS: access(accessdir_rx/accessfile_x, X_OK) as nobody
access01.c:262: PASS: access(accessdir_wx/accessfile_r, F_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_r, F_OK) as nobody
access01.c:262: PASS: access(accessdir_wx/accessfile_r, R_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_r, R_OK) as nobody
access01.c:262: PASS: access(accessdir_wx/accessfile_r, W_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_w, F_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_w, F_OK) as nobody
access01.c:262: PASS: access(accessdir_wx/accessfile_w, R_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_w, W_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_w, W_OK) as nobody
access01.c:262: PASS: access(accessdir_wx/accessfile_x, F_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_x, F_OK) as nobody
access01.c:262: PASS: access(accessdir_wx/accessfile_x, R_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_x, W_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_x, X_OK) as root
access01.c:262: PASS: access(accessdir_wx/accessfile_x, X_OK) as nobody
access01.c:282: PASS: access(accessdir_r/accessfile_r, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_r, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_r, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_r, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_r, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_w, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_w, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_w, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_w, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_w, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_x, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_x, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_x, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_r/accessfile_x, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_r, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_r, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_r, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_r, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_r, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_w, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_w, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_w, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_w, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_w, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_x, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_x, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_x, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_w/accessfile_x, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_r, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_r, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_r, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_w, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_w, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_w, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_x, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_x/accessfile_x, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_r, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_r, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_r, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_r, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_r, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_w, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_w, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_w, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_w, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_w, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_x, F_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_x, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_x, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rw/accessfile_x, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_r, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_r, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_r, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_w, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_w, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_w, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_x, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_rx/accessfile_x, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_r, W_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_r, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_r, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_w, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_w, X_OK) as root: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_w, X_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_x, R_OK) as nobody: EACCES
access01.c:282: PASS: access(accessdir_wx/accessfile_x, W_OK) as nobody: EACCES

Summary:
passed   199
failed   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=2 cstime=3
<<<test_end>>>
<<<test_start>>>
tag=access02 stime=1527945479
cmdline="access02"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1015: INFO: Timeout per run is 0h 05m 00s
access02.c:158: PASS: access(file_f, F_OK) as root behaviour is correct.
access02.c:158: PASS: access(file_f, F_OK) as nobody behaviour is correct.
access02.c:158: PASS: access(file_r, R_OK) as root behaviour is correct.
access02.c:158: PASS: access(file_r, R_OK) as nobody behaviour is correct.
access02.c:158: PASS: access(file_w, W_OK) as root behaviour is correct.
access02.c:158: PASS: access(file_w, W_OK) as nobody behaviour is correct.
access02.c:158: PASS: access(file_x, X_OK) as root behaviour is correct.
access02.c:158: PASS: access(file_x, X_OK) as nobody behaviour is correct.
access02.c:158: PASS: access(symlink_f, F_OK) as root behaviour is correct.
access02.c:158: PASS: access(symlink_f, F_OK) as nobody behaviour is correct.
access02.c:158: PASS: access(symlink_r, R_OK) as root behaviour is correct.
access02.c:158: PASS: access(symlink_r, R_OK) as nobody behaviour is correct.
access02.c:158: PASS: access(symlink_w, W_OK) as root behaviour is correct.
access02.c:158: PASS: access(symlink_w, W_OK) as nobody behaviour is correct.
access02.c:158: PASS: access(symlink_x, X_OK) as root behaviour is correct.
access02.c:158: PASS: access(symlink_x, X_OK) as nobody behaviour is correct.

Summary:
passed   16
failed   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=1 cstime=1
<<<test_end>>>
<<<test_start>>>
tag=access03 stime=1527945479
cmdline="access03"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1015: INFO: Timeout per run is 0h 05m 00s
access03.c:66: PASS: access(0xffffffffffffffff, F_OK) as root: EFAULT
access03.c:66: PASS: access(0xffffffffffffffff, F_OK) as nobody: EFAULT
access03.c:66: PASS: access(0xffffffffffffffff, R_OK) as root: EFAULT
access03.c:66: PASS: access(0xffffffffffffffff, R_OK) as nobody: EFAULT
access03.c:66: PASS: access(0xffffffffffffffff, W_OK) as root: EFAULT
access03.c:66: PASS: access(0xffffffffffffffff, W_OK) as nobody: EFAULT
access03.c:66: PASS: access(0xffffffffffffffff, X_OK) as root: EFAULT
access03.c:66: PASS: access(0xffffffffffffffff, X_OK) as nobody: EFAULT

Summary:
passed   8
failed   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=access04 stime=1527945479
cmdline="access04"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1015: INFO: Timeout per run is 0h 05m 00s
access04.c:87: PASS: access as root failed expectedly: EINVAL
access04.c:87: PASS: access as nobody failed expectedly: EINVAL
access04.c:87: PASS: access as root failed expectedly: ENOENT
access04.c:87: PASS: access as nobody failed expectedly: ENOENT
access04.c:87: PASS: access as root failed expectedly: ENAMETOOLONG
access04.c:87: PASS: access as nobody failed expectedly: ENAMETOOLONG
access04.c:87: PASS: access as root failed expectedly: ENOTDIR
access04.c:87: PASS: access as nobody failed expectedly: ENOTDIR
access04.c:87: PASS: access as root failed expectedly: ELOOP
access04.c:87: PASS: access as nobody failed expectedly: ELOOP
access04.c:87: PASS: access as root failed expectedly: EROFS
access04.c:87: PASS: access as nobody failed expectedly: EROFS

Summary:
passed   12
failed   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=acct01 stime=1527945479
cmdline="acct01"
contacts=""
analysis=exit
<<<test_output>>>
acct01      0  TINFO  :  Using test device LTP_DEV='/dev/loop0'
acct01      0  TINFO  :  Formatting /dev/loop0 with ext2 opts='' extra opts=''
mke2fs 1.42.9 (28-Dec-2013)
acct01      1  TPASS  :  acct failed as expected: TEST_ERRNO=EISDIR(21): Is a directory
acct01      2  TPASS  :  acct failed as expected: TEST_ERRNO=EACCES(13): Permission denied
acct01      3  TPASS  :  acct failed as expected: TEST_ERRNO=ENOENT(2): No such file or directory
acct01      4  TPASS  :  acct failed as expected: TEST_ERRNO=ENOTDIR(20): Not a directory
acct01      5  TPASS  :  acct failed as expected: TEST_ERRNO=EPERM(1): Operation not permitted
acct01      6  TPASS  :  acct failed as expected: TEST_ERRNO=EPERM(1): Operation not permitted
acct01      7  TPASS  :  acct failed as expected: TEST_ERRNO=ELOOP(40): Too many levels of symbolic links
acct01      8  TPASS  :  acct failed as expected: TEST_ERRNO=ENAMETOOLONG(36): File name too long
acct01      9  TPASS  :  acct failed as expected: TEST_ERRNO=EROFS(30): Read-only file system
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=1 cstime=1
<<<test_end>>>
<<<test_start>>>
tag=add_key01 stime=1527945479
cmdline="add_key01"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1015: INFO: Timeout per run is 0h 05m 00s
add_key01.c:38: PASS: add_key call succeeded

Summary:
passed   1
failed   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=add_key02 stime=1527945479
cmdline="add_key02"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1015: INFO: Timeout per run is 0h 05m 00s
packet_write_wait: Connection to 192.168.56.102 port 22: Broken pipe
`

**Comment by jstancek** [comment]
Looks like you found a kernel bug, you can confirm by checking serial console or setting up kdump to capture vmcore. Nothing here suggest a problem on LTP side.

**Comment by lnsyyj** [comment]
@metan-ucw @tang-chen @jstancek I am doing your interview questions
The kernel version is as follows: 
[root@cephL ~]# cat /proc/version 
Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017

**Comment by jstancek** [comment]
As suspected, it's kernel bug. Looking at RH bugzilla, this problem has been fixed in kernel-3.10.0-794.el7.
Nothing to do on LTP side, closing.
