### ISSUE TITLE
perf_event_open02.c test failed (ratio was greater than ) 

### ISSUE THREAD

**Issue by minhhungft9** [linux-test-project/ltp#329]
Recently, Linaro community has suggested skipping this test case on all board, https://review.linaro.org/#/c/23909/

In addition, I found a patchwork on kernel indicated that the test case won't fail anymore on kernel 4.5-rc6, which includes:

- Fixing scaling vs. perf_install_in_context()
- Fixing scaling vs. perf_event_enable()
- Fixing scaling vs. perf_event_enable_on_exec()
- Fixing ctx time tracking by introducing EVENT_TIME

https://patchwork.kernel.org/patch/8006581/

Do you have any idea about this test case? Thank you.

**Comment by metan-ucw** [comment]
Was the test still failing before 4.5-rc6 after the patch I've applied recently in a3c0ce0a6d00 or were you running the test without that patch?
