### ISSUE TITLE
Open08 FAIL, If It opens a test executable

### ISSUE THREAD

**Issue by gnourt89** [linux-test-project/ltp#330]
I had run the test case “./open08” on my ARM board
Test case was failed when we tried to open a test executable (in this case "/bin/cat" ) in WRONLY mode with Read-only file system error.
open08      1  TPASS  :  expected failure - errno = 17 : File exists
open08      2  TPASS  :  expected failure - errno = 21 : Is a directory
open08      3  TPASS  :  expected failure - errno = 20 : Not a directory
open08      4  TPASS  :  expected failure - errno = 36 : File name too long
open08      5  TFAIL  :  open08.c:121: unexpected error - 30 : Read-only file system - expected 13
open08      6  TPASS  :  expected failure - errno = 14 : Bad address

I analyzed this.If I mount root device read-write by command "/bin/mount -o rw, remount / ", Test case will be passed.
open08      1  TPASS  :  expected failure - errno = 17 : File exists
open08      2  TPASS  :  expected failure - errno = 21 : Is a directory
open08      3  TPASS  :  expected failure - errno = 20 : Not a directory
open08      4  TPASS  :  expected failure - errno = 36 : File name too long
open08      5  TPASS  :  expected failure - errno = 13 : Permission denied
open08      6  TPASS  :  expected failure - errno = 14 : Bad address

I found that normally kernel will be mounted the root file system as read-only to improve device security.
Please check and confirm:
1. In this case, Do we need to open "/bin/cat"(Read-only file system) in WRONLY mode?
2. Do we need to mount the root file system as read-write before we perform testing for this case? Or need some suitable changes in test case?

**Comment by metan-ucw** [comment]
The best solution would be changing the testcase not to open anything outside the test temporary directory and to create all files needed for the testing there in the setup() function.

**Comment by jstancek** [comment]
Posted for review: http://lists.linux.it/pipermail/ltp/2018-June/008448.html
