### ISSUE TITLE
Rename TEST_ERRNO and TEST_RETURN

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#336]
When I was redesigning the test library I kept the TEST() macro as it was in previous version, in retrospective this has been a mistake I should have renamed these to match the new library tst_ prefix and also shortened them to something as TST_ERR and TST_RET. Some may argue that variables should be lower case but in this case I like the uppercase which is hinting the user that these are special variables defined in the test library.

So this issue is about renaming these variables for new library, which should be easy enough job.

**Comment by jstancek** [comment]
Should the TEST() macro also be renamed to have TST prefix, or just TST(), or do we keep it as 'TEST()'?

**Comment by metan-ucw** [comment]
Hi!
> Should the TEST() macro also be renamed to have TST prefix, or just TST(), or do we keep it as 'TEST()'?

TST() sounds too cryptic to me, and I do not care that much if we call
it TST_TEST() or TEST(), TST_TEST() would be a bit cleaner but TEST()
is shorther...

-- 
Cyril Hrubis
chrubis@suse.cz

**Comment by vapier** [comment]
we need to keep the concepts of "errno" and "error" separate.  they aren't the same.
