### ISSUE TITLE
Simplify the fuzzy sync library for the common case

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#338]
I've used the library to synchronize two threads for the inotify09.c testcase and it's quite easy to forget one of the calls and end up with one of the threads stuck in an infinite loop.

The current code for the reproducer thread looks like:
             
```
static void *reproducer_thread(void *unused)
{
        while (tst_fzsync_wait_update_b(&fzsync_pair)) {
                tst_fzsync_delay_b(&fzsync_pair);
                // CALL THE RACY SYSCALL HERE
                tst_fzsync_time_b(&fzsync_pair);
                // DO ANY OTHER WORK HERE
                if (!tst_fzsync_wait_b(&fzsync_pair))
                        break;
        }
        return unused;
}
```

The two comments usually end up being just one call. We may as well simplify it with macros a bit, which would reduce possibility for a user error.

Maybe something as:

```
static void *write_seek(void *unused)
{
        TST_FZYNC_LOOP_B(
                 SAFE_WRITE(0, fd, buf, sizeof(buf)), // racy syscall
                 SAFE_LSEEK(fd, 0, SEEK_SET) // setup for next iteration
         )
         return unused;
}
```

And we should do something similar about the loop in the main thread as well.

**Comment by richiejp** [comment]
Yeah, so to clarify you are talking about the call to tst_fzsync_wait_b at the bottom of the loop which appears redundant until you _really_ think it through.

The macro looks nice, but we have not used the library a lot yet so I wonder if it really is the common case. It may be significant whether your take the time before or after the system call for example. Maybe it would be better to write a Coccinelle script (or similar) which uses some heuristic to warn the author about common problems.

**Comment by metan-ucw** [comment]
> Yeah, so to clarify you are talking about the call to tst_fzsync_wait_b at the bottom of the loop which appears redundant until you really think it through.

I do not understand why we have a `while(tst_fzsync_wait_update_b(&fzsync_pair))` as well as ` if (!tst_fzsync_wait_b(&fzsync_pair)) break;` either. Generally the interface is quite complex and easy to make a typo, it's not really clear where to call wait and where to call wait_update for instance.

I would expect that the most common case could be described as:

* optional pre preparation
* racy syscall
* optional post preparation

For both threads A as well as B, but that is just my guess, we should probably review reasonable sample of the CVE reproduces to get a better picture, or we may draft something and redesign it later on once we have more complete picture.

Also I guess that we should be passing the fzync_pair to the library explicitly to the macro or hide it in the library completely.

**Comment by metan-ucw** [comment]
Let's close this, the fuzzy sync library has been finalized long time ago.
