### ISSUE TITLE
Increase fallocate05 coverage

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#356]
Recently we hit a bug in fallocate() on Btrfs on ppc64le where PAGE_SIZE is greater than the size used in the fallocate05 testcase and it's reproducible on x86_64 if we change the FALLOCATE_SIZE to be less than PAGE_SIZE. The fallocate05 test should probably be changed to cycle through several fallocate sizes per each filesystem.

**Comment by mdoucha** [comment]
This ticket was resolved by c0ebfa14956439ca54126c1f37152a9d8ca3eadc
