### ISSUE TITLE
Use timer with fuzzy sync to limit execution time

### ISSUE THREAD

**Issue by richiejp** [linux-test-project/ltp#370]
Limiting the execution time by the number of iterations results in timeout failures on slower machines. Instead we should try to perform as many iterations as possible in a limited time. This can be done with the timer API.

**Comment by metan-ucw** [comment]
Sounds much better than pre-defined number of iterations.

The question is how to determine the runtime, one option would be measuring how long it takes to trigger the issue on different machines and multiply it by some reasonable constant, e.g. 2.

We should probably also automatically adjust the test timeout to be based on the runtime as well, something as 1.5 * runtime should work well I guess.

**Comment by richiejp** [comment]
> The question is how to determine the runtime, one option would be measuring how long it takes to trigger the issue on different machines and multiply it by some reasonable constant, e.g. 2.

It is very difficult to get right, especially for devs without a wide selection of hardware, but it seems like the only solution until we can create something a lot more ambitious. I think the importance of the vulnerability/bug should also be taken into account. Users are probably more willing to burn electricity/time finding a major bug than a less important one.

I suspect with the right algorithm we could get most bugs to activate so quickly we could just have a default time of less than a second.

Having looked at the library code and tests cases again, I think this will require some small modifications to both the library and maybe all tests which are using it. Verifying the tests still work after any changes could be a big pain.
