### ISSUE TITLE
ZRAM and Swap memory configuration in LTP test cases.

### ISSUE THREAD

**Issue by gnourt89** [linux-test-project/ltp#376]
Hello all,
There are some concerns related to ZRAM and Swap memory configuration in LTP test cases as below:
1. Zram might only be needed to be enabled only for some and not for all the LTP tests, is that right?
2. If Zram only enable for some test cases which need that feature only. How can we control this in our test suite to ensure that it disable for test no need?
3. Is there any effect on the testing result when we enable Zram in kernel?

Please help to check and confirm if possible
Thanks and best regards!

**Comment by metan-ucw** [comment]
Enabled zram is explicitly needed only for the three zram testcases, the rest of the LTP should run fine regardless if zram is enabled or not.

To disable tests a skipfile with names of tests to be skipped can be passed to runltp script.
