### ISSUE TITLE
read_all - avoid touching /dev/watchdog

### ISSUE THREAD

**Issue by jstancek** [linux-test-project/ltp#377]
Documentation/watchdog/wdt.txt says:
All the interfaces provide /dev/watchdog, which when open must be written
to within a timeout or the machine will reboot.

So, inproper release leads to surprising reboots. In some occasions without any call trace.

**Comment by metan-ucw** [comment]
Haven't we fixed this by dropping privileges before we attempt to traverse over the /dev/ subtree? See the -p option we pass to read_all in the case of /dev/ filesystem in the runtest/fs.

**Comment by jstancek** [comment]
Good point, but it still manages to crash my system. I'm looking into this some more.

**Comment by jstancek** [comment]
OK, turns out system didn't have 2ba7534264e96933ac3fba1aa3f1059c565b076a applied. Closing, NOTABUG.
