### ISSUE TITLE
move_pages12: timeout on aarch64 servers with big hugepages

### ISSUE THREAD

**Issue by major** [linux-test-project/ltp#387]
We found an LTP failure on 4.18 during the `move_pages12` test:

```
<<<test_output>>>
tst_test.c:1015: INFO: Timeout per run is 0h 05m 00s
move_pages12.c:199: INFO: Free RAM 122147776 kB
move_pages12.c:217: INFO: Increasing 524288kB hugepages pool on node 0 to 4
move_pages12.c:227: INFO: Increasing 524288kB hugepages pool on node 1 to 4
move_pages12.c:143: INFO: Allocating and freeing 4 hugepages on node 0
move_pages12.c:143: INFO: Allocating and freeing 4 hugepages on node 1
Test timeouted, sending SIGKILL!
tst_test.c:1055: INFO: If you are running on slow machine, try exporting LTP_TIMEOUT_MUL > 1
tst_test.c:1056: BROK: Test killed! (timeout?)

Summary:
passed   0
failed   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=300 termination_type=exited termination_id=2 corefile=no
cutime=14740 cstime=15258
<<<test_end>>>
```

It appears that the test is hitting the timeout due to very large hugepages on an aarch64 server. The test ran on a `Huawei TaiShan 2280`.

**Comment by metan-ucw** [comment]
Hmm, the tests actually does memset() over two huge pages in a loop that does 1000 iterations while child process moves the huge pages between two NUMA nodes. No wonder that this timeouts for 512MB pages. I guess that increasing the timeout wouldn't be much better as the test would run for ages (you can try to set the timeout to -1 in the tst_test structure and measure how long the test runs). So I guess that we should skip the test in a case that huge pages are too big, i.e. check for hugepage size in the setup and do tst_brk(TCONF, ...) if the size is too big.

**Comment by major** [comment]
@metan-ucw Oh, I wasn't aware that there were that many iterations. That certainly does explain a lot.

**Comment by jstancek** [comment]
Could we add a time check into that loop? Something like "stop after 1000 iterations or after ~4 minutes".

**Comment by metan-ucw** [comment]
@jstancek we can use the new and shiny timer functions we added for the CVE related testcases, then we can run this tests with pre-defined time limit instead of for pre-defined number of iterations. The questions is how many iterations we can do for 512MB pages and if we even have a chance to trigger a bug with that...

**Comment by jstancek** [comment]
Posted v1 for review: https://lists.linux.it/pipermail/ltp/2018-August/009133.html
