### ISSUE TITLE
mmap15: failed on qemu mips64

### ISSUE THREAD

**Issue by Nettoysfkf** [linux-test-project/ltp#390]
Failed:
`mmap15      1  TFAIL  :  mmap15.c:86: mmap into high region failed unexpectedly - expect errno=ENOMEM, got: errno=EINVAL(22): Invalid argument`
uname -a:
`Linux qemumips64 4.18.0-rc6-yoctodev-standard #1 SMP PREEMPT Mon Sep 10 03:20:29 UTC 2018 mips64 mips64 mips64 GNU/Linux
`
I use gdb debug kernel, I found in file mm/mmap.c, get_unmapped_area function:
`addr = get_area(file, addr, len, pgoff, flags);`
this return -22, errno=EINVAL(22)

**Comment by DengkeDu** [comment]
Why define the [0xa000000000000000UL](https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/mmap/mmap15.c#L44) for __ia64__?
I means if I using mips64, what the value can I use?

**Comment by metan-ucw** [comment]
The problem with the test is that the high address is architecture specific.

You have to specify address that is above the process address space but at the same time you have to get address that is usable for mapping the memory.

If you look at the commit that changed the address for ia64 you will see:

    mmap15: Fix for ia64
    
    The task size on ia64 is 0xa000000000000000UL and the task memory is
    divided into segments which does not cover whole task memory but instead
    there are holes that couldn't be used for mappings and these are
    considered "usupported by architecture" and fails with ENIVAL. We
    happened to hit that with the previous value.

**Comment by jstancek** [comment]
Should we drop this test or relax the condition (e.g. any errno is PASS)?

**Comment by DengkeDu** [comment]
For mips and mips64, return EINVAL, the kernel check the [addr](https://github.com/torvalds/linux/blob/master/arch/mips/mm/mmap.c#L71)
For x86, return ENOMEM, the kernel not check the [addr](https://github.com/torvalds/linux/blob/master/arch/x86/kernel/sys_x86_64.c#L192)
So I think EINVAL and ENOMEM all right.

**Comment by metan-ucw** [comment]
@jstancek I would be for passing with both ENOMEM and EINVAL. I doubt that there are any other errnos that are correct responses for an invalid address.
