### ISSUE TITLE
mmap_11-4.run-test

### ISSUE THREAD

**Issue by csqshz** [linux-test-project/ltp#391]
Source code: testcases/open_posix_testsuite/conformance/interfaces/mmap/11-4.c
`62:  snprintf(tmpfname, sizeof(tmpfname), "/tmp/pts_mmap_11_5_%d", getpid());`

If '/tmp' mentioned above is mounted with tmpfs, it will fail with promption, "Test FAILED: Modification of the partial page, at the end of an object is written out"

If '/tmp' is mounted with ext4 fs, it will success.

Could someone tell me why?

Reproduce:
    You can reproduce the issue on any linux distributions.

Thanks.

**Comment by DengkeDu** [comment]
Change the mapped file on real filesystem not on tempfs?
