### ISSUE TITLE
The arguement of fcntl is changed with no reason

### ISSUE THREAD

**Issue by csqshz** [linux-test-project/ltp#395]
32-bit arch
l_len is set '1': 
[https://github.com/linux-test-project/ltp/blob/2b0ec7699939534d460932a68a1b7cc531e6c106/testcases/kernel/syscalls/fcntl/fcntl34.c#L74](url)

But when calls SAFE_FCNTL():
[https://github.com/linux-test-project/ltp/blob/2b0ec7699939534d460932a68a1b7cc531e6c106/testcases/kernel/syscalls/fcntl/fcntl34.c#L79](url)

The value of l_len is changed to '0'.
I used 'strace -f ./fcntl34' to trace the process.
`[pid   310] fcntl64(6, F_OFD_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, --> **l_len=0** <--- } <unfinished ...>`

So why the value of l_len is changed to '0'.

**Comment by jstancek** [comment]
This looks like 32-bit arch, so my guess is some mixup between flock and flock64 structs.
Can you provide more details about your environment?
Is the test failing or is this just strace output?
Have you tried replacing SAFE_FCNTL with syscall(__NR_fcntl64,...) ? Does that make a difference?

**Comment by csqshz** [comment]
> This looks like 32-bit arch, so my guess is some mixup between flock and flock64 structs.
> Can you provide more details about your environment?
> Is the test failing or is this just strace output?
> Have you tried replacing SAFE_FCNTL with syscall(__NR_fcntl64,...) ? Does that make a difference?

syscall(__NR_fcntl64,...) makes the program running normally.

**Comment by jstancek** [comment]
Could be related to glibc's commit:
  06ab719d30b0 ("Fix Linux fcntl OFD locks for non-LFS architectures (BZ#20251)")

which now casts arg to flock and then fills in flock64 struct:
```
      case F_OFD_SETLKW:
        {
          struct flock *flk = (struct flock *) arg;
          struct flock64 flk64 =
          {
            .l_type = flk->l_type,
            .l_whence = flk->l_whence,
            .l_start = flk->l_start,
            .l_len = flk->l_len,
            .l_pid = flk->l_pid
          };
```

**Comment by csqshz** [comment]
> Could be related to glibc's commit:
> 06ab719d30b0 ("Fix Linux fcntl OFD locks for non-LFS architectures (BZ#20251)")

I didn't understand it well.
Should ltp be modified?

**Comment by jstancek** [comment]
What distro/arch/kernel/glibc do you have?

**Comment by fweimer** [comment]
`fcntl` always uses `struct flock` arguments. If you use `struct flock64`, you should be using `fcntl64`. The issue also goes away if you build with `-D_FILE_OFFSET_BITS=64` because then `struct flock` and `struct flock64` are basically identical.

The reason for the change was that there is no 32-bit version of the OFD locks and no separate `F_OFD_SETLKW` constant, and that `fcntl` defaulting to 64-bit in 32-bit mode was just too confusing. The previous/non-OFD locks did not do that.

**Comment by csqshz** [comment]
> `fcntl` always uses `struct flock` arguments. If you use `struct flock64`, you should be using `fcntl64`. The issue also goes away if you build with `-D_FILE_OFFSET_BITS=64` because then `struct flock` and `struct flock64` are basically identical.



> 
> The reason for the change was that there is no 32-bit version of the OFD locks and no separate `F_OFD_SETLKW` constant, and that `fcntl` defaulting to 64-bit in 32-bit mode was just too confusing. The previous/non-OFD locks did not do that.

**Comment by jstancek** [comment]
I'm planning to post patch for LTP.

**Comment by csqshz** [comment]
> `fcntl` always uses `struct flock` arguments. If you use `struct flock64`, you should be using `fcntl64`. 
1. _FILE_OFFSET_BITS is not defined
Whether using fcntl or fcntl64 in ltp/.../fcntl34.c, it doesn't work.
[](url)

Unless replace SAFE_FCNTL with syscall(__NR_fcntl64,...)


The issue also goes away if you build with `-D_FILE_OFFSET_BITS=64` because then `struct flock` and `struct flock64` are basically identical.
> 
> The reason for the change was that there is no 32-bit version of the OFD locks and no separate `F_OFD_SETLKW` constant, and that `fcntl` defaulting to 64-bit in 32-bit mode was just too confusing. The previous/non-OFD locks did not do that.

**Comment by csqshz** [comment]
> I'm planning to post patch for LTP.

I found that compile ltp with -D_FILE_OFFSET_BITS=64 is fine.

**Comment by csqshz** [comment]
> I'm planning to post patch for LTP.

Could you tell me how do you want to do？

**Comment by jstancek** [comment]
I want to convert 32-bit OFD fcntl() calls to use fcntl64() syscall directly. Rest can use glibc's fcntl() func with struct flock, which should work on old and new glibc.
