### ISSUE TITLE
Question: sigwaitinfo01.c, 374: why is the (void *)1 ?

### ISSUE THREAD

**Issue by csqshz** [linux-test-project/ltp#398]
Source code:
[https://github.com/linux-test-project/ltp/blob/d365ea2dee8e141eff3ccef62543cc88f6d95f52/testcases/kernel/syscalls/sigwaitinfo/sigwaitinfo01.c#L374](url)

I doesn't understand why use "(void *)1".
Where does the (void *)1 point to?

Thanks.

**Comment by jstancek** [comment]
Nowhere, it's test for invalid ptr.
Is this by chance related to http://lists.linux.it/pipermail/ltp/2018-September/009338.html ?
