### ISSUE TITLE
migrate_pages02 fails on Huawei aarch64 hosts

### ISSUE THREAD

**Issue by spbnick** [linux-test-project/ltp#407]
The following reproduces quite reliably (but not all the time) on Huawei aarch64 hosts:

    migrate_pages02    5  TFAIL  :  migrate_pages02.c:159: pid(37337) addr 0x27705c80 not on expected node: 2 , expected 1

As investigated by @jstancek, it appears NUMA balancing takes the page to a different node right after the migration and before the check, the test passes reliably after switching from malloc to mmap and turning off NUMA balancing.

CC'ing @wangli5665 on @jstancek request.

**Comment by jstancek** [comment]
Suggested course:
1) change private anonymous case to use mmap rather than malloc, or align malloc ptr to page
2) turn off numa balancing while running this test
3) print mem stats only on TFAIL - to reduce test output

**Comment by metan-ucw** [comment]
I guess that we will need a library function to turn off NUMA balancing for the set_mempolicy() tests I'm working on so that it will not move pages in the middle of the test for the MPOL_PREFERRED.
