### ISSUE TITLE
setrlimit05 failed on mips

### ISSUE THREAD

**Issue by csqshz** [linux-test-project/ltp#416]
**My project was qemu-mips.**
**The child process was killed by SIGBUS. I didn't know why.**

**I found that the testcase was killed before implementing the following code.**
`SYSCALL_DEFINE2(setrlimit, unsigned int, resource, struct rlimit __user *, rlim)`

**Debugged with gdb: It implement the following code. But I was not well known about them.**
`handle_sys () at /usr/src/kernel/arch/mips/kernel/scall32-o32.S:104`
`104		li	t0, -EMAXERRNO - 1	# error?`
`(gdb) s`
`105		sltu	t0, t0, v0`
`(gdb) `
`106		sw	t0, PT_R7(sp)		# set error flag`
`(gdb) `
`107		beqz	t0, 1f`
`(gdb) `
`112	1:	sw	v0, PT_R2(sp)		# result`
`(gdb) `
`115		j	syscall_exit_partial`
`

Thanks.

**Comment by metan-ucw** [comment]
Hmm, we do pass (void *)-1 as the address and expect to get 'EFAULT'. As far as I can tell some architectures return 'SIGBUS' when we try to access an address that technically cannot be used for mappings, I think that I've seen that on Itanium. So it's quite likely that there is no problem at all.

I do wonder if there are any other tests that fail like this as (void *)-1 has been used frequently in LTP as an invalid address.

Also we do have 'tst_get_bad_addr()' helper now, which will return an address that should work on mips as well. Does the test work fine if you pass address from the tst_get_bad_addr() to the setrlimit() call?

**Comment by csqshz** [comment]
> Hmm, we do pass (void *)-1 as the address and expect to get 'EFAULT'. As far as I can tell some architectures return 'SIGBUS' when we try to access an address that technically cannot be used for mappings, I think that I've seen that on Itanium. So it's quite likely that there is no problem at all.
> 
> I do wonder if there are any other tests that fail like this as (void *)-1 has been used frequently in LTP as an invalid address.
> 
> Also we do have 'tst_get_bad_addr()' helper now, which will return an address that should work on mips as well. Does the test work fine if you pass address from the tst_get_bad_addr() to the setrlimit() call?

**It works by modifying setrlimit05.c as following:**
`void * bad_addr = tst_get_bad_addr(NULL);`
`TEST(setrlimit(RLIMIT_NOFILE, (struct rlimit *)bad_addr));`

The former code is as following:
`TEST(setrlimit(RLIMIT_NOFILE, (void *)-1));`

**Comment by csqshz** [comment]
> I do wonder if there are any other tests that fail like this as (void *)-1 has been used frequently in LTP as an invalid address.

Sorry, I have not tested all cases. And maybe each arch has different processing methods when meet (void *)-1.

**Comment by metan-ucw** [comment]
This has been fixed in 80bed467bc6ab
