### ISSUE TITLE
the mcast4-queryfld01 problem

### ISSUE THREAD

**Issue by fun2yang** [linux-test-project/ltp#437]
this case was in net_stress.multicast ,when i test this case in my system,it was faild， Also failed in the latest kernel（4.20.0-rc5）
it will show this error : 'sendto(): No buffer space available' 

i don't know it's a problem in this case or a problem in the kernel,but the error apper in this file '/home/src/ltp/testcases/network/stress/ns-tools/ns-mcast_join.c' ，it always send igmp query to '224.0.0.1' ,but i don't know why do this .
lhost use this commond 'rsh -n xxxx /opt/ltp/testcases/bin/ns-igmp_querier -I eth0 -t 3600 -r 0' to set up this service

**Comment by fun2yang** [comment]
This test uses 10 cpu and 10240 memory on my virtual machine.
"mcast4-queryfld01 mcast4-queryfld01" this is the case

**Comment by pevik** [comment]
To be honest I'm not able to run most of multicast tests. IMHO there is no much point trying to fix some issue before cleanup and rewrite into network API (see #440). Feel free to assign to it, I'll help you with review.

**Comment by pevik** [comment]
Tests has been rewritten, see #440. I suppose error is ok. Feel free to reopen if not.
