### ISSUE TITLE
increase fsync() converage

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#452]
The fsync() coverage for error conditions is lacking, currently it covers EBADF and EINVAL for pipe. We should at least check for EINVAL for socket and EROFS as well.

**Comment by metan-ucw** [comment]
Also the fsync03 test should be converted into the new library format in a separate patch before we attempt to add any new functiontality.

**Comment by ngie-eign** [comment]
The EROFS part is going to be a bit tricky, potentially, depending on how it's done.

**Comment by mdoucha** [comment]
Working on it.

**Comment by Martchus** [comment]
Looks like this has been implemented in fda6b32a48d09ffe13e63eac62c42a4060a2c0f2 and d4c1590845568f8226a8afb9974410edcb2acd39 so this issue can likely be closed.

**Comment by metan-ucw** [comment]
Yep, looks complete enough.
