### ISSUE TITLE
the VIRT_PERF_THRESHOLD problem

### ISSUE THREAD

**Issue by fun2yang** [linux-test-project/ltp#453]
when i test the "vxlan_multi_03 vxlan03.sh -d multi" case,It will succeed on a host of 10 CPUs but will fail on 2 CPUs of the same host.so i want to ask what's the standard of the VIRT_PERF_THRESHOLD

size =10000
vxlan03 1 TINFO: IP4 vxlan over IP4 slower by 319 % （per）
vxlan03 1 TINFO: IP6 vxlan over IP4 slower by 434 %  (per6)
vxlan03 1 TFAIL: Test failed, threshold: 160 %

**Comment by pevik** [comment]
@fun2yang Do you use netns or SSH based testing?

**Comment by akodanev** [comment]
Not sure what is the "size 10000" in the log, number of requests  "-r" option?

If you use ssh, this likely means that there are two hosts involved in this test. And netns - for a single host setup (using veth). With two hosts, the result might be influenced by the link setup, switches used and Nic drivers, available offloads. That is why we need a tunable threshold to adjust according to the test environment.

VxLAN adds overhead and you should decide how much is acceptable threshold for your setup, may be compare to the other virtual tunnels, for example geneve, or gre, etc.

You may also try a single thread setup, environment variable:
TST_NETLOAD_CLN_NUMBER=1

And increase the number of requests, to make results more stable, with:
TST_NETLOAD_CLN_REQUESTS=100000

**Comment by pevik** [comment]
@fun2yang can we close the issue?
