### ISSUE TITLE
clock_settime/clock_settime_8-1: hardly ever passes

### ISSUE THREAD

**Issue by rafaeldtinoco** [linux-test-project/ltp#478]
This test hardly ever passes with recent kernels. I have made different tests in different architectures:

https://bugs.linaro.org/show_bug.cgi?id=3965#c13
https://bugs.linaro.org/show_bug.cgi?id=3965#c14
https://bugs.linaro.org/show_bug.cgi?id=3965#c15

and I would say 95% of the times this test fails with a DELTA time of 2 seconds, when the acceptable DELTA would be just 1 second.

**Comment by jstancek** [comment]
No luck reproducing it on x86 kvm guest so far:
```
# for i in `seq 1 10`; do ./clock_settime_8-1.run-test ; done
Test PASSED
Test PASSED
Test PASSED
Test PASSED
Test PASSED
Test PASSED
Test PASSED
Test PASSED
Test PASSED
Test PASSED
# uname -r
5.0.0-rc3+
```

I don't recall seeing this test fail before. There have been hardly any changes made to that test for 5+ years.

Your experiment with increasing values by 2 shows, that the gap increased as well. Is there a ntp/chrony/etc. running that could interfere with the test?

Are you able to get output from "strace -f -t -T"?
How long does the test run when it fails? "time ./clock_settime_8-1.run-test"
Do you have a link for your x86 kernel config? I could try building with that one.

**Comment by metan-ucw** [comment]
Feel free to reopen if the test still fails for you and please include the requested information as well.
