### ISSUE TITLE
Get rid of include_j_h.h library

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#482]
There are two remanding tests that use the ugly library get_mempolicy01 and sigwaitinfo01 after that it could be finally deleted.

**Comment by pevik** [comment]
Patch sent https://patchwork.ozlabs.org/project/ltp/patch/20201208132814.16497-1-pvorel@suse.cz/

**Comment by pevik** [comment]
Merged in eb9908ab3.
