### ISSUE TITLE
Write tests for namespace ioctl()s

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#483]
See:
http://man7.org/linux/man-pages/man2/ioctl_ns.2.html

There are no tests for the NS_GET_* ioctls() at the moment.

**Comment by fedeb95** [comment]
Hi, I'd like to work on this

**Comment by pevik** [comment]
@fedeb95 You're welcome :). If you can, please send patches to our ML (https://lists.linux.it/listinfo/ltp), that's preferred over using github pull requests.

**Comment by fedeb95** [comment]
Thanks, it may take a while since I'm new to the project. I'll make sure to follow the guide part about mailing from git then

**Comment by metan-ucw** [comment]
Implemented in 3c8704ff14ff5a7ba371aafeffe3513b674d6651
