### ISSUE TITLE
testcases/bin mentioned in README is missing in this github

### ISSUE THREAD

**Issue by kribalac** [linux-test-project/ltp#505]
README file says that Each test case has its own executable or script in tescases/bin. Also the testcases/data folder has been removed.

**Comment by metan-ucw** [comment]
Which README file?

Also each test executable _is_ installed into $PREFIX/testcases/bin directory.

Also is this a bugreport or a question? Can you please state the problem more clearly?

**Comment by kribalac** [comment]
I am refering to  ltp/README.md file in this github.

Uptil ltp bucket ltp20180515 we were having bin and data folders as below :
[krishnaja@kte (AUS) testcases]$ ls ltp20180515/testcases
Makefile  **bin**  commands  cve  **data**  kdump  kernel  lib  misc  network  open_posix_testsuite  realtime
Since 20180926 release, data and bin folders are not present:
[krishnaja@kte (AUS) ltp]$ ls ltp_20180926/testcases
Makefile  commands  cve  kdump  kernel  lib  misc  network  open_posix_testsuite  realtime
[krishnaja@kte (AUS) ltp]$

**Comment by kribalac** [comment]
If this was intentional, then this issue would rather be a question, how is the directory changes handles? 
Since we were directly executing the testcases using executable or script in testcases/bin our test setup seems to be broken. Could you please suggest what changes went through..and how we need to execute our tests?

**Comment by pevik** [comment]
You're mixing directory with installed LTP (in case of ltp20180515) and source directory (ltp_20180926).
Using git log you see, that `testcases/bin` nor `testcases/data` never exist.

**Comment by kribalac** [comment]
As I understood, these 2 directories show up once ltp is installed. I shall revisit my test setup. Thanks for help.

**Comment by pevik** [comment]
Yes, i.e. not in tarball or git tree, but in prefix after `make install`. Default prefix is `/opt/ltp`.
Feel free to reopen this ticket if you find something broken.
