### ISSUE TITLE
Add infrastructure to choose between libc syscall wrapper and direct call using syscall()

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#506]
It has been discussed on the LTP mailing list that testing only libc wrapper or only the direct syscall is not sufficient. From the system point of view, we should make sure that the libc wrappers are working fine, but in certain cases older syscalls may be emulated by calling newer ones so either way we test we would loose some coverage.

The best solution would be testing both. We can either prepare some build-time magic to build two tests for both scenarios, just like we do on for the 16bit syscall variants. Or we can choose which one to run at runtime. It may be possible to do this in the test library as well, so that the run function would be executed twice once for libc wrapper and once for raw syscall.

**Comment by metan-ucw** [comment]
RFC send to ML http://patchwork.ozlabs.org/project/ltp/list/?series=95706

**Comment by pevik** [comment]
V3 from metan (likely to be merged)
https://patchwork.ozlabs.org/project/ltp/list/?series=98725&state=*

**Comment by metan-ucw** [comment]
Fixed in ce08216e743f3a319068299d304f90a1dbafcd29
