### ISSUE TITLE
configure --without-foo options mishandle 3rd & 4th args to AC_ARG_WITH

### ISSUE THREAD

**Issue by pevik** [linux-test-project/ltp#508]
Current configure options `--with-{numa,tirpc}` are used to disable autotools
detection of presence headers and libraries (+ in case of NUMA it also changes
error message of the compiled binary).
But this confuses users a bit as usually --without-foo usually means that part
of the software is completely excluded (not being compiled). It's also confusing
as `--with-open-posix-testsuite` and `--with-realtime-testsuite` options work like users
expect it.
IMHO we compile binaries which only say "compiled without FOO support" because
runtime files expect them, but this could be solved by not installing affected
runtime files. The obvious benefits are smaller size and shorter compiled time.

There could be these configured options (all default on):
`--with{,out}-syscalls` (or kernel?)
`--with{,out}-net`
`--with{,out}-rpc` (we removed RPC support, so we have TIRPC only now)
`--with{,out}-numa`
`--with{,out}-cve` (this one is problematic, as it's also among syscalls)
`--with{,out}-commands` (or userspace ?)

**Comment by vapier** [comment]
it's simply a bug.  the 3rd/4th args to many `AC_ARG_WITH` macros are currently incorrect.

for numa, it's:
```
AC_ARG_WITH([numa],
  AC_HELP_STRING([--without-numa], [without numa support (default=no)]),
  [with_numa=no],
  [with_numa=yes]
)
```

the `with_numa=no` is supposed to be `with_numa=$withval`.  the `with_numa=yes` prob should be `with_numa=auto` and adapting the numa logic to handle that tristate.

**Comment by pevik** [comment]
Joerg actually sent patch containing also fixes you proposed.
https://lists.linux.it/pipermail/ltp/2019-November/014403.html
