### ISSUE TITLE
Write tests for pidfd

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#511]
Looks like pidfd patches has been merged into 5.0 rc now, once 5.0 is out we should write tests for it:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3eb39f47934f
https://lwn.net/Articles/773459/

**Comment by amannch** [comment]
I started working on that

**Comment by pevik** [comment]
Merged as these commits:
106a60d2f syscalls/pidfd_send_signal03
36a08e2a2 syscalls/pidfd_send_signal02
e3c82be31 syscalls/pidfd_send_signal01

Thanks for your work Christian.
