### ISSUE TITLE
fs_perms01 failed 

### ISSUE THREAD

**Issue by gnourt89** [linux-test-project/ltp#513]
fs_perms01 is failing on arm systems (kernel 3.14): 
**#./fs_perms 005 99 99 12 100 x 0
fs_perms    1  TFAIL  :  fs_perms.c:238: x a 005 file owned by (99/99) as user/group (12/100)**

I analyzed this case and found that: 
The requested access would be denied to the file since "var/volatile" mounted with noexec option so can't access to file and permission denied when executing a file as nobody.
Solution: run 2 command “mount -t tmpfs -o remount,exec /var/volatile” and “chmod o+x /bin/sh”. The test will be passed.
**#./fs_perms 005 99 99 12 100 x 0
fs_perms    1  TPASS  :  x a 005 file owned by (99/99) as user/group (12/100)**

So I want to ask, Does the test lose its meaning if we changed the system like that before doing the test? or Is that the necessary requirement before we run this test case?
What is the best solution in this case?
This is also happens for fs_perms02, fs_perms03.

**Comment by metan-ucw** [comment]
The test uses tst_tmpdir() call that creates test temporary directory on the top of the path passed in TMPDIR (which defaults to /tmp). If that path is mounted with noexec a few tests will fail there is not much we can do about it.

And the same with /bin/sh, if that is not executable on the system, some tests will fail.
