### ISSUE TITLE
af_alg04 crash the ppc64 LPAR(P9)

### ISSUE THREAD

**Issue by chetjain** [linux-test-project/ltp#522]
af_alg04 crash the ppc64 LPAR(P9)

Is this test doing an intentional crash? When it is run on RHEL8.0 latest kernel, it immediately crashes the LPAR
Power platform: ppc64 (p9)

**Comment by chetjain** [comment]
[root@vimlp1 crash]# uname -a
Linux vimlp1.isst.aus.stglabs.ibm.com 4.18.0-80.el8.ppc64le #1 SMP Wed Mar 13 11:26:21 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

**Comment by pevik** [comment]
Your kernel is probably missing commit [bb2964810233](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bb29648102335586e9a66289a1d98a0cb392b6e5) ("crypto: vmac - separate tfm and request context"), which is described at the test (https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/crypto/af_alg04.c).
See also warning added in LTP commit b694897a9.

**Comment by pevik** [comment]
@ebiggers FYI

**Comment by chetjain** [comment]
Thanks,
Should we request RedHat to pick this up in their upcoming kernel. How do I test to verify this now?

**Comment by jstancek** [comment]
Feel free to BZ at bugzilla.redhat.com. Easiest way to work around it for now is to comment this test out in "runtest/crypto" file.

**Comment by chetjain** [comment]
I have an internal bugzilla opened now and it is under screen. Will mirror to RH soon

**Comment by chetjain** [comment]
RH Bugzilla  RH1702702. We are trying to include bb2964810233 in the latest red kernel to verify this. Stay tuned.

**Comment by chetjain** [comment]
The commit has fixed this issue.
