### ISSUE TITLE
tst_require_root: command not found

### ISSUE THREAD

**Issue by chetjain** [linux-test-project/ltp#523]
Most of the LTP test suites are failing " tst_require_root: command not found" not found error.
tst_require_root file is also not found under any LTP directory. How to overcome this?

Platform: Power9
Distro: RHEL 4.18.0-80.el8.ppc64le

Example:
Tried to run can test suite. -->

INFO: creating /opt/ltp/results directory
Checking for required user/group ids

'nobody' user id and group found.
'bin' user id and group found.
'daemon' user id and group found.
Users group found.
Sys group found.
Required users/groups exist.
If some fields are empty or look unusual you may have an old version.
Compare to the current minimal requirements in Documentation/Changes.

/etc/os-release
/etc/redhat-release
/etc/system-release
NAME="Red Hat Enterprise Linux"
VERSION="8.0 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.0"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.0:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.0"
Red Hat Enterprise Linux release 8.0 (Ootpa)
Red Hat Enterprise Linux release 8.0 (Ootpa)

uname:
Linux vimlp1.isst.aus.stglabs.ibm.com 4.18.0-80.el8.ppc64le #1 SMP Wed Mar 13 11:26:21 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

/proc/cmdline
BOOT_IMAGE=/vmlinuz-4.18.0-80.el8.ppc64le root=/dev/mapper/rhel_vimlp1-root ro crashkernel=2048M rd.lvm.lv=rhel_vimlp1/root rd.lvm.lv=rhel_vimlp1/swap

Gnu C                  gcc (GCC) 8.2.1 20180905 (Red Hat 8.2.1-3)
Clang                 
Gnu make               4.2.1
util-linux             linux 2.32.1
mount                  linux 2.32.1 (libmount 2.32.1: selinux, btrfs, debug)
modutils               25
e2fsprogs              1.44.3
Linux C Library        > libc.2.28
Dynamic linker (ldd)   2.28
Procps                 3.3.15
Net-tools              2.10-alpha
iproute2               iproute2-ss180813
iputils                iputils-s20180629
Kbd                    2.0.4
Sh-utils               8.30
Modules Loaded         can_raw can loop xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nft_counter nf_nat_tftp nf_conntrack_tftp tun bridge stp llc kvm_pr kvm devlink rpcsec_gss_krb5 auth_rpcgss nfsv4 dns_resolver nfs lockd grace fscache nf_tables_set nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat_ipv6 nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 nft_chain_route_ipv6 nft_chain_nat_ipv4 nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nft_chain_route_ipv4 nf_conntrack libcrc32c ip6_tables nft_compat ip_set nf_tables nfnetlink sunrpc sg pseries_rng xts vmx_crypto binfmt_misc ip_tables ext4 mbcache jbd2 dm_service_time sd_mod ibmvfc scsi_transport_fc ibmveth dm_multipath dm_mirror dm_region_hash dm_log dm_mod

free reports:
              total        used        free      shared  buff/cache   available
Mem:        4150272     1548736     2210176        5056      391360     2127168
Swap:       6291392      428800     5862592

cpuinfo:
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  8
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Model:               2.2 (pvr 004e 0202)
Model name:          POWER9 (architected), altivec supported
Hypervisor vendor:   pHyp
Virtualization type: para
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            10240K
NUMA node0 CPU(s):   0-7

AppArmor disabled

SELinux status:                 disabled
no big block device was specified on commandline.
Tests which require a big block device are disabled.
You can specify it with option -z
COMMAND:    /opt/ltp/bin/ltp-pan   -e -S   -a 27262     -n 27262 -p -f /tmp/ltp-AplpX06kWU/alltests -l /opt/ltp/results/LTP_RUN_ON-2019_04_24-20h_53m_39s.log  -C /opt/ltp/output/LTP_RUN_ON-2019_04_24-20h_53m_39s.failed -T /opt/ltp/output/LTP_RUN_ON-2019_04_24-20h_53m_39s.tconf
INFO: Restricted to can_filter
LOG File: /opt/ltp/results/LTP_RUN_ON-2019_04_24-20h_53m_39s.log
FAILED COMMAND File: /opt/ltp/output/LTP_RUN_ON-2019_04_24-20h_53m_39s.failed
TCONF COMMAND File: /opt/ltp/output/LTP_RUN_ON-2019_04_24-20h_53m_39s.tconf
Running tests.......
<<<test_start>>>
tag=can_filter stime=1556153620
cmdline="can_run_tests.sh can_filter"
contacts=""
analysis=exit
<<<test_output>>>
/opt/ltp/testcases/bin/can_run_tests.sh
/opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
modprobe: FATAL: Module vcan not found.
Usage: tst_brkm TTYPE FUNC STRING
	TTYPE  - Test Result Type; one of TFAIL, TBROK and TCONF.
	FUNC   - Cleanup function (ignored), but MUST be provided
	STRING - Message explaining the test result
modprobe: FATAL: Module vcan not found in directory /lib/modules/4.18.0-80.el8.ppc64le
Usage: tst_brkm TTYPE FUNC STRING
	TTYPE  - Test Result Type; one of TFAIL, TBROK and TCONF.
	FUNC   - Cleanup function (ignored), but MUST be provided
	STRING - Message explaining the test result
RTNETLINK answers: Operation not supported
Usage: tst_brkm TTYPE FUNC STRING
	TTYPE  - Test Result Type; one of TFAIL, TBROK and TCONF.
	FUNC   - Cleanup function (ignored), but MUST be provided
	STRING - Message explaining the test result
/opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0 type vcan failed: ret - 2: command not found
Cannot find device "vcan0"
Usage: tst_brkm TTYPE FUNC STRING
	TTYPE  - Test Result Type; one of TFAIL, TBROK and TCONF.
	FUNC   - Cleanup function (ignored), but MUST be provided
	STRING - Message explaining the test result
Device "vcan0" does not exist.
Usage: tst_brkm TTYPE FUNC STRING
	TTYPE  - Test Result Type; one of TFAIL, TBROK and TCONF.
	FUNC   - Cleanup function (ignored), but MUST be provided
	STRING - Message explaining the test result
SIOCGIFINDEX: No such device
(null)      1  TFAIL  :  ltpapicmd.c:188: Test can_filter FAIL
incrementing stop
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=2 cstime=0
<<<test_end>>>
INFO: ltp-pan reported all tests PASS
LTP Version: 20190115

       ###############################################################

            Done executing testcases.
            LTP Version:  20190115
       ###############################################################

can_filter.LOG:/opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
can_rcv_own_msgs.LOG:/opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
can_run_tests.sh.LOG:/opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
can_run_tests.sh.LOG:/opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
cpuacct.sh.LOG:/opt/ltp/testcases/bin/cgroup_fj_common.sh: line 85: tst_require_root: command not found

**Comment by pevik** [comment]
We can't help you without pasting command you run. `can_run_tests.sh` uses legacy shell API [test.sh](https://github.com/linux-test-project/ltp/blob/master/testcases/lib/test.sh), which contain function `tst_require_root`. I'd expect something like `/opt/ltp/testcases/bin/can_run_tests.sh: 26: .: test.sh: not found`.

**Comment by chetjain** [comment]
/opt/ltp/runltp -f can

**Comment by chetjain** [comment]
Hi, Can someone help us here?

**Comment by chetjain** [comment]
It is some PATH issue. This can be closed

**Comment by sasibindut** [comment]
Hi pevik,

please help us how to get/where to find  tst_test_cmds,tst_tmpdir,tst_require_root  binary files.

vimlp1:~/MY_LTP/ltp-master/testcases # /opt/ltp/testcases/bin/ssh-stress
/opt/ltp/testcases/bin/ssh-stress
# tst_net_iface_prefix.c:145: INFO: prefix and interface not found for 'fd00:1:1:1::2'.

(null)      0  TINFO  :  Network
(null)      0  TINFO  :  eth0
(null)      0  TINFO  :  10.33.15.199/16
(null)      0  TINFO  :  fd00:1:1:1::2/64
/opt/ltp/testcases/bin/tst_net.sh: line 336: tst_test_cmds: command not found
/opt/ltp/testcases/bin/ssh-stress: line 48: tst_require_root: command not found
/opt/ltp/testcases/bin/ssh-stress: line 49: tst_test_cmds: command not found
/opt/ltp/testcases/bin/tst_net.sh: line 336: tst_test_cmds: command not found
/opt/ltp/testcases/bin/ssh-stress: line 60: tst_tmpdir: command not found
(null)      0  TINFO  :  Generate configuration file and key at the remote host
(null)      0  TINFO  :  Generate authorized_keys
(null)      0  TINFO  :  restore context of authorized_keys

Thanks in Advance

**Comment by pevik** [comment]
@chetjain in `$LTPROOT/testcases/bin/` which is as default (and also as your case) in `/opt/ltp/testcases/bin/`).
