### ISSUE TITLE
pcrypt_aead01 crashing the LPAR

### ISSUE THREAD

**Issue by chetjain** [linux-test-project/ltp#525]
Running the crypto testsuite is crashing the P9 LPAR.
@./runtest -f crypto
kernel: 4.18.0-80.el8.bug177022.ppc64le 

Tried the apply the commit from issue mentioned in #522, but not helped. Opened RH bug as well  RH1702779

crash> bt
PID: 6850   TASK: c0000000ac40a480  CPU: 1   COMMAND: "pcrypt_aead01"
 #0 [c00000011a8873e0] crash_kexec at c000000000234210
 #1 [c00000011a887420] oops_end at c000000000027868
 #2 [c00000011a8874a0] bad_page_fault at c000000000078c38
 #3 [c00000011a887510] handle_page_fault at c00000000000a710
 Data Access [300] exception frame:
 R0:  c000000000637850    R1:  c00000011a887800    R2:  c0000000015bd100   
 R3:  c0000000fce2dc00    R4:  c00000011a8878d0    R5:  0000000000000000   
 R6:  0000000000000001    R7:  ffffffffffffffff    R8:  0000000000000000   
 R9:  c0000000fce2dc00    R10: ffffffff00000001    R11: d000000000a21e60   
 R12: c0000000006377f0    R13: c000000007faee00    R14: 000000001001e4c0   
 R15: 00007fffcb185b20    R16: 0000000010042d70    R17: 0000000010042d78   
 R18: 000000001004055c    R19: 00007fffcb1859f8    R20: 00007fffcb185a08   
 R21: 0000000000000c93    R22: c00000011a8878d0    R23: c00000011a887820   
 R24: c0000000fce2dc10    R25: 0000000000000000    R26: c0000000fce2dc00   
 R27: c00000011a887840    R28: c0000000014bfb90    R29: c00000011a887830   
 R30: c00000011a8878d0    R31: 0000000000000000   
 NIP: c000000000636598    MSR: 8000000000009033    OR3: c000000000008934
 CTR: c0000000006377f0    LR:  c000000000637850    XER: 0000000020040000
 CCR: 0000000024008844    MQ:  0000000000000000    DAR: 0000000000000000
 DSISR: 0000000040000000     Syscall Result: 0000000000000000
 [NIP  : crypto_remove_spawns+152]
 [LR   : crypto_unregister_instance+96]
 #4 [c00000011a887800] crypto_remove_spawns at c000000000636598
 #5 [c00000011a8878b0] crypto_unregister_instance at c000000000637850  (unreliable)
 #6 [c00000011a887900] crypto_del_alg at d000000000a21768 [crypto_user]
 #7 [c00000011a887960] crypto_user_rcv_msg at d000000000a20a54 [crypto_user]
crash>

**Comment by pevik** [comment]
Finding bugs is LTP goal, which sometimes involves kernel oops. But there is no point to report kernel with this sort of bugs/vulnerabilities (It's not a bug in a test it's an expected behavior, or what do you expect from us to do? Am I missing something?).
You need to report it to your kernel provider (Red Hat in your case).
