### ISSUE TITLE
ext4-new-features: rewrite into new API

### ISSUE THREAD

**Issue by pevik** [linux-test-project/ltp#527]
Tests under [`testcases/kernel/fs/ext4-new-features/`](https://github.com/linux-test-project/ltp/tree/master/testcases/kernel/fs/ext4-new-features/) should be either rewritten into new shell API (or deleted if no longer relevant).

These tests are not in any runtest file (`runtest/fs_ext4`): `ext4-alloc-test.sh`, `ext4_inode_version_test.sh`, `ext4_journal_checksum.sh`, `ext4_online_defrag_test.sh` (probably has never been enabled.
\+ I guess [xfstests tests](https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git) are probably better source for ext4 testing.

**Comment by xuyang0410** [comment]
@pevik  Since these case has been deleted after your patch [29f51a85b12](https://github.com/linux-test-project/ltp/commit/29f51a85b122c08744d759286b9b54de95ec89aa) , we should close this issue.
