### ISSUE TITLE
Cannot run test when root FS in RO-mode

### ISSUE THREAD

**Issue by CrazyLionHeart** [linux-test-project/ltp#53]
Because zoo-file created in root-fs (which could be read-only) - test case failed with error: 
pan(8410): Could not open zoo as "8410", errno:30 Read-only file system

**Comment by metan-ucw** [comment]
Looks like the runltp script passes `-a $$` to the ltp-pan and there is no way to override it. You can workaround this by changing the PAN_COMMAND string in runltp script to something as `-a /tmp/$$` for now.

The proper solution would likely be adding a switch to the script, I will have a look into that.

**Comment by metan-ucw** [comment]
This should be fixed now, there were several recent commit to fix this mainly c5e8c14a8df94963b2417eaf23f7be5d76483db3 and e5964d69ee021305e4e28ed1dfe7e796b071fe54.
