### ISSUE TITLE
Question: Should I manually configure cgroup for sched_rr_get_interval01 case

### ISSUE THREAD

**Issue by csqshz** [linux-test-project/ltp#533]
sched_rr_get_interval01 case failed with error info:
"TBROK  :  sched_rr_get_interval01.c:131: sched_setscheduler() failed"
"sched_setscheduler(0, SCHED_RR, [1])    = -1 EPERM (Operation not permitted)"

I find this is because: the group that sched_rr_get_interval01 case process belongs to is not set cpu.rt_runtime.us.

I didn't find any reference about doing some preparation for sched_rr_get_interval01 case.
So I want to know if I should manually preparing related cgroup in advance.

**Comment by metan-ucw** [comment]
LTP tests does not support being executed inside of a cgroup. Tests that require root, which this one does, expect to have unrestricted access.
