### ISSUE TITLE
lcov flagging C++ Doxygen comments as unvisited

### ISSUE THREAD

**Issue by noloader** [linux-test-project/ltp#534]
I'm working on Fedora 29 x86_64, fully patched. I have a C++ project with Doxygen comments. It looks like lcov is marking Doxygen comments as unvisited, and it is driving coverage down to 25% in some cases.

My recipe to perform the coverage test is at https://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L1125 . In the recipe, syms = `-g3` and opts = `-O1`. All the coverage tests,
like lcov, asan, ubsan and valgrind, use the same.

-----

![lcov-doxygen](https://user-images.githubusercontent.com/3538226/58301273-ce94ff80-7db3-11e9-9cb7-f74564dc0fc6.png)

-----

```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 29 (Twenty Nine)
Release:        29
Codename:       TwentyNine

$ dnf info lcov
Installed Packages
Name         : lcov
Version      : 1.13
Release      : 5.fc29
Architecture : noarch
Size         : 368 k
Source       : lcov-1.13-5.fc29.src.rpm
Repository   : @System
From repo    : fedora
Summary      : LTP GCOV extension code coverage tool
URL          : http://ltp.sourceforge.net/coverage/lcov.php
License      : GPLv2+
Description  : LCOV is an extension of GCOV, a GNU tool which provides
             : information about what parts of a program are actually executed
             : (i.e. "covered") while running a particular test case. The
             : extension consists of a set of PERL scripts which build on the
             : textual GCOV output to implement HTML output and support for
             : large projects.
```

**Comment by pevik** [comment]
Thanks for your report, Jeffrey. This is issue tracker for LTP project. Please put your issue into lcov project: https://github.com/linux-test-project/lcov/issues.
