### ISSUE TITLE
Should not use tst_brk after calling cleanup_ipc()

### ISSUE THREAD

**Issue by fallen** [linux-test-project/ltp#537]
in the process of exiting, after having printed the Summary, do_cleanup() is called.
Which then calls cleanup_ipc(), which unmaps results. See 
https://github.com/linux-test-project/ltp/blob/master/lib/tst_test.c#L924
https://github.com/linux-test-project/ltp/blob/master/lib/tst_test.c#L138

But then, afterward, tst_wallclock_restore() is called which itself can call tst_brk upon some syscall failure: https://github.com/linux-test-project/ltp/blob/0410a51c961b830ddbea85ebcf28a948c02e5077/lib/tst_wallclock.c#L59

This is wrong since tst_brk will call do_exit again and will try to de-reference results ( https://github.com/linux-test-project/ltp/blob/master/lib/tst_test.c#L593 ) and this leads to a segfault.

I experienced this segfault while running tests and for some reason the tst_clock_settime call failed.

output example:
> 
> Summary:
> passed   6
> failed   0
> skipped  0
> warnings 0
> tst_wallclock.c:59: BROK: tst_clock_settime() realtime failed: EINVAL
> 
> Summary:
> Segmentation fault
> 

Another solution would be to make `results` NULL upon unmapping it.

**Comment by metan-ucw** [comment]
I guess that we can move the tst_wallclock_restore() before the call to the cleanup_ipc(), that should fix the problem as well.

**Comment by fallen** [comment]
Yes I agree.

**Comment by fallen** [comment]
But maybe adding some `results = NULL` upon unmapping would also be a safe thing to do anyway.

**Comment by metan-ucw** [comment]
Sure, zeroing results after unmapping sounds good as well.

Will you send a patch or should I do it?

**Comment by fallen** [comment]
I'll send a patch later.
You prefer the patches to be sent to the mailing list, right?

**Comment by metan-ucw** [comment]
Yes, mailing list is preferred.

**Comment by fallen** [comment]
Patch sent, email waiting for moderation.

**Comment by fallen** [comment]
Patch arrived on the mailinglist: https://lists.linux.it/pipermail/ltp/2019-June/012292.html

**Comment by fallen** [comment]
re-sent with corrections and missing Signed-off-by line.

**Comment by fallen** [comment]
Thanks!
