### ISSUE TITLE
syscalls/statx05 test requires e2fsprogs version> = 1.43

### ISSUE THREAD

**Issue by Cypresslin** [linux-test-project/ltp#542]
This statx05 test will run mkfs.ext4 with a "-O encrypt" flag.

However, this feature not only need kernel >= 4.11, but also requires the e2fsprogs version> = 1.43 to work.

On older distros like Ubuntu Xenial, this test will fail with:
```
 tst_device.c:230: INFO: Using test device LTP_DEV='/dev/loop0'
 tst_test.c:1072: INFO: Timeout per run is 0h 05m 00s
 tst_mkfs.c:90: INFO: Formatting /dev/loop0 with ext4 opts='' extra opts='-O encrypt -b 4096'
 mke2fs 1.42.13 (17-May-2015)
 Invalid filesystem option set: encrypt
 tst_mkfs.c:101: BROK: mkfs.ext4:1: statx05.c failed with 94
```
It will be great if we can detect the package version, or supported feature before running this test.

BugLink: https://bugs.launchpad.net/bugs/1798524

**Comment by metan-ucw** [comment]
Hmm, we do need a way how to check for the support. I guess that one way would be parsing the output from 'mkfs.ext3 -V'

**Comment by Cypresslin** [comment]
Or make use of the output from ver_linux, which includes the version number here:

    modutils               24
    e2fsprogs              1.44.1
    Linux C Library        > libc.2.27

**Comment by pevik** [comment]
`ver_linux` is for reporting, it'd be overkilling to use it for reporting.
Use either of these (I'd prefer `mkfs.ext4`):
```
mkfs.ext4 -V 2>&1 |grep mke2fs | awk '{print $2}'
tune2fs 2>&1 | grep "^tune2fs" | awk '{print $2}'
```

**Comment by pevik** [comment]
@metan-ucw FYI:

In IMA patchset I introduced `check_evmctl()` for checking `evmctl` version.
https://patchwork.ozlabs.org/project/ltp/patch/20200925185034.24155-4-pvorel@suse.cz/

I plan to turn it into general helper in shell API as I didn't expect it to be required for C API.
But if needed I could create C API and binary similar to https://github.com/linux-test-project/ltp/blob/master/lib/tst_kvercmp.c so it could be used in both C and shell API.
