### ISSUE TITLE
some test names are truncated in the log file

### ISSUE THREAD

**Issue by egrigore** [linux-test-project/ltp#544]
LTP Version:  20190115

**test file:**

```
root@machine:/opt/ltp# cat runtest/my_test_file
TEST-PANEL echo "first command"
```

**start command**

`runltp -p -l my_tests_results.txt -f /opt/ltp/runtest/my_test_file -o /opt/ltp/output/my_tests_log_file`

**In the log file the test name is TEST-PAN instead of TEST-PANEL:**

```
root@machine:/opt/ltp# cat results/my_tests_results.txt
Test Start Time: Fri Jul  5 05:20:28 2019
-----------------------------------------
Testcase                                           Result     Exit Value
--------                                           ------     ----------
TEST-PAN                                           PASS       0

-----------------------------------------------
Total Tests: 1
Total Skipped Tests: 0
Total Failures: 
```

**while on the output file is the right name TEST-PANEL:**

root@machine:/opt/ltp# cat output/my_tests_log_file
```
<<<test_start>>>
tag=TEST-PANEL stime=1562304028
cmdline="echo "first command""
contacts=""
analysis=exit
<<<test_output>>>
first command
[ 1914.289455] LTP: starting TEST-PANEL (echo "first command")
incrementing stop
check the case runtime at L
case timeout is 5400
<<<execution_status>>>
initiation_status="ok"
duration=1 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>
```

**Comment by yangx-jy** [comment]
Hi  egrigore,

I cannot reproduce the issue by following your steps:

LTP Version: 20190115

# cat runtest/my_test_file 
TEST-PANEL echo "first command"

# ./runltp -p -l my_tests_results.txt -f /opt/ltp/runtest/my_test_file -o /opt/ltp/output/my_tests_log_file

# cat results/my_tests_results.txt 
Test Start Time: Sat Jul 27 20:58:35 2019
-----------------------------------------
Testcase                                           Result     Exit Value
--------                                           ------     ----------
TEST-PANEL                                         PASS       0    
-----------------------------------------------
Total Tests: 1
Total Skipped Tests: 0
Total Failures: 0
Kernel Version: 3.10.0-862.el7.x86_64
Machine Architecture: x86_64
Hostname: RHEL7U5GA_Intel64

# cat output/my_tests_log_file 
<<<test_start>>>
tag=TEST-PANEL stime=1564232315
cmdline="echo "first command""
contacts=""
analysis=exit
<<<test_output>>>
first command
incrementing stop
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=0 cstime=0
<<<test_end>>>

Best Regards,
Xiao Yang

**Comment by ElenaGrigore** [comment]
Hi @yangx-jy , I worked around the problem by using "panel" instead of "PANEL". The difference that I see between our environments is that I have kernel 4.19.35 and arm architecture. I don't know if this matters.

**Comment by egrigore** [comment]
Hi @yangx-jy , I worked around the problem by using "panel" instead of "PANEL". The difference that I see between our environments is that I have kernel 4.19.35 and arm architecture. I don't know if this matters.

**Comment by metan-ucw** [comment]
This really shouldn't happen, the limit in ltp-pan was set to 30 characters to begin with and it was increased to 50 in 5ce0615cad1b549e234157d9e669f5aba3cb1e97.

Feel free to reopen if the bug is reproducible on latest release.
