### ISSUE TITLE
Skip / re-order fanotify07 test on system with older kernels

### ISSUE THREAD

**Issue by Cypresslin** [linux-test-project/ltp#552]
On Ubuntu Xenial (kernel 4.4.0), test fanotify07 will fail with timeout and cause hang, all the following fanotify* tests will fail with timeout error.[1][2]

This is a valid regression-tester, but it's generating a false positive result in the test report for other fanotify tests.

Matthew Ruffell tried to backport the fix for fanotify07 into upstream 4.4 and 4.9, but the scenario is too complicated to get this fixed, in the end Greg K-H agreed with Matthew, the patches were dropped, and this won't be getting fixed upstream. [3]

So I think maybe we should skip this test with older kernels, or move this test to the end of fanotify tests.

Bug link: https://bugs.launchpad.net/bugs/1775165

[1] https://bugs.launchpad.net/bugs/1808107
[2] https://bugs.launchpad.net/bugs/1828813
[3] https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1775165/comments/7

**Comment by metan-ucw** [comment]
The upstream LTP has a policy not to workaround buggy kernels, even if the fixes are not going to be applied on older stable releases. Ideally you should maintain a skiplist per distribution in your environment, that's what we do in SUSE and Linaro guys do in Lava. Unfortunately there is no upstream solution for this.

**Comment by Cypresslin** [comment]
Make sense, thank you.
