### ISSUE TITLE
runltp   line:783

### ISSUE THREAD

**Issue by floatice** [linux-test-project/ltp#553]
![image](https://user-images.githubusercontent.com/18067441/62620415-d9d7e000-b94b-11e9-8d01-da60117394e3.png)

useless parameters

**Comment by pevik** [comment]
`runltp` needs to be replaced with something else. There is no ticket, but @metan-ucw is working on this:
https://github.com/metan-ucw/runltp-ng
https://hackweek.suse.com/17/projects/prototype-new-ltp-upstream-runltp-script
