### ISSUE TITLE
statx04 for ext2

### ISSUE THREAD

**Issue by lecopzer** [linux-test-project/ltp#557]
Dear all,

I have a failure in statx04 with CONFIG_EXT2 enabled.
This issue was discussed in #267 and https://bugs.linaro.org/show_bug.cgi?id=4012.

The solution was patched at Linux v5.1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=93bc420ed41df63a18ae794101f7cbf45226a6ef
but still failed in version < 5.1.

None of the following solutions is really submitted:
1. Remove CONFG_EXT2_FS and add CONFIG_EXT4_USE_FOR_EXT2 in defconfig
2. Jan Kara's patch back ported to LTS versions

My question is what really need for kernel version < 5.1 is solution 2,
however, if nobody in kernel community interest in this issue, maybe a solution in LTP side like
https://github.com/linux-test-project/ltp/commit/c190fcf131bf9b6ef9c6dcf7e54c6d9241f34a7c is needed?

**Comment by metan-ucw** [comment]
There is actually a patch on the mailing list that I guess was send in order to fix this:

http://lists.linux.it/pipermail/ltp/2019-August/013080.html

However I'm not sure that we should do this since kernel devs declared this to be bug after all.

**Comment by lecopzer** [comment]
Thanks a lot for reply,
Do we need to ping Greg KH or someone like Jan Kara to back ported to LTS or just wait for this commit?
It's almost a year that nobody fixes this issue.

**Comment by xuyang0410** [comment]
My v2 patch about statx04.c has been sent to ltp community. 
[1][http://lists.linux.it/pipermail/ltp/2019-August/013259.html

**Comment by metan-ucw** [comment]
The statx04 was fixed in 4d30d7a2c54ef3c56bfef96ebce91f6980342644
