### ISSUE TITLE
(Re)move ffsb

### ISSUE THREAD

**Issue by pevik** [linux-test-project/ltp#560]
`utils/ffsb-6.0-rc2/` is a separate project (dependency for the ext4-new-features tests), which has been embedded into LTP as the easiest way to comply the dependency. But that caused an issue after autoconf reconfigure its' files `utils/ffsb-6.0-rc2/config.h.in` and `utils/ffsb-6.0-rc2/configure` get modified (known issue, also reported in #559), which is uncomfortable.

IMHO it should be 1) either moved to it's own git tree [1] 2) or we could remove it and ask LTP users to use `ffsb` from the fork. 2) means less work, but we lost it's control, therefore I'd be for 1). Some of this have been discussed on ML[3].

[1] https://github.com/linux-test-project/ffsb
[2] https://github.com/FFSB-Prime/ffsb
[3] https://patchwork.ozlabs.org/patch/1141241/

**Comment by HW42** [comment]
Even if moved into another git repo, the `configure` problem needs to be solved. Since it seems `autoconf` is called anyway, `configure` & co. probably can be simply removed, but I'm not familiar with LTP and ffsb, so maybe there's some reason for the current state.

**Comment by metan-ucw** [comment]
Given that only a few ext4 related tests depends on ffsb the best solution would be checking if the same functionality is covered in xfstests already and if so we can simply remove ffsb along with the tests that are using it.

**Comment by pevik** [comment]
> Given that only a few ext4 related tests depends on ffsb the best solution would be checking if the same functionality is covered in xfstests already and if so we can simply remove ffsb along with the tests that are using it.

+1. I'll check it.

**Comment by pevik** [comment]
Asked on linux-ext4 and linux-fsdevel ML:
https://marc.info/?l=linux-ext4&m=157184634203735&w=2

**Comment by pevik** [comment]
Patch to delete ffsb and New ext4 features tests
http://lists.linux.it/pipermail/ltp/2019-October/014111.html
https://patchwork.ozlabs.org/patch/1182722/

Based on Jan's and Ted's answer on ML
https://marc.info/?l=linux-fsdevel&m=157187153211649&w=2
https://marc.info/?l=linux-ext4&m=157190318618555&w=2
and Yong Sun volunteered to migrate 2 partly valid tests to xfstests.
