### ISSUE TITLE
/ltpstress.sh

### ISSUE THREAD

**Issue by zhongyong** [linux-test-project/ltp#563]
why remove ltpstress.sh？
What is now used to replace the pressure script for parallel stability?

**Comment by metan-ucw** [comment]
Because that basically duplicated what runltp does, moreover ltpstress and it's runtest files were not maintained at all so it didn't make sense to keep these files around.

**Comment by zhongyong** [comment]
thank，but I consulted the data to do stability 7 * 24 hours parallel stress test information is all using the ltpstress.sh script

**Comment by metan-ucw** [comment]
Not sure what you consulted, there is no reference to ltpstress in LTP source tree or github pages.

**Comment by zhongyong** [comment]
thank，The example demo of the online query is the information of the ltpstress.sh script used.

**Comment by metan-ucw** [comment]
I do not understand at all, which demo? Where?

**Comment by zhongyong** [comment]
https://blog.csdn.net/andy205214/article/details/52334433




------------------ 原始邮件 ------------------
发件人: "Cyril Hrubis"<notifications@github.com>; 
发送时间: 2019年9月6日(星期五) 下午5:44
收件人: "linux-test-project/ltp"<ltp@noreply.github.com>; 
抄送: "钟勇"<18455668@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [linux-test-project/ltp] /ltpstress.sh (#563)




I do not understand at all, which demo? Where?
 
&mdash;

**Comment by metan-ucw** [comment]
I can't read chinese but I clearly see that the blog post is wrong on a few things, for example it uses LTP from 2011 in 2016. LTP from 2011 misses five years of fixes, that would be hundreds of fixed tests. So my advice would be not to follow that blog post at all.

If you want to run LTP for seven days all you need to do is to pass -t 7d to runltp script. If you want to run it in parallel you can run runltp three times, I guess that you would need to specify different output directories for each with -o as well. However some test may rarely fail if they happen to run concurently with other tests that use the same system resources. If you want just stress the machine and do not need to look into the test results the above would work.

**Comment by zhongyong** [comment]
Thanks, then I will use the latest version.




------------------ 原始邮件 ------------------
发件人: "Cyril Hrubis"<notifications@github.com>; 
发送时间: 2019年9月6日(星期五) 下午5:59
收件人: "linux-test-project/ltp"<ltp@noreply.github.com>; 
抄送: "钟勇"<18455668@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [linux-test-project/ltp] /ltpstress.sh (#563)




I can't read chinese but I clearly see that the blog post is wrong on a few things, for example it uses LTP from 2011 in 2016. LTP from 2011 misses five years of fixes, that would be hundreds of fixed tests. So my advice would be not to follow that blog post at all.
 
If you want to run LTP for seven days all you need to do is to pass -t 7d to runltp script. If you want to run it in parallel you can run runltp three times, I guess that you would need to specify different output directories for each with -o as well. However some test may rarely fail if they happen to run concurently with other tests that use the same system resources. If you want just stress the machine and do not need to look into the test results the above would work.
 
&mdash;

**Comment by zhongyong** [comment]
> I can't read chinese but I clearly see that the blog post is wrong on a few things, for example it uses LTP from 2011 in 2016. LTP from 2011 misses five years of fixes, that would be hundreds of fixed tests. So my advice would be not to follow that blog post at all.
> 
> If you want to run LTP for seven days all you need to do is to pass -t 7d to runltp script. If you want to run it in parallel you can run runltp three times, I guess that you would need to specify different output directories for each with -o as well. However some test may rarely fail if they happen to run concurently with other tests that use the same system resources. If you want just stress the machine and do not need to look into the test results the above would work.

When I ran it for 7 days, it was actually executed quickly, and the parameter of adding -I was also executed individually. Whether it can be executed in a loop.

**Comment by Aigf** [comment]
我觉得这篇文章说的很对现在的LTP更侧重于长时间的测试，但用于实际生产中，更需要短期大量的测试，测试整个系统的稳定性。
linux 系统下的压力测试工具LTP和stress区别_ltpstress-CSDN博客：https://blog.csdn.net/qq_34870631/article/details/113943368
