### ISSUE TITLE
rsh/rcp does not exist in rhel8 - tests fail

### ISSUE THREAD

**Issue by steven-unruh** [linux-test-project/ltp#565]
rcp01.sh    1  TFAIL  :  ltpapicmd.c:188: Test broken: rcp: command not found
rsh01.sh    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found

4.18.0-135.el8.ppc64le #1 SMP Fri Aug 16 19:25:25 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

needs to identify if on rhel8+ and not run rsh/rcp tests

**Comment by pevik** [comment]
No, we don't fix issues like this by identifying a distro, we rather check whether particular command is available. There is `TST_NEEDS_CMDS="rsh"`, but that's only in new shell API (in `tst_test.sh`, for network tests used via `tst_net.sh`). For these tests it's already reported in #128 

There is ongoing rewrite of both C and shell tests, but still many tests need to be rewritten, you're more then welcome to help :).
