### ISSUE TITLE
runall test including possible resets

### ISSUE THREAD

**Issue by olerem** [linux-test-project/ltp#57]
Hallo all,
first of all, thank your for this project.
I'm using LTP to test embedded devices and my primer target is to monitor state of system development.
The problem which i have is that some LTP test may cause system reset (it is kind of normal), and i wont to be able to continue the test, and gether all possible results including reset events.

I didn't found any LTP tool with this functionality. If there are some, please point me. If there are nothing ready to use, where is the best place to begin and make it upstream ready?

**Comment by metan-ucw** [comment]
LTP has no support for resuming the work after reboot and testcase that reboots the machine is not expected behaviour. The best bet at the moment is to identify problematic testcases and disable them temporarily in runtest files.

Doing reboot persistent test run would be tricky task. There are two problems there. One is making sure that the state was properly saved, which nearly impossible on the machine under test. The other one is picking up where we left last time, which means hooking somewhere into init scripts/systemd which would be pain to do reliably across different distributions.

And given that the runltp script and ltp-pan.c are messy and currently in maintenance mode it may need to be written from scratch.

Also most of the discussion about LTP development happens at the mailing list, it would be better to move the conversation there.

**Comment by olerem** [comment]
Suddenly i don't have access to my privat email account from work. Github is the only working way here :(
About this issue. As workaround i use this hacky script in combination with jenkins:

```bash
while read -u 100 LPT_LIST_LINE; do
        $SSH root@$CUSTOM_TARGET_IP "echo $LPT_LIST_LINE > /tmp/ltp-line";
        TESTNAME="$(echo $LPT_LIST_LINE | cut -d " " -f 1)"

        $SSH root@$CUSTOM_TARGET_IP "echo LTP run: $TESTNAME > /dev/kmsg"
        echo -n "$(date +%Y-%m-%dT%T) Test: $TESTNAME ";

        $SSH root@$CUSTOM_TARGET_IP "$TEST_DIR_TARGET/runltp -f /tmp/ltp-line \
                -l /dev/null -o /dev/null \
                -C /dev/null -g /dev/null \
                -T /dev/null -d /var/opt/CUSTOM/dynamic/ltp-tmp > /dev/null"; RETURN=$?;

        echo "Result: $RETURN";
        sleep 1

        if [ "$RETURN" = 255 ]; then
                STATUS="RESET"
                echo "Reset detected, making clean reboot."
                ltp_prepare_target;
        elif ! $SSH root@$CUSTOM_TARGET_IP "test -e $TEST_DIR_TARGET/runltp"; then
                STATUS="RESET"
                echo "Connection problem detected, making clean reboot."
                ltp_prepare_target;
        else
                STATUS="ONLINE"
        fi

        echo "$TESTNAME $RETURN $STATUS" >> $RESULTS_NODE/my_log.txt

done 100<$LTP_LIST_NODE

```

**Comment by olerem** [comment]
With other words it is not important to make ltprun remember last test, it can be done by host.  In case of my script, for some reasons some test will fail if i do it so.
About fixing test issues: it is not a valid option becose target should reset in some cases.

**Comment by metan-ucw** [comment]
Driving the testrun from another host sounds like a good idea. FYI there is no reason to start the test via runltp script in case that you want to run single test. You can do just with setting `$PATH` to include path to LTP directory with test binaries and running the cmdline from runtest files directly in 99% of the cases a few of them would need `$LTPROOT` to point to `/opt/ltp` as well but that should be all.

I guess that having a script that would take runtest files and execute testcases over ssh would be handy. If we fix it to capture the test output, make it possible to pass some options like device to be used for tests, etc.

**Comment by olerem** [comment]
I was thinking about it to but had some doubts that it would be not really portable.

**Comment by metan-ucw** [comment]
> I was thinking about it to but had some doubts that it would be not really portable.

What exactly do you have in mind? Running the testcases directly, capturing the output from ssh, ...?

**Comment by olerem** [comment]
Yes, and starting testcases directly without ltprun

**Comment by metan-ucw** [comment]
> Yes, and starting testcases directly without ltprun

If you find test that does not work with correct `$PATH` and `$LTPROOT` just report a bug.

**Comment by olerem** [comment]
Ok, thank you!

**Comment by metan-ucw** [comment]
Let's close this one.
