### ISSUE TITLE
Write tests for CLONE_PIDFD

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#577]
commit b3e5838252665ee4cfa76b82bdf1198dca81e5be
Author: Christian Brauner <christian@brauner.io>
Date:   Wed Mar 27 13:04:15 2019 +0100

    clone: add CLONE_PIDFD

**Comment by coolgw** [comment]
it seems current testcases/kernel/syscalls/clone3/clone301.c has some coverage on this flag, we need cover more scenario or we can close this ?

**Comment by metan-ucw** [comment]
@coolgw Looks like Viresh indeed wrote a test for this flag in 1b0e8dd71d3624cd9d9afbc5793e50ba802a0824. Thanks for pointing it out.
