### ISSUE TITLE
tst_test.sh: no cleanup is run unless setup is defined and started

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#586]
It seems that this has been in the library from the beginning, unless setup has been defined and executed the library will not call the cleanup. This is inconsistent with the C library and also quite counter intuitive.

So the idea here would be:

* Checking that running cleanup unconditionally will not break anything
* Getting rid of this inconsistency

**Comment by pevik** [comment]
I haven't found any breakage.

**Comment by pevik** [comment]
Well, some bug has been found :(
https://patchwork.ozlabs.org/project/ltp/patch/20200518130132.19312-1-pvorel@suse.cz/
