### ISSUE TITLE
LTP build broken on tumbleweed fails recent travis builds

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#587]
Looks like tumbleweed now treats implicit-function-declaration as an error now, which fails LTP build in travis. The fix is obvious, we have to make sure there are no implicit function declarations in LTP.

**Comment by pevik** [comment]
It's a broken `getdents64()` detection via autotools.

**Comment by pevik** [comment]
Patch fixing this: https://patchwork.ozlabs.org/patch/1173147/

**Comment by pevik** [comment]
Fixed by 859ac7e1e
