### ISSUE TITLE
About perf_event_open02 case

### ISSUE THREAD

**Issue by nick650823** [linux-test-project/ltp#588]
Hi all,

In my knowledge, the pass condition of perf_event_open02 is that the ratio should not be greater than the number of hw counter. It means that the 'task-clock' event without binding 'instructions' event should be the first to start counting and the last to die. 
But how should we guarantee that? I have encounter the case failed and found out that the event->ctx->time of 'task-clock' event without binding 'instructions' event is not the last when the event is stopped by prctl().

**Comment by metan-ucw** [comment]
I guess that this, and all kind of small rounding errors, is why we do have the + 0.0001 in the ratio > nhw + 0.0001 condition at the end of the test, so I suppose that this epsion is too small. Does it work reliably with a greater epsion value?

**Comment by nick650823** [comment]
I don't think it is a kind of rounding error. If there is no guarantee that the 'task-clock' event without binding 'instructions' event should be the first to start counting and the last to die, the total count it gets may be smaller than the count of other events. As a result, the calculation afterward is logically wrong.
I am testing specifically in riscv. Does other architecture guarantee that the 'task-clock' event without binding 'instructions' event should be the first to start counting and the last to die?

**Comment by jstancek** [comment]
I see it fail sporadically also on x86:
```
perf_event_open02    0  TINFO  :  overall task clock: 84219637
perf_event_open02    0  TINFO  :  hw sum: 901958982, task clock sum: 252826793
perf_event_open02    0  TINFO  :  ratio: 3.001993
perf_event_open02    1  TFAIL  :  perf_event_open02.c:369: test failed (ratio was greater than )
```
"total count it gets may be smaller than the count of other events" - which is presumably why there is a tolerance in ratio comparison.

prctl(PR_TASK_PERF_EVENTS_DISABLE) walks a list, so I assume it will disable events in order they were created. Perhaps we could  try ioctl(PERF_EVENT_IOC_DISABLE) to disable all other events before tsk0 is disabled.
