### ISSUE TITLE
如何设计其他工具支持的 Posix-API 接口功能（套接字、Epoll、Kqueue）测试方案

### ISSUE THREAD

**Issue by suyuexin** [linux-test-project/ltp#590]
最近想给某工具进行性能测试和兼容性测试，已经安装了LTP测试集，但是不知道如何下手，不知道有没有前辈有过经验可以指导一下？如果想自己设计测试集，需要改哪？读了LTP里面的文档和网上的博客（网上的博客貌似都比较久远了，能搜到的也不是很多）但是没找到我需要的，本人比较菜，对LTP刚接触

**Comment by pevik** [comment]
Please, ask your question in english.
