### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by liangtiansheng** [linux-test-project/ltp#591]
When i used master branch to make a test, my host crashed. And i can not do any operation. The hanging location is as below. By the way, i succeeded when i use ltp-20170516 edition.

<<<test_start>>>
tag=inotify07 stime=1570945053
cmdline="inotify07"
contacts=""
analysis=exit
<<<test_output>>>
tst_device.c:238: INFO: Using test device LTP_DEV='/dev/loop0'
tst_mkfs.c:90: INFO: Formatting /dev/loop0 with ext2 opts='' extra opts=''
mke2fs 1.42.9 (28-Dec-2013)
tst_test.c:1118: INFO: Timeout per run is 0h 05m 00s
inotify07.c:156: INFO: mntpoint/ovl/test_dir ino=16386
inotify07.c:166: INFO: mntpoint/ovl/test_dir ino=16386
inotify07.c:135: FAIL: didn't get event: mask=40000004 
inotify07.c:135: FAIL: didn't get event: mask=00000020 
inotify07.c:135: FAIL: didn't get event: mask=00000008 
inotify07.c:135: FAIL: didn't get event: mask=00000004 

Summary:
passed   0
failed   4
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=2 termination_type=exited termination_id=1 corefile=no
cutime=3 cstime=7
<<<test_end>>>
<<<test_start>>>
tag=inotify08 stime=1570945055
cmdline="inotify08"
contacts=""
analysis=exit
<<<test_output>>>
tst_device.c:238: INFO: Using test device LTP_DEV='/dev/loop0'
tst_mkfs.c:90: INFO: Formatting /dev/loop0 with ext2 opts='' extra opts=''
mke2fs 1.42.9 (28-Dec-2013)
tst_test.c:1118: INFO: Timeout per run is 0h 05m 00s
inotify08.c:149: INFO: mntpoint/ovl/test_file ino=49154, dev=0:43
inotify08.c:160: INFO: mntpoint/ovl/test_file ino=49154, dev=0:43
inotify08.c:127: FAIL: didn't get event: mask=4 
inotify08.c:127: FAIL: didn't get event: mask=20 
inotify08.c:127: FAIL: didn't get event: mask=8 

Summary:
passed   0
failed   3
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=1 termination_type=exited termination_id=1 corefile=no
cutime=0 cstime=4
<<<test_end>>>
<<<test_start>>>
tag=inotify09 stime=1570945056
cmdline="inotify09"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1118: INFO: Timeout per run is 0h 05m 00s
../../../../include/tst_fuzzy_sync.h:504: INFO: Minimum sampling period ended
../../../../include/tst_fuzzy_sync.h:328: INFO: loop = 1024, delay_bias = 0
../../../../include/tst_fuzzy_sync.h:317: INFO: start_a - start_b: { avg =   -53ns, avg_dev =     7ns, dev_ratio = 0.14 }
../../../../include/tst_fuzzy_sync.h:317: INFO: end_a - start_a  : { avg =  2054ns, avg_dev =    26ns, dev_ratio = 0.01 }
../../../../include/tst_fuzzy_sync.h:317: INFO: end_b - start_b  : { avg =  2524ns, avg_dev =    24ns, dev_ratio = 0.01 }
../../../../include/tst_fuzzy_sync.h:317: INFO: end_a - end_b    : { avg =  -523ns, avg_dev =    27ns, dev_ratio = 0.05 }
../../../../include/tst_fuzzy_sync.h:317: INFO: spins            : { avg =    47  , avg_dev =     3  , dev_ratio = 0.06 }
../../../../include/tst_fuzzy_sync.h:516: INFO: Reached deviation ratios < 0.10, introducing randomness
../../../../include/tst_fuzzy_sync.h:519: INFO: Delay range is [-227, 188]
../../../../include/tst_fuzzy_sync.h:328: INFO: loop = 1044, delay_bias = 0
../../../../include/tst_fuzzy_sync.h:317: INFO: start_a - start_b: { avg =   -57ns, avg_dev =     6ns, dev_ratio = 0.10 }
../../../../include/tst_fuzzy_sync.h:317: INFO: end_a - start_a  : { avg =  2107ns, avg_dev =    42ns, dev_ratio = 0.02 }
../../../../include/tst_fuzzy_sync.h:317: INFO: end_b - start_b  : { avg =  2545ns, avg_dev =    19ns, dev_ratio = 0.01 }
../../../../include/tst_fuzzy_sync.h:317: INFO: end_a - end_b    : { avg =  -495ns, avg_dev =    42ns, dev_ratio = 0.09 }
../../../../include/tst_fuzzy_sync.h:317: INFO: spins            : { avg =    44  , avg_dev =     4  , dev_ratio = 0.08 }

Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(10.0.12.151:22) at 13:38:29.

Type `help' to learn how to use Xshell prompt.

**Comment by pevik** [comment]
You simply found a bug in kernel on SUT which is triggered by `inotify09` test (source code [testcases/kernel/syscalls/inotify/inotify09.c](https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/inotify/inotify09.c)). Your kernel probably doesn't have backported commit d90a10e2444b "fsnotify: Fix fsnotify_mark_connector race" (see description at `inotify09`). This test was added in LTP `20180926` release, that's why `20170516` was ok for you.

**Comment by liangtiansheng** [comment]
> You simply found a bug in kernel on SUT which is triggered by `inotify09` test (source code [testcases/kernel/syscalls/inotify/inotify09.c](https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/inotify/inotify09.c)). Your kernel probably doesn't have backported commit d90a10e2444b "fsnotify: Fix fsnotify_mark_connector race" (see description at `inotify09`). This test was added in LTP `20180926` release, that's why `20170516` was ok for you.

Thanks a lot, i will figure it out later
