### ISSUE TITLE
fallocate05: fallocate() succeeded unexpectedly

### ISSUE THREAD

**Issue by jstancek** [linux-test-project/ltp#610]
http://lists.linux.it/pipermail/ltp/2019-October/014141.html
fallocate05 failed on stable 5.3:
```
tst_mkfs.c:89: INFO: Formatting /dev/loop0 with ext4 opts='' extra opts=''
mke2fs 1.45.3 (14-Jul-2019)
tst_test.c:1116: INFO: Timeout per run is 0h 05m 00s
tst_fill_fs.c:29: INFO: Creating file mntpoint/file0 size 21710183
tst_fill_fs.c:29: INFO: Creating file mntpoint/file1 size 8070086
tst_fill_fs.c:29: INFO: Creating file mntpoint/file2 size 3971177
tst_fill_fs.c:29: INFO: Creating file mntpoint/file3 size 36915315
tst_fill_fs.c:29: INFO: Creating file mntpoint/file4 size 70310993
tst_fill_fs.c:29: INFO: Creating file mntpoint/file5 size 4807935
tst_fill_fs.c:29: INFO: Creating file mntpoint/file6 size 90739786
tst_fill_fs.c:29: INFO: Creating file mntpoint/file7 size 76896492
tst_fill_fs.c:49: INFO: write(): ENOSPC (28)
fallocate05.c:50: PASS: write() wrote 8192 bytes
fallocate05.c:54: FAIL: fallocate() succeeded unexpectedly
```

Can we rely on fallocate reserving only what we ask? Man page suggest it can be more, but implies it's not more than block size chunk:
```
Because allocation is done in block size chunks, fallocate() may allocate a larger range of disk space than was specified
```

**Comment by metan-ucw** [comment]
Maybe we should change the test so that it fallocates() and fills buffers in a loop and we would expect that we will succeed writing out the buffer after successful fallocate.

**Comment by jstancek** [comment]
I talked to Carlos Maiolino off-list and he pointed out couple ways why relying on write() returning ENOSPC might not be reliable way to know that subsequent fallocate will fail too:

Q: Will fallocate reserve only 8k?
[quote aggregated from multiple emails]
It's filesystem dependent. For example, in XFS, if you use extent hints, you may allocate more than 8k, because essentially, XFS will try to allocate extents at least the size configured by the user when using extent hints, but, that's only one reason why it could happen. We may well allocate more blocks than required. In XFS, extent size hints as I noted above is one of them, unwritten extents is another thing that might also trigger it.

One thing that comes to my mind, is how ltp actually 'decides' when the filesystem is full. Depending on the situation, a write may return ENOSPC, and after a fsync happens, we get some space back.
This might occur for example when we reserve disk space for metadata, during journal transactions. We usually reserve disk space for the 'worst case', because we can never know in advance if, for example, a new write will require a Btree split and we'll need enough disk to write new btree blocks.

So, we always do metadata reservations for the worst case, and then we return  the unused blocks to the free pool. Something happening in parallel with another transacion, may see an ENOSPC, and after the transaction finishes, we get space back and fallocate might succeed, specially small reservations like the test is doing. Anyway, this is just one possibility, there might be others.
[end quote]

That made me think, we introduce fsync() to fill_fs() and bump FALLOCATE_SIZE to something like 16M or more, to avoid these corner cases.

I can't reproduce this on-demand, but I still see it failing in CKI occasionally. Most commonly on s390, which are a bit slower.

**Comment by wangli5665** [comment]
when I shrink the size of FALLOCATE_SIZE to 4096, it becomes more easy to reproduce this fail.

# uname -r
4.18.0-148.el8.cki.s390x

# ./fallocate05
...
tst_test.c:1179: INFO: Testing on xfs
tst_mkfs.c:90: INFO: Formatting /dev/loop0 with xfs opts='' extra opts=''
tst_test.c:1118: INFO: Timeout per run is 0h 05m 00s
tst_fill_fs.c:29: INFO: Creating file mntpoint/file0 size 21710183
tst_fill_fs.c:29: INFO: Creating file mntpoint/file1 size 8070086
tst_fill_fs.c:29: INFO: Creating file mntpoint/file2 size 3971177
tst_fill_fs.c:29: INFO: Creating file mntpoint/file3 size 36915315
tst_fill_fs.c:29: INFO: Creating file mntpoint/file4 size 70310993
tst_fill_fs.c:29: INFO: Creating file mntpoint/file5 size 4807935
tst_fill_fs.c:29: INFO: Creating file mntpoint/file6 size 90739786
tst_fill_fs.c:29: INFO: Creating file mntpoint/file7 size 76896492
tst_fill_fs.c:49: INFO: write(): ENOSPC (28)
fallocate05.c:50: PASS: write() wrote 4096 bytes
fallocate05.c:54: FAIL: fallocate() succeeded unexpectedly
