### ISSUE TITLE
oom03, oom05, ksm03, ksm04 testcases don't work with cgroup2

### ISSUE THREAD

**Issue by jstancek** [linux-test-project/ltp#611]
http://lists.linux.it/pipermail/ltp/2019-October/014141.html

systemd on Fedora31 started using cgroup2 exclusively:
  cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate)

oom03, oom05 tests are trying to mount single controller on cgroup1 and get EBUSY
```
[pid 283933] 04:57:26 mkdir("/dev/cgroup", 0777) = 0
[pid 283933] 04:57:26 mount("memcg", "/dev/cgroup", "cgroup", 0, "memory") = -1 EBUSY (Device or resource busy)
```

**Comment by jstancek** [comment]
ksm03/ksm04 appear to run into same problem on Fedora31
```
tag=ksm03 stime=1574117009
cmdline="ksm03"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1215: INFO: Timeout per run is 0h 05m 00s
mem.c:757: BROK: mount /dev/cgroup: EBUSY (16)
```

**Comment by jstancek** [comment]
Reference to discussion about ksm02 tests:
https://lore.kernel.org/linux-arm-kernel/1039472143.12305448.1589384415559.JavaMail.zimbra@redhat.com/T/#m7a1095171fdc23a964d2fd4fdb2d55a9751ec401

F32 distro and podman tests use cgroup2 by default, LTP test cgroup1. Mixing those two means that cpuset controller is moving between hierarchies, which is not fully supported/recommended.

**Comment by wangli5665** [comment]
A proposal patchset to solve the problem:
http://lists.linux.it/pipermail/ltp/2020-May/017307.html

**Comment by wangli5665** [comment]
With the new cgroup test API merging, I assume this issue has been solved.
Any question please leave a comment or reopen it.
