### ISSUE TITLE
aio_error return code didn't match expected value (0 != 22)

### ISSUE THREAD

**Issue by abeginnera** [linux-test-project/ltp#618]
Hi,
    I tested LTP with glibc 2.27 on aarch64 machine, and got following "UNTESTED" log:
"aio_error/3-1.c return code didn't match expected value (0 != 22). "

    Then I saw the source code of aio_error in glibc, it likes this:
====code start====
int
aio_error (const struct aiocb *aiocbp)
{
  return aiocbp->__error_code;
}
====code end====

   I think aio_error should return 0 in case aio_error/3-1.c even though the aio_reqprio field is less than 0 for there is no aio_read or aio_write function call before aio_error is called.

**Comment by xuyang0410** [comment]
Yes. only called aio_write or aio_read with invalid aio_reqprio(-1), then it can error. We have a patch（in reviewing） to fix this:  [aio_error/3-1.c: Call write before aio_error ](https://patchwork.ozlabs.org/patch/1257892/)

**Comment by abeginnera** [comment]
@xuyang0410 
Thank you for reply.
By the way, I think the following cases have nearly the same problem:
aio_return/2-1.c
aio_return/4-1.c
aio_return/3-2.c

**Comment by xuyang0410** [comment]
@abeginnera  Yes, we should use aio_write in 4-1.c.  But for aio_return/2-1.c 3-2.c , IMO they should be dropped  because for aiocbp aio return function should be called only once for any given request.  They don't make sense(they only get the last return value).

**Comment by abeginnera** [comment]
@xuyang0410 OK, get it. Thank you.

**Comment by xuyang0410** [comment]
@abeginnera  would you like to send a patch to fix these or I send this with your reported-by?

**Comment by abeginnera** [comment]
@xuyang0410 'reported-by' is OK.

**Comment by xuyang0410** [comment]
@abeginnera  OK. please provide me with your name and email.

**Comment by metan-ucw** [comment]
As per the discussion on the mailing list the aio_error_3-1 actually correctly returns UNTESTED which means that optional POSIX functionality is not implemented in glibc.
