### ISSUE TITLE
ifconfig compatible probem in set_ipv4addr

### ISSUE THREAD

**Issue by suyj-fnst** [linux-test-project/ltp#620]
In recent rhel distros when set address with ifconfig, corresponding route entry wont be added automatically.
For example, node1 and node2 are one the same lan. 
First ifconfig eth0 192.168.100.10/24
Then ping node2 from node1 wont work
      [node1] ---- [node2]
192.168.100.10 192.168.100.20
On node1, 192.168.100.0/24 route entry is not exist so ping node2 fails.

**Comment by pevik** [comment]
I guess you're talking about `testcases/network/stress/route/route4-rmmod` am I right (the only test which uses `ifconfig` and `set_ipv4addr`).
`set_ipv4addr` is used in old tests, which should be rewritten to use network shell API `tst_net.sh`.
For route tests, it's WIP (#310), there are other tests to be rewritten: multicast (#440) and other using `rsh` (#128).
