### ISSUE TITLE
why don't do inline assignment

### ISSUE THREAD

**Issue by Jeffchal** [linux-test-project/ltp#630]
IN https://github.com/linux-test-project/ltp/wiki/Style-Guide , i find the statement ，but i dont`t know why or if do it , What effect will it have

4. Inline assigments
Don't do inline assignment, i.e.

```
int foo = 0;
```
Use separate statements:

```
int foo;
foo = 0;
```

The only exception to this is when you define global variables.

**Comment by metan-ucw** [comment]
I guess that the original point author was trying to make is readability.

We generally follow the LKML coding style, where inline assignment is not discouraged so we may as well remove that.

Actually the whole Style-Guide is obsolete so we may as well remove it. There are more up-to-date document covering this now.

**Comment by pevik** [comment]
> Actually the whole Style-Guide is obsolete so we may as well remove it. There are more up-to-date document covering this now.

@metan-ucw I was planning to update it as @jstancek pointed this document out in [1]. But I'd also prefer to remove this document as we have new style documented in [2]. Maybe we want to add something to C code (I'm aware just to "avoid including kernel headers due bugs in uapi on older distros").

[1] https://lists.linux.it/pipermail/ltp/2019-November/014541.html
[2] https://github.com/linux-test-project/ltp/wiki/Test-Writing-Guidelines#13-coding-style

**Comment by metan-ucw** [comment]
@pevik we probably need a more elaborate writeup how to deal with backward compatibility that covers m4, fallback definitions in lapi/, run-time detection etc.

**Comment by pevik** [comment]
OK. I'll close this and create new ticket.

**Comment by pevik** [comment]
Replaced by #631.

**Comment by Jeffchal** [comment]
OK。 Thanks a million
