### ISSUE TITLE
I can`t find the commit 54a307ba8d3c of  fanotify09

### ISSUE THREAD

**Issue by yumdeer** [linux-test-project/ltp#633]
I have a test in Redhat 3.10.0- release 。In case of  fanotify09 have a error .

 I find  a commit in the code ,like “This is a regression test for commit 54a307ba8d3c: or Test case #2 is a regression test for commit b469e7e47c8a:  "but i can`t find 54a307ba8d3c and b469e7e47c8a  in the Issues 。Are they planned tasks ? will modify them in the future ?

Sorry i don't know much about fanotify or can tell me what caused the error , PLZ  and THX 。

`
******************LTP INIT HERE******************
              total        used        free      shared  buff/cache   available
Mem:          96490         826       95452          27         211       95216
Swap:          5119         266        4853
./ltp_init.sh: line 5: addgroup: command not found
groupadd: group 'bin' already exists
groupadd: group 'daemon' already exists
groupadd: group 'sys' already exists
groupadd: group 'users' already exists
groupadd: group 'nobody' already exists
useradd: user 'bin' already exists
useradd: user 'bin' already exists
useradd: user 'daemon' already exists
useradd: user 'nobody' already exists
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
umount: /sys/fs/cgroup/memory: not mounted
umount: /sys/fs/cgroup/net_cls: not mounted
umount: /sys/fs/cgroup/cpu,cpuacct: not mounted
umount: /sys/fs/cgroup/hugetlb: not mounted
umount: /sys/fs/cgroup/devices: not mounted
umount: /sys/fs/cgroup/freezer: not mounted
umount: /sys/fs/cgroup/perf_event: not mounted
umount: /sys/fs/cgroup/cpuset: not mounted
umount: /sys/fs/cgroup/blkio: not mounted
TMPDIR is: /tmp
ln: failed to create symbolic link './diff': File exists
******************LTP INIT END ******************
tst_test.c:1096: INFO: Timeout per run is 0h 05m 00s
fanotify09.c:161: INFO: Test #0: Events on children with both inode and mount marks
fanotify09.c:150: PASS: group 0 got event: mask 2 pid=12718 fd=6 path=/tmp/vTT21V/mntpoint/tfile_12718
fanotify09.c:218: FAIL: group 1 got event
fanotify09.c:135: FAIL: group 1 got event: mask 2 (expected 10) pid=12718 fd=6
fanotify09.c:218: FAIL: group 2 got event
fanotify09.c:135: FAIL: group 2 got event: mask 2 (expected 10) pid=12718 fd=6
fanotify09.c:161: INFO: Test #1: Events on children and subdirs with both inode and mount marks
fanotify09.c:150: PASS: group 0 got event: mask 2 pid=12718 fd=6 path=/tmp/vTT21V/mntpoint/tfile_12718
fanotify09.c:150: PASS: group 0 got event: mask 10 pid=12718 fd=7 path=/tmp/vTT21V/mntpoint/testdir
fanotify09.c:202: FAIL: first group got more than 2 events (72 > 48)
fanotify09.c:218: FAIL: group 1 got event
fanotify09.c:135: FAIL: group 1 got event: mask 2 (expected 10) pid=12718 fd=6
fanotify09.c:218: FAIL: group 2 got event
fanotify09.c:135: FAIL: group 2 got event: mask 2 (expected 10) pid=12718 fd=6

Summary:
passed   3
failed   9
skipped  0
warnings 0
`

**Comment by pevik** [comment]
That's a kernel commit :).

**Comment by metan-ucw** [comment]
These are kernel commits missing the the 3.10.0 kernel you are running. In short your kernel is buggy.

**Comment by metan-ucw** [comment]
Also recent enough LTP prints this information on test failure, something as:

```
...
fanotify09.c:135: FAIL: group 1 got event: mask 2 (expected 10) pid=12718 fd=6
fanotify09.c:218: FAIL: group 2 got event
fanotify09.c:135: FAIL: group 2 got event: mask 2 (expected 10) pid=12718 fd=6

HINT: You _MAY_ be missing kernel fixes, see:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8edc6e1688fc
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d989903058a8

Summary:
passed 3
failed 9
skipped 0
warnings 0
```

**Comment by yumdeer** [comment]
> 这些是缺少您正在运行的3.10.0内核的内核提交。简而言之，您的内核是越野车。

EXM , how can I find the contents of the kernel patch? I can't seem to find it in the search bar at  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/

**Comment by metan-ucw** [comment]
Try asking on a forum whose purpose is to help beginners.

Here we discuss only LTP related issues.

**Comment by yumdeer** [comment]
> Try asking on a forum whose purpose is to help beginners.
> 
> Here we discuss only LTP related issues.

sorry ， my bad .. I find it
