### ISSUE TITLE
Commit 9e83513e (tst_device.h: Use lapi/syscalls.h instead of <sys/syscall.h>) is causing failure to socketcall01 test

### ISSUE THREAD

**Issue by Cypresslin** [linux-test-project/ltp#634]
Environment: Ubuntu Bionic with 5.0.0-1028-gcp kernel

Bisect shows before commit 9e83513e, the socketcall01 test will be skipped with:

    tst_test.c:853: CONF: The socketcall() syscall is not supported

After that, it will fail with:

    socketcall01.c:42: FAIL: socketcall() for TCP stream failed with -1: ENOSYS (38)
    socketcall01.c:42: FAIL: socketcall() for unix domain dgram failed with -1: ENOSYS (38)
    socketcall01.c:42: FAIL: socketcall() for Raw socket failed with -1: ENOSYS (38)
    socketcall01.c:42: FAIL: socketcall() for UDP dgram failed with -1: ENOSYS (38)

**Comment by pevik** [comment]
Thanks for a report, I've noticed it on other distros as well. Interesting, I'd expect it would work, as `lapi/syscalls.h` include `<sys/syscall.h>`, but obviously not.

**Comment by pevik** [comment]
IMHO test is broken by adding `__NR_socketcall`.

**Comment by pevik** [comment]
OK, `__NR_socketcall` is ` -1`, that's obviously wrong.

**Comment by pevik** [comment]
Proposed fix: https://patchwork.ozlabs.org/patch/1225869/
