### ISSUE TITLE
execve05 hang up

### ISSUE THREAD

**Issue by gogobravo** [linux-test-project/ltp#635]
LTP v20190517, Altera Cyclon V SOCFPGA - Dual ARMv71, kernel 4.14.134-rt63-rt-...
What might be the reason. The output is constantly something like this:
[  557.858875] Out of memory: Kill process 15545 (execve05) score 0 or sacrifice child
[  557.896262] Killed process 15575 (execve05) total-vm:1816kB, anon-rss:68kB, file-rss:776kB, shmem-rss:4kB
but before that it kills all other processes including ltp-pan and agetty...I can only power cycle.

**Comment by metan-ucw** [comment]
Hm, looking at the test it starts 20 children and each of the children then does execve(). That should not stress the systems at all.

I guess that there is something else that ate the memory, maybe a kernel memory leak.

**Comment by embtux** [comment]
@gogobravo,

In the given log, execve05 is a 'zero' score process and the OOM-Killer should not kill a 'zero' score process.
I believe the real culprit is some other (perhaps, a parent) process.

Please share 

1. the complete log and 
2. output of commands - 
   - `$ cat /proc/meminfo`
   - `$ cat /proc/sys/vm/overcommit_memory`

**Comment by gogobravo** [comment]
@embtux ,
This test is not logged because I can't even interrupt it. I run the ltp through serial console and since *getty, systemd-network and other major processes are killed I can't even make ssh to it. The only part of this test which is recorded is in output file so I can give this to you 
:
<<<test_start>>>
tag=execve05 stime=1579864785
cmdline="execve05 -i 5 -n 32"
contacts=""
analysis=exit
<<<test_output>>>
tst_test.c:1096: INFO: Timeout per run is 0h 05m 00s
execve05.c:75: FAIL: execve() returned unexpected errno: EACCES
execve05.c:75: FAIL: execve() returned unexpected errno: EACCES
execve05.c:75: FAIL: execve() returned unexpected errno: EACCES

After reading the man page i think that we fall into one of the following situations:
1. EACCES Execute permission is denied for the file or a script or ELF interpreter. -  we have the sanitary minimum of users in our system. systemd users and our 2. Even root is not what it is supposed to be.
2. EACCES The filesystem is mounted noexec. -  All tmpfs are mounted with noexec.
I am sure that the test is very simple. I already justified it before quality guys, I was just curious.

**Comment by metan-ucw** [comment]
Cases like these could be debugged by saving a kernel crash dump and analyzing it later on. You can also try to access the magic sysrq menu over the serial console to lists running tasks.

**Comment by metan-ucw** [comment]
@embtux There is more than one execve05 process running there, but given that the kernel killed one of the execve05 children that was using less than 2MB of memory something else must have eaten the machine memory.

**Comment by metan-ucw** [comment]
Feel free to reopen if you have any additional information or want to continue to discuss the failures.
