### ISSUE TITLE
aio02 test  tst_test.c:853: CONF: test requires libaio and its development packages

### ISSUE THREAD

**Issue by embdlover** [linux-test-project/ltp#638]
Hi,
am trying to run aio02 test on ubuntu 18.04 ,while running it is saying **test requires libaio and its development packages** i have added some libaio packages through 

$apt-get install libaio1
$sudo apt-get install -y libaio-dev    
also upgraded the packages but still test case is not passing
![Screenshot from 2020-02-10 12-48-13](https://user-images.githubusercontent.com/45843740/74134922-5e642d80-4c11-11ea-9e06-9176991f6e9f.png)

**Comment by metan-ucw** [comment]
You have to re-run configure script and recompile the tests after installing the libaio-dev package.

**Comment by embdlover** [comment]
i already recompiled it by 
$make autotools
$ ./configure
$make
$make install
but still didnt got isnt it correct???

**Comment by embdlover** [comment]
> You have to re-run configure script and recompile the tests after installing the libaio-dev package.
i already recompiled it by
$make autotools
$ ./configure
$make
$make install
but still didnt got isnt it correct or else any other way i need to do it??

**Comment by metan-ucw** [comment]
You have to do 'make clean' as well before make.

**Comment by embdlover** [comment]
> You have to do 'make clean' as well before make.

yes!!worked thanks!!

**Comment by embdlover** [comment]
facing another issue 
safe_macros.c:223: BROK: aio02.c:130: open(file,16961,0644) failed: EINVAL (22)
while running same test case aio02
![Screenshot from 2020-02-10 17-54-25](https://user-images.githubusercontent.com/45843740/74149936-f91f3500-4c2e-11ea-90b2-0fdf9adbdadb.png)

**Comment by embdlover** [comment]
> You have to do 'make clean' as well before make.



> You have to do 'make clean' as well before make.

facing another issue
safe_macros.c:223: BROK: aio02.c:130: open(file,16961,0644) failed: EINVAL (22)
while running same test  aio02 one thing i am using RISCV target
![Screenshot from 2020-02-10 17-54-25](https://user-images.githubusercontent.com/45843740/74150496-07ba1c00-4c30-11ea-81fa-d850ea01825e.png)
