### ISSUE TITLE
safe_macros.c:223: BROK: aio02.c:130: open(file,16961,0644) failed: EINVAL (22)

### ISSUE THREAD

**Issue by embdlover** [linux-test-project/ltp#639]
Hi,
i am running aio02 test on my RISC v machine,my testing is getting failed with the message
**safe_macros.c:223: BROK: aio02.c:130: open(file,16961,0644) failed: EINVAL (22)**
![Screenshot from 2020-02-10 17-54-25](https://user-images.githubusercontent.com/45843740/74212581-d9cde980-4cba-11ea-808a-76b73c35ec15.png)

**Comment by xuyang0410** [comment]
I guess some flag is not supported on your machine. Can you provide more info(df -Th, kernel version)?

**Comment by embdlover** [comment]
can you elaborate,which flag ?

**Comment by embdlover** [comment]
kernel version 5.4.3
![Screenshot from 2020-02-11 15-09-20](https://user-images.githubusercontent.com/45843740/74225349-88d0ec00-4ce0-11ea-832d-dceb4cb17e9c.png)
$df -TH

Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       23G   21G  1.5G  94% /
devtmpfs       devtmpfs  4.2G     0  4.2G   0% /dev
tmpfs          tmpfs     4.2G     0  4.2G   0% /dev/shm
tmpfs          tmpfs     4.2G   36M  4.2G   1% /run
tmpfs          tmpfs     4.2G     0  4.2G   0% /sys/fs/cgroup
tmpfs          tmpfs     4.2G     0  4.2G   0% /tmp
tmpfs          tmpfs     4.2G   78k  4.2G   1% /var/volatile

**Comment by xuyang0410** [comment]
like yang xiao said, O_DIRECT flag is not supported for tmpfs,  you can remove .needs_tmpdir = 1(it will leave file in current dir) or mount valid filesytem to make case pass temporary.  Also, if you have sent a mail to ltp mail list, it will not need to create a issue on github.
