### ISSUE TITLE
new access01 tests fail as root

### ISSUE THREAD

**Issue by jjelinek** [linux-test-project/ltp#64]
Is running this test as root unsupported? Here is the output:
<<<test_output>>>
access01.c:88: PASS: access(accessfile_rwx, F_OK)
incrementing stop
access01.c:88: PASS: access(accessfile_rwx, X_OK)
access01.c:88: PASS: access(accessfile_rwx, W_OK)
access01.c:88: PASS: access(accessfile_rwx, R_OK)
access01.c:88: PASS: access(accessfile_rwx, R_OK|W_OK)
access01.c:88: PASS: access(accessfile_rwx, R_OK|X_OK)
access01.c:88: PASS: access(accessfile_rwx, W_OK|X_OK)
access01.c:88: PASS: access(accessfile_rwx, R_OK|W_OK|X_OK)
access01.c:88: PASS: access(accesfile_x, X_OK)
access01.c:88: PASS: access(accesfile_w, W_OK)
access01.c:88: PASS: access(accesfile_r, R_OK)
access01.c:105: PASS: access(accesfile_r, X_OK): EACCES
access01.c:95: FAIL: access(accesfile_r, W_OK) succeded unexpectedly
access01.c:95: FAIL: access(accesfile_w, R_OK) succeded unexpectedly
access01.c:105: PASS: access(accesfile_w, X_OK): EACCES
access01.c:95: FAIL: access(accesfile_x, R_OK) succeded unexpectedly
access01.c:95: FAIL: access(accesfile_x, W_OK) succeded unexpectedly
access01.c:105: PASS: access(accesfile_r, W_OK|X_OK): EACCES
access01.c:105: PASS: access(accesfile_r, R_OK|X_OK): EACCES
access01.c:95: FAIL: access(accesfile_r, R_OK|W_OK) succeded unexpectedly
access01.c:105: PASS: access(accesfile_r, R_OK|W_OK|X_OK): EACCES
access01.c:105: PASS: access(accesfile_w, W_OK|X_OK): EACCES
access01.c:105: PASS: access(accesfile_w, R_OK|X_OK): EACCES
access01.c:95: FAIL: access(accesfile_w, R_OK|W_OK) succeded unexpectedly
access01.c:105: PASS: access(accesfile_w, R_OK|W_OK|X_OK): EACCES
access01.c:95: FAIL: access(accesfile_x, W_OK|X_OK) succeded unexpectedly
access01.c:95: FAIL: access(accesfile_x, R_OK|X_OK) succeded unexpectedly
access01.c:95: FAIL: access(accesfile_x, R_OK|W_OK) succeded unexpectedly
access01.c:95: FAIL: access(accesfile_x, R_OK|W_OK|X_OK) succeded unexpectedly

**Comment by metan-ucw** [comment]
Known issue, the read/write flags are ignored as root is allowed to read/write all the files on system.

I will have to fix the test to run the checks as different user.
