### ISSUE TITLE
running kill11 test setrlimit(4,0x3ffff109c0) failed: errno=EINVAL(22): Invalid argument

### ISSUE THREAD

**Issue by embdlover** [linux-test-project/ltp#640]
Hi,
 i am trying to run kill11 test on machine my test is getting breaked with follwing message.

kill11      0  TINFO  :  Adjusting RLIMIT_CORE to 1048576
kill11      1  TBROK  :  ../../../../include/old/safe_macros.h:312: kill11.c:207: setrlimit(4,0x3ffff109c0) failed: errno=EINVAL(22): Invalid argument
kill11      2  TBROK  :  ../../../../include/old/safe_macros.h:312: Remaining cases broken

**Comment by xuyang0410** [comment]
RLIMIT_CORE
              This  is  the maximum size of a core file (see core(5)) in bytes that the process may dump.  When 0 no core dump files are created.  When nonzero, larger dumps are truncated to this size.
 EINVAL The value specified in resource is not valid; or, for setrlimit() or prlimit(): rlim->rlim_cur was greater than rlim->rlim_max.
I guess  rlim->rlim_max less than  1048576, so it will reports EINVAL. Can you print rlimit.rlim_max ( tst_resm(TINFO, "%lu %lu", rlim.rlim_cur, rlim.rlim_max);)info before setrlimit.

**Comment by xuyang0410** [comment]
You can run "ulimit -c 1024", and then run this case. It will pass.

**Comment by embdlover** [comment]
i ran the ulimit-c command but didnt worked also i am getting foolowing results
rlim.rlim_cur=524288  rlim.rlim_max=524288  TINFO  :  Adjusting RLIMIT_CORE to 1048576

where i should make the changes?

**Comment by xuyang0410** [comment]
Can you please attach  the output of your "ulimit -c 1024"  command. From your log,  rlim.rlim_max less than 1048576, so it got EINVAL. Also, unprivileged user can not raise rlim.rlim_max value. Do you test this under root user?

**Comment by embdlover** [comment]
yes i am running these as root...ulimit-c 1024 doesnt returned anything both rlim.rlim_cur=524288 rlim.rlim_max=524288 having same values.i am attaching test output here

**Comment by xuyang0410** [comment]
It is strange. Maybe your blocksize is 512 not 1024 , kill11.c uses 1024 *1024.  "ulimit -c 2048" can make this case pass.

**Comment by xuyang0410** [comment]
From ulimit manpage, in POSIX Mode 512-byte blocks are used for the `-c' and `-f' options.  So you may run "ulimit -c 2048" command before this case.

**Comment by embdlover** [comment]
my rlim.rlim_max=524288 and it is saying Adjusting RLIMIT_CORE to 1048576. How it can set RLIMIT_CORE to  1048576 as rlim.rlim_max=524288???
is it possible?

**Comment by xuyang0410** [comment]
Yes, under privileged user, you can raise this value by adding  “”rlim.rlim_max = MIN_RLIMIT_CORE "before setrlimit. But if you ran "ulimit -c 2048"(it set cur and max as a same value), it also can pass  because it doesn't run into this if.

**Comment by embdlover** [comment]
yes!!worked with ulimit -c 2048....but didnt got why it is like so????

**Comment by xuyang0410** [comment]
I have said in previous comment. From "ulimit" man pages, in posix mode, ulimit -c used  512-byte blocks, common mode used 1024-byte blocks.  Use ulimit -c 1024(the cur and max value is 1024 * 512), ulimit -c 2048 (the cur and max value is 2048 * 512),  MIN_RLIMIT_CORE is 1024 * 1024, so ulimit -c 2048 meet this min core size and pass.

**Comment by xuyang0410** [comment]
Also, I will cleanup this case(convert into new api) and avoid this similar issue.

**Comment by embdlover** [comment]
but i am rebuilding again it is throwing same result...is there any way to permanently resolve it ??

**Comment by xuyang0410** [comment]
like the way Jan stancek said in [syscalls/kill11: add a check between hard limit and MIN_RLIMIT_CORE](http://lists.linux.it/pipermail/ltp/2020-February/015395.html), it can always pass under root user. You can try it (this way is the same as my first way set rlim.rlim_max to MIN_RLIMIT_CORE )

**Comment by embdlover** [comment]
ok..thank you

**Comment by embdlover** [comment]
Also i am running test case min_free_kbytes test in which 6 testcases are failing with min_free_kbytes.c:134: FAIL: child unexpectedly failed: 139
![Screenshot from 2020-02-13 14-11-14](https://user-images.githubusercontent.com/45843740/74416168-b9449180-4e6a-11ea-85dd-3b8994dc7d16.png)
