### ISSUE TITLE
write regression test for kernel commit 6551d5c56eb0d02db2274d7a8d26c333deba7fd2

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#644]
commit 6551d5c56eb0d02db2274d7a8d26c333deba7fd2
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Tue Feb 18 10:12:58 2020 -0800

    pipe: make sure to wake up everybody when the last reader/writer closes

    Andrei Vagin reported that commit 0ddad21d3e99 ("pipe: use exclusive
    waits when reading or writing") broke one of the CRIU tests.  He even
    has a trivial reproducer:
    
        #include <unistd.h>
        #include <sys/types.h>
        #include <sys/wait.h>
    
        int main()
        {
                int p[2];
                pid_t p1, p2;
                int status;
    
                if (pipe(p) == -1)
                        return 1;
    
                p1 = fork();
                if (p1 == 0) {
                        close(p[1]);
                        read(p[0], &status, sizeof(status));
                        return 0;
                }
                p2 = fork();
                if (p2 == 0) {
                        close(p[1]);
                        read(p[0], &status, sizeof(status));
                        return 0;
                }
                sleep(1);
                close(p[1]);
                wait(&status);
                wait(&status);
    
                return 0;
        }
    
    and the problem - once he points it out - is obvious.  We use these nice
    exclusive waits, but when the last writer goes away, it then needs to
    wake up _every_ reader (and conversely, the last reader disappearing
    needs to wake every writer, of course).

**Comment by xuyang0410** [comment]
I have sent a patch [syscalls/pipe13: Add regression test for pipe to wake up all readers ](https://patchwork.ozlabs.org/patch/1242985/) about this.

**Comment by yangx-jy** [comment]
This regression test is already introduced by cbc2b00.
Thanks a lot for Yang Xu's work.
