### ISSUE TITLE
ksm03,ksm04 and oom03 test cases failing

### ISSUE THREAD

**Issue by embdlover** [linux-test-project/ltp#645]
I am running ksm03, kms04 ,oom03 on my RISC  v system wth linux 5.4.3,LTP Version: 20200120-55-g537fb6535 with custom Yocto distro,test is  breaking with following errors.

**tst_test.c:1215: INFO: Timeout per run is 0h 05m 00s
mem.c:760: BROK: mount /dev/cgroup: EINVAL (22)**

tst_test.c:1215: INFO: Timeout per run is 0h 05m 00s
**safe_macros.c:167: BROK: mem.c:750: mkdir(/dev/cgroup,0777) failed: EEXIST (17)**

From the log and observation i come to know that is trying to mount at /dev/cgroup instead /sys/fs/cgroups/ but i am not able to get why it is trying to mount there ??

**Comment by wangli5665** [comment]
Thanks for reporting this error.

Trying to mount cgroup v1 at /dev/cgroup is only for temporary resource-limit setting in tests. As you run the tests on kernel-5.4+, which probably enabling cgroup-v2 already, there will be conflict in mixed using v1 and v2.

A proposal patchset to solving the problem:
http://lists.linux.it/pipermail/ltp/2020-May/017307.html

**Comment by wangli5665** [comment]
With the new cgroup test API merging, I assume this issue has been solved.
Any question please leave a comment or reopen it.

https://github.com/linux-test-project/ltp/commit/3b716981bd5422c256e1bdf76fe55c653bd460fa
https://github.com/linux-test-project/ltp/commit/cff40383fcaae77e7b2dbd3aef29c6e7ae821a1d
