### ISSUE TITLE
Since glibc v2.31, settimeofday tests start to fail

### ISSUE THREAD

**Issue by ywangwrs** [linux-test-project/ltp#646]
Glibc v2.31 released on Feb 01, 2020
https://sourceware.org/ml/libc-announce/2020/msg00001.html

Since this version, settimeofday function got some change which is mentioned in above release notes. This change caused failures when running test cases settimeofday01 and settimeofday02.

root@intel-x86-64:~/ltp-master/testcases/kernel/syscalls/settimeofday# ./settimeofday01
settimeofday01    1  TPASS  :  Test condition 1 successful
settimeofday01    2  TBROK  :  tst_sig.c:232: unexpected signal SIGSEGV(11) received (pid = 5531).
settimeofday01    3  TBROK  :  tst_sig.c:232: Remaining cases broken

Which is because settimeofday (tv, tz) will cause broken when both tv and tz are NULL.

So these test cases need to be changed to adapt to v2.31 of glibc.

**Comment by xuyang0410** [comment]
I perfer to remove this situation(EFAULT error, when both tv and tz are NULL ). Or, cleanup this case only to test time but not timezone.

**Comment by metan-ucw** [comment]
I guess that we can safely remove the second testcase in the gettimeofday01 where we pass -1 casted to a pointer to the call. Also the test should be cleaned up.

**Comment by xuyang0410** [comment]
@metan-ucw  I will remove  gettimeofday01.c test case. Also, I will clean up settimeofday01.c and settimeofday02.c.

**Comment by xuyang0410** [comment]
@ywangwrs ，these two cases have been rewritten.
[c9607c15](https://github.com/linux-test-project/ltp/commit/c9607c152249df9904a90d6f8bcd415e193602e8)
[ccbbe7715](https://github.com/linux-test-project/ltp/commit/ccbbe7715ba632982ff0b9e2f8be20c80e)

**Comment by pevik** [comment]
Correct, they're fixed. @xuyang0410 thanks for pointing this out.

**Comment by ywangwrs** [comment]
> @ywangwrs these two cases have been rewritten.
> [c9607c1](https://github.com/linux-test-project/ltp/commit/c9607c152249df9904a90d6f8bcd415e193602e8), [0c99e15](https://github.com/linux-test-project/ltp/commit/0c99e15cbbe7715ba632982ff0b9e2f8be20c80e)

Thanks a lot, xuyang0410.
