### ISSUE TITLE
LTP project TCases documentation

### ISSUE THREAD

**Issue by IslamHelmy** [linux-test-project/ltp#65]
I have a concern regarding the **LTP project test cases documentation** , is it there somewhere or only we have to rely on the test case source code ?

As i need to analyze some of the test cases after being executed at my system however i can't find a documentation for that to understand the purpose of the test.

My proposal is to have this documentation added to the source code itself instead of having it somewhere else. (as a comments at the beginning of the test code)
If this is not doable, then what are the proposals that we might have for doing so ? 

Thanks for this useful project and i hope we all work to get it always in a better shape

**Comment by metan-ucw** [comment]
Most of the testcases have a short comment explaining the purpose of a test at the top of the source code already, if it's not there you have to look at the test source code. Patches to add short and reasonable description to testcases that miss it are of course welcome.

Also generally you will end up reading the source code for any failing testcases anyway, the comment on the top only helps you to understand the big picture before you dive into the technical details. So there is no point in overcommenting them or in explaining the obvious, etc.

**Comment by IslamHelmy** [comment]
Thanks for your answer , 
I think we need to work on pushing that approach for many reasons.
This will have definitely more than one advantage as follows :

1. To track the purpose vs Test case [reviewing and identifying mistakes within test-case]
2. To know what are the scenarios missing from a testing point of view [Positive,Negative test scenarios,robustness test ,and missing test techniques]
3. To simply the test case analysis in case of failure.

**Comment by metan-ucw** [comment]
As I said patches are certainly welcome.

**Comment by IslamHelmy** [comment]
Just to make sure i understand you fully , by patches you mean to have a patch file which will override the test case source code [adding the comments], or it's something else ?

**Comment by metan-ucw** [comment]
Yes, and technically patch does not override source code but rather adds or removes lines.

**Comment by IslamHelmy** [comment]
Thank you
