### ISSUE TITLE
vma05 test case 1 failed with 5.6.0 mainline kernel

### ISSUE THREAD

**Issue by Cypresslin** [linux-test-project/ltp#650]
Environment: Ubuntu Focal + 5.6.0-050600rc4-generic

In 5.6.0 kernel, the pattern in /proc/self/maps will be like:

    ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0 [vsyscall]

So it does not match the test case expectation:

    ffffffffff600000-ffffffffff601000[[:space:]]r-xp

And eventually failed with:

     vma05 1 TFAIL: [vsyscall] reporting wrong

Maybe it has something to do with https://github.com/torvalds/linux/commit/bd49e16e3339f052fae05fb3e955c5db0c9c6445 which add the XONLY mode and make it execute-only.

    $ grep -i vsys /boot/config-5.6.0-050600rc4-generic 
    CONFIG_GENERIC_TIME_VSYSCALL=y
    CONFIG_X86_VSYSCALL_EMULATION=y
    # CONFIG_LEGACY_VSYSCALL_EMULATE is not set
    CONFIG_LEGACY_VSYSCALL_XONLY=y
    # CONFIG_LEGACY_VSYSCALL_NONE is not set

**Comment by metan-ucw** [comment]
I guess that we can replace the r in the RIGHT pattern with a dot '.' that matches any character, does that fix the issue for you?

**Comment by Cypresslin** [comment]
Hi yes,
or we can use [r-] instead, in case it became something else:

    RIGHT="ffffffffff600000-ffffffffff601000[[:space:]][r-]-xp"

**Comment by metan-ucw** [comment]
Can you send a patch then?

**Comment by Cypresslin** [comment]
OK!

**Comment by metan-ucw** [comment]
Fixed in 1c0e86d28f34e2d7b0d8772700595aafec18ca76
