### ISSUE TITLE
bpf_prog02 and bpf_prog03 fails with EPERM(1)

### ISSUE THREAD

**Issue by mikefn** [linux-test-project/ltp#651]
Both tests fails with error EPERM (1) after CAP_SYS_ADMIN is dropped:

> ./bpf_prog02 -i 10
tst_buffers.c:55: INFO: Test is using guarded buffers
tst_test.c:1229: INFO: Timeout per run is 0h 05m 00s
bpf_common.c:18: INFO: Raising RLIMIT_MEMLOCK to 18874368
tst_capability.c:29: INFO: Dropping CAP_SYS_ADMIN(21)
bpf_common.c:43: BROK: Failed to create array map: EPERM (1)
Summary:
passed   0
failed   0
skipped  0
warnings 0

> ./bpf_prog03
tst_buffers.c:55: INFO: Test is using guarded buffers
tst_test.c:1229: INFO: Timeout per run is 0h 05m 00s
bpf_common.c:18: INFO: Raising RLIMIT_MEMLOCK to 18874368
tst_capability.c:29: INFO: Dropping CAP_SYS_ADMIN(21)
bpf_common.c:43: BROK: Failed to create array map: EPERM (1)
Summary:
passed   0
failed   0
skipped  0
warnings 0

I tried to compile tests without caps dropping:

`      .caps = (struct tst_cap []) {
              TST_CAP(TST_CAP_DROP, CAP_SYS_ADMIN),
              {}
      },`

and tests PASS:

> ./bpf_prog02
tst_buffers.c:55: INFO: Test is using guarded buffers
tst_test.c:1229: INFO: Timeout per run is 0h 05m 00s
bpf_common.c:18: INFO: Raising RLIMIT_MEMLOCK to 18874368
bpf_common.c:82: PASS: Loaded program
bpf_prog02.c:119: PASS: val = 1152921504606846976 + 1
bpf_prog02.c:136: PASS: val = 1152921504606846976 - 1
Summary:
passed   3
failed   0
skipped  0
warnings 0

> ./bpf_prog03
tst_buffers.c:55: INFO: Test is using guarded buffers
tst_test.c:1229: INFO: Timeout per run is 0h 05m 00s
bpf_common.c:18: INFO: Raising RLIMIT_MEMLOCK to 18874368
bpf_prog03.c:107: PASS: Failed verification: EACCES (13)
Summary:
passed   1
failed   0
skipped  0
warnings 0

I'm not sure this is expected behavior. Is it really needs to drop CAP_SYS_ADMIN?

**Comment by xuyang0410** [comment]
AFAIK, bpf_prog02 is a regression test for unprivileged user . Also unprivileged user can run this syscall when /proc/sys/kernel/unprivileged_bpf_disabled is 0.   So it is need to drop CAP_SYS_ADMIN.
If /proc/sys/kernel/unprivileged_bpf_disabled is 1, this case should report TCONF, but bpf_common.h has a small problem fail to report it, see[bpf_common.h: Use errno instead of TST_ERR ](https://patchwork.ozlabs.org/patch/1248892/).

**Comment by metan-ucw** [comment]
The patch from the second comment has been accepted, feel free to reopen if that haven't fixed the issue.
