### ISSUE TITLE
Does LTP test have a standard rootfs?

### ISSUE THREAD

**Issue by gengcixi** [linux-test-project/ltp#662]
I would like to know if we have a rootfs that contains all needed package and libs etc.

**Comment by metan-ucw** [comment]
There is no such thing, at least no official one I know of.

For libraries you can have a look at files in the travis directory, these contain installation instructions for different distributions, for example for debian we have this one:

https://github.com/linux-test-project/ltp/blob/master/travis/debian.sh

As for binaries, there is no docs AFAIK. For filesystem related tests LTP needs mkfs.* to format the device, there are a few tests that needs quotactl command and there maybe a few more.

**Comment by pevik** [comment]
IMHO rootfs is provided by linux distribution. Compile LTP with https://buildroot.org/ or https://www.yoctoproject.org/ to get whole working system with dependencies. Or, if you plan to use LTP just on regular Linux distribution, search in sources for `TST_NEEDS_CMDS` (dependencies for shell) and for `.needs_cmds` (dependency for C code).

**Comment by gengcixi** [comment]
Thanks all your answers, I am building a debian rootfs for ltp test on github:
https://github.com/gengcixi/build-debian-rootfs.git
and supplement the packages by mytest log, Now I will continue to add from your answers 
Thanks again!
