### ISSUE TITLE
Missing kernel object file: ltp_fw_load.ko

### ISSUE THREAD

**Issue by ywangwrs** [linux-test-project/ltp#665]
When doing the fw_load test, it always complains:
==============
fw_load     1  TCONF  :  tst_module.c:69: Failed to find module 'ltp_fw_load.ko'
fw_load     2  TCONF  :  tst_module.c:69: Remaining cases not appropriate for configuration
==============
When doing it manually, I got this:
==============
# cd ltp/testcases/kernel/firmware/fw_load_kernel
# make
make: Nothing to be done for 'all'.
==============

**Comment by xuyang0410** [comment]
I guess you miss kernel-devel package on your system. more info see [kbuild](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/kbuild/modules.rst) and [build-system-guide.txt](https://github.com/linux-test-project/ltp/blob/master/doc/build-system-guide.txt#L76). Also have m4/ltp-kernel_devel.m4 to detect this.

**Comment by ywangwrs** [comment]
Thanks for the response, @xuyang0410.

I followed the instruction in [kbuild](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/kbuild/modules.rst) to build out the missing file ltp_fw_load.ko successfully.

Basically, the steps are:

- Include kernel-devsrc into build config file
- Load the image onto target, and download LTP package
- cd ltp/testcases/kernel/firmware/fw_load_kernel
- make -C /lib/modules/`uname -r`/build M=$PWD
- The ltp_fw_load.ko got generated
- Then I copy ltp_fw_load.ko into the folder to run fw_load, for example: ltp/testcases/kernel/firmware/fw_load_user/
- cd ltp/testcases/kernel/firmware/fw_load_user && ./fw_load

=======Passed=======
ltp_fw_load: device registered
ltp_fw_load: firmware 'n0_load_tst.fw' requested
ltp_fw_load: Firmware has size '4096'
ltp_fw_load: firmware 'n1_load_tst.fw' requested
ltp_fw_load: Firmware has size '4096'
ltp_fw_load: firmware 'n2_load_tst.fw' requested
ltp_fw_load: Firmware has size '4096'
ltp_fw_load: firmware 'n3_load_tst.fw' requested
ltp_fw_load: Firmware has size '4096'
 ltp_fw_load: Direct firmware load for n4_load_tst.fw failed with error -2
ltp_fw_load: Can't request firmware 'n4_load_tst.fw'
fw_load     1  TPASS  :  Expect: can load firmware '.../n0_load_tst.fw'
fw_load     2  TPASS  :  Expect: caltp_fw_load: device released
ltp_fw_load: module exited
n load firmware '.../n1_load_tst.fw'
fw_load     3  TPASS  :  Expect: can load firmware '.../n2_load_tst.fw'
fw_load     4  TPASS  :  Expect: can load firmware '.../n3_load_tst.fw'
fw_load     5  TPASS  :  Expect: can't load firmware '.../n4_load_tst.fw'
====================

But how when running '/opt/ltp/runltp -s fw_load' still fails with missing file ltp_fw_load.ko?

I did "make -C  /lib/modules/`uname -r`/build M=$PWD modules_install", but it only copies ltp_fw_load.ko into /lib/modules/`uname -r`/extra, which doesn't help with running runltp.

How can we make this test pass without extra manual steps?

**Comment by xuyang0410** [comment]
fw_load.c uses tst_module_load api, it will check module whether existed in ltp installed directory, if not existed, it will check whether existed in current workdir. more info see[tst_module.c](https://github.com/linux-test-project/ltp/blob/master/lib/tst_module.c#L45). So you should cp ltp_fw_load.ko into /opt/ltp/testcases/bin, then you can run pass. But I would like install kernel-dev package if you use offical distritbution , then make autotools && ./configure && make &&  make install && ./runltp -s fw_load. kbuild is a backgroud knowledge。

**Comment by ywangwrs** [comment]
Thanks @xuyang0410 .

Then close this ticket.
