### ISSUE TITLE
chown tests fail on ARM device (Marvell CN96xx): /dev/loop1 is mounted; will not make a filesystem here!

### ISSUE THREAD

**Issue by ywangwrs** [linux-test-project/ltp#672]
This issue looks like: https://github.com/linux-test-project/ltp/issues/92, but fails with different test cases, it happens from time to time.

=================Test Log===============
<<<test_start>>>
tag=chown04 stime=1583994817
cmdline="chown04"
contacts=""
analysis=exit
<<<test_output>>>
mke2fs 1.45.4 (23-Sep-2019)
/dev/loop1 is mounted; will not make a filesystem here!
chown04 0 TINFO : Using test device LTP_DEV='/dev/loop1'
chown04 0 TINFOLTP: starting chown04_16
: Formatting /dev/loop1 with ext4 opts='' extra opts=''
chown04 1 TBROK : tst_mkfs.c:100: chown04.c:152: mkfs.ext4 failed with 1
chown04 2 TBROK : tst_mkfs.c:100: Remaining cases broken
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=6
<<<test_end>>>
<<<test_start>>>
tag=chown04_16 stime=1583994817
cmdline="chown04_16"
contacts=""
analysis=exit
<<<test_output>>>
mke2fs 1.45.4 (23-Sep-2019)
/dev/loop1 is mounted; will not make a filesystem hereLTP: starting chown05
!
chown04_16 0 TINFO : Using test device LTP_DEV='/dev/loop1'
chown04_16 0 TINFO : Formatting /dev/loop1 with ext4 opts='' extra opts=''
chown04_16 1 TBROK : tst_mkfs.c:100: chown04.c:152: mkfs.ext4 failed with 1
chown04_16 2 TBROK : tst_mkfs.c:100: Remaining cases broken
<<<execution_status>>>
initiation_status="ok"
duration=1 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=2
<<<test_end>>>

<<<test_start>>>
tag=fchown04 stime=1583994875
cmdline="fchown04"
contacts=""
analysis=exit
<<<test_output>>>
mke2fs 1.45.4 (23-Sep-2019)
/dev/loop1 is mounted; will not make a filesystem here!
fchown04 0 TINFO : Using test device LTP_DEV='/dev/loop1'
fchown04 0 TINFO : Formatting /dev/loop1 with ext4 opts='' extra opts=''
fchown04 1 TBROK : tst_mkfs.c:100: fchown04.c:116: mkfs.ext4 failed with 1
fchown04 2 TBROK : tst_mkfs.c:100: Remaining cases broken
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=2LTP: starting fchownat01
corefile=no
cutime=1 cstime=4
<<<test_end>>>
<<<test_start>>>
tag=fchown04_16 stime=1583994875
cmdline="fchown04_16"
contacts=""
analysis=exit
<<<test_output>>>
mke2fs 1.45.4 (23-Sep-2019)
/dev/loop1 is mounted; will not make a filesystem here!
fchown04_16 0 TINFO : Using test device LTP_DEV='/dev/loop1'
fchown04_16 0 TINFO : Formatting /dev/loop1 with ext4 opts='' extra opts=''
fchown04_16 1 TBROK : tst_mkfs.c:100: fchown04.c:116: mkfs.ext4 failed with 1
fchown04_16 2 TBROK : tst_mkfs.c:100: Remaining cases broken
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=1
<<<test_end>>>

<<<test_start>>>
tag=fallocate04 stime=1583994872
cmdline="fallocate04"
contacts=""
analysis=exit
<<<test_output>>>
tst_device.c:244: INFO: Using test device LTP_DEV='/dev/loop1'
tst_supported_fs_types.c:60: INFO: Kernel supports ext2
tst_supported_fs_types.c:44: INFO: mkfs.ext2 does exist
tst_supported_fs_types.c:60: INFO: Kernel supports ext3
tst_supported_fs_types.c:44: INFO: mkfs.ext3 does exist
tst_supported_fs_types.c:60: INFO: Kernel supports ext4
tst_supported_fs_types.c:44: INFO: mkfs.ext4 does exist
tst_supported_fs_types.c:83: INFO: Filesystem xfs is not supported
tst_supported_fs_types.c:60: INFO: Kernel supports btrfs
tst_supported_fs_types.c:40: INFO: mkfs.btrfs does not exist
tst_supported_fs_types.c:60: INFO: Kernel supports vfat
tst_supported_fs_types.c:44: INFO: mkfs.vfat does exist
tst_supported_fs_types.c:83: INFO: Filesystem exfat is not supported
tst_supported_fs_types.c:83: INFO: Filesystem ntfs is not supported
tst_test.c:1278: INFO: Testing on ext2
tst_mkfs.c:89: INFO: Formatting /dev/loop1 with ext2 opts='' extra opts=''
mke2fs 1.45.4 (23-Sep-2019)
/dev/loop1 is mounted; will not make a filesystem here!
tst_mkfs.c:100: BROK: tst_test.c:830: mkfs.ext2 failed with 1

Summary:
passed 0
failed 0
skipped 0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=1 termination_type=exited termination_id=2 corefile=no
cutime=2 cstime=19
<<<test_end>>>

**Comment by jstancek** [comment]
This is sometimes side-effect of failing test which ran prior to chown04, got stuck and had to be killed. Was there any failure from tests which ran before chown04?

**Comment by metan-ucw** [comment]
Closing since there was no response for two months, fee free to reopen if needed.
