### ISSUE TITLE
query about testcase 'realtime'

### ISSUE THREAD

**Issue by qyjyork** [linux-test-project/ltp#675]
Hi,
I have a query about the testcase 'realtime'.
In the 'readme' of 'realtime', it says, and I quote, 'realtime tests is an open-source testsuite for testing real-time Linux'. and 'The latest version of this testsuite is available from http://rt.wiki.kernel.org.'
Yet when I opened ri.wiki, I found a new testsuite called 'rt_test' which is quite different from the one in LTP.
So I'd like to ask about the relationship and difference between the testcase 'realtime' from LTP and the 'rt_test' from rt.wiki.  Thanks.

![rt_test](https://user-images.githubusercontent.com/31507240/81365162-0195e780-911a-11ea-8892-2ff7815ba55f.png)

Best regards.

**Comment by metan-ucw** [comment]
I guess that LTP includes older version of these test, if nothing else the realtime tests in LTP were not update in a long time so you are probably better with the test from the realtime wiki.
