### ISSUE TITLE
query about stress test

### ISSUE THREAD

**Issue by qyjyork** [linux-test-project/ltp#676]
Hi,
In some vintage documentations, they mentioned a script for stress test called 'ltpstress.sh'.
However, I cannot find it in the latest version of LTP.
So, is 'ltpstress.sh' no longer avaliable? And if I want to perform a stress test, should I run 'runltp' instead with additional options?

Thanks.
Best regards.

**Comment by dotleo** [comment]
I have the same question。Do you porting ltp to android ?

**Comment by qyjyork** [comment]
nope, I use it in embedded system

**Comment by pevik** [comment]
It was removed in e752f7c19674d9b2f7d37aed123561a3f6410e97 (released in 20190115). Just run those runtest files with `runltp`. FYI even `runltp` is deprecated, we're working on making Cyril's [runltp-ng](https://github.com/metan-ucw/runltp-ng) ready for upstreaming.
https://people.kernel.org/metan/towards-parallel-kernel-test-runs
