### ISSUE TITLE
Who has the experience of transplanting LTP to Android system

### ISSUE THREAD

**Issue by dotleo** [linux-test-project/ltp#677]
Who has the experience of transplanting LTP to Android system, can you share it?

**Comment by dotleo** [comment]
Who has the experience of transplanting LTP to Android system, can you share it? tks a lot

**Comment by metan-ucw** [comment]
There is latest stable version in the android AOSP tree at https://android.googlesource.com/platform/external/ltp/

Also @smuckle should know more.

**Comment by smuckle** [comment]
There's a readme in that tree at https://android.googlesource.com/platform/external/ltp/+/refs/heads/master/android/README.md that talks about running LTP on Android through VTS. Unfortunately there's a bit of churn there at the moment, the VTS tests have all just recently been reworked (LTP in the last few days) so these instructions are now a little out of date. I expect the instructions will be updated by early next week.

**Comment by dotleo** [comment]
> There's a readme in that tree at https://android.googlesource.com/platform/external/ltp/+/refs/heads/master/android/README.md that talks about running LTP on Android through VTS. Unfortunately there's a bit of churn there at the moment, the VTS tests have all just recently been reworked (LTP in the last few days) so these instructions are now a little out of date. I expect the instructions will be updated by early next week.

Thanks a lot for your reply.

**Comment by dotleo** [comment]
> There is latest stable version in the android AOSP tree at https://android.googlesource.com/platform/external/ltp/
> 
> Also @smuckle should know more.

Thanks a lot for your reply.

**Comment by pevik** [comment]
\+ I also tried to fix LTP upstream to be buildable with Android standalone compiler, but it's a long time. We also merged some fixes for Android runtime (posted by Android developers).

**Comment by dotleo** [comment]
> + I also tried to fix LTP upstream to be buildable with Android standalone compiler, but it's a long time. We also merged some fixes for Android runtime (posted by Android developers).

DO you use VTS to run the ltp testcases ？ OR adb push  /opt/ltp/ into the phone?

**Comment by metan-ucw** [comment]
I think that petr only worked on build failures. Anyway let's close this one, feel free to reopen for a further discussion.
