### ISSUE TITLE
Cannot run fcntl31 and fcntl31_64 as process leaders over SSH

### ISSUE THREAD

**Issue by fallen** [linux-test-project/ltp#679]
This fails:
ssh localhost path/to/fcntl31
This does not fail:
./path/to/fcntl31

**Comment by fallen** [comment]
See this PR for the fix: https://github.com/linux-test-project/ltp/pull/680

**Comment by metan-ucw** [comment]
Let's close this since there is a patch waiting for review at https://patchwork.ozlabs.org/project/ltp/patch/20200513121327.16342-1-ysionneau@kalray.eu/

**Comment by fallen** [comment]
Isn't it better to wait for the patch to be merged before closing the issue?

**Comment by fallen** [comment]
Ah, I notice it has just been merged, thanks :)
