### ISSUE TITLE
Kdump test code is out of date.

### ISSUE THREAD

**Issue by GGain** [linux-test-project/ltp#68]
/proc filesystem has been refactored in 3.10, many function used in Kdump test has been removed.
For example.
 In current code, it use create_proc_* but it changed to proc_create.

Please update the test code.

**Comment by metan-ucw** [comment]
Feel free to send a patch. :)

This should be as easy as a few ifdefs in the crasher.c source code, there are a few
```
#ifdef LINUX_VERSION_CODE < KERNEL_VERSION(...)

#endif
```
there already.

**Comment by metan-ucw** [comment]
FYI: I'm looking at the pull #66 which is supposed to fix this.

**Comment by GGain** [comment]
Thank you for quick response. The pull #66 is helpful. I will apply it and check in Ubuntu.
Sorry because of no looking in the pull request for finding if there is some work fixed it.
