### ISSUE TITLE
The problem about core dump

### ISSUE THREAD

**Issue by AaronDot** [linux-test-project/ltp#682]
Hi,
I find some test cases, such as kill11 and mmap16, that will produce the core dump in the system.
But these test cases are still passed at last.
Is this normal?
How can I explain it?

**Comment by metan-ucw** [comment]
This is a kernel testsuite some test are crashing on purpose since we need to (ideally) cover all codepaths in the kernel.

**Comment by wangli5665** [comment]
And we could also add tst_no_corefile(0) in the target process to avoid dumping core file if possible.

i.e like what we do for testcases/kernel/syscalls/pkeys/pkey01.c
https://github.com/linux-test-project/ltp/blob/master/include/tst_coredump.h

**Comment by AaronDot** [comment]
> And we could also add tst_no_corefile(0) in the target process to avoid dumping core file if possible.
> 
> i.e like what we do for testcases/kernel/syscalls/pkeys/pkey01.c
> https://github.com/linux-test-project/ltp/blob/master/include/tst_coredump.h

OK，I see.
I will have a try!

Thanks.
