### ISSUE TITLE
[LTP] controller case 'cpuset_load_balance' failed

### ISSUE THREAD

**Issue by YanfeiXu** [linux-test-project/ltp#685]
Hello experts,
cpuset_load_balance process want to read from /dev/cpuset/cpuset.cpu_exclusive, but it get a wrong filename that /dev/cpuset/cpu_exclusive in fact.I wonder if the older version about /dev/cpuset/* are didn't have the "cpuset." prefix? If that, the func cpuset_query() in libcpuset.c should be updated.
The blow link is the detailed process for addressing the issue.(And sorry for the mess composition in the mail) http://lists.linux.it/pipermail/ltp/2020-February/015594.html

Thanks,
Yanfei

**Comment by YanfeiXu** [comment]
@ywangwrs

**Comment by yangx-jy** [comment]
This issue is same as #690 which has been fixed by commit ee1315c
