### ISSUE TITLE
cpuset_hotplug test fails due to race condition

### ISSUE THREAD

**Issue by qais-yousef** [linux-test-project/ltp#693]
Hi

We have come across a failure in cpuset_hotplug test due to a race condition in the way information are exported via sysfs. Hopefully the following commit message explains it well

https://lore.kernel.org/lkml/20200211141554.24181-1-qais.yousef@arm.com/

Tejun didn't take this fix in favour of another fix that was already queued in his tree.

https://lore.kernel.org/lkml/1510755615-25906-3-git-send-email-prsood@codeaurora.org/

But sadly the fix caused a regression and had to be reverted

https://lore.kernel.org/lkml/F0388D99-84D7-453B-9B6B-EEFF0E7BE4CC@lca.pw/

And Tejun was opposed to taking my fix pointed up above because he thinks the test should be fixed instead

https://lore.kernel.org/lkml/20200407133520.GI162390@mtj.duckdns.org/

AFAIK nothing has been done to re-instate the synchronous operation in cpuset. Do you think LTP can do something to fix the problem itself?

**Comment by pevik** [comment]
LGTM. Next time please send patch to our ML https://lists.linux.it/listinfo/ltp.

**Comment by qais-yousef** [comment]
Thanks Petr. I have address Huacai comment and updated both the PR and send it to the ML.
