### ISSUE TITLE
cpuset_base_ops_testset.sh using invalid "0-" cpuset input

### ISSUE THREAD

**Issue by paulgortmaker** [linux-test-project/ltp#695]
As of v5.0 kernels, the kernel has more strict parsing rules and now rejects the undocumented and rather nonsensical "0-" input which used to be allowed, resulting in two false positives:

 cpuset_base_ops 37 TFAIL: cpuset.cpus: Test result -  Expected string - "0"
 cpuset_base_ops 65 TFAIL: cpuset.mems: Test result -  Expected string - "0"

More extensive documentation of the issue can be found here:

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1830359

It would seem logical to remove the "0-" test from this script.

**Comment by ywangwrs** [comment]
@ywangwrs

**Comment by yangx-jy** [comment]
@paulgortmaker 

The mentoined commit from https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1830359 seems wrong, because I still got -EINVAL when writing '0-' to cpuset.cpus/cpuset.mems on v4.19 which doesn't apply the commit.

**Comment by yangx-jy** [comment]
@metan-ucw @pevik 

This is a change of behavior instead of bug, so do you perfer to drop '0-' subtest directly or accept either 0 or  -EINVAL?

Thanks,
Xiao Yang

**Comment by richiejp** [comment]
If it is undocumented we probably should have never tested it unless entering `0-` caused a bug at some point?

**Comment by yangx-jy** [comment]
After doing investigation, the following commit actually changes the behavior:

commit d9282cb66353be502aae09aae75d05a6863eb979
Author: Pan Xinhui <xinhuix.pan@intel.com>
Date:   Wed Sep 9 15:37:05 2015 -0700

    lib/bitmap.c: fix a special string handling bug in __bitmap_parselist

    If string end with '-', for exapmle, bitmap_parselist("1,0-",&mask,
    nmaskbits), It is not in a valid pattern, so add a check after loop.
    Return -EINVAL on such condition.

    Signed-off-by: Pan Xinhui <xinhuix.pan@intel.com>
    Cc: Yury Norov <yury.norov@gmail.com>
    Cc: Chris Metcalf <cmetcalf@ezchip.com>
    Cc: Rasmus Villemoes <linux@rasmusvillemoes.dk>
    Cc: Sudeep Holla <sudeep.holla@arm.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

**Comment by yangx-jy** [comment]
@richiejp 

Thanks for your reply.

'0-' seems undocumented and entering 0- doesn't cause any bug currently.
But I will send a patch to keep it because I am not sure if entering 0- may cause a bug in future.

Of course, I will remove it directly if maintainers(e.g. Cyril. Petr, Jan) are against keeping it.
