### ISSUE TITLE
Implement kconfig check for shell API (tst_kconfig_check, NEEDS_KCONFIGS, TWARN_IF_NO_CONFIG)

### ISSUE THREAD

**Issue by pevik** [linux-test-project/ltp#700]
C API has gained support for parsing kernel config some time ago
https://github.com/linux-test-project/ltp/wiki/Test-Writing-Guidelines#2228-parsing-kernel-config

It'd be good to enable it in shell API as well: add `tst_check_kconfig()` function and `NEEDS_KCONFIGS` variable.

Both C and shell API should also have variable to disable TCONF when kconfig is not missing (for some embedded). Alexey suggested `TCONF_IF_KCONFIG` but as the feature should be default off, it should have different name (`TWARN_IF_NO_CONFIG`).

Based on this discussion:
https://patchwork.ozlabs.org/project/ltp/patch/20200617154926.32588-1-alexey.kodanev@oracle.com/

**Comment by metan-ucw** [comment]
Btw, the kconfig API has to be redesigned so that it can implement more complex queries, so we may as well wait for that.

See:
http://patchwork.ozlabs.org/project/ltp/patch/20191220092529.3239-4-pengfei.xu@intel.com/

**Comment by pevik** [comment]
Thanks, I was going to post it as well :)

**Comment by pevik** [comment]
FYI shell tests which require this functionality (incomplete list):
[testcases/commands/sysctl/sysctl02.sh](https://github.com/linux-test-project/ltp/blob/master/testcases/commands/sysctl/sysctl02.sh)
[testcases/kernel/security/integrity/ima/tests/ima_tpm.sh](https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/security/integrity/ima/tests/ima_tpm.sh)

**Comment by pevik** [comment]
Continue in https://github.com/linux-test-project/ltp/issues/891
