### ISSUE TITLE
failed umount on acquired device makes all subsequent tests fail

### ISSUE THREAD

**Issue by jstancek** [linux-test-project/ltp#703]
runltp currently creates loop device if one is not provided via env. variable. And this loop device is used for all tests. Problem is that when one of the tests gets stuck or fails for any reason to umount loop device, then all subsequent tests that need a device will also fail. For example when trying to create a filesystem:
```
/dev/loop0 is mounted; will not make a filesystem here!
```
Ideally, LTP library should try to acquire new device, so subseuqent tests can continue.

**Comment by metan-ucw** [comment]
Well, we can easily fix that just by removing the code that creates the device from runltp and let the tests managed that themselves.

**Comment by jstancek** [comment]
Agreed. It would perhaps be better if we first included Martin's patch that allocates backing file with fallocate ([PATCH] Use fallocate() to create loop device backing file).

And then drop creation of loop device from runltp:
```
diff --git a/runltp b/runltp
index ec0811834862..94e290d6dbb9 100755
--- a/runltp
+++ b/runltp
@@ -963,17 +963,7 @@ create_block()

 set_block_device()
 {
-    if [ -z "$DEVICE" ]; then
-        create_block
-        if [ $? -ne 0 ]; then
-            echo "no block device was specified on commandline."
-            echo "Block device could not be created using loopback device"
-            echo "Tests which require block device are disabled."
-            echo "You can specify it with option -b"
-       else
-            export LTP_DEV=$DEVICE
-        fi
-    else
+    if [ -n "$DEVICE" ]; then
         export LTP_DEV=$DEVICE
     fi
 }
```

**Comment by metan-ucw** [comment]
Sound good.
