### ISSUE TITLE
thp04 case affects cgroup_fj_stress_memory cases on old kernel

### ISSUE THREAD

**Issue by xuyang0410** [linux-test-project/ltp#705]
On old kernel (like 3.10.0-1136.el7.x86_64 )without this kernel fix[mm, thp: Do not make page table dirty unconditionally in touch_p[mu]d()](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a8f97366452e), even thp04 triggers the default timeout(5 minutes), we can't kill thp04 process because its process state is in "D".  And this will slow or hang cgroup_fj_stress_memory case.   I want to move mm after controllers in scenario_groups/default, so it will don't block my test. Does anyone have other idea?

**Comment by metan-ucw** [comment]
If tests ends up stuck in a D state you have a bug in kernel, there is no way around it. So you either disable the test completely in your local environment and accept that there is a kernel bug, or get the kernel fixed.
