### ISSUE TITLE
Write basic test for watch queue

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#709]
New generalized event notification mechanism was added to 5.8 see:

https://www.kernel.org/doc/html/latest/watch_queue.html
https://lwn.net/Articles/760714/

**Comment by acerv** [comment]
I'm taking responsibility for this task. In progress

**Comment by metan-ucw** [comment]
The watchqueue tests were added in a patchset starting with 1035f06d1308c4c5c4309207d222a3b6a5893dad
