### ISSUE TITLE
Write test for close_range() sycall

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#710]
See: https://lwn.net/Articles/789023/

**Comment by PhysixProject** [comment]
This looks like fun! I am looking into this.

**Comment by treedavies** [comment]
Support for this is in kernel, but not yet in current version glibc (version 2.32).

**Comment by metan-ucw** [comment]
This has been implemented in f87846b9b1f94b4f83b6ea5a439cbef9080178b9 and 4f709350cb1d52d648cdbfbf21a447fd8699fcc3
