### ISSUE TITLE
clock_settime03

### ISSUE THREAD

**Issue by rasibley** [linux-test-project/ltp#712]
While we updated to a  recent commit for CKI, newly onboarded clock_settime03 test is failing with  BROK: timer_create() failed: EOPNOTSUPP (95) error for all non x86_64 arches, see below:

```
>>> 80:clock_settime03 BROK <<<
###############################################################################
# Test Num    : 80                                                            #
# Test Case   : clock_settime03                                               #
# Test Result : BROK                                                          #
###############################################################################

     1	<<<test_start>>>
     2	tag=clock_settime03 stime=1596809785
     3	cmdline="clock_settime03"
     4	contacts=""
     5	analysis=exit
     6	<<<test_output>>>
     7	tst_test.c:1245: INFO: Timeout per run is 0h 05m 00s
     8	clock_settime03.c:41: INFO: Testing variant: syscall with old kernel spec
     9	clock_settime03.c:70: BROK: timer_create() failed: EOPNOTSUPP (95)
    10	
    11	Summary:
    12	passed   0
    13	failed   0
    14	skipped  0
    15	warnings 0
    16	<<<execution_status>>>
    17	initiation_status="ok"
    18	duration=0 termination_type=exited termination_id=2 corefile=no
    19	cutime=0 cstime=0
    20	<<<test_end>>>
```

**Comment by metan-ucw** [comment]
That is a bit strange, the syscall that fails is timer_create() with CLOCK_REALTIME_ALARM. I guess that there may be missing support for RTC wakeup either in kernel or hardware.

Does the test work if you change the CLOCK_REALTIME_ALARM into just CLOCK_REALTIME?

**Comment by jstancek** [comment]
http://lists.linux.it/pipermail/ltp/2020-August/018560.html

**Comment by jstancek** [comment]
From what I recall, the report was from ppc kvm guest.

**Comment by metan-ucw** [comment]
Well yes, but I do not see anything that would actually require the _ALARM clock, we do not suspend the OS in the middle, so it may be better to just change to plain CLOCK_REALTIME.

**Comment by Cypresslin** [comment]
For the record, we're seeing this failures on the following kernels as well (not fully tested on various releases yet):
Ubuntu Bionic 4.15 KVM kernel on KVM nodes (4.15.0-1072.73)
Ubuntu Xenial 4.4 kernel on P8 / s390x (4.4.0-189.219)

**Comment by wangli5665** [comment]
this has been solved in https://github.com/linux-test-project/ltp/commit/21721a3172333a15aefce4e5ba16281d3fcdb484
