### ISSUE TITLE
trunc_mean is not a mean, rather it's a summation - tst_timer_test.c

### ISSUE THREAD

**Issue by Vishwajith-K** [linux-test-project/ltp#715]
https://github.com/linux-test-project/ltp/blob/221688d25485436b5dcec67efe77b67f8cf0f2dd/lib/tst_timer_test.c#L313
***
trunc_mean is sigma of samples collected. See 
https://github.com/linux-test-project/ltp/blob/221688d25485436b5dcec67efe77b67f8cf0f2dd/lib/tst_timer_test.c#L302-L303
***
Mean is sum/samples, in this case it might actually be: (trunc_mean / keep_samples)
https://github.com/linux-test-project/ltp/blob/221688d25485436b5dcec67efe77b67f8cf0f2dd/lib/tst_timer_test.c#L305-L308
***
Doesn't it cause a failure display? (It failed for me at clock_nanosleep02 command, tcases[5])

**Comment by metan-ucw** [comment]
This is all done in integer arithmetic so we do compare the truncated sum (trunc_mean) against expected value (usec) multiplied by a number of samples (nsamples - discard) in order to avoid rounding errors. I guess that the variable names are slightly confusing here but the code is correct.
