### ISSUE TITLE
stdout typo'd as stderr in tst_test.c

### ISSUE THREAD

**Issue by Vishwajith-K** [linux-test-project/ltp#716]
https://github.com/linux-test-project/ltp/blob/660cdae362591b92420c355e10fe449a144ff09c/lib/tst_test.c#L1377-L1383
Please compare message and fflush arguments. It can be a typo ⚠️ 
L1381 is: `rval = fflush(stderr);`
and may be it was supposed to be: `rval = fflush(stdout);`

OR message displayed must be on stderr 🤔

**Comment by metan-ucw** [comment]
Looks like a typo, looks like we wanted to flush both stderr and stdout there, so the second one should be fflush(stdout).

Can send a patch?

**Comment by Vishwajith-K** [comment]
Please take a look at pull request: #717

**Comment by xuyang0410** [comment]
@wangli5665   This is a typo, we can directly merge it.

**Comment by wangli5665** [comment]
Patch merged, thanks
