### ISSUE TITLE
Tests to run under qemu/kvm (question of maybe feature request)

### ISSUE THREAD

**Issue by vt-alt** [linux-test-project/ltp#719]
Hello,

1. Would be interesting to know what tests people select to run in what environments. (Maybe this question is for mailing list?)

2. Main question is: I want to integrate some `LTP` tests into kernel building process (into rpm spec `%check` section) for ALT Linux (it would run qemu-kvm similar to how [virtme](https://github.com/amluto/virtme) works, using 9P to access build env files).

What tests would you recommend for that use case?

Basically, they (probable) should 
* run not too long (10-15 minutes max) and not be quiet for a long periods (minutes).
* should not have (high probability) failures or otherwise fragile tests (for example build env could be highly loaded so there could be time jitter or delays that could break some time sensitive tests).
* not need to run stress tests (like burning all cpus or eating all memory)
* Just basic kernel sanity tests.

It would be good to have test profiles like quick, long, or extended, to run in different environments.

Thanks,

**Comment by vt-alt** [comment]
It seems that `quickhit` is a good list to start with. Except, for these tests that take too long:
~~~
kill02         0  10.47  4%
kill09         0  5.44   7%
select01       0  17.15  2%
select04       0  25.50  1%
time01         0  4.45   9%
wait02         0  9.79   4%
~~~
(columns are: exit code, run time in seconds, on cpu %).

**Comment by metan-ucw** [comment]
Forget about quickhit, that one is not maintained and is going to get removed soon enough. For a start I would go for syscalls run.

Also we are working on runltp replacement that can spawn virtual machine, run the tests, and even recover from a kernel crash, see https://github.com/metan-ucw/runltp-ng. We are also working on support for parallel testruns at the moment, hopefully that would speed up things soon enough as well.

As for long running tests, we are trying to speed these up as much as we can.

As for the tests you have reported:

* kill02 -- old and messy test, needs to be rewritten
* kill09 -- that one is supposed to be fast
* select01 -- here as well this one is fast
* select04 -- this one asserts timer precision and runs for longer time, nothing can be done here, but this test should be skipped on VMs
* time01 -- this is fast one as well
* wait01 -- and this is fast as well

Generally it looks like the measurements are flawed somehow? Maybe the bare metal host that runs the VMs is overbooked?

**Comment by vt-alt** [comment]
@metan-ucw Thanks for the answer! Bare metal test server was idle, but, I was running the tests via `runltp -q -Q -s $testname` (time/cpu measurement is using `time`). Now, I re-executed all tests directly which made the tests you said fast really fast. Now outliers (with run-time `>=` 1 sec) are:
~~~
fsync01        0   1.09   28%
kill02         0   10.03  0%
select04       0   25.06  0%
wait02         0   1.00   0%
~~~

**Comment by vt-alt** [comment]
Direct run time/cpu measurements for `syscalls` list (outliers with run-time `>=` 10 sec):
~~~
fcntl15                   0   10.00   0%
fcntl15_64                0   10.00   0%
fork13                    0   90.12   96%
gettimeofday02            0   10.00   99%
inotify09                 0   150.50  99%
kill02                    0   10.03   0%
mkdir09                   0   10.00   98%
move_pages12              1   12.99   99%
msgstress03               0   154.87  99%
msgstress04               0   544.25  98%
preadv203                 0   100.22  97%
preadv203_64              0   127.04  97%
ptrace07                  0   15.64   99%
select04                  0   25.10   0%
sendmsg02                 0   15.43   95%
shmctl05                  0   10.50   99%
perf_event_open02         0   10.56   99%
~~~
Probably, for the final list I should just remove these tests from the list. I tried, in that case overall `runtest -s syscalls-filtered` run is 274.97 seconds.

**Comment by metan-ucw** [comment]
There are about two or three testcases in that list that will get cleaned up and are slow for no good reason but majority in that list is testing timers or trying to trigger a race conditions that requires many loop so they are not going to get any faster.

**Comment by vt-alt** [comment]
IC. Well, race conditions tests seems not suitable for quick qemu-kvm testing anyway, timer tests probably too (due to possible other load on the test host). If you improve `quickhit` or create slow test blacklist for `syscalls` list that would be excellent.

**Comment by metan-ucw** [comment]
Well the best we can do for now is to maintain an official list of long running testcases so that you can pass them as a SKIPFILE to the runltp script.

When we switch to runltp-ng we will be able to propagate test metadata and handle this case more cleanly.

**Comment by vt-alt** [comment]
@metan-ucw Great. Thanks!

**Comment by metan-ucw** [comment]
Also FYI there are still some in-flight patches to convert test to the max_runtime such as http://patchwork.ozlabs.org/project/ltp/list/?series=305129

Feel free to open issues if you find any long running tests that are not max_runtime aware yet.

**Comment by vt-alt** [comment]
IC (for `20220527`) only 46 tests are tagged with `max_runtime` and thus are _long running_. What are run time expectations of non-_long running_ tests? Thanks,

**Comment by vt-alt** [comment]
Ah, `any test that runs for more than a second or two` `max_runtime has to be defined`. Perhaps this.

**Comment by metan-ucw** [comment]
Indeed that's the definition, it's not precisely defined yet, but anything that runs for multiple seconds on a modest hardware should ideally get the proper runtime tag and treatment.
