### ISSUE TITLE
mtest06_3 do not using custom tmp ltp folder

### ISSUE THREAD

**Issue by olerem** [linux-test-project/ltp#72]
mtest06_3 failed with this log:

2016-06-23T10:51:53 Test: mtest06_3 Testparm: mmap3 -x 0.002 -p
mkfile(): mkstemp(): Read-only file system
main(): mkfile(): Failed to create temp file.
mkfile(): mkstemp(): Read-only file system

I run tests on readonly remote machine, for more info see:
https://github.com/linux-test-project/ltp/issues/57

looks like mmap3 is ignoring LTPTMP env variable.

**Comment by metan-ucw** [comment]
It looks like the test wasn't really ported to LTP, it does not use any of the LTP API at all.

It should be fixed to at least use the LTP temp directory and ideally it should use LTP result reporting as well. I will look into this.

**Comment by olerem** [comment]
Thank you :)
