### ISSUE TITLE
`rm -rf ${TMP}` of the user's TMP dir on `runltp -h` (breaking system)

### ISSUE THREAD

**Issue by vt-alt** [linux-test-project/ltp#722]
ALT Linux tries to be secure and sets `TMP` and `TMPDIR` env like this:
~~~
TMP=/tmp/.private/root
TMPDIR=/tmp/.private/root
~~~
After `runltp -h` is run once, on the second run it produces an error:
~~~
/usr/lib/ltp/runltp: line 108: cannot create temp file for here-document: No such file or directory
~~~
This is because users (root's) tmp dir is wholly deleted (which is also bad for user and system in general). This, in turn, is because `cleanup` is doing `rm -rf ${TMP}` *before* `TMP` is set to `mktemp -d` value due to `exit` in `usage` call on `runltp -h`.
~~~
cleanup()
{
    [ "$LOOP_DEV" ] && losetup -d $LOOP_DEV
    rm -rf ${TMP}
}
~~~

Would be nice if you fix this!

**Comment by vt-alt** [comment]
And, to add, `cleanup` is called via `    trap "cleanup" 0`.

**Comment by metan-ucw** [comment]
Looking at the script obvious fix would be setting the trap in the main function after we do the mkdtemp and set the TMP and TMPDIR variables. Can you send a patch to the mailing list or should I do so?

**Comment by vt-alt** [comment]
Thanks. OK I may send just for the fun of it.
