### ISSUE TITLE
Is realtime testsuite workable? (prio_wake, matrix_mult FAIL on -rt kernel)

### ISSUE THREAD

**Issue by vt-alt** [linux-test-project/ltp#723]
(I am just started to use LTP, so maybe I'm doing something wrong. But,) is Realtime Testsuite working good? For example, in PREEMPT_RT_FULL kernel (4.19.142.rt63, latest for 4.19 on not loaded bare metal box) I get such result of prio wake test:
~~~
-----------------------
Priority Ordered Wakeup
-----------------------
Worker Threads: 32
Calling pthread_cond_broadcast() with mutex: LOCKED

00001714 us: Master thread about to wake the workers

Criteria: Threads should be woken up in priority order
FAIL: Thread 1 woken before 32
FAIL: Thread 23 woken before 27
FAIL: Thread 13 woken before 14
Result: FAIL
~~~
And matrix_mult:
~~~
---------------------------------------
Matrix Multiplication (SMP Performance)
---------------------------------------

Running 128 iterations
Matrix Dimensions: 100x100
Calculations per iteration: 8
Number of CPUs: 32

Running sequential operations
Min: 0 us
Max: 0 us
Avg: 0.0000 us
StdDev: 0.0000 us

Running concurrent operations
Min: 0 us
Max: 1 us
Avg: 11.0000 us
StdDev: 0.2114 us

Concurrent Multipliers:
Min: -nan
Max: 0.0000
Avg: 0.0000

Criteria: 24.00 * average concurrent time < average sequential time
Result: FAIL
~~~

**Comment by metan-ucw** [comment]
The code has been mostly unmaintained for last couple of years, some people send patches though, so it's quite likely that at least subset of the testcases are/were useful.

I guess that the prio_wake failures could be explained by https://bugzilla.redhat.com/show_bug.cgi?id=447871

My guess for the matrix_multi would be that modern hardware is too fast and it's not doing enough iterations to measure anything meaningful.

**Comment by vt-alt** [comment]
Thanks for the explanation!

**Comment by pevik** [comment]
It'd be great if realtime developers would have look into the code.
