### ISSUE TITLE
Failed to build recvmmsg01.c

### ISSUE THREAD

**Issue by Cypresslin** [linux-test-project/ltp#727]
Build failed for recvmmsg01.c on Ubuntu Bionic 5.4.0-49.53~18.04.1:

        recvmmsg01.c: In function ‘do_test’:
        recvmmsg01.c:86:9: error: request for member ‘type’ in something not a structure or union
        timeout.type = tv->ts_type;
        ^
        recvmmsg01.c: At top level:
        recvmmsg01.c:127:1: warning: missing initializer for field ‘caps’ of ‘struct tst_test’ [-Wmissing-field-initializers]
        };
        ^
        In file included from ../../../../include/tst_timer.h:19:0,
        from ../../../../include/time64_variants.h:20,
        from ../sendmmsg/sendmmsg.h:9,
        from recvmmsg01.c:13:
        ../../../../include/tst_test.h:248:18: note: ‘caps’ declared here
        struct tst_cap *caps;
        ^~~~
        make[4]: *** [recvmmsg01] Error 1
        make[3]: *** [all] Error 2
        make[2]: *** [all] Error 2
        make[1]: *** [all] Error 2
        make: *** [testcases-all] Error 

Introduced in: 135af8ededd4 ("syscalls/{send|recv}mmsg: add a test case for timeout and errno test")

**Comment by pevik** [comment]
Already sent fix https://patchwork.ozlabs.org/project/ltp/patch/20200923084422.13101-1-yangx.jy@cn.fujitsu.com/

**Comment by pevik** [comment]
You can add your `Reported-by` or `Review-by` tag on the patch on mailing list.
