### ISSUE TITLE
syscalls/memcpy: expects specific behavior despite it's undefined one.

### ISSUE THREAD

**Issue by kamiccolo** [linux-test-project/ltp#73]
Last two [testcases](https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/memcpy/memcpy01.c#L141-193) of memcpy expects copying of overlapping memory regions to succeed, despite the C standard clearly states following:

> 7.24.2.1 The memcpy function
> ...
> If copying takes place between objects that overlap, the behavior is undefined.

Another thing, does it make sense having `C library` tests in the `syscalls` subfolder?
For example [memcmp](https://github.com/linux-test-project/ltp/tree/master/testcases/kernel/syscalls/memcmp), [memcpy](https://github.com/linux-test-project/ltp/tree/master/testcases/kernel/syscalls/memcpy), [memset](https://github.com/linux-test-project/ltp/tree/master/testcases/kernel/syscalls/memset), etc.

As far as I understand, those are not syscalls. Am I just missing some motivation behind this?

**Comment by metan-ucw** [comment]
There is continuous transition between Linux low level calls that are only thin wrappers that just pack arguments and switch to kernel context to calls implemented purely in userspace, but you cannot really divide them into just two classes. For instance ```abort()``` is implemented using signal manipulating syscalls in glibc. The ```profil()``` is implemented in glibc using ITIMER_PROF, etc.

The syscalls directory is named as such for purely historical reasons, I guess that it could be renamed to something more descriptive, if you can find fitting name...

Anyway, the memcpy tests should be fixed.

**Comment by kamiccolo** [comment]
Opened a pull-request #76

Just removing those two tests.

I'd like to refactor these later. Also a few other bloated ones.
