### ISSUE TITLE
Add tests for seccomp() syscall

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#730]
We do have some of the seccomp() functionality covered in prctl() tests, but we have no test that would test the seccomp() syscall itself and there is no coverage for the user space notification.

There is a nice example to be added to manual pages here:

https://lwn.net/Articles/833128/

**Comment by treedavies** [comment]
I'm taking on this task.

**Comment by pevik** [comment]
Note from #290: The seccomp call gained support for userspace notifications see: https://lwn.net/Articles/776035/#userspace

**Comment by coolgw** [comment]
checking.

**Comment by coolgw** [comment]
https://patchwork.ozlabs.org/project/ltp/patch/20230921021445.2075-1-wegao@suse.com/

**Comment by coolgw** [comment]
This need v2 version, i will continue work on this.

**Comment by coolgw** [comment]
So i hold my action.
