### ISSUE TITLE
syscalls/timer_settime/timer_settime01 is fragile on s390x arch

### ISSUE THREAD

**Issue by eaibmz** [linux-test-project/ltp#733]
Hi,

the test syscalls/timer_settime/timer_settime01.c sometimes fails with:

```
timer_settime01.c:96: TINFO: Testing for using absolute time:
timer_settime01.c:169: TPASS: timer_settime(CLOCK_REALTIME) passed
timer_settime01.c:169: TPASS: timer_settime(CLOCK_MONOTONIC) passed
timer_settime01.c:169: TPASS: timer_settime(CLOCK_PROCESS_CPUTIME_ID) passed
timer_settime01.c:169: TPASS: timer_settime(CLOCK_THREAD_CPUTIME_ID) passed
timer_settime01.c:169: TPASS: timer_settime(CLOCK_BOOTTIME) passed
timer_settime01.c:111: TCONF: CLOCK_BOOTTIME_ALARM unsupported: EOPNOTSUPP (95)
timer_settime01.c:111: TCONF: CLOCK_REALTIME_ALARM unsupported: EOPNOTSUPP (95)
timer_settime01.c:156: TFAIL: timer_gettime(CLOCK_TAI) reported bad values (0: 50000019): SUCCESS (0)
timer_settime01.c:169: TPASS: timer_settime(CLOCK_TAI) passed
```

and

```
timer_settime01.c:96: TINFO: Testing for using absolute time:
timer_settime01.c:169: TPASS: timer_settime(CLOCK_REALTIME) passed
timer_settime01.c:169: TPASS: timer_settime(CLOCK_MONOTONIC) passed
timer_settime01.c:169: TPASS: timer_settime(CLOCK_PROCESS_CPUTIME_ID) passed
timer_settime01.c:169: TPASS: timer_settime(CLOCK_THREAD_CPUTIME_ID) passed
timer_settime01.c:156: TFAIL: timer_gettime(CLOCK_BOOTTIME) reported bad values (0: 50000097): SUCCESS (0)
timer_settime01.c:169: TPASS: timer_settime(CLOCK_BOOTTIME) passed
timer_settime01.c:111: TCONF: CLOCK_BOOTTIME_ALARM unsupported: EOPNOTSUPP (95)
timer_settime01.c:111: TCONF: CLOCK_REALTIME_ALARM unsupported: EOPNOTSUPP (95)
timer_settime01.c:169: TPASS: timer_settime(CLOCK_TAI) passed
```

I think the check on line 154 is too strict.

Regards
Alex

**Comment by metan-ucw** [comment]
This is probably the same issue as with:

http://patchwork.ozlabs.org/project/ltp/patch/20201006085309.32227-1-cascardo@canonical.com/

Can you please check that the changes I've proposed in the reply fix the problem for you?

**Comment by eaibmz** [comment]
Yes, it *seems* to fix the problem i'm facing.
In general, we have many tests which fail due to timeout/timer values being exceeded because we run our
tests inside a virtualized environment like LPARs and zVMs where scheduling of events might be subject to steal time.

Regards
Alex

**Comment by metan-ucw** [comment]
This time it was a rounding problem, could please ack the patch on LTP ML so that I can commit it?

Also we do have a virtual environment detection in place which is then used to lower expectation for a few timer tests. So first of all have a look at lib/tst_virt.c and check that tst_is_virt() detects LPARs and zVMs.

**Comment by eaibmz** [comment]
> This time it was a rounding problem, could please ack the patch on LTP ML so that I can commit it?
Done.

> 
> Also we do have a virtual environment detection in place which is then used to lower expectation for a few timer tests. So first of all have a look at lib/tst_virt.c and check that tst_is_virt() detects LPARs and zVMs.

Thanks for the pointer. It is not able to detect our VMs yet :( To fix it i need to extend `tst_is_virt` and then use it in all tests which might fail due to steal time, right ?

Regards
Alex

**Comment by metan-ucw** [comment]
Yes that would be best way forward I believe.

**Comment by metan-ucw** [comment]
The patch fixing the original issue has been applied.
