### ISSUE TITLE
Add a test for MSG_STAT_ANY and SEM_STAT_ANY

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#738]
The SHM_STAT_ANY is at least partially covered in shmct04.c.

**Comment by xuyang0410** [comment]
The MSG_STAT_ANY has been covered in msgctl06.c.

**Comment by xuyang0410** [comment]
The SEM_STAT_ANY has been covered in semctl09.c  since commit [2a3e43abe](https://github.com/linux-test-project/ltp/commit/2a3e43abeef8b6c5507663724bcf7d00e871172e).  Now, SHM_STAT_ANT/MSG_STAT_ANY/SEM_STAT_ANY also use nobody user to test  whther skip perm check
