### ISSUE TITLE
How to run LTP for many different linux kernels on local PC?

### ISSUE THREAD

**Issue by xiaokc** [linux-test-project/ltp#74]
Hi, I only want to test kernel which base on linux kernel, such as android kernel, not all linux features.  Can I use this LTP frawork to test android kernel on my PC? Here, I have built android OS image, and I don't want to flash this image to any device. Is it possiable? Can any one help me? Thanks so much~

**Comment by metan-ucw** [comment]
Sorry we have no idea how tu run LTP on android.
