### ISSUE TITLE
./Configure error

### ISSUE THREAD

**Issue by Nanjayan** [linux-test-project/ltp#741]
I tried to configure cross compiling for ARM architecture using the command:
./configure CC=arm-linux-gnueabi-gcc --prefix=/opt/ltp_arm32 --host=armv7

I got this error 
./configure: line 6386: syntax error near unexpected token `LIBMNL,'
./configure: line 6386: `    PKG_CHECK_MODULES(LIBMNL, libmnl,'

I tried installing LIBMNL individually but still getting this error

**Comment by vapier** [comment]
your system is missing pkg-config development files.  please see INSTALL for more info.
