### ISSUE TITLE
pthread_cond_destroy_2-1 failed with glibc-2.32

### ISSUE THREAD

**Issue by YanfeiXu** [linux-test-project/ltp#746]
Hi experts,

After I upgrate my glibc from v2.31 to v2.32, the pthread_cond_destroy_2-1 always returns failure. Look into the codes, the pthread_cond_destroy()  hangs and then timeout. However when I debug it with gdb and run testcase  step by step, it runs sucessfully.

The specific scenarii of  pthread_cond_destroy_2-1 is scenarii[4], which is test the pthread_cond_destroy() function with process-shared mutex and cond.

Have you ever met this issue? Any comments will appreciate! 

Kernel version: 5.4
Mechine: x86-64 and qemux86 
Glibc: 2.32

//Yanfei

**Comment by metan-ucw** [comment]
I had a quick look at the test and the locking there looks strange I would have to have a closer look to say anything more than that though.

**Comment by YanfeiXu** [comment]
> I had a quick look at the test and the locking there looks strange I would have to have a closer look to say anything more than that though.

Any progress? :)

**Comment by kamiccolo** [comment]
@YanfeiXu could You please also specify GCC version?

**Comment by YanfeiXu** [comment]
> @YanfeiXu could You please also specify GCC version?

Sorry for the late reply.
Yes, after I specify the GCC version, it works.

**Comment by pevik** [comment]
> Yes, after I specify the GCC version, it works.

@YanfeiXu Not sure, if I understand you. We wanted to know which gcc (or clang) version are you using. But from your comment it looks like compilation is working.
BTW while we don't test gentoo in Travis CI (although you're welcome to submit a patch for testing it), we cover in our testing other distros which use gcc 2.32 (e.g. Tumbleweed).

**Comment by River9527** [comment]
@YanfeiXu  Hi, I meet the same issue, could you please tell me how to specify gcc when testing? I am new to ltp, thank you very much!

**Comment by YanfeiXu** [comment]
@pevik  @River9527  I use yocto to build my linux. Currently yocto use V2.33 gcc, and this ltp case will run failed with it.( It fails either with V2.32).  After I specify the gcc version to V2.31 in yocto gcc layer, and the case will run successfully.    
Hope I have made myself clear.

**Comment by pevik** [comment]
I'm sorry, no more update. I can just confirm, that it hangs with glibc 2.33 (confirmed locally and with openSUSE kernel CI: https://openqa.opensuse.org/tests/1650458#step/pthread_cond_destroy_2-1/5). We need to have a closer look into the issue.

**Comment by YanfeiXu** [comment]
I have confirmed that it is a glibc bug and has been fixed in glibc-2.34. The commit c4ad832276(nptl: Remove private futex optimization [BZ #27304]) works.
https://sourceware.org/bugzilla/show_bug.cgi?id=27304

**Comment by fweimer-rh** [comment]
I didn't realize that this bug was visible anywhere. I'm going to backport the fix into the 2.32 and 2.33 upstream branches. Sorry for the inconvenience.

**Comment by pevik** [comment]
For a record @fweimer-rh backported fix [c4ad832276](https://sourceware.org/git/?p=glibc.git;a=commit;h=c4ad832276f4dadfa40904109b26a521468f66bc) into 2.33 upstream branch as [79c6be6a0a](https://sourceware.org/git/?p=glibc.git;a=commit;h=79c6be6a0ad59e28cfb73ad6cae6b073e22836e3).
