### ISSUE TITLE
atomic_add: function not implemented

### ISSUE THREAD

**Issue by NicolaGiardino** [linux-test-project/ltp#747]
I'm trying to use the realtime testcases, when running them i always get this message:
`atomic_add: Function not implemented`

Ex.:
```
--- Running testcase async_handler_jk -c 100  ---
mar  1 dic 2020, 18.53.55, CET
Logging to /home/pi/ltp/testcases/realtime/logs/raspberrypi-armv7l-4.19.71-rt24-v7l+-2020-12-01-async_handler_jk-c100.log
atomic_add: Function not implemented

mar  1 dic 2020, 18.53.55, CET
The async_handler_jk test appears to have completed.
```

I also had to remove the inclusion of a `realtime_config.h` library, which does not exist.

**Comment by NicolaGiardino** [comment]
UPDATE:
Tried also by installing the kernel w/ the preempt_rt patch on my personal pc, under Ubuntu, having the same results

**Comment by pevik** [comment]
Is it this error?

https://github.com/linux-test-project/ltp/blob/b09fe070947c374cd9e6bb3185e4d9f55e816471/include/tst_atomic.h#L299-L303

I assume you have `x86_64`. Any idea how RT toolchain, libc and kernel headers differs from normal kernel? Could you at least wrote package names you use?

**Comment by NicolaGiardino** [comment]
No, that's not the error, in fact my compiler does provide `__sync_add_and_fetch`, as shown while calling the `make autotools` command. My error is just `atomic_add: Function not implemented`
I've tried with all the packages in the realtime subdirectory, the error is always the same. 
I tried both on x86 and x86_64.

**Comment by metan-ucw** [comment]
> I also had to remove the inclusion of a `realtime_config.h` library, which does not exist.

This is the reason your build is broken. You have to run the configure script in the realtime directory as well which creates this file, which then is used to enable the `__sync_add_and_fetch()` in the librrtest.h.
