### ISSUE TITLE
testinfo.pl: Escape strings properly

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#754]
The testinfo.pl produces asciidoc output that is later on processed into html pages, the problem is that we do not escape the strings we get from the metadata.json properly. It could be seen on the umip_basic_test where the logical or `|` between two kernel config options ends up in the middle of table and messes ups the table rows.

**Comment by pevik** [comment]
NOTE: more docparser TODO: https://patchwork.ozlabs.org/project/ltp/patch/20201216143244.8180-1-pvorel@suse.cz/#2601425
