### ISSUE TITLE
how compile just one case?

### ISSUE THREAD

**Issue by gengcixi** [linux-test-project/ltp#758]
Dear LTP: 
Does LTP have a compilation mechanism similar to the kernel module?
I am developing some cases,and only need compile my new case for debug。

**Comment by richiejp** [comment]
For most tests you can call `make` from the test's source directory and it will just build the tests in that directory. Then you can run it from the source directory or copy it to some VM if the C library matches.

FYI https://github.com/linux-test-project/ltp/wiki/C-Test-Case-Tutorial#3-create-the-test-skeleton

**Comment by pevik** [comment]
Also this could help: https://github.com/linux-test-project/ltp/#quick-guide-to-running-the-tests
