### ISSUE TITLE
 memcg_test_3 test failing 

### ISSUE THREAD

**Issue by pankajjoshi347** [linux-test-project/ltp#760]
Hi,
i am running  memcg_test_3 with 5.10.2 with custom kernel but test is getting failed while executing in parent
I am attaching the log file for the  memcg_test_3 please find
[ memcg_test_3.txt](https://github.com/linux-test-project/ltp/files/5774447/memcg_test_3.txt)

Can someone help me to get the issue resolve ??

Thanks

**Comment by pevik** [comment]
`Operation not permitted`: maybe just a permission problem?
