### ISSUE TITLE
timing issue in epoll_pwait01 testcase

### ISSUE THREAD

**Issue by nylon7** [linux-test-project/ltp#765]
Hi,all

When I run LTP's epoll_pwait01 testcase in our environment(Linux-5.4), we will be encountering two kinds of result in epoll_pwait01's case2(NULL sigmask, verify_nonsigmask)

./runltp  -b /dev/mmcblk0p3 -q -s epoll_pwait01

[1] epoll_pwait01    2  TPASS  :  epoll_wait() failed as expected: TEST_ERRNO=EINTR(4): Interrupted system call
[2] epoll_pwait01    3  TBROK  :  safe_macros.c:633: tst_res.c:433: waitpid(14462,0x9d899b5c,0) failed: errno=EINTR(4): Interrupted system call

`static void do_test(sigset_t *sigmask)
{
      ...

        TEST(epoll_pwait(epfd, &epevs, 1, 100, sigmask));
        
        if (sigmask != NULL)
                verify_sigmask();
        else
                verify_nonsigmask();

        ...
}
`

it's random, but I can reproduce the error when I change epoll_pwait()'s timeout argument (default:100->10)

I can just modify timeout agrument (e.g. default:100->200), and the error can be avoided.

so, I just wonder, is this error just a timing issue? or is there something I missed ?

**Comment by metan-ucw** [comment]
Looks like a race in the test.

What the test does is:

- start a child, that waits for the parent to sleep in syscall, then sends a signal
- parent starts epoll_wait() with 100ms timeout

If the epoll_wait() timeouts before the child sends the signal the parent will get it while waiting in the wait() signal instead.

I will have a look at the code and introduce more proper locking.

**Comment by metan-ucw** [comment]
Can you please try this patch and report if it helps?

http://patchwork.ozlabs.org/project/ltp/patch/20210112132911.4031-1-chrubis@suse.cz/

**Comment by nylon7** [comment]
> Can you please try this patch and report if it helps?
> 
> http://patchwork.ozlabs.org/project/ltp/patch/20210112132911.4031-1-chrubis@suse.cz/

Ok, I will try this tomorrow.

**Comment by nylon7** [comment]
> Can you please try this patch and report if it helps?
> 
> http://patchwork.ozlabs.org/project/ltp/patch/20210112132911.4031-1-chrubis@suse.cz/

I try this and it can solve my problem.

Thanks, again.

**Comment by metan-ucw** [comment]
Thanks for the testing!
