### ISSUE TITLE
open_posix_testsuite compliance test

### ISSUE THREAD

**Issue by ouyanghaley** [linux-test-project/ltp#768]
hi，is the open_posix_testsuite represent all posix standard？
if not，can open_posix_testsuite cases represent all posix standard？after so many years，posix standard has many versions，which version does the open_posix_testsuite represent ？

thanks

**Comment by metan-ucw** [comment]
To be honest, no idea about this. Most of the testcases would apply to all POSIX revisions as new revision usually mostly contains fixes and corrections. However it's hard to say if the testsuite is even complete enough to cover the whole specification regardless the version. Remember his is a best effort testsuite written in good faith, but there are no guarantees for completion or correctness.

**Comment by ouyanghaley** [comment]
> To be honest, no idea about this. Most of the testcases would apply to all POSIX revisions as new revision usually mostly contains fixes and corrections. However it's hard to say if the testsuite is even complete enough to cover the whole specification regardless the version. Remember his is a best effort testsuite written in good faith, but there are no guarantees for completion or correctness.

thanks for your reply，do you know any other posix compliance test framework or testsuites？

**Comment by metan-ucw** [comment]
The opengroup maintains certification testsuites, however these are not generally free, see http://www.opengroup.org/testing/testsuites/vsxpcts2003.htm

**Comment by kamiccolo** [comment]
@ouyanghaley I believe, that it's been forked (?) from posixtest [1] years ago. Currently dumping their CVS repository, to be sure. But on the sourceforge [1] page it states that the main target was POSIX 2001. The codebase itself looks... smelly. I wonder, if there would be any interest to clean it up and refactor on top of LTP primitives...

[1] https://sourceforge.net/projects/posixtest/

**Comment by metan-ucw** [comment]
@kamiccolo Indeed this is a continuation of the abandoned posixtest project. As usual patches are welcome. Basing it on the LTP primitives is probably no-go, since LTP is strictly Linux only and the posix testsuite has to run on anything that implements minimal set of POSIX APIs.
