### ISSUE TITLE
Make tst_taint print thuman readable error messages instead of numerical codes

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#776]
The lib/tst_taint.c should print human-readable messages, i.e. instead of "kernel is already tainted: 128" we should get "kernel is already tainted: TAINT_D (OOPS)" or similar.

**Comment by pevik** [comment]
Kushal Chand has started working on it.

More instructions:
https://lore.kernel.org/ltp/YeFoCtIgRTB0mZwl@pevik/T/#me6a1c93bf81cf6ce28b0da41e67d4edacc4034d4

**Comment by pevik** [comment]
Another his attempt: https://lore.kernel.org/ltp/20220114161612.206475-1-kushalkataria5@gmail.com/T/#u
