### ISSUE TITLE
Test mallinfo2()

### ISSUE THREAD

**Issue by pevik** [linux-test-project/ltp#778]
`mallinfo2()` (glibc specific) was added few months ago to glibc by Martin Liska, released in 2.33.

**Comment by coolgw** [comment]
Should this ticket closed since i found testcases/kernel/syscalls/mallinfo2/mallinfo2_01.c ?

**Comment by coolgw** [comment]
Maybe we can close this since i found testcases/kernel/syscalls/mallinfo2 in currently LTP
