### ISSUE TITLE
memcg_stat_test 3 TFAIL: unevictable is 0, 4096 expected

### ISSUE THREAD

**Issue by liyanhou** [linux-test-project/ltp#780]
hi
When I run this case, failed with following error message

<<<test_start>>>
tag=memcg_stat stime=1611740901
cmdline="memcg_stat_test.sh"
contacts=""
analysis=exit
<<<test_output>>>
incrementing stop
memcg_stat_test 1 TINFO: Starting test 1
/lkp/benchmarks/ltp-latest/testcases/bin/memcg_lib.sh: line 522: echo: write error: Device or resource busy
memcg_stat_test 1 TINFO: set /dev/memcg/memory.use_hierarchy to 0 failed
memcg_stat_test 1 TINFO: Running memcg_process --shm -k 3 -s 135168
memcg_stat_test 1 TINFO: Warming up pid: 19314
memcg_stat_test 1 TINFO: Process is still here after warm up: 19314
memcg_stat_test 1 TPASS: cache is 135168 as expected
memcg_stat_test 2 TINFO: Starting test 2
/lkp/benchmarks/ltp-latest/testcases/bin/memcg_lib.sh: line 522: echo: write error: Device or resource busy
memcg_stat_test 2 TINFO: set /dev/memcg/memory.use_hierarchy to 0 failed
memcg_stat_test 2 TINFO: Running memcg_process --mmap-file -s 135168
memcg_stat_test 2 TINFO: Warming up pid: 19343
memcg_stat_test 2 TINFO: Process is still here after warm up: 19343
memcg_stat_test 2 TPASS: mapped_file is 135168 as expected
memcg_stat_test 3 TINFO: Starting test 3
/lkp/benchmarks/ltp-latest/testcases/bin/memcg_lib.sh: line 522: echo: write error: Device or resource busy
memcg_stat_test 3 TINFO: set /dev/memcg/memory.use_hierarchy to 0 failed
memcg_stat_test 3 TINFO: Running memcg_process --mmap-lock1 -s 4096
memcg_stat_test 3 TINFO: Warming up pid: 19372
memcg_stat_test 3 TINFO: Process is still here after warm up: 19372
memcg_stat_test 3 TFAIL: unevictable is 0, 4096 expected
memcg_stat_test 4 TINFO: Starting test 4

In the new kernel code , Because in memcg_stat_show, the output is the vmstat_local information in memcg, and the information is stored in batch on per-cpu.
https://github.com/torvalds/linux/blob/master/mm/memcontrol.c

**Comment by richiejp** [comment]
Thanks. Also `use_hierarchy=0`, has been removed from the kernel.

There appears to be a patch in flight for this test: http://lists.linux.it/pipermail/ltp/2021-January/020761.html, I'm not sure if that would fix this issue or not.

**Comment by MofX** [comment]
The patch I submitted, does not fix this bug. But I have seen this error as well and my next step is analysing and fixing the errors

**Comment by MofX** [comment]
Just FYI:
I traced this failure down to this commit: https://github.com/torvalds/linux/commit/766a4c19d880887c457811b86f1f68525e416965
This makes sense, because that commit changes the local vmstat counters to be update only in batches. This makes these counters significantly inexact (Up to ncpus * MEMCG_CHARGE_BATCH (which is 32) I think this is in pages.)

I experimented with setting the memory allocated in the test to PAGESIZES, that was introduced for other tests here f0b9d187d863fea1a2c92f1378228248f51ed7ab. This fixes the error.

So I guess if the counters are not supposed to be exact anymore, this is what I will submit as a patch later.

@richiejp 
> Also use_hierarchy=0, has been removed from the kernel.
What do you mean with this? I don't see any removal in the kernel code, but in systems using systemd, use_hierarchy will never be 0, because it is hardcoded into systemd, to set it to 1 for the root group and the kernel forces it to 1 for all subgroups.

**Comment by liyanhou** [comment]
> I traced this failure down to this commit: [torvalds/linux@766a4c1](https://github.com/torvalds/linux/commit/766a4c19d880887c457811b86f1f68525e416965)
> This makes sense, because that commit changes the local vmstat counters to be update only in batches. This makes these counters significantly inexact (Up to ncpus * MEMCG_CHARGE_BATCH (which is 32) I think this is in pages.)
> 
> I experimented with setting the memory allocated in the test to PAGESIZES, that was introduced for other tests here [f0b9d18](https://github.com/linux-test-project/ltp/commit/f0b9d187d863fea1a2c92f1378228248f51ed7ab). This fixes the error.
> 
> So I guess if the counters are not supposed to be exact anymore, this is what I will submit as a patch later.
> 
> @richiejp
> 
> > Also use_hierarchy=0, has been removed from the kernel.
> 
> What do you mean with this? I don't see any removal in the kernel code, but in systems using systemd, use_hierarchy will never be 0, because it is hardcoded into systemd, to set it to 1 for the root group and the kernel forces it to 1 for all subgroups.

It work for me.
I have change memcg_stat_test.sh testcase_3 and testcase_4 function
$PAGESIZE to $PAGESIZES
my test works
