### ISSUE TITLE
configure:7350: error: possibly undefined macro: AC_DEFINE

### ISSUE THREAD

**Issue by Dmole** [linux-test-project/ltp#787]
```
#make autotools
sed -n '1{s:LTP-:m4_define([LTP_VERSION],[:;s:$:]):;p;q}' VERSION > m4/ltp-version.m4
aclocal -I m4
autoconf
configure:7350: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
make: *** [/media/btrfs/ltp/include/mk/automake.mk:51: configure] Error 1
```

**Comment by pevik** [comment]
You need to install `pkg-config` or `pkgconfig`. You can have look for dependencies for some major distros in https://github.com/linux-test-project/ltp/tree/master/travis. But I'll have look how to improve this error message to be more obvious.

**Comment by pevik** [comment]
Proposed fix posted to https://patchwork.ozlabs.org/project/ltp/patch/20210215110419.2964-1-pvorel@suse.cz/
Feel free to test it and add your Reviewed-by / Tested-by tag.

**Comment by Dmole** [comment]
Thanks @pevik but something is still not quite working;

```
# make headers_install
# cd ../ltp
# apt-get -qq install gcc git make pkgconf autoconf automake bison flex m4 libc6-dev
# make clean > /dev/null 2>&1
# make autotools
autoconf
configure.ac:33: error: must install pkg-config or pkgconfig and pkg.m4 macro (usual dependency)
configure.ac:33: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
make: *** [/media/btrfs/ltp/include/mk/automake.mk:51: configure] Error 1
```

Maybe it's not finding the headers?

**Comment by Dmole** [comment]
but now

```
# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
...
checking for add_key in -lkeyutils... no
./configure: line 7229: syntax error near unexpected token `LIBMNL,'
./configure: line 7229: `    PKG_CHECK_MODULES(LIBMNL, libmnl,'
```

**Comment by Dmole** [comment]
Building worked.
I made a separate issue #788 for clean.
The patch is now testable and works, though I'd recommend re-wording it to something like

> Missing dependency, please read the ./INSTALL file.

**Comment by pevik** [comment]
Yep, I should mention `INSTALL` file as well. But I'll certainly want to keep in the message what is missing: `pkg-config` and/or `pkg.m4` macro.
