### ISSUE TITLE
make clean

### ISSUE THREAD

**Issue by Dmole** [linux-test-project/ltp#788]
make clean is not performing as expected and is leaving behind the following;

	aclocal.m4
	autom4te.cache/
	compile
	confEDnt6F/
	config.guess
	config.log
	config.status
	config.sub
	configure
	execltp
	include/config.h
	include/config.h.in
	include/mk/config-openposix.mk
	include/mk/config.mk
	include/mk/features.mk
	include/stamp-h1
	install-sh
	lib/ltp.pc
	m4/Makefile
	m4/Makefile.in
	m4/ltp-version.m4
	missing
	testcases/kernel/device-drivers/tbio/tbio_kernel/.ltp_tbio.o.d
	testcases/realtime/autom4te.cache/

**Comment by metan-ucw** [comment]
This is known problem see discussion in #559
