### ISSUE TITLE
Passing ltp-pan -a option from runltp

### ISSUE THREAD

**Issue by becroyd-irdeto** [linux-test-project/ltp#79]
I'm looking to pass -a to ltp-pan from runltp in order to control where the zoofile is created.
Is there a way to do this, or is this a feature that needs to be implemented?

**Comment by metan-ucw** [comment]
It's hardcoded in ```runltp``` to ```$$```. But it's just a shell script, you can easily edit it yourself to workaround this quickly.

**Comment by metan-ucw** [comment]
This has been fixed in c5e8c14a8df94963b2417eaf23f7be5d76483db3.
