### ISSUE TITLE
testcases sched_rr_get_interval01  in misp  loongson fail

### ISSUE THREAD

**Issue by LianJieZhang** [linux-test-project/ltp#793]
```c
	if (proc_flag)
		TST_ASSERT_INT("/proc/sys/kernel/sched_rr_timeslice_ms", tst_ts_to_ms(tp));

When HZ is not 100, the test fails, and this problem exists on all architectures.

**Comment by xuyang0410** [comment]
I remember that here has a regression Does your kernel backport this following patch?
It is also a regression test for kernel
 * commit 975e155ed873 ("sched/rt: Show the 'sched_rr_timeslice' SCHED_RR
 * timeslice tuning knob in milliseconds").

**Comment by xuyang0410** [comment]
Close it.  Feel free to repen if you still have problem when backporting the kernel patch.
