### ISSUE TITLE
what is the reason to execute heartbeat before executing the test

### ISSUE THREAD

**Issue by weidongkl** [linux-test-project/ltp#797]
![image](https://user-images.githubusercontent.com/7512609/109974696-c877d500-7d34-11eb-8a81-a29c47d0c9a3.png)

As shown in the picture, what is the reason to execute heartbeat before executing the test

**Comment by pevik** [comment]
See info at commit which introduced it 1893e017b55906d76a189a31bb6a1ef0e19b3e34.
NOTE: most of the developers work through mailing list (https://github.com/linux-test-project/ltp/wiki#developers-corner)

**Comment by weidongkl** [comment]
> See info at commit which introduced it [1893e01](https://github.com/linux-test-project/ltp/commit/1893e017b55906d76a189a31bb6a1ef0e19b3e34).
> NOTE: most of the developers work through mailing list (https://github.com/linux-test-project/ltp/wiki#developers-corner)

Thank you. I'll subscribe mailinglist

**Comment by metan-ucw** [comment]
Because tst_start_time has to be initialized before we run test setup().
