### ISSUE TITLE
recvmmsg:bad address test will  trigger  segment fault segment fault  in libc on 32bit system.

### ISSUE THREAD

**Issue by BufferMan0823** [linux-test-project/ltp#803]
The recvmmsg bad timeout address will trigger a segment fault when use glibc(valid_timespec64_to_timespec()  ) on 32bit system.

These LTP tests that check for EFAULT on invalid addresses are inherent wrong,
and LTP is fixing them over the releases once libc need to wrap the arguments
to support different things (such as LFS, 64 bit time, etc.).

(If LTP wants to check for EFAULT semantic it should issue the syscall directly
without libc).

**Comment by BufferMan0823** [comment]
test log:
<<<test_output>>>
tst_buffers.c:55: TINFO: Test is using guarded buffers
tst_test.c:1261: TINFO: Timeout per run is 0h 05m 00s
recvmmsg01.c:102: TINFO: Testing variant: vDSO or syscall with libc spec
recvmmsg01.c:92: TPASS: recvmmsg() bad socket file descriptor: EBADF (9)
recvmmsg01.c:92: TPASS: recvmmsg() bad message vector address: EFAULT (14)
recvmmsg01.c:92: TPASS: recvmmsg() negative seconds in timeout: EINVAL (22)
recvmmsg01.c:92: TPASS: recvmmsg() overflow in nanoseconds in timeout: EINVAL (22)
**tst_test.c:1313: TBROK: Test killed by SIGSEGV!**

**Comment by pevik** [comment]
You're right, test is broken. BTW there are more test failures on syscalls running on 32bit system.

**Comment by metan-ucw** [comment]
This is the same as #807 let's track it there.
