### ISSUE TITLE
Some addresses in LTP cases are out of range under lib32 rootfs

### ISSUE THREAD

**Issue by charleshardy** [linux-test-project/ltp#807]
As below, there are some test cases failed because of addresses out of range, which is quite similar to [#193](https://github.com/linux-test-project/ltp/issues/193)

adjtimex02 FAIL 2
getitimer02 FAIL 2
getrusage02 FAIL 2
msgctl04 FAIL 2
msgget02 FAIL 1
msgrcv02 FAIL 2
sched_rr_get_interval03 FAIL 2
semctl03 FAIL 2
setitimer02 FAIL 2
shmctl02 FAIL 2 

For an instance, adjtimex02 failed without handling the singnal of SIGSEGV.

...
<<<test_start>>>
tag=adjtimex02 stime=1597559401
cmdline="adjtimex02"
contacts=""
analysis=exit
<<<test_output>>>
tst_buffers.c:55: INFO: Test is using guarded buffers
tst_test.c:1244: INFO: Timeout per run is 0h 05m 00s
tst_test.c:1291: BROK: Test killed by SIGSEGV!

Summary:
passed 0
failed 0
skipped 0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=2
<<<test_end>>>

...

To simplied the test code in [adjtimex02.c](https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/adjtimex/adjtimex02.c) as the following, "bufp = (struct timex *)-1;" which assigns the "0xffffffff"  (for 32 bit)  address to bufp and adjtimex try to fetch content from bufp ,the target SIGSEGV the access since the address is out of range.

> int main()
> {
>         struct timex *bufp;
>         bufp = (struct timex *)-1;
>        adjtimex(bufp);
>   return 0;
> }
>

**Comment by vinay110974** [comment]
Hi Charles, 

> adjtimex02 FAIL 2

With below changes we can capture SIGSEGV and inform,


		diff --git a/testcases/kernel/syscalls/adjtimex/adjtimex02.c b/testcases/kernel/syscalls/adjtimex/adjtimex02.c
		old mode 100644
		new mode 100755
		index 19ee97158..e20a34fbd
		--- a/testcases/kernel/syscalls/adjtimex/adjtimex02.c
		+++ b/testcases/kernel/syscalls/adjtimex/adjtimex02.c
		@@ -18,12 +18,18 @@ static int hz;			/* HZ from sysconf */
		 
		 static struct timex *tim_save;
		 static struct timex *buf;
		 static struct passwd *ltpuser;
		 
		+static void sighandler(int sig)
		+{
		+	tst_res(TINFO, "received signal: SIGSEGV");
		+	exit (0);
		+}
		+
		 static void verify_adjtimex(unsigned int nr)
		 {
			struct timex *bufp;
		+	struct sigaction sa;
			int expected_errno = 0;
		 
			/*
		@@ -39,6 +45,9 @@ static void verify_adjtimex(unsigned int nr)
				return;
			}
		 
		+	sa.sa_sigaction = &sighandler;
		+	sigaction(SIGSEGV, &sa, NULL);
		+
			*buf = *tim_save;
			buf->modes = SET_MODE;
			bufp = buf;
		@@ -90,6 +99,7 @@ static void verify_adjtimex(unsigned int nr)
		 
		 static void setup(void)
		 {
		+
			tim_save->modes = 0;
		 
			/* set the HZ from sysconf */


Output of adjtimex02 with the above changes is as below, 

	/home/ltp/lib/tst_buffers.c:55: TINFO: Test is using guarded buffers
	/home/ltp/lib/tst_test.c:1289: TINFO: Timeout per run is 0h 05m 00s
	/home/ltp/testcases/kernel/syscalls/adjtimex/adjtimex02.c:25: TINFO: received signal: SIGSEGV

**Comment by metan-ucw** [comment]
@vinay110974 That code is broken, you can't call tst_res() nor exit() from sycall handler.

The best solution here is to call raw syscall() for the EFAULT cases. Also it would make sense to run the test both for the libc call and for the raw syscall and skip the EFAULT for the libc call. We use test variants for example in the clock_nanosleep01.c

**Comment by vinay110974** [comment]
Hi @metan-ucw, 

>> Also it would make sense to run the test both for the libc call and for the raw syscall and skip the EFAULT for the libc call. We use test variants for example in the clock_nanosleep01.c 

Created a pull request for adjtimex02.c at  #818  with changes as per your suggestions. Also, took reference of "clock_adjtime01.c".

Based on the this review, will update above remaining testcases.

**Comment by vinay110974** [comment]
Hi @metan-ucw,

Thanks for the review.

Worked on #818 review comments. Submitted 2 commit with all the corrections suggested.
https://github.com/linux-test-project/ltp/pull/818/commits/3b7abc09eaf0c3a72f12f7015519a07f87b5fcad

**Comment by vinay110974** [comment]
Hi @metan-ucw,

We are seeing some CI errors as below in #818 with code changes https://github.com/linux-test-project/ltp/pull/818/commits/faffcfbce357828e38085136097149c04ba581dd. 
error link : https://travis-ci.org/github/linux-test-project/ltp/jobs/772176720
```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
The command "$CONTAINER build $CONTAINER_ARGS -t ltp ." failed and exited with 1 during .

```
Please let us know is there anything pending from our side.

**Comment by pevik** [comment]
> toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> The command "$CONTAINER build $CONTAINER_ARGS -t ltp ." failed and exited with 1 during .
> ```
> 
> Please let us know is there anything pending from our side.

No problem at your side. Travis is broken, I'm working on https://github.com/linux-test-project/ltp/issues/761 to fix it.

FYI, although we accept github pull requests, we're not big fans of it. We prefer patches sent to our mailing list
https://github.com/linux-test-project/ltp#developers-corner

**Comment by vinay110974** [comment]
Hi @pevik,

> We prefer patches sent to our mailing list

Thanks for confirming. Will send patch to mailing list.

**Comment by vinay110974** [comment]
Hi @pevik,

Posted the patch to ltp mailing list. 
Link: https://lists.linux.it/pipermail/ltp/2021-June/023003.html

Regards,
Vinay

**Comment by vinay110974** [comment]
Hi @metan-ucw,

Edited below tests for sigsegv fix.

> adjtimex02 FAIL 2
> getitimer02 FAIL 2
> getrusage02 FAIL 2
> msgctl04 FAIL 2
> sched_rr_get_interval03 FAIL 2
> semctl03 FAIL 2
> setitimer02 FAIL 2
> shmctl02 FAIL 2

For "msgget02" and "msgrcv02" issue does not exists.

Sent patches to mailing list for each testcases.
https://lists.linux.it/pipermail/ltp/2021-June/023051.html 
https://lists.linux.it/pipermail/ltp/2021-June/023052.html
https://lists.linux.it/pipermail/ltp/2021-June/023053.html
https://lists.linux.it/pipermail/ltp/2021-June/023054.html
https://lists.linux.it/pipermail/ltp/2021-June/023055.html
https://lists.linux.it/pipermail/ltp/2021-June/023056.html
https://lists.linux.it/pipermail/ltp/2021-June/023057.html

**Comment by vinay110974** [comment]
Hi @metan-ucw,

FYI, below tests are pending for review,

semctl03.c
https://lists.linux.it/pipermail/ltp/2021-June/023116.html

shmctl02.c
https://lists.linux.it/pipermail/ltp/2021-June/023118.html
https://lists.linux.it/pipermail/ltp/2021-June/023166.html

**Comment by metan-ucw** [comment]
Yes I know, you are in the queue, please be patient.

**Comment by vinay110974** [comment]
Hi @metan-ucw,

Thanks for review of shmctl02.c and semctl03.c

**Comment by metan-ucw** [comment]
Are there any other tests that has to be fixed or can we close this issue now?

**Comment by vinay110974** [comment]
Hi @metan-ucw,

No other tests are pending. We can close the issue. 
Thanks.
