### ISSUE TITLE
shmctl02.c:99: TBROK: shmget(1627390644, 2048, 600) failed: EEXIST (17)

### ISSUE THREAD

**Issue by vinay110974** [linux-test-project/ltp#810]
With shmctl02 getting below error on multiple instances of execution. 

First instance of execution
root@qemuarm:~# ./shmctl02
/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:76: TPASS: shmctl(1, 2, 0x43b120): EACCES (13)

Second instance of execution and onwards.
root@qemuarm:~# ./shmctl02
/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:99: TBROK: shmget(1627390644, 2048, 600) failed: EEXIST (17)

On further analysis found that the  shmclt02 calls shmget internally. 

        shm_id1 = SAFE_SHMGET(shmkey1, SHM_SIZE, IPC_CREAT | IPC_EXCL);
        shm_id2 = SAFE_SHMGET(shmkey2, SHM_SIZE, IPC_CREAT | IPC_EXCL | SHM_RW);

So the IPC_EXCL used along with IPC_CREATE is causing problem. If we remove IPC_EXCL flag from the shmget the testcases doesn't break.

**Comment by metan-ucw** [comment]
Looking at the code the test attempts to cleanup after itself in:

```
static void cleanup(void)
{
        if (shm_id1 >= 0)
                SAFE_SHMCTL(shm_id1, IPC_RMID, NULL);

        if (shm_id2 >= 0)
                SAFE_SHMCTL(shm_id2, IPC_RMID, NULL);

        if (shm_id3 >= 0) {
                SAFE_SETEUID(0);
                SAFE_SHMCTL(shm_id3, IPC_RMID, NULL);
        }
}
```

And it works just fine for me, when I run the test in a loop. So something else is broken there.

Is the output from `ipcs` different if you run it before and after the test? What about the shmkey1 and shmkey2 are these different when the test fails?

**Comment by vinay110974** [comment]
> Is the output from ipcs different if you run it before and after the test? 

When we boot the image and before executing shmctl02 "ipcs -m" results are empty.
However, "ipcs -m" results are identical in both pass and fail case.
 
	root@qemuarm:~# ipcs -m

	------ Shared Memory Segments --------
	key        shmid      owner      perms      bytes      nattch     status      
	0x00000000 0          root       600        2048       0                       
	0x610002b4 1          nobody     0          2048       0                       
	0x620002b4 2          nobody     600        2048       0 

Also, attached the snaphot for reference.
![ipcs-shmctl02_1](https://user-images.githubusercontent.com/44431084/114814457-dc056980-9dd1-11eb-9f16-2acb99a8e602.jpeg)

> What about the shmkey1 and shmkey2 are these different when the test fails?

When the test passes.
	
	/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:115: TINFO: shmkey1 1627390644
	/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:116: TINFO: shmkey2 1644167860
	/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:91: TPASS: shmctl(1, 2, 0x4cb120): EACCES (13)

When the test fails.
	
	/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:115: TINFO: shmkey1 1627390644
	/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:116: TINFO: shmkey2 1644167860
	/home/ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl02.c:118: TBROK: shmget(1627390644, 2048, 600) failed: EEXIST (17)

**Comment by metan-ucw** [comment]
So clearly the test does not cleanup after itself because it gets SIGVSEGV during the first run.

Also it looks like you have changed the code because the test does not handle SIGSEGV itself.

**Comment by vinay110974** [comment]
Hi @metan-ucw,

This test is part of #807 bug. Working on the same as per your guidelines and update in the same ticket.

**Comment by metan-ucw** [comment]
I guess that we can close this then and follow up in #807.
