### ISSUE TITLE
test_fs_bind.sh returns SUCCESS even after TBROK happend.

### ISSUE THREAD

**Issue by multiple1** [linux-test-project/ltp#813]
Hello!

ARM platform Kernel 5.4.* running ltp 20210121 reports success even if test is broken?
`BindMounts $LTPROOT/testscripts/test_fs_bind.sh`

```
Running tests.......
<<<test_start>>>
tag=BindMounts stime=1582221281
cmdline="$LTPROOT/testscripts/test_fs_bind.sh"
contacts=""
analysis=exit
<<<test_output>>>
incrementing stop
/mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh    0  TINFO  :  /mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh: kernel >= 2.6.15 detected -- continuing
/mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh    1  TPASS  :  /mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh: umounted simplest shared subtree
/mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh    1  TBROK  :  /home/dev_ltp/ltp/ltp-20210121/tools/apicmds/ltpapicmd.c:172: move/test04: stale catalog of "/tmp/ltp_tmp/ltp-XXXX6HzYWg/sandbox"
/mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh    2  TBROK  :  /home/dev_ltp/ltp/ltp-20210121/tools/apicmds/ltpapicmd.c:172: Remaining cases broken
/mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh    1  TBROK  :  /home/dev_ltp/ltp/ltp-20210121/tools/apicmds/ltpapicmd.c:172: move/test04: failed to save pre-test state of "/tmp/ltp_tmp/ltp-XXXX6HzYWg/sandbox"
/mnt/ltp/opt/ltp/testscripts/test_fs_bind.sh    2  TBROK  :  /home/dev_ltp/ltp/ltp-20210121/tools/apicmds/ltpapicmd.c:172: Remaining cases broken
<<<execution_status>>>
initiation_status="ok"
duration=4 termination_type=exited termination_id=0 corefile=no
cutime=30 cstime=135
<<<test_end>>>
INFO: ltp-pan reported all tests PASS
LTP Version: 20210121

       ###############################################################

            Done executing testcases.
            LTP Version:  20210121
       ###############################################################

exit code 0
```

**Comment by metan-ucw** [comment]
The test_fs_bind.sh is messy script that is not well maintained. Unless some finds time to clean it up it would be better to remove it.

**Comment by multiple1** [comment]
Ah ok.
On the embedded device /tmp is a devtmpfs. The test fails early at the begin.
On my desktop debian it also fails with TBROK when the target is a devtmpfs but somewhere in the middle.
Normal ext4 /tmp shows no issue.

`
move/test21    9  TPASS  :  move/test21: PASSED
/opt/ltp/testscripts/test_fs_bind.sh   10  TBROK  :  ltpapicmd.c:172: move/test20: stale catalog of "/ramdisk/ltp_tmp/ltp-JoTcEhysjh/sandbox"
/opt/ltp/testscripts/test_fs_bind.sh   11  TBROK  :  ltpapicmd.c:172: Remaining cases broken
/opt/ltp/testscripts/test_fs_bind.sh   10  TBROK  :  ltpapicmd.c:172: move/test20: failed to save pre-test state of "/ramdisk/ltp_tmp/ltp-JoTcEhysjh/sandbox"
/opt/ltp/testscripts/test_fs_bind.sh   11  TBROK  :  ltpapicmd.c:172: Remaining cases broken
<<<execution_status>>>
initiation_status="ok"
duration=2 termination_type=exited termination_id=0 corefile=no
cutime=59 cstime=14
<<<test_end>>>
INFO: ltp-pan reported all tests PASS
LTP Version: 20210121-295-g52510deb2

       ###############################################################

            Done executing testcases.
            LTP Version:  20210121-295-g52510deb2
       ###############################################################

0
`

**Comment by metan-ucw** [comment]
These tests were rewritten in  e4be4115619d
