### ISSUE TITLE
Who is using LTP and how?

### ISSUE THREAD

**Issue by vt-alt** [linux-test-project/ltp#817]
(I briefly mentioned the first question in the other issue, but let's ask it separately.)
1. Who is using LTP regularly and are there publicly available run logs or other results? Which testcase lists are run, how frequently?
2. Who is also doing coverage analysis are there publicly viewable code coverage reports for the kernel? How much % of the kernel code is covered by LTP?

This would be useful for other users to start testing to see other's experiences, tips, and best practices!

Some googling showed that
1. Intel's LKP is only running 2 testcase lists from LTP: [dio and fs_radonly](https://git.kernel.org/pub/scm/linux/kernel/git/wfg/lkp-tests.git/tree/tests/ltp.yaml). Why so few?
2. There is a site that ran LTP **once** with a coverage report [there](https://www.verifysoft.com/en_rolands_blog.html).

Would be happy and grateful to know about more usage.

**Comment by pevik** [comment]
You may want to ask on LTP mailing list (http://lists.linux.it/listinfo/ltp) or automated-testing mailing list (https://lists.yoctoproject.org/g/automated-testing/).

AFAIK: SUSE for SLES and openSUSE (https://openqa.opensuse.org/group_overview/32) , Red Hat (don't know the details, maybe part of kernelci) and Linaro (https://linux.kernelci.org/job/).

**Comment by pevik** [comment]
https://www.verifysoft.com/ is unknown page for me, but it references LTP from 2006. IMHO something abandoned.

**Comment by metan-ucw** [comment]
Have a look at https://kernelci.org that's a project that attempts to aggregate kernel testing results across the companies.

As for the coverage I guess that nobody bothers. My take on this is that our coverage is so obviously sparse that there is no point in generating coverage reports at all.

**Comment by pevik** [comment]
@vt-alt I guess we can close this. Feel free to ask for more on our mailing list.

**Comment by vt-alt** [comment]
Excuse me for the delay. 

> AFAIK: SUSE for SLES and openSUSE (https://openqa.opensuse.org/group_overview/32)

This page is full of failed builds. So how it's determined tests pass acceptable or not?

**Comment by pevik** [comment]
> 1. Intel's LKP is only running 2 testcase lists from LTP: [dio and fs_radonly](https://git.kernel.org/pub/scm/linux/kernel/git/wfg/lkp-tests.git/tree/tests/ltp.yaml). Why so few?

You have to ask them :). 

We try to concentrate on new subsystems, but with given manpower most of new things is not covered. And we're in the middle of rewriting tests into new API (legacy API is buggy). Probably most valuable are: syscalls, cve and others which have been ported to new API or written recently (as these aren't buggy): e.g. uevent, crypto, pty. All these are written in C. aiodio tests are broken on current mainline and should be probably deleted as they're probably covered by fstests.

There are also tests written in shell, most of them are network tests. Valuable are probably: net.nfs, ima, net_stress.ipsec_icmp. net.features and some other stress tests are interesting, but affected by environment (compare speed).

You might be interested in metan's blog: https://people.kernel.org/~metan
