### ISSUE TITLE
getrlimit03 fail at getrlimit_long function on kernel5.4

### ISSUE THREAD

**Issue by gengcixi** [linux-test-project/ltp#819]
I test ltp on my kernel5.4,use arm arch, and find getlimit03  testcase failed 
and I add print-debug info ,use strace to track the case. find  it will pass on
 getrlimit_u64 and  getrlimit_ulong , but failed on  getrlimit_long.

does the kernel5.4-arm no longer support gertlimit_long? 
the following is strace info , wish someone can help me.

[pid 32574] wait4(-1, 0xbec0d104, 0, NULL) = -1 ECHILD (No child processes)
[pid 32574] prlimit64(0, RLIMIT_NICE, NULL, {rlim_cur=40, rlim_max=40}) = 0
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 97external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:74: INFO: resource 13 run at 74..) = 97
[pid 32574] ugetrlimit(RLIMIT_NICE, {rlim_cur=40, rlim_max=40}) = 0
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 87external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:103: INFO: run at 103..) = 87
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 87external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:118: INFO: run at 118..) = 87
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 87external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:118: INFO: run at 118..) = 87
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 141external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:173: PASS: __NR_prlimit64(13) and __NR_ugetrlimit(13) gave consistent results) = 141
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 87external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:174: INFO: run at 174..) = 87
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 87external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:178: INFO: run at 178..) = 87
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 97external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:87: INFO: resource 13 run at 87..) = 97
[pid 32574] syscall_0xffffffff(0xd, 0xbec0d0e8, 0xffffffff, 0xd, 0x57, 0xd) = 0xd
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 87external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:181: INFO: run at 181..) = 87
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 87external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:187: INFO: run at 187..) = 87
[pid 32574] write(2, "external/ltp/testcases/kernel/sy"..., 159external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:100: FAIL: __NR_prlimit64(13) returned 0 (SUCCESS) but __NR_getrlimit(13) returned 13 (SUCCESS)) = 159

**Comment by metan-ucw** [comment]
Looking at the strace we attempt to call syscall number 0xffffffff which means that we pass -1 to syscall() that is used for undefined syscall numbers in the lapi/syscalls.h header.

I guess that there is something wrong with the syscall name mapping at the start of the getrlimit03.c source code. What are the values of __NR_getrlimit __NR_ugetrlimit and __NR_prlimit64 on this platform? I guess that both __NR_getrlimit and __NR_ugetrlimit may be undefined (set to -1) and only __NR_prlimit64 may be implemented.

**Comment by gengcixi** [comment]
only in the fail syscall  __NR_getrlimit is -1, the two other passed is normally

[pid 16002] wait4(-1, 0xbee5a104, 0, NULL) = -1 ECHILD (No child processes)
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 105external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:58: INFO: __NR_prlimit64=369, resource=14
) = 105
[pid 16002] prlimit64(0, RLIMIT_RTPRIO, NULL, {rlim_cur=0, rlim_max=0}) = 0
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 111external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:75: INFO: __NR_getrlimit_ulong=191, resource=14
) = 111
[pid 16002] ugetrlimit(RLIMIT_RTPRIO, {rlim_cur=0, rlim_max=0}) = 0
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 141external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:171: PASS: __NR_prlimit64(14) and __NR_ugetrlimit(14) gave consistent results
) = 141
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 104external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:88: INFO: __NR_getrlimit=-1, resource=14
) = 104
[pid 16002] syscall_0xffffffff(0xe, 0xbee5a0e8, 0xffffffff, 0xffffffff, 0xe, 0xe) = 0xe
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 159external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:101: FAIL: __NR_prlimit64(14) returned 0 (SUCCESS) but __NR_getrlimit(14) returned 14 (SUCCESS)
) = 159
[pid 16002] wait4(-1, 0xbee5a104, 0, NULL) = -1 ECHILD (No child processes)
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 105external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:58: INFO: __NR_prlimit64=369, resource=15
) = 105
[pid 16002] prlimit64(0, RLIMIT_RTTIME, NULL, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 111external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:75: INFO: __NR_getrlimit_ulong=191, resource=15
) = 111
[pid 16002] ugetrlimit(RLIMIT_RTTIME, {rlim_cur=RLIM_INFINITY, rlim_max=RLIM_INFINITY}) = 0
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 141external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:171: PASS: __NR_prlimit64(15) and __NR_ugetrlimit(15) gave consistent results
) = 141
[pid 16002] write(2, "external/ltp/testcases/kernel/sy"..., 104external/ltp/testcases/kernel/syscalls/getrlimit/getrlimit03.c:88: INFO: __NR_getrlimit=-1, resource=15

**Comment by gengcixi** [comment]
[trace.log](https://github.com/linux-test-project/ltp/files/6532504/trace.log)
here is the full test tracing log

**Comment by metan-ucw** [comment]
Looks like this may have been broken by 59d278d61ed9 that removed certain syscalls from the arm.in file including getrlimit which may end up being undefined after this change.

Does adding "getrlimit (__NR_SYSCALL_BASE+ 76)" into include/lapi/syscalls/arm.in then running configure && make fix the issue for you?
