### ISSUE TITLE
error: redefinition of ‘struct statfs’ -- glibc version is 2.28

### ISSUE THREAD

**Issue by NoahLovesLife** [linux-test-project/ltp#820]
when I do `make all`, I got a error:
```
/usr/include/aarch64-linux-gnu/bits/ustat.h:24:8: error: redefinition of ‘struct statfs’
 struct ustat
        ^~~~~
In file included from /usr/include/aarch64-linux-gnu/sys/statfs.h:25,
                 from /usr/include/aarch64-linux-gnu/sys/vfs.h:4,
                 from ../../../../include/tst_safe_macros.h:14,
                 from ../../../../include/tst_test.h:93,
                 from ustat01.c:9:
/usr/include/aarch64-linux-gnu/bits/statfs.h:47:8: note: originally defined here
 struct statfs
        ^~~~~~
In file included from ../../../../include/tst_test.h:14,
                 from ustat01.c:9:
/usr/include/aarch64-linux-gnu/sys/ustat.h:33:12: error: conflicting types for ‘statfs’
 extern int ustat (__dev_t __dev, struct ustat *__ubuf) __THROW;
            ^~~~~
In file included from /usr/include/aarch64-linux-gnu/sys/vfs.h:4,
                 from ../../../../include/tst_safe_macros.h:14,
                 from ../../../../include/tst_test.h:93,
                 from ustat01.c:9:
/usr/include/aarch64-linux-gnu/sys/statfs.h:31:12: note: previous declaration of ‘statfs’ was here
 extern int statfs (const char *__file, struct statfs *__buf)
```
Anyone help!

**Comment by metan-ucw** [comment]
The snippet looks really strange it complain about redefinition of struct statfs then it points to struct ustat.

Can you please describe what exact steps have you done in order to compile LTP?

Also which distribution is this on, which libc, etc?

**Comment by NoahLovesLife** [comment]
> The snippet looks really strange it complain about redefinition of struct statfs then it points to struct ustat.
> 
> Can you please describe what exact steps have you done in order to compile LTP?
> 
> Also which distribution is this on, which libc, etc?

Thanks for your time!
I commented the redefinition code, and that works!
`/usr/include/aarch64-linux-gnu/bits/ustat.h:24:8: error: redefinition of ‘struct statfs’
 struct ustat`
`/usr/include/aarch64-linux-gnu/sys/ustat.h:33:12: error: conflicting types for ‘statfs’
 extern int ustat (__dev_t __dev, struct ustat *__ubuf) __THROW;`
