### ISSUE TITLE
mtest06: mmap1 test execution time and LTP_TIMEOUT_MUL

### ISSUE THREAD

**Issue by multiple1** [linux-test-project/ltp#824]
Hello!

For me it looks like mmap1 executes its test until the test reaches the set timeout.
mmap1 will stop its execution if only n seconds are remaining until timeout.
https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/mem/mtest06/mmap1.c#L228

The test argument -x 0.02 changes the test timeout.
https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/mem/mtest06/mmap1.c#L219

But if I set LTP_TIMEOUT_MUL=2 the ltp lib will multiply the set timeout e.g. -x 0.02*2.
So the test would run twice as long, or am I wrong?
I think mmap1 and maybe other tests misuse the timeout mechanism of ltp?

**Comment by metan-ucw** [comment]
This is known problem, timeout multiplication only increases tests in this case and yes I do plan to introduce a new variable something as LTP_MAX_RUNTIME as currently there is no way how to set a test runtime for these testcases.

**Comment by multiple1** [comment]
Ok, good to know. So for now LTP_TIMEOUT_MUL can/should not be used.

**Comment by metan-ucw** [comment]
I've send a patchset that attempts to fix this issue http://patchwork.ozlabs.org/project/ltp/list/?series=247935 I guess that there will be some changes needed before it could be applied but it should show the direction where this is heading to.

**Comment by metan-ucw** [comment]
Should be fixed by the runtime patchset starting with 0f72d519a95cb2e0d231e9bbdb44d288a974dacf patch.
