### ISSUE TITLE
test case running issues

### ISSUE THREAD

**Issue by donngchao** [linux-test-project/ltp#826]
[root@centos ~/ltp/testcases/kernel/syscalls/getpid]# make
../../../../include/mk/env_pre.mk:91: /root/ltp/include/mk/config.mk: No such file or directory
../../../../include/mk/env_pre.mk:92: /root/ltp/include/mk/features.mk: No such file or directory
make: *** No rule to make target `/root/ltp/include/mk/features.mk'.  Stop.

Can not run test cases on my machine.

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp#quick-guide-to-running-the-tests
https://github.com/linux-test-project/ltp/blob/master/INSTALL
`make autotools && ./configure && make -j$(nproc)`
