### ISSUE TITLE
PCI: The twelfth tpci test case failed

### ISSUE THREAD

**Issue by guohui0712** [linux-test-project/ltp#828]
The twelfth tpci test case calls the kernel function “pci_assign_resource“ to return the value in only two cases:
1, the return value is 0, which means success
2, The return value is -ENOMEM has no memory
After analysis, the function “pci_assign_resource“ will not return -EBUSY
In the kernel function “pci_bus_alloc_from_region“, -EBUSY will be converted to -ENOMEM, so even -EBUSY will be processed as -ENOMEM in the end. Therefore, -EBUSY will be processed as failure in the LTP tpci use case. This processing  is unreasonable.

**Comment by xuyang0410** [comment]
I guess it has been fixed since [ltp_tpci.c: Add release operation before allocation](https://github.com/linux-test-project/ltp/commit/d631e9caef6818cffae6e028191787efcf65b3da). Feel free to reopen this issue if you still have problem when using lastest ltp.
