### ISSUE TITLE
Invalid argument on setrlimit

### ISSUE THREAD

**Issue by bogdancarpusor** [linux-test-project/ltp#83]
kill11 and abort01 fail when setting the rlimit for RLIMIT_CORE on Ubuntu16.04. 

I have tried to manually set the rlimit value using the default method, from resource.h - setrlimit(), and it worked (method returned 0 and the value was changed)

kill11      0  TINFO  :  Adjusting RLIMIT_CORE to 1048576
kill11      1  TBROK  :  ../../../../include/old/safe_macros.h:322: kill11.c:207: setrlimit(4,0x7ffe8314ec80) failed: errno=EINVAL(22): Invalid argument
kill11      2  TBROK  :  ../../../../include/old/safe_macros.h:322: Remaining cases broken

abort01     0  TINFO  :  Adjusting RLIMIT_CORE to 1048576
abort01     1  TBROK  :  ../../../../include/old/safe_macros.h:322: abort01.c:142: setrlimit(4,0x7ffebb497a20) failed: errno=EINVAL(22): Invalid argument
abort01     2  TBROK  :  ../../../../include/old/safe_macros.h:322: Remaining cases broken

**Comment by metan-ucw** [comment]
What the test does is to get current limit by ```getrlimit()``` then uses this limits for ```setrlimit()``` only changing the ```rlim_cur```. The manual for ```setrlimit()``` says that we may get ```EINVAL``` in case that ```rlim_cur``` > ```rlim_max```, can you check that this is the case here?

**Comment by bogdancarpusor** [comment]
The default values are: 
 - **rlim_cur 0** 
 - **rlim_max 18446744073709551615**

I've pasted the code that I ran for further info: 
```c
#include <sys/time.h>
#include <sys/resource.h>
#include <stdio.h>

#define MIN_RLIMIT_CORE (1024 * 1024)

int main() {
        struct rlimit rlim;

        getrlimit(RLIMIT_CORE, &rlim);
        fprintf(stdout, "%lu %lu \n", rlim.rlim_cur, rlim.rlim_max);

        rlim.rlim_cur = MIN_RLIMIT_CORE;
        int retval = setrlimit(RLIMIT_CORE, &rlim);
        fprintf(stdout, " %i %lu %lu \n", retval, rlim.rlim_cur, rlim.rlim_max);

        return 1;
}
```

**Comment by metan-ucw** [comment]
Strange. I've looked into the kernel setrlimit syscall and the only way to get ```EINVAL``` is either the ```rlim_cur``` > ```rlim_max``` or invalid resource number. But the error messages from the tests shows clearly that the resource is 4 which is correct.

Can you try to add a debug prints to the test itself and try to rerun them?

**Comment by bogdancarpusor** [comment]
Added a print in the ```safe_getrlimit()``` function.
```c 
tst_resm(TINFO, "rlim values: %lu %lu", rlim->rlim_cur, rlim->rlim_max);
```

Apparently the values for rlimit are the same. I'm running the tests on an Ubuntu 16.04 (4.4.0-24-generic) under a Hyper-V Manager.
```
kill11      0  TINFO  :  rlim values: 524288 524288
kill11      0  TINFO  :  Adjusting RLIMIT_CORE to 1048576
kill11      1  TBROK  :  ../../../../include/old/safe_macros.h:322: kill11.c:206     
:setrlimit(4,0x7fffb4399400) failed: errno=EINVAL(22): Invalid argument
```

```
abort01     0  TINFO  :  rlim values: 524288 524288
abort01     0  TINFO  :  Adjusting RLIMIT_CORE to 1048576
abort01     1  TBROK  :  ../../../../include/old/safe_macros.h:322: abort01.c:14
1:setrlimit(4,0x7fff7af18800) failed: errno=EINVAL(22): Invalid argument
```

**Comment by bogdancarpusor** [comment]
**#update**

Looked for  other instances where rlimit is being set and apparently in those examples the values are also equal.

```
mlock02     0  TINFO  :  rlim values: 65536 65536
munmap03    0  TINFO  :  rlim values: 18446744073709551615 18446744073709551615
```

**Comment by jstancek** [comment]
How are you running the tests? Is some test harness involved?
Is it also failing if you run single test by hand, e.g.:
```
# ./testcases/kernel/syscalls/abort/abort01
```

**Comment by bogdancarpusor** [comment]
If I ran the tests separately they pass. 

```
abort01     0  TINFO  :  rlim values: 0 18446744073709551615
abort01     0  TINFO  :  Adjusting RLIMIT_CORE to 1048576
abort01     1  TPASS  :  abort dumped core
abort01     2  TPASS  :  abort raised SIGIOT
abort01     3  TPASS  :  abort dumped core
abort01     4  TPASS  :  abort raised SIGIOT
abort01     5  TPASS  :  abort dumped core
abort01     6  TPASS  :  abort raised SIGIOT
```

I am running ltplite with the following command:
```bash
./runltplite.sh -c 4 -p -q -l ltp-results.log -o ltp-output.log
```

**Comment by jstancek** [comment]
So it looks like problem is ulimit calls in runtest files. "In POSIX Mode 512-byte blocks are used for the `-c' and `-f' options.". And  test tries to set 1024*1024:
```
$ grep ulimit  -r runtest/ | grep -e abort -e kill
runtest/stress.part3:abort01 ulimit -c 1024;abort01
runtest/stress.part3:kill11 ulimit -c 1024;kill11
runtest/ltplite:abort01 ulimit -c 1024;abort01
runtest/ltplite:kill11 ulimit -c 1024;kill11
```

**Comment by bogdancarpusor** [comment]
Just to understand things better, why is the ```ulimit``` being set for those tests before executing them?

And what would be a possible fix for this issue?

**Comment by embdlover** [comment]
i am also facing same problem in abort but i dont have stress.part3 under runtest.....where should i make changes??
