### ISSUE TITLE
Debian testing with asciidoc 9.0.0~rc2-1 occasionally fails

### ISSUE THREAD

**Issue by pevik** [linux-test-project/ltp#833]
```
./configure --with-metadata-generator=asciidoc --enable-metadata-pdf
cd docparse/ && make -j`nproc`
...
a2x: ERROR: "xsltproc" --stringparam toc.section.depth 1 --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0 --stringparam chunk.section.depth 0  --stringparam base.dir "metadata.chunked/" "/etc/asciidoc/docbook-xsl/chunked.xsl" "/__w/ltp/ltp/docparse/metadata.xml" returned non-zero exit status 5
```
It might be fixed by newer release `9.1.0` which is not yet packaged in Debian, but it's in Tumbleweed. I'll retest it.

**Comment by pevik** [comment]
@metan-ucw Hm, I'm not able to reproduce it on Debian testing, nor on Tumbleweed. Maybe it's something specific to github docker. Do we just disable affected jobs? ATM it's at least 13th job `debian:testing, clang, asciidoc-pdf`, I'd wait little longer to see which other jobs are affected (there will be more on Debian, but don't remember which ones).

**Comment by pevik** [comment]
Another commit (9c552ccb650cd7d353297071d563525a19f2ff52) fails again on [debian:testing, clang, asciidoc-pdf](https://github.com/linux-test-project/ltp/runs/2821081489) job. It's again metadata chunked html, thus maybe disabling html for debian testing. I'll try to debug it with github actions.

**Comment by pevik** [comment]
Yes, test keeps failing, I'll have final effort to see what's wrong on asciidocs on github actions and then just disable it for debian testing.

**Comment by metan-ucw** [comment]
It's failing again on debian testing and in metadata, let's just disable metadata on debian testing, this is just generating a noise.
