### ISSUE TITLE
pthread_rwlock_unlock/3-1 testcase fail

### ISSUE THREAD

**Issue by jiaoff** [linux-test-project/ltp#836]
pthread_rwlock_unlock/3-1 testcase fail
1.hard environment: arm64/x86; software environment: centos 8
2.run results，pthread_rwlock_unlock/3-1 testcase fail
main: write lock
main: create writer1, with priority: 3
writer1: attempt write lock
main: create reader, with priority: 3
reader: attempt read lock
main: create writer2, with priority: 1
writer2: attempt write lock
main: release write lock
reader: acquired read lock
Test fail: writer did not get write lock, when main release the lock
3.Glibc set "PTHREAD_RWLOCK_DEFAULT_NP = PTHREAD_RWLOCK_PREFER_READER_NP", therefore result is step2.
4.Do you need to modify the expected results of pthread_rwlock_unlock/3-1 ?

**Comment by metan-ucw** [comment]
This is known and longstanding glibc issue see https://sourceware.org/bugzilla/show_bug.cgi?id=25619
