### ISSUE TITLE
cgroup_regression_test.sh easily FAILs with "Device or resource busy"

### ISSUE THREAD

**Issue by ycliang-tw** [linux-test-project/ltp#839]
Hi all,
I am running LTP on RISC-V platform with 5.4 kernel.
This platform can easily fail cgroup_regression_test.sh with mount showing "Device or resource busy".
Have managed to reduce the failing sequnence to the following.
```
mkdir cgroup
mount -t cgroup -o cpu,cpuacct xxx cgroup/  ## cpu and cpuacct are the only two subsystems that our kernel has
mkdir cgroup/test 
rmdir cgroup/test 
umount cgroup
mount -t cgroup -o cpu xxx cgroup/ ## this command failed "Device or resource busy"
```
Somehow adding some delay between `rmdir` and `umount` would set it back to normal.
```
mkdir cgroup
mount -t cgroup -o cpu,cpuacct xxx cgroup/  
mkdir cgroup/test 
rmdir cgroup/test 
sleep 1 or sync  # either one will do 
umount cgroup
mount -t cgroup -o cpu xxx cgroup/
```
After a little bit of tracing, we found out there was one release code path that was missing in the previous rmdir and umount.
Thus the `mount` came after would fail with -EBUSY.

Related debug log of the failed case:
```
Thread 3 hit Breakpoint 1, rebind_subsystems (dst_root=0xf25b6000, ss_mask=3) at kernel/cgroup/cgroup.c:1625   ## mount
Thread 1 hit Breakpoint 1, rebind_subsystems (dst_root=0xf1e1c000, ss_mask=2) at kernel/cgroup/cgroup.c:1625   ## mount
Thread 1 hit Breakpoint 2, kill_css (css=0xf1f82fc0) at kernel/cgroup/cgroup.c:4997                        ## rmdir
Thread 1 hit Breakpoint 2, kill_css (css=0xf1f336c0) at kernel/cgroup/cgroup.c:4997
Thread 1 hit Breakpoint 4, css_killed_ref_fn (ref=0xf1f82fc8) at kernel/cgroup/cgroup.c:4978
Thread 1 hit Breakpoint 4, css_killed_ref_fn (ref=0xf1f336c8) at kernel/cgroup/cgroup.c:4978
Thread 1 hit Breakpoint 5, css_killed_work_fn (work=0xf1f8300c) at kernel/cgroup/cgroup.c:4956
Thread 1 hit Breakpoint 3, css_release (ref=0xf1f82fc8) at kernel/cgroup/cgroup.c:4630
Thread 1 hit Breakpoint 5, css_killed_work_fn (work=0xf1f3370c) at kernel/cgroup/cgroup.c:4956
Thread 1 hit Breakpoint 3, css_release (ref=0xf1f336c8) at kernel/cgroup/cgroup.c:4630
Thread 1 hit Breakpoint 6, css_release_work_fn (work=0xf1f8300c) at kernel/cgroup/cgroup.c:4577
Thread 1 hit Breakpoint 6, css_release_work_fn (work=0xf1f3370c) at kernel/cgroup/cgroup.c:4577
Thread 1 hit Breakpoint 7, css_free_rwork_fn (work=0xf1f8301c) at kernel/cgroup/cgroup.c:4528
Thread 1 hit Breakpoint 7, css_free_rwork_fn (work=0xf1f3371c) at kernel/cgroup/cgroup.c:4528
Thread 1 hit Breakpoint 3, css_release (ref=0xf25bd208) at kernel/cgroup/cgroup.c:4630
Thread 1 hit Breakpoint 6, css_release_work_fn (work=0xf25bd24c) at kernel/cgroup/cgroup.c:4577
Thread 1 hit Breakpoint 7, css_free_rwork_fn (work=0xf25bd25c) at kernel/cgroup/cgroup.c:4528
```
Related debug log of the successful case (add `sleep 1` or `sync` ):
```
Thread 3 hit Breakpoint 1, rebind_subsystems (dst_root=0xf25b4000, ss_mask=3) at kernel/cgroup/cgroup.c:1625  ## mount
Thread 4 hit Breakpoint 1, rebind_subsystems (dst_root=0xf261e000, ss_mask=2) at kernel/cgroup/cgroup.c:1625  ## mount
Thread 4 hit Breakpoint 2, kill_css (css=0xf1f83180) at kernel/cgroup/cgroup.c:4997                        ## rmdir
Thread 4 hit Breakpoint 2, kill_css (css=0xf1f33a80) at kernel/cgroup/cgroup.c:4997
Thread 4 hit Breakpoint 4, css_killed_ref_fn (ref=0xf1f83188) at kernel/cgroup/cgroup.c:4978
Thread 4 hit Breakpoint 4, css_killed_ref_fn (ref=0xf1f33a88) at kernel/cgroup/cgroup.c:4978
Thread 4 hit Breakpoint 5, css_killed_work_fn (work=0xf1f831cc) at kernel/cgroup/cgroup.c:4956
Thread 4 hit Breakpoint 3, css_release (ref=0xf1f83188) at kernel/cgroup/cgroup.c:4630
Thread 4 hit Breakpoint 5, css_killed_work_fn (work=0xf1f33acc) at kernel/cgroup/cgroup.c:4956
Thread 4 hit Breakpoint 3, css_release (ref=0xf1f33a88) at kernel/cgroup/cgroup.c:4630
Thread 4 hit Breakpoint 6, css_release_work_fn (work=0xf1f831cc) at kernel/cgroup/cgroup.c:4577
Thread 4 hit Breakpoint 6, css_release_work_fn (work=0xf1f33acc) at kernel/cgroup/cgroup.c:4577
Thread 4 hit Breakpoint 7, css_free_rwork_fn (work=0xf1f831dc) at kernel/cgroup/cgroup.c:4528
Thread 4 hit Breakpoint 7, css_free_rwork_fn (work=0xf1f33adc) at kernel/cgroup/cgroup.c:4528
Thread 4 hit Breakpoint 3, css_release (ref=0xf25bd008) at kernel/cgroup/cgroup.c:4630
Thread 4 hit Breakpoint 6, css_release_work_fn (work=0xf25bd04c) at kernel/cgroup/cgroup.c:4577
Thread 4 hit Breakpoint 7, css_free_rwork_fn (work=0xf25bd05c) at kernel/cgroup/cgroup.c:4528

Thread 3 hit Breakpoint 3, css_release (ref=0xf25b4018) at kernel/cgroup/cgroup.c:4630                    ## umount
Thread 3 hit Breakpoint 6, css_release_work_fn (work=0xf25b405c) at kernel/cgroup/cgroup.c:4577
Thread 3 hit Breakpoint 7, css_free_rwork_fn (work=0xf25b406c) at kernel/cgroup/cgroup.c:4528
Thread 3 hit Breakpoint 1, rebind_subsystems (dst_root=0xc0ce93e8 <cgrp_dfl_root>, ss_mask=3) at kernel/cgroup/cgroup.c:1625
```
There is a release code path missing in the failed case. ( release-related function, ex. `css_release`)

Currently,  `sync`  was added a work around.
Does anyone has similiar experiences on this cgroup_regression_test or has any comments on this behavior ?

Thanks in advance!
Leo

**Comment by pevik** [comment]
@ycliang-tw I'm not sure if this is test is not broken on all archs (verifying). All cgroup shell tests are very old thus don't work on CGroups V2 and IMHO many of them have false positives due race conditions. C based tests with new API (use `tst_test.h`) are much more stable, these which also contain `tst_cgroup_require()` support both both V1 and V2.
@richiejp @wangli5665 please correct me if I'm wrong.

**Comment by pevik** [comment]
> @ycliang-tw I'm not sure if this is test is not broken on all archs (verifying).

Test is working on intel on openSUSE 5.12.12. But still not sure if test is not outdated (written in 2009, look at the kernel history and search for cgroup in our mailing list and github issues, you see that generally cgroup shell tests are just buggy).

**Comment by metan-ucw** [comment]
I'm not sure if these tests are valid, If I remember correctly some of the operations the tests try in order to check for a regression are not possible anymore even in v1. Anyways it would be nice if @richiejp could have a look at these so that we can get rid of the useless parts once for all.

**Comment by ycliang-tw** [comment]
Thank you guys for replying so quickly.
I've noticed there's a lot of rewrite going on with these cgroup related tests.
I think we all agree that this test may be out-dated, so this fail could probably be omitted.
And I'll try out the newer C-based cgroup tests.
Thanks again for the help! 

Maybe we could keep this issue open for a few days if anyone has further comments.
I'll close this if otherwise.

**Comment by richiejp** [comment]
The comment about `sync` is useful to know. I have experienced this issue when unmounting before. However I just used MNT_DETACH. This doesn't actually delete the CGroup root. So maybe syncing will be a better option.

The tests look valid in principle, but are likely to fail on some setups. Also I wasn't aware it's possible to mount an empty V1 hierarchy (no controllers attached). So they need a closer look.

Also could you just send a patch adding sync in the appropriate place?

**Comment by ycliang-tw** [comment]
Of course! I'll send the patch right away.
Thanks for the suggestion!

> Also I wasn't aware it's possible to mount an empty V1 hierarchy (no controllers attached).

I am not very familiar with cgroup, so I might not get it right.
But I thought the `cpu` and `cpuacct` are attached, or are they not controllers ?

**Comment by richiejp** [comment]
> I am not very familiar with cgroup, so I might not get it right.
> But I thought the `cpu` and `cpuacct` are attached, or are they not controllers ?

You are correct, on some tests it finds an existing cgroup mount and remounts it. So then you have the cpu and cpuacct controllers.

However on other tests it just mounts an new empty hierarchy with no controllers attached.
