### ISSUE TITLE
cpuhotplug04 fails because can not offline cpu0

### ISSUE THREAD

**Issue by NgaHoang10** [linux-test-project/ltp#84]
Hello all, 
I have one issue when execute cpuhotplug04. Our kernel doesn't allow offline cpu0 while the test tries to offline the hotpluggable CPUs. So the test fails with error "Could not offline cpu0". Does anybody have idea about this, please help.

**Comment by metan-ucw** [comment]
If the ```cpu0``` creates the ```/sys/devices/system/cpu/cpu0/online``` it should be possible to offline it. And if you have a look into ```doc/Documentation/cpu-hotplug.txt``` in the kernel git repository it explicitly states that certain architectures cannot offline ```cpu0``` and that the ```online``` file will be missing from the ```cpu0``` sysfs directory in that case.

**Comment by olerem** [comment]
Ok, so it means, the kernel should be fixed.
