### ISSUE TITLE
Few of the LTP tstcases are failing in SLES distro(kernel version-5.3.18)

### ISSUE THREAD

**Issue by shirishaganta1** [linux-test-project/ltp#840]
LTP tests failed  ['shmget03',  'netns_comm_ns_exec_ipv4_netlink', 'netns_comm_ns_exec_ipv6_netlink', 'netns_comm_ip_ipv4_netlink', 'netns_comm_ip_ipv6_netlink',  'zram01', 'zram02', 'zram03']

I followed below steps to run 
1. wget https://github.com/linux-test-project/ltp/archive/master.zip
2. unzip master.zip
3. cd ltp-master
4. ./build.sh -i
5. cd
6. cd ltp-install
7. ./runltp -f  test
 test file contains below testcases
localhost:\~/ltp-install \# cat runtest/test
shmget03 shmget03
netns_comm_ns_exec_ipv4_netlink netns_comm.sh ns_exec ipv4 netlink
netns_comm_ns_exec_ipv6_netlink netns_comm.sh ns_exec ipv6 netlink
netns_comm_ip_ipv4_netlink netns_comm.sh ip ipv4 netlink
netns_comm_ip_ipv6_netlink netns_comm.sh ip ipv6 netlink
zram01 zram01.sh
zram02 zram02.s
zram03 zram03
localhost:\~/ltp-install # 

Below attaching the log
[nohup_ltp_s15sp3.txt](https://github.com/linux-test-project/ltp/files/6739636/nohup_ltp_s15sp3.txt)

**Comment by xuyang0410** [comment]
For shmget03 failure,  I guess your environmet was not clean, so it reports failure in setup phase. You can verify this by using ipcs -m command before running this case.

**Comment by mdoucha** [comment]
>        shmget03 shmget03

That failure is likely caused by too small memory limits in `/proc/sys/kernel/shm*` or too much SHM resource usage by other processes. The test passes in our test setup on all supported SLE versions and archs.

>        netns_comm_ns_exec_ipv4_netlink netns_comm.sh ns_exec ipv4 netlink
>        netns_comm_ns_exec_ipv6_netlink netns_comm.sh ns_exec ipv6 netlink
>        netns_comm_ip_ipv4_netlink netns_comm.sh ip ipv4 netlink
>        netns_comm_ip_ipv6_netlink netns_comm.sh ip ipv6 netlink

The `iputils` package is missing on your test system. Install it to fix the failures.

>        zram01 zram01.sh
>        zram02 zram02.s
>        zram03 zram03

It appears that `/dev/zram0` is already in use on your test machine. The `zram*` tests only work if all zram devices are free and preferably the `zram` kernel module is not loaded at all in the beginning.

**Comment by shirishaganta1** [comment]
> > ```
> >    shmget03 shmget03
> > ```
> 
> That failure is likely caused by too small memory limits in `/proc/sys/kernel/shm*` or too much SHM resource usage by other processes. The test passes in our test setup on all supported SLE versions and archs.
> 
Shmget03  looking into it.
> > ```
> >    netns_comm_ns_exec_ipv4_netlink netns_comm.sh ns_exec ipv4 netlink
> >    netns_comm_ns_exec_ipv6_netlink netns_comm.sh ns_exec ipv6 netlink
> >    netns_comm_ip_ipv4_netlink netns_comm.sh ip ipv4 netlink
> >    netns_comm_ip_ipv6_netlink netns_comm.sh ip ipv6 netlink
> > ```
> 
> The `iputils` package is missing on your test system. Install it to fix the failures.
> 
By installing iputils package the above one's got fixed
> > ```
> >    zram01 zram01.sh
> >    zram02 zram02.s
> >    zram03 zram03
> > ```
> 
> It appears that `/dev/zram0` is already in use on your test machine. The `zram*` tests only work if all zram devices are free and preferably the `zram` kernel module is not loaded at all in the beginning.

zram  looking into it
Thanks

**Comment by pevik** [comment]
> > ```
> >    netns_comm_ns_exec_ipv4_netlink netns_comm.sh ns_exec ipv4 netlink
> >    netns_comm_ns_exec_ipv6_netlink netns_comm.sh ns_exec ipv6 netlink
> >    netns_comm_ip_ipv4_netlink netns_comm.sh ip ipv4 netlink
> >    netns_comm_ip_ipv6_netlink netns_comm.sh ip ipv6 netlink
> > ```
> 
> The `iputils` package is missing on your test system. Install it to fix the failures.

Good catch. FYI I sent a patch adding missing check in https://patchwork.ozlabs.org/project/ltp/patch/20210716100415.27410-2-pvorel@suse.cz/ (part of patchset cleanup in https://patchwork.ozlabs.org/project/ltp/list/?series=253817).

**Comment by metan-ucw** [comment]
Feel free to reopen if needed.
