### ISSUE TITLE
Strace ftp-download-stress01-rmt.sh  failed on x86

### ISSUE THREAD

**Issue by Aniketpatil4406** [linux-test-project/ltp#841]
hi ,i executed flt-download-stress01-rmt.sh but this test failed
after executed this test this one output
curl: (3) Bad URL
ftp-download-stress01-rmt 1 TINFO: stat: time=0.000000 size=0 speed=0.000
ftp-download-stress01-rmt 1 TINFO: Expected file size ''
ftp-download-stress01-rmt 1 TBROK: Failed to download ftp:///

also i add strace log file 
[output.txt](https://github.com/linux-test-project/ltp/files/6767538/output.txt)

**Comment by metan-ucw** [comment]
You cannot execute these scripts manually, these are executed by a framework and passed down correct parameters that way as well.

**Comment by metan-ucw** [comment]
See also: https://github.com/linux-test-project/ltp/blob/master/testcases/network/README.md
