### ISSUE TITLE
 The testcase of broken_ip-nexthdr failed on Raspberry pi (kernel version 5.10.17-v7lt) 

### ISSUE THREAD

**Issue by rameshwarl** [linux-test-project/ltp#843]
broken_ip-nexthdr 1 TINFO: initialize 'lhost' 'ltp_ns_veth2' interface
broken_ip-nexthdr 1 TINFO: add local addr 10.0.0.2/24
broken_ip-nexthdr 1 TINFO: add local addr fd00:1:1:1::2/64
broken_ip-nexthdr 1 TINFO: initialize 'rhost' 'ltp_ns_veth1' interface
broken_ip-nexthdr 1 TINFO: add remote addr 10.0.0.1/24
broken_ip-nexthdr 1 TINFO: add remote addr fd00:1:1:1::1/64
broken_ip-nexthdr 1 TINFO: Network config (local -- remote):
broken_ip-nexthdr 1 TINFO: ltp_ns_veth2 -- ltp_ns_veth1
broken_ip-nexthdr 1 TINFO: 10.0.0.2/24 -- 10.0.0.1/24
broken_ip-nexthdr 1 TINFO: fd00:1:1:1::2/64 -- fd00:1:1:1::1/64
broken_ip-nexthdr 1 TINFO: timeout per run is 0h 5m 0s
broken_ip-nexthdr 1 TINFO: Sending ICMPv4 with wrong next header for 10 sec
ns-icmpv4_sender: invalid option -- 'n'
ns-icmpv4_sender [OPTION]
	-I if_name	Interface name of the source host
	-S ip_addr	IPv4 address of the source host
	-M mac_addr	MAC address of the destination host
	-D ip_addr	IPv4 address of the destination host
	-s packetsize	number of data bytes (exclude header)
	-t value	timeout [sec]
	-d		display debug informations
	-h		display this usage

	[options for fake]
	  -c	break checksum
	  -f	break fragment information
	  -i	break IPv4 destination address
	  -l	break header length
	  -L	break total length
	  -p	break protocol number
	  -v	break IP version
broken_ip-nexthdr 1 TFAIL: 'ns-icmpv4_sender -s 0 -n -I ltp_ns_veth2 -S 10.0.0.2 -D 10.0.0.1 -M 0a:60:f9:b6:ed:45 -t 2' fail
broken_ip-nexthdr 1 TPASS: ping -I ltp_ns_veth2 -c 500 -s 56 -f 10.0.0.1 >/dev/null passed as expected

Summary:
passed   1
failed   1
broken   0
skipped  0
warnings 0

**Comment by metan-ucw** [comment]
Looks like a typo, these tests were rewritten recently, assigning to Peter who did the rewrite, he will have a look once he is back from vacation.

**Comment by pevik** [comment]
Some tests are supposed to be run on IPv4 only or IPv6 only (this reported test). @rameshwarl does not use runtest/net_stress.broken_ip but run it manually. Already working on a fix.

**Comment by pevik** [comment]
Patch fixing this sent: https://patchwork.ozlabs.org/project/ltp/list/?series=253498
