### ISSUE TITLE
How to execute ftp-download-stress01-rmt.sh?

### ISSUE THREAD

**Issue by Ankita-020696** [linux-test-project/ltp#844]
Hi,
How can I execute **ftp-download-stress01-rmt.sh** test?
Does it expect any argument?

> ftp-download-stress01-rmt.sh
> curl: (3) Bad URL
> ftp-download-stress01-rmt 1 TINFO: stat: time=0.000000 size=0 speed=0.000
> ftp-download-stress01-rmt 1 TINFO: Expected file size ''
> ftp-download-stress01-rmt 1 TBROK: Failed to download ftp:///

Thanks

**Comment by pevik** [comment]
Everything is described here:
https://github.com/linux-test-project/ltp/tree/master/testcases/network
https://github.com/linux-test-project/ltp#shortcut-to-running-a-single-test
