### ISSUE TITLE
Write a test for cgroup kill button

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#846]
See: https://lwn.net/Articles/855049/

**Comment by coolgw** [comment]
checking

**Comment by coolgw** [comment]
https://patchwork.ozlabs.org/project/ltp/patch/20230430074811.29555-3-wegao@suse.com/ 
so can be closed?

**Comment by Martchus** [comment]
The change has been merged so it looks like this could be closed, indeed.

**Comment by pevik** [comment]
Implemented in 448f2e47da9aa2bb6723339e367294ca8d599189, thanks!
