### ISSUE TITLE
segfault for LTP 32-bit binary fstat03/setrlimit05 of syscalls in libc-2.28.so on 64-bit OS setup

### ISSUE THREAD

**Issue by hongyuni** [linux-test-project/ltp#851]
Hi, 

based on LTP version 20210524-184-g18800c0de, Linux Kernel v5.13,
there are following segfault met to run LTP 32-bit binary of syscalls test on 64-bit OS:

fstat03[31976]: segfault at 0 ip 00000000f7eae911 sp 00000000ffeb0c04 error 6 in libc-2.28.so[f7dcb000+1a1000]
setrlimit05[32681]: segfault at f7f44000 ip 00000000f7e7684a sp 00000000ffb76ea0 error 4 in libc-2.28.so[f7d92000+1a1000]

my question are:
is there something not expected by LTP test? 
or is there anything should be changed in the test setup?

Thanks

**Comment by metan-ucw** [comment]
The setrlimit05 and fstat03 tests are expected to get segfault when binary is executed in compat mode (i.e. 32bit on 64bit) and it's pretty clear if you look at the test source code.
