### ISSUE TITLE
LTP syscalls mmap18 (both 32-bit and 64-bit binary) segfault error 6 in mmap18 on 64-bit Linux OS

### ISSUE THREAD

**Issue by hongyuni** [linux-test-project/ltp#852]
Hi

based on LTP version 20210524-184-g18800c0de, found a LTP syscalls mmap18 segfault in both 32-bit and 64-bit binary, in the same 64-bit OS setup, Linux Kernel version v5.13.

32-bit mmap18 segfault info:
mmap18[32160]: segfault at f7dbbffc ip 000000000804aae3 sp 00000000f7dbc000 error 6 in mmap18[8048000+26000]
mmap18[32162]: segfault at f7dafffc ip 000000000804aae3 sp 00000000f7db0000 error 6 in mmap18[8048000+26000]

64-bit mmap18 segfault info:
mmap18[91645]: segfault at 7f609099aff8 ip 0000000000403c96 sp 00007f609099b000 error 6 in mmap18[400000+24000]
mmap18[91647]: segfault at 7f609098eff8 ip 0000000000403c96 sp 00007f609098f000 error 6 in mmap18[400000+24000]

is there anything unexpected by LTP test? or anything might need to fix here?

**Comment by metan-ucw** [comment]
Same here, the segfault is expected and it's easy to figure it out from the test source code.
