### ISSUE TITLE
LTP syscalls modify_ldt02 (32-bit binary) segfault error 4 in modify_ldt02 on 64-bit Linux OS setup

### ISSUE THREAD

**Issue by hongyuni** [linux-test-project/ltp#854]
Hi,

based on LTP version 20210524-184-g18800c0de, Linux Kernel v5.13,
there is following segfault met for LTP syscalls modify_ldt02 (32-bit binary) running on 64-bit Linux OS setup:

modify_ldt02[32329]: segfault at 0 ip 000000000804a9ce sp 00000000ffa04f40 error 4 in modify_ldt02[8048000+27000]

is there anything unexpected by LTP test?

**Comment by metan-ucw** [comment]
Same here as well, the segfault is expected and it's easy to figure it out from the test source code.
