### ISSUE TITLE
LTP syscalls shmat01 (32-bit binary) segfault error 6 in shmat01 on 64-bit Linux OS setup

### ISSUE THREAD

**Issue by hongyuni** [linux-test-project/ltp#855]
Hi

based on LTP version 20210524-184-g18800c0de, Linux Kernel v5.13,

there is following segfault met during LTP shmat01 (32-bit binary) running on 64-bit Linux OS setup:

shmat01[32859]: segfault at f7f6c000 ip 000000000804ae0a sp 00000000ffaeac04 error 6 in shmat01[8048000+27000]

is there anything not expected by LTP test?

**Comment by metan-ucw** [comment]
Same here, the segfault is expected and it's easy to figure it out from the test source code.
