### ISSUE TITLE
AMP tests

### ISSUE THREAD

**Issue by Ankita-020696** [linux-test-project/ltp#856]
Hello,
Does LTP includes AMP testcases?

Thanks

**Comment by metan-ucw** [comment]
What does AMP mean?

**Comment by Ankita-020696** [comment]
> What does AMP mean?

AMP stands for Asymmetric Multi-Processing (AMP).

Thanks

**Comment by metan-ucw** [comment]
Can you please describe better what exactly you are trying to test?

Asymetric Multi-Processing is too generic term to describe your setup. Are you trying to isolate a single CPU for a specific task with isolcpu? Did you isolate a CPU in a some kind of supervisor and want check that Linux runs fine on such setup? Or anything completely else?

**Comment by metan-ucw** [comment]
Feel free to reopen if needed.
