### ISSUE TITLE
set panic_on_oom=0 for min_free_kbytes

### ISSUE THREAD

**Issue by olerem** [linux-test-project/ltp#86]
Hi,
th TC min_free_kbytes usually triggers an reset on our system because panic_on_oom is enabled by default.
Since panic_on_oom=0 is a requirement for this test, may be this value should be set and recovered by the tests itself?

**Comment by metan-ucw** [comment]
Either that or we may skip these testcases if ```panic_on_oom``` is set.

**Comment by olerem** [comment]
return 32?

**Comment by metan-ucw** [comment]
Yes, something as ```tst_brkm(TCONF, "panic_on_oom is set, disable it to run these testcases");```

**Comment by Vertigo0709** [comment]
Hi @olerem @metan-ucw 

Sorry I did not notice this issue before doing the commit (so it missed Fixes #... in commit message.)
Could you please help to close this ?
