### ISSUE TITLE
ioctl_loop5 test cases are failing

### ISSUE THREAD

**Issue by priyama2** [linux-test-project/ltp#865]
LTP: starting AD000 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD001 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD002 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD003 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD004 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD005 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD006 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD007 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD008 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting AD009 (aiodio_append $TMPDIR/aiodio.$$/file2)
LTP: starting 1_ITERATION_ioctl_loop05 (ioctl_loop05)
print_req_error: I/O error, dev loop1, sector 0
LTP: starting 2_ITERATION_ioctl_loop05 (ioctl_loop05)
loop_set_status: loop1 () has still dirty pages (nrpages=1)
loop_set_status: loop1 () has still dirty pages (nrpages=3)
loop_set_status: loop1 () has still dirty pages (nrpages=3)
LTP: starting 3_ITERATION_ioctl_loop05 (ioctl_loop05)
loop_set_status: loop1 () has still dirty pages (nrpages=2)
loop_set_status: loop1 () has still dirty pages (nrpages=2)
loop_set_status: loop1 () has still dirty pages (nrpages=3)
LTP: starting 4_ITERATION_ioctl_loop05 (ioctl_loop05)
loop_set_status: loop1 () has still dirty pages (nrpages=3)
loop_set_status: loop1 () has still dirty pages (nrpages=2)
loop_set_status: loop1 () has still dirty pages (nrpages=3)
loop_set_status: loop1 () has still dirty pages (nrpages=1)
LTP: starting 5_ITERATION_ioctl_loop05 (ioctl_loop05)

**Comment by xuyang0410** [comment]
Hi , can you provide your test's output and kernel version? Also,  which filesystem does your tmp directory use?

**Comment by priyama2** [comment]
kernel_version: sles15sp2 maintweb (4.12.14-122.83-default)
FS used: btrfs
[ioctl_loop5.log](https://github.com/linux-test-project/ltp/files/7089950/ioctl_loop5.log)

**Comment by xuyang0410** [comment]
I don't see any failure in ioctl_loop05.log. As you described, it only has some strange message in dmesg log and it doesn't affect anything.
