### ISSUE TITLE
prot_hsymlinks fail on read only remote machine

### ISSUE THREAD

**Issue by NgaHoang10** [linux-test-project/ltp#88]
2016-08-26T12:07:51 Test: prot_hsymlinks Testparm: prot_hsymlinks
useradd: cannot lock /etc/passwd; try again later.
userdel: user 'hsym' does not exist
prot_hsymlinks    1  TBROK  :  prot_hsymlinks.c:320: Failed to run cmd: useradd hsym
prot_hsymlinks    2  TBROK  :  prot_hsymlinks.c:320: Remaining cases broken
prot_hsymlinks    3  TBROK  :  prot_hsymlinks.c:320: Failed to run cmd: userdel -r hsym
prot_hsymlinks    4  TBROK  :  tst_sig.c:233: unexpected signal SIGIOT/SIGABRT(6) received (pid = 24146).
prot_hsymlinks    5  TBROK  :  tst_sig.c:233: unexpected signal SIGIOT/SIGABRT(6) received (pid = 24146)
......
I run tests on read-only remote machine #87  
I think it should return 32 test not supported in case of read-only file system

**Comment by metan-ucw** [comment]
Hmm, this one would be hard to fix. The test only executes ```useradd``` and ```userdel``` it would be hard to tell that they failed because of read-only mounted ```/etc/``` or something completely different.

**Comment by NgaHoang10** [comment]
Thank you...You're right. What do you think if we add some code to check if the system is read-only or not. If yes return 32.

**Comment by metan-ucw** [comment]
Feel free to send a pull request if you have solved this problem meanwhile.
