### ISSUE TITLE
Write test for futex_waitv()

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#880]
https://lwn.net/Articles/866112/
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=595b28fb0c8949463d8ec1e485f36d17c870ddb2

There are some selftests but I haven't checked if the coverage is sufficient.

**Comment by acerv** [comment]
Maybe it's a bit straight forward as a suggestion, but why not bringing Linux kernel selftests inside LTP?
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests/futex

**Comment by kamiccolo** [comment]
> Maybe it's a bit straight forward as a suggestion, but why not bringing Linux kernel selftests inside LTP? https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests/futex

I'm not so sure, how well could we manage different kernel versions with "integrated kselftests"? From the looks, it seems that we would need to rewrite those anyways adding "tst_kvercmp()" there and there. Please correct me if I'm wrong.

**Comment by metan-ucw** [comment]
There are many other problems in there, apart from the missing check for the syscall existence. These tests are written so that they are all executed by a single script, there is no proper result reporting etc. Also most of these tests should be already present in LTP, since the original futex tests the selftest are based on have been part of the LTP for years. And as these tests were rewritten and cleaned up there is no reason to do verbatim copy to LTP at all. We only need to implement LTP test for the recent additions that are not covered by LTP yet.

**Comment by acerv** [comment]
futex_waitv tests have been added inside LTP, so the ticket can be cosed
