### ISSUE TITLE
Why  aio_error3-1 UNTESTED

### ISSUE THREAD

**Issue by luyuantaolll** [linux-test-project/ltp#883]
Example in：open_posix_testsuite/conformance/interfaces/aio_error/3-1.c
testcase said that : aio_error() may fail if:[EINVAL] The aiocbp argument does not refer to an asynchronous
But aio_error(&aiocb)    return  zero

**Comment by metan-ucw** [comment]
Well it's exactly as the test reported 'may fail' means optional behavior in POSIX spec, so the test reports that the optional functionality does not seem to be implemented.

Generally Linux usually does not implement anything that is optional in POSIX while BSDs usually implement most of the optional behavior.

**Comment by luyuantaolll** [comment]
Thank you. I checked AIO_ Error source code does not seem to realize this function
