### ISSUE TITLE
LTP on 32 bit Linux

### ISSUE THREAD

**Issue by Ankita-020696** [linux-test-project/ltp#894]
Hi,
Can LTP be executed on 32 bit LINUX or is it specific to 64 bit?

Thanks

**Comment by richiejp** [comment]
Yes, it can be ran on 32-bit linux or 32-bit compat mode (-m32).

**Comment by pevik** [comment]
@Ankita-020696 https://github.com/linux-test-project/ltp/blob/master/INSTALL#L168

You can also use build script, which supports also 32bit compilation
https://github.com/linux-test-project/ltp/blob/master/build.sh
