### ISSUE TITLE
the  **__COARSE testcase of clock_gettime04 fail

### ISSUE THREAD

**Issue by jiaoff** [linux-test-project/ltp#898]
TFAIL: CLOCK_MONOTONIC_COARSE(vDSO with old kernel spec): Difference between successive readings greater than 5 ms (2): 10
 TFAIL: CLOCK_REALTIME_COARSE(vDSO with old kernel spec): Difference between successive readings greater than 5 ms (2): 10

**Comment by wangli5665** [comment]
https://lists.linux.it/pipermail/ltp/2022-March/028389.html
