### ISSUE TITLE
 Whether we still need tcon_msg member in tst_test struct

### ISSUE THREAD

**Issue by xuyang0410** [linux-test-project/ltp#900]
If we set this member, then case will not run and it onlys compile. I don't see any case use this.  It seems we can delete this member. Any idea?

**Comment by metan-ucw** [comment]
It's set by the TST_TEST_TCONF() macro that is usually used in tests as:

```
#ifdef FOO_H
#include <foo.h>

// test is implemented here

#else
TST_TEST_TCONF("foo library was missing during compilation");
#endif
```
