### ISSUE TITLE
How long does runLTP complete test usually take? 

### ISSUE THREAD

**Issue by Vvooi** [linux-test-project/ltp#902]
How long does runLTP complete test usually take? I have not finished the test for fourteen hours, and the computer is still very stuck. Do you usually run the arm board test to complete

**Comment by pevik** [comment]
New tests have 5 min timeout, maybe tests not yet rewritten to new API can run longer.
And yes, people test LTP on arm boards as well.

**Comment by metan-ucw** [comment]
That is really hard to answer as it depends on the particular machine quite a lot.

If you run just runltp it will execute default scenario that runs 32 different groups (runtest files) of tests. Different groups are different in size so the runtime per group does vary a lot as well. And of course if you have a buggy kernel the testrun will crash the machine.

Generally it's better to run the tests in smaller chunks and there are also better options available for executing the tests than the dated runltp script. We do have a prototype for a [runltp-ng](https://github.com/metan-ucw/runltp-ng) that is designed to control small board from a different computer and reboot it if it gets stuck. And there are other more sophisticated solutions such as [fuego](http://fuegotest.org/) or [lava](https://docs.lavasoftware.org/lava/index.html).

**Comment by pevik** [comment]
Ah, I was talking about timeout for single test, But you probably talk about runtest file.

**Comment by theken111** [comment]
i ran all suites, take about more than 8 h, and some cases missing.
