### ISSUE TITLE
Write test for process_madvise

### ISSUE THREAD

**Issue by acerv** [linux-test-project/ltp#909]
process_madvise syscall is not yet tested in the cma testing suite.
Please check https://lwn.net/Articles/789153/

**Comment by acerv** [comment]
I take care of this one

**Comment by coolgw** [comment]
@acerv  one year pass now, what's the plan ? : )

**Comment by acerv** [comment]
Hi @coolgw , there's a patch already, but it's unfinished. I had many other things to do in the meanwhile and I didn't have occasion to finish it
