### ISSUE TITLE
How to analyze the failed items in the report

### ISSUE THREAD

**Issue by Vvooi** [linux-test-project/ltp#914]
Are there any steps to learn how to analyze the error items in the report

**Comment by metan-ucw** [comment]
Do you mean how to figure out why test have failed?

For that I would say that you should first understand what the failing test is doing then pinpointing out the reasons for the failure based on that.

**Comment by Vvooi** [comment]
> 

accept02.c:55: TBROK: setsockopt(7, 0, 42, 0xfff043cf78, 136) failed: ENODEV (19)
failed: ENODEV (19)

What does this mean? I think it's no such device.

SAFE_SETSOCKOPT(server_sockfd,SOL_IP,MCAST_JOIN_GROUP,mc_group,mc_group_len);

How to look to know what kind of equipment it is?

**Comment by Vvooi** [comment]
> 你的英文是如何了解测试失败的原因？
> 
> 为此，我会说您应该先了解失败的测试在做什么，然后根据这次确定失败的原因。

accept02.c:55：TBROK：setsockopt（7、0、42、0xfff043cf78、136）失败：ENODEV（19）
失败：ENODEV（19）

这是什么意思？我认为他的意思是没有这样的设备

SAFE_SETSOCKOPT(server_sockfd,SOL_IP,MCAST_JOIN_GROUP,mc_group,mc_group_len);

怎么看才知道是什么设备？

**Comment by metan-ucw** [comment]
Looks like something is wrong with multicast on the machine, no idea why it does not work though, you have to figure that out yourself.

Also please stick to English.

**Comment by Vvooi** [comment]
Is it possible that my device does not support multicast

**Comment by Vvooi** [comment]
> Is it possible that my device does not support multicast

Is it possible that my device does not support multicast

**Comment by Vvooi** [comment]
> Looks like something is wrong with multicast on the machine, no idea why it does not work though, you have to figure that out yourself.
> 
> Also please stick to English.

Is it possible that my device does not support multicast
