### ISSUE TITLE
Crash on pty07 test

### ISSUE THREAD

**Issue by NoahLovesLife** [linux-test-project/ltp#930]
Crashed on pty07 test using ssh.
What is "pty07" doing?

**Comment by metan-ucw** [comment]
Each test has it's description in a form of a comment at the start of the tests source, see:

https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/pty/pty07.c

**Comment by NoahLovesLife** [comment]
Thanks a lot. Problem solved after patching.
