### ISSUE TITLE
PCI: The 12th tpci test case crashed

### ISSUE THREAD

**Issue by NoahLovesLife** [linux-test-project/ltp#931]
I'm using the latest LTP. 
Crashed when `test_pci 203 TPASS :  PCI bus 01 slot 00 : Test-case '11'`
I think there's a panic when running `Test-case '12' `
I've checked the `ltp_tpci.c`, and it seems all right. Any help?

**Comment by metan-ucw** [comment]
No idea what happened. Try logging the kernel messages to a serial console, without kernel log who knows what happened...

**Comment by metan-ucw** [comment]
Feel free to reopen with any additional information.
