### ISSUE TITLE
Building and installing selective testcases

### ISSUE THREAD

**Issue by vj-kumar** [linux-test-project/ltp#936]
Wondering if there a way to build and install selective testcases in ltp?

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp#shortcut-to-running-a-single-test

**Comment by vj-kumar** [comment]
> https://github.com/linux-test-project/ltp#shortcut-to-running-a-single-test

Yes. Thanks. I guess there is no current provision to select a group of tests and build them. We might have to cd to the directory and build them for each of the tests in the group.

**Comment by pevik** [comment]
You could also go to `testcases/` directory and make one of these directories. But that's just the cd variant. If you want to improve build system, please consider writing concrete proposal to our mailing list https://lists.linux.it/listinfo/ltp.

**Comment by metan-ucw** [comment]
Let's close this now, we have a workaround that kind of works for this case.
