### ISSUE TITLE
Need to debug network testcase failure issue

### ISSUE THREAD

**Issue by SamirMulani** [linux-test-project/ltp#937]
The following network-related test cases are failed
**Platform:** SUSE
**command used:** Under /opt/ltp
-> ./runltp -f net.features

1. sctp01                                             FAIL       1    

Error: sctp01 2 TFAIL: performance result is -342% < threshold -200%

2. sctp01_ipv6                                        FAIL       1  

Error: sctp01 1 TFAIL: performance result is -1887% < threshold -200%
Error: sctp01 2 TFAIL: performance result is -347% < threshold -200%

3. macsec01                                           FAIL       1    

macsec01 1 TFAIL: performance result is -309% < threshold -100%
macsec01 1 TFAIL: performance result is -315% < threshold -100%
macsec01 1 TFAIL: performance result is -298% < threshold -100%
macsec01 1 TFAIL: performance result is -309% < threshold -100%
macsec01 1 TFAIL: performance result is -288% < threshold -100%
macsec01 1 TFAIL: performance result is -301% < threshold -100%

 Following is a common observation for all three test cases:

macsec01 2 TINFO: AppArmor enabled, this may affect test results
macsec01 2 TINFO: it can be disabled with TST_DISABLE_APPARMOR=1 (requires super/root)
macsec01 2 TINFO: loaded AppArmor profiles: none

Is it correct that to pass the above three test cases, AppArmor needs to be disabled? 
There are a few error logs observed in AppArmor logs when the above three test cases are run,
/org/opensuse/Network/Interface/252.getManagedObjects failed. Server responds:
May 23 06:42:31 localhost wickedd-nanny[824]: org.freedesktop.DBus.Error.UnknownMethod: Method "GetManagedObjects" with signature "" on interface "org.freedesktop.DBus.ObjectManager" doesn't exist

**Comment by pevik** [comment]
No, in this case it's really not about AppArmor, dbus error is also unrelated. Unfortunately `net.features` are performance tests, thus they can fail. We should rewrite them to be just functional tests.
@akodanev FYI

**Comment by SamirMulani** [comment]
@pevik Thank you for the clarification.
