### ISSUE TITLE
Why are these threads in D state？

### ISSUE THREAD

**Issue by haidong-yao** [linux-test-project/ltp#938]
./runltp -c 2 -i 200

  the thread  1458  is D.

root        1444  0.0  0.0   2644   544 ttyS2    S    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --cpu 2
root        1445  0.0  0.0   2644   512 ttyS2    S    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1451  0.0  0.0   2644   240 ttyS2    S    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1452  0.0  0.0   2644    88 ttyS2    S    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --cpu 2
**root        1454  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200**
root        1455 99.8  0.0   2644    88 ttyS2    R    19:03  19:21 /ota/ltp20220121/opt/ltp/testcases/bin/genload --cpu 2
**root        1456  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200**
root        1457 99.8  0.0   2644    88 ttyS2    R    19:03  19:21 /ota/ltp20220121/opt/ltp/testcases/bin/genload --cpu 2
**root        1458  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1459  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1460  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1461  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1462  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1463  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1464  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1465  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1466  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1467  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1469  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1470  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1471  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1472  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1473  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1474  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1475  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1476  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200
root        1477  0.0  0.0   2644    88 ttyS2    D    19:03   0:00 /ota/ltp20220121/opt/ltp/testcases/bin/genload --io 200**
.......

**Comment by metan-ucw** [comment]
Because they are waiting for I/O. It's normal to have processes in D state when there is heavy I/O happening.
