### ISSUE TITLE
Need to understand how to debug LTP projects.

### ISSUE THREAD

**Issue by SamirMulani** [linux-test-project/ltp#942]
I am trying to understand the below command implementation. Can anyone explain how i can debug any command?
What is the preferred tool for debugging ?

**Ex: ->** ./runltp -f net.features

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp#running-tests
https://github.com/linux-test-project/ltp/wiki/Test-Writing-Guidelines#51-runtest-files

You can read even more in depth info in
https://github.com/linux-test-project/ltp/wiki/C-Test-Case-Tutorial
https://github.com/linux-test-project/ltp/wiki/C-Test-API
https://github.com/linux-test-project/ltp/wiki/Shell-Test-API
