### ISSUE TITLE
64 bit syscalls tests

### ISSUE THREAD

**Issue by Ankita-020696** [linux-test-project/ltp#943]
Hi,
Are there any syscalls tests specific to only 64 bit Linux or all tests are generic(works for both 32/64 bit)?

Thanks

**Comment by metan-ucw** [comment]
That actually depends on for which architecture LTP is compiled. If you compile LTP for example on 32bit PC i.e. x86 the testcases are testing 32bit ABI, and if you, for example, compile it on 64bit PC i.e. x86_64 you are testing 64bit ABI.

You can also compile LTP for 32bit ABI on a 64bit architecture in cases where it's supported and this is actually used to test the kernel 32bit compat layer. You can do that with passing -m32 in both 'CFLAGS' and 'LDFLAGS' to the 'configure' script.
