### ISSUE TITLE
Syntax error observed in tracing module

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#952]
syntax error on /opt/ltp/testcases/bin/ftrace_lib.sh: Syntax error: "(" unexpected (expecting "}").
Please remove the “(“ and “)” on line no. 63 which is fixing the issue and passes below cases now.

ftrace_regression01
ftrace_regression02
ftrace-stress-test

**Comment by pevik** [comment]
Thanks for your report, I'll fix it. Could you please post here your name and email address, so that I can add your tag to git commit: `Suggested-by: Your Name <your@email>` ?

**Comment by anilbp** [comment]
Name: Anilkumar
Mail id : ***@***.***

Regards,
Anilkumar

**Comment by pevik** [comment]
@anilbp I need a real address, not `***@***.***`. Could you please write me mail to my suse address shown at https://github.com/pevik/ltp/commit/7396e89f824f12ee177acf2004aba48b91b266b3 ? I'll add that mail to git commit. Otherwise I'll merge it without your `Suggested-by:` tag.
