### ISSUE TITLE
syscall/statx04: statx04.c:86: TBROK: Unexpected ioctl() error: EINVAL (22)

### ISSUE THREAD

**Issue by pragat220** [linux-test-project/ltp#956]
DISTRIB_RELEASE=22.04
OS : Ubuntu 22.04
Kernel : Linux intel 5.19.0-rc6-
LTP Version : 20220527-191-gf42f6f3b4

Command: # ./runltp -f syscalls

<<<test_start>>>
tag=statx04 stime=1659728923
cmdline="statx04"
contacts=""
analysis=exit
<<<test_output>>>
tst_device.c:89: TINFO: Found free device 8 '/dev/loop8'
tst_test.c:1526: TINFO: Timeout per run is 0h 00m 30s
tst_supported_fs_types.c:89: TINFO: Kernel supports ext2
tst_supported_fs_types.c:51: TINFO: mkfs.ext2 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports ext3
tst_supported_fs_types.c:51: TINFO: mkfs.ext3 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports ext4
tst_supported_fs_types.c:51: TINFO: mkfs.ext4 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports xfs
tst_supported_fs_types.c:47: TINFO: mkfs.xfs does not exist
tst_supported_fs_types.c:89: TINFO: Kernel supports btrfs
tst_supported_fs_types.c:47: TINFO: mkfs.btrfs does not exist
tst_supported_fs_types.c:89: TINFO: Kernel supports vfat
tst_supported_fs_types.c:51: TINFO: mkfs.vfat does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports exfat
tst_supported_fs_types.c:47: TINFO: mkfs.exfat does not exist
tst_supported_fs_types.c:89: TINFO: Kernel supports ntfs
tst_supported_fs_types.c:51: TINFO: mkfs.ntfs does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports tmpfs
tst_supported_fs_types.c:38: TINFO: mkfs is not needed for tmpfs
tst_test.c:1599: TINFO: Testing on ext2
tst_test.c:1064: TINFO: Formatting /dev/loop8 with ext2 opts='' extra opts=''
mke2fs 1.46.5 (30-Dec-2021)
statx04.c:112: TPASS: STATX_ATTR_COMPRESSED is supported
statx04.c:112: TPASS: STATX_ATTR_APPEND is supported
statx04.c:112: TPASS: STATX_ATTR_IMMUTABLE is supported
statx04.c:112: TPASS: STATX_ATTR_NODUMP is supported
tst_test.c:1599: TINFO: Testing on ext3
tst_test.c:1064: TINFO: Formatting /dev/loop8 with ext3 opts='' extra opts=''
mke2fs 1.46.5 (30-Dec-2021)
statx04.c:112: TPASS: STATX_ATTR_COMPRESSED is supported
statx04.c:112: TPASS: STATX_ATTR_APPEND is supported
statx04.c:112: TPASS: STATX_ATTR_IMMUTABLE is supported
statx04.c:112: TPASS: STATX_ATTR_NODUMP is supported
tst_test.c:1599: TINFO: Testing on ext4
tst_test.c:1064: TINFO: Formatting /dev/loop8 with ext4 opts='' extra opts=''
mke2fs 1.46.5 (30-Dec-2021)
statx04.c:112: TPASS: STATX_ATTR_COMPRESSED is supported
statx04.c:112: TPASS: STATX_ATTR_APPEND is supported
statx04.c:112: TPASS: STATX_ATTR_IMMUTABLE is supported
statx04.c:112: TPASS: STATX_ATTR_NODUMP is supported
tst_test.c:1599: TINFO: Testing on vfat
tst_test.c:1064: TINFO: Formatting /dev/loop8 with vfat opts='' extra opts=''
statx04.c:83: TCONF: Inode attributes not supported: ENOTTY (25)
tst_test.c:1599: TINFO: Testing on ntfs
tst_test.c:1064: TINFO: Formatting /dev/loop8 with ntfs opts='' extra opts=''
The partition start sector was not specified for /dev/loop8 and it could not be obtained automatically.  It has been set to 0.
The number of sectors per track was not specified for /dev/loop8 and it could not be obtained automatically.  It has been set to 0.
The number of heads was not specified for /dev/loop8 and it could not be obtained automatically.  It has been set to 0.
To boot from a device, Windows needs the 'partition start sector', the 'sectors per track' and the 'number of heads' to be set.
Windows will not be able to boot from this device.
tst_test.c:1078: TINFO: Trying FUSE...
statx04.c:86: TBROK: Unexpected ioctl() error: EINVAL (22)

Summary:
passed   12
failed   0
broken   1
skipped  1
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=2 termination_type=exited termination_id=2 corefile=no
cutime=2 cstime=49
<<<test_end>>>

**Comment by xuyang0410** [comment]
I guess we can skip the ntfs filesystem,  then try again

**Comment by pevik** [comment]
Well, fuse has been skipped in 4d30d7a2c:
`
tst_supported_fs_types.c:166: TINFO: Skipping FUSE based ntfs as requested by the test
`
@pragat220 are you sure you test the latest LTP version?

**Comment by pragat220** [comment]
yes always using latest version. Every time downloading as per below link
git clone https://github.com/linux-test-project/ltp.git

**Comment by pevik** [comment]
Hm, maybe we really need to add `ntfs` to `.skip_filesystems`. Could you please test it? I have 5.19.1-1-default, but I have ntfs via fuse, thus being skipped:
```
tst_supported_fs_types.c:119: TINFO: FUSE does support ntfs
tst_supported_fs_types.c:51: TINFO: mkfs.ntfs does exist
```

**Comment by pevik** [comment]
@pragat220 could you please put here your email and real name? I'd put it to `Reported-by:` to the patch which should fix it:
https://patchwork.ozlabs.org/project/ltp/patch/20220824080947.9414-1-akumar@suse.de/

**Comment by pevik** [comment]
I put some extra info to the patch: https://lore.kernel.org/ltp/Yxiwo%2FOtgISy0BGX@pevik/
Plan to merge after getting name and mail from @pragat220 (if he's reasonably fast) + add extra info to the commit message.

**Comment by pragat220** [comment]
> @pragat220 could you please put here your email and real name? I'd put it to `Reported-by:` to the patch which should fix it: https://patchwork.ozlabs.org/project/ltp/patch/20220824080947.9414-1-akumar@suse.de/

Name: Pragat Singh
Mail: pragat2006@gmail.com
