### ISSUE TITLE
tst_capability.c:12:10: fatal error: lapi/syscalls.h: No such file or directory

### ISSUE THREAD

**Issue by VincentLee-EN** [linux-test-project/ltp#958]
When I used the command "make" to complie, I got the error as follows:
make -C "lib" \
        -f "/home/liwenqiang/9p/ltp-master/lib/Makefile" all
make[1]: Entering directory '/home/liwenqiang/9p/ltp-master/lib'
tst_capability.c:12:10: fatal error: lapi/syscalls.h: No such file or directory
 #include "lapi/syscalls.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
../include/mk/rules.mk:15: recipe for target 'tst_capability.o' failed
make[1]: *** [tst_capability.o] Error 1
make[1]: Leaving directory '/home/liwenqiang/9p/ltp-master/lib'
Makefile:106: recipe for target 'lib-all' failed
make: *** [lib-all] Error 2

**Comment by metan-ucw** [comment]
If the `lapi/syscalls.h` is missing you haven't run `.configure` before compilation.

**Comment by VincentLee-EN** [comment]
Thanks.
The problem is solved, and the reason is that I didn't give the exec permmision to rtp-master
