### ISSUE TITLE
gcc version required for ltp

### ISSUE THREAD

**Issue by Ankita-020696** [linux-test-project/ltp#959]
Hi,
I am getting below error after using make command, what could be the reason?

> make -C "lib" \        -f "/home/root/ltp/lib/Makefile" all
> make[1]: Entering directory '/home/root/ltp/lib'
> AR libltp.a
> RANLIB libltp.a
> /mnt/usr/bin/../lib/gcc/riscv64-oe-linux/8.3.0/../../../../riscv64-oe-linux/bin/ld: cannot find -lltp
> collect2: error: ld returned 1 exit status
> make[2]: *** [../../include/mk/rules.mk:29: test01] Error 1
> make[1]: *** [../include/mk/generic_trunk_target.inc:105: all] Error 2
> make[1]: Leaving directory '/home/root/ltp/lib'
> make: *** [Makefile:104: lib-all] Error 2

can LTP be used with gcc 8.3.0? 

Thanks

**Comment by pevik** [comment]
Definitely :). I suppose you compiled it properly:
https://github.com/linux-test-project/ltp#quick-guide-to-running-the-tests
make autotools && ./configure && make -j`nproc`

Could you pass `V=1` to make (i.e. `make -j`nproc V=1`) so that we know what is the problem?

**Comment by metan-ucw** [comment]
LTP should work with variety of gcc versions. This snippet looks wrong, almost as if something tried to link against libltp.a before it was created, but the snippet is too short to really tell anything about the error and you also haven't included exact steps how LTP was compiled, which LTP version are you using etc. so no idea what went wrong.

**Comment by metan-ucw** [comment]
I guess that the question was answered, let's close this now.
