### ISSUE TITLE
[LTP][Smoketest][macsec02]:  1 TFAIL: performance result is -118% < threshold -100% macsec02 1 TFAIL: performance result is -112% < threshold -100%

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#961]
Title:
------- 
macsec02 1 TFAIL: performance result is -118% < threshold -100% macsec02 1 TFAIL: performance result is -112% < threshold -100%

Description: 
--------------
Smoketest module -> macsec02 test case is failing due to threshold 

Config Details:
-----------------

	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 
        GNU/Linux

Steps to reproduce:
----------------------
1. Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
2. Run ./runltp -f <modulename> in /opt/ltp path

Host logs:
-------------
tag=macsec02 stime=1661159202
cmdline="macsec02.sh"
contacts=""
analysis=exit
<<<test_output>>>
macsec02 1 TINFO: initialize 'lhost' 'ltp_ns_veth2' interface
macsec02 1 TINFO: add local addr 10.0.0.2/24
macsec02 1 TINFO: add local addr fd00:1:1:1::2/64
macsec02 1 TINFO: initialize 'rhost' 'ltp_ns_veth1' interface
macsec02 1 TINFO: add remote addr 10.0.0.1/24
macsec02 1 TINFO: add remote addr fd00:1:1:1::1/64
macsec02 1 TINFO: Network config (local -- remote):
macsec02 1 TINFO: ltp_ns_veth2 -- ltp_ns_veth1
macsec02 1 TINFO: 10.0.0.2/24 -- 10.0.0.1/24
macsec02 1 TINFO: fd00:1:1:1::2/64 -- fd00:1:1:1::1/64
macsec02 1 TINFO: timeout per run is 0h 5m 0s
macsec02 1 TINFO: setup IPsec transport/esp_aead des3_ede
macsec02 1 TINFO: setup local macsec with 'icvlen 16 encodingsa 0 replay on window 300 encrypt on protect on'
macsec02 1 TINFO: setup rhost macsec with 'icvlen 16 encodingsa 0 replay on window 300 encrypt on protect on'
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H 10.23.0.1 -n 100 -N 100 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv4' 5 times
macsec02 1 TPASS: netstress passed, median time 362 ms, data: 359 361 362 367 365
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H fd00:23::1 -n 100 -N 100 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv6' 5 times
macsec02 1 TPASS: netstress passed, median time 359 ms, data: 366 379 353 359 357
macsec02 1 TINFO: run server 'netstress -D ltp_ns_veth1 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -H 10.0.0.1 -n 100 -N 100 -D ltp_ns_veth2 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_lan' 5 times
macsec02 1 TPASS: netstress passed, median time 290 ms, data: 1311 290 292 283 286
macsec02 1 TINFO: time lan IPv4(290) macsec IPv4(362) and IPv6(359) ms
macsec02 1 TPASS: performance result is -24%, in range [-100:]%
macsec02 1 TPASS: performance result is -23%, in range [-100:]%
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H 10.23.0.1 -n 1000 -N 1000 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv4' 5 times
macsec02 1 TPASS: netstress passed, median time 741 ms, data: 754 736 752 695 741
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H fd00:23::1 -n 1000 -N 1000 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv6' 5 times
macsec02 1 TPASS: netstress passed, median time 738 ms, data: 738 789 738 715 735
macsec02 1 TINFO: run server 'netstress -D ltp_ns_veth1 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -H 10.0.0.1 -n 1000 -N 1000 -D ltp_ns_veth2 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_lan' 5 times
macsec02 1 TPASS: netstress passed, median time 286 ms, data: 285 286 286 289 290
macsec02 1 TINFO: time lan IPv4(286) macsec IPv4(741) and IPv6(738) ms
macsec02 1 TFAIL: performance result is -159% < threshold -100%
macsec02 1 TFAIL: performance result is -158% < threshold -100%
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H 10.23.0.1 -n 2000 -N 2000 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv4' 5 times
macsec02 1 TPASS: netstress passed, median time 1835 ms, data: 1805 1835 1841 1822 1843
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H fd00:23::1 -n 2000 -N 2000 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv6' 5 times
macsec02 1 TPASS: netstress passed, median time 1862 ms, data: 1869 1862 1821 1848 1868
macsec02 1 TINFO: run server 'netstress -D ltp_ns_veth1 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -H 10.0.0.1 -n 2000 -N 2000 -D ltp_ns_veth2 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_lan' 5 times
macsec02 1 TPASS: netstress passed, median time 532 ms, data: 547 532 532 531 537
macsec02 1 TINFO: time lan IPv4(532) macsec IPv4(1835) and IPv6(1862) ms
macsec02 1 TFAIL: performance result is -244% < threshold -100%
macsec02 1 TFAIL: performance result is -250% < threshold -100%
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H 10.23.0.1 -n 1650 -N 1650 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv4' 5 times
macsec02 1 TPASS: netstress passed, median time 1681 ms, data: 1700 1681 1671 1696 1662
macsec02 1 TINFO: run server 'netstress -D ltp_v0 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -D ltp_v0 -H fd00:23::1 -n 1650 -N 1650 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_ipv6' 5 times
macsec02 1 TPASS: netstress passed, median time 1702 ms, data: 1702 1719 1711 1698 1684
macsec02 1 TINFO: run server 'netstress -D ltp_ns_veth1 -R 500000 -B /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M'
macsec02 1 TINFO: run client 'netstress -l -H 10.0.0.1 -n 1650 -N 1650 -D ltp_ns_veth2 -a 2 -r 2000 -d /tmp/ltp-ooSodfVwF8/LTP_macsec02.KQ0Xw3Jj9M/res_lan' 5 times
macsec02 1 TPASS: netstress passed, median time 538 ms, data: 547 539 536 538 524
macsec02 1 TINFO: time lan IPv4(538) macsec IPv4(1681) and IPv6(1702) ms
macsec02 1 TFAIL: performance result is -212% < threshold -100%
macsec02 1 TFAIL: performance result is -216% < threshold -100%
macsec02 2 TINFO: cleanup virtual interfaces...
macsec02 2 TINFO: AppArmor enabled, this may affect test results
macsec02 2 TINFO: it can be disabled with TST_DISABLE_APPARMOR=1 (requires super/root)
macsec02 2 TINFO: loaded AppArmor profiles: none

Summary:
passed   14
failed   6
broken   0
skipped  0
warnings 0
incrementing stop
<<<execution_status>>>
initiation_status="ok"
duration=69 termination_type=exited termination_id=1 corefile=no
cutime=218 cstime=6907
<<<test_end>>>
INFO: ltp-pan reported some tests FAIL
LTP Version: 20220527-206-gcb4e7e453
------------------------------------------------------------------------------------------------------------

Name: Anilkumar
Mail id : anilkumar@intel@intel.com

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp/issues/964#issuecomment-1225472726
