### ISSUE TITLE
[LTP][tpm_tools​]: All tpm_tool test cases got failed with 5.19 kernel

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#962]
Title:  [LTP][tpm_tools​]: All tpm_tool test cases got failed with 5.19 kernel

Description:
--------------
 Below are the tpm_tools test cases got failed

1. tpm01
2. tpm02
3. tpm03
4. tpm04
5. tpm05
6. tpm06
7. tpmtoken01
8. tpmtoken02
9. tpmtoken03
10. tpmtoken04
11. tpmtoken05
12. tpm07 

tpm_version    0  TINFO  :  INIT: Inititalizing tests.
tpm_version    1  TBROK  :  ltpapicmd.c:133: Test: tpm_version command does not exist. Reason:
tpm_version    2  TBROK  :  ltpapicmd.c:133: Remaining cases broken

tpmtoken_init    0  TINFO  :  INIT: Inititalizing tests.
tpmtoken_init    1  TBROK  :  ltpapicmd.c:133: Setup: tpmtoken_init command does not exist. Reason:
tpmtoken_init    2  TBROK  :  ltpapicmd.c:133: Remaining cases broken

tpm_clear    0  TINFO  :  INIT: Inititalizing tests.
tpm_clear    1  TBROK  :  ltpapicmd.c:133: Setup: tpm_clear command does not exist. Reason:
tpm_clear    2  TBROK  :  ltpapicmd.c:133: Remaining cases broken

Config Details:
-------------------
	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
----------------------
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
------------
[tpm_tools.txt](https://github.com/linux-test-project/ltp/files/9412718/tpm_tools.txt)
---------------------------------------------------------------------------------------------------------------------------------

Name: Anilkumar
Mail id : anilkumar@[intel@intel.com](mailto:intel@intel.com)

**Comment by pevik** [comment]
`Test: tpm_version command does not exist.` means you're missing a tpm-tools package. Also TPM tests are broken and outdated, it should be rewritten (out of the scope of current LTP team) or removed.
https://github.com/linux-test-project/ltp/issues/964#issuecomment-1225472726
