### ISSUE TITLE
[LTP][s390x_tests][vmcp] : initiation_status="pan(859369): execvp of 'vmcp_m.sh' (tag vmcp) failed.  errno:2  No such file or directory"

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#963]
Title: initiation_status="pan(859369): execvp of 'vmcp_m.sh' (tag vmcp) failed.  errno:2  No such file or directory"
-----
Description: [s390x_tests][vmcp] is failed due to vmcp_m.sh file missing
-------------

Config Details:
-----------------
	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
---------------------
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
------------
[s390x_tests.txt](https://github.com/linux-test-project/ltp/files/9412747/s390x_tests.txt)
===============================================================================

Name: Anilkumar
Mail id : anilkumar@intel.com

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp/issues/964#issuecomment-1225472726
