### ISSUE TITLE
[LTP][net.tirpc_tests]: rpc_test 1 TCONF: 'rpcinfo' not found

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#964]
Title: [LTP][net.tirpc_tests]: rpc_test 1 TCONF: 'rpcinfo' not found

Description: net.tirpc_tests below test cases got failed due to rpcinfo not found

1. tirpc_rpcb_rmtcall   
2. tirpc_rpc_broadcast  
3. tirpc_rpc_broadcast_exp 

Config Details:

	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
[net.tirpc_tests.txt](https://github.com/linux-test-project/ltp/files/9412806/net.tirpc_tests.txt)

Name: Anilkumar
Mail id : [anilkumar@intel.com](mailto:anilkumar@intel.com)

**Comment by pevik** [comment]
Well, "'rpcinfo' not found" is quite obvious, you need to install it. Please stop reporting useless reports like this, issues on github are meant to report bugs in tests, not a support forum to explain why some test fail on your kernel/distro. Even you find a bug (not this case) you should report it to Linux distro you're testing not to us.
