### ISSUE TITLE
[LTP][net_stress.appl] : dns-stress 1 TCONF: 'named' not found

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#965]
Title:  [LTP][net_stress.appl] : dns-stress 1 TCONF: 'named' not found

Description: net_stress.appl module below test cases got failed due to named not found

1. dns4-stress  
2. dns6-stress

Config Details:

	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
[net_stress.appl.txt](https://github.com/linux-test-project/ltp/files/9412824/net_stress.appl.txt)

Name: Anilkumar
Mail id : [anilkumar@intel.com](mailto:anilkumar@intel.com)

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp/issues/964#issuecomment-1225472726
