### ISSUE TITLE
[LTP][net.sctp][test_1_to_1_connectx] : test_1_to_1_connectx.c    3  TBROK  :  test_1_to_1_connectx.c:140: sctp_connectx with invalid address error:-1, errno:110

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#966]
Title: [LTP][net.sctp][test_1_to_1_connectx] : test_1_to_1_connectx.c    3  TBROK  :  test_1_to_1_connectx.c:140: sctp_connectx with invalid address error:-1, errno:110

Description: net.sctp ---> test_1_to_1_connectx is failed due to below reason
test_1_to_1_connectx.c    3  TBROK  :  test_1_to_1_connectx.c:140: sctp_connectx with invalid address error:-1, errno:110
test_1_to_1_connectx.c    4  TBROK  :  test_1_to_1_connectx.c:140: Remaining cases broken

Config Details:

	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
[net.sctp.txt](https://github.com/linux-test-project/ltp/files/9412848/net.sctp.txt)

Name: Anilkumar
Mail id : [anilkumar@intel.com](mailto:anilkumar@intel.com)

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp/issues/964#issuecomment-1225472726
