### ISSUE TITLE
[LTP][net.rpc_tests] : rpc_test 1 TCONF: 'rpcinfo' not found

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#967]
Title: [LTP][net.rpc_tests] : rpc_test 1 TCONF: 'rpcinfo' not found

Description: net.rpc_tests module below test cases got failed due to rpcinfo not found

1. rpc_pmap_rmtcall 
2. rpc_clnt_broadcast 
3. rpc_svc_destroy   
4. rpc_svcfd_create  
5. rpc_xprt_register
6. rpc_xprt_unregister   

Config Details:

	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
[net.rpc_tests.txt](https://github.com/linux-test-project/ltp/files/9412886/net.rpc_tests.txt)

Name: Anilkumar
Mail id : [anilkumar@intel.com](mailto:anilkumar@intel.com)

**Comment by pevik** [comment]
https://github.com/linux-test-project/ltp/issues/964#issuecomment-1225472726
