### ISSUE TITLE
[LTP][net.features] : TFAIL: performance result is -352% < threshold -200%

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#968]
Title: [LTP][net.features] : TFAIL: performance result is -352% < threshold -200%

Description: net.features module below test cases got failed due to threshold issue

1. sctp01 -- sctp01 2 TFAIL: performance result is -352% < threshold -200%
2. sctp01_ipv6  ---- sctp01 2 TFAIL: performance result is -6101% < threshold -200%
3. macsec02  ---- macsec02/03 1 TFAIL: performance result is -140% < threshold -100%
4. macsec03 ---- macsec02/03 1 TFAIL: performance result is -133% < threshold -100%

Config Details:

	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
[net.features.txt](https://github.com/linux-test-project/ltp/files/9412919/net.features.txt)

Name: Anilkumar
Mail id : [anilkumar@intel.com](mailto:anilkumar@intel.com)

**Comment by pevik** [comment]
Likely overbooked VM. These are performance tests, unfortunately we don't have just a functional tests of these.
https://github.com/linux-test-project/ltp/issues/964#issuecomment-1225472726
