### ISSUE TITLE
[LTP][controllers] : tst_cgroup.c:792: TBROK: 'rdma' controller is unknown to LTP cgroup_regression_test 7 TBROK: 'tst_cgctl require' exited

### ISSUE THREAD

**Issue by anilbp** [linux-test-project/ltp#969]
Title: tst_cgroup.c:792: TBROK: 'rdma' controller is unknown to LTP cgroup_regression_test 7 TBROK: 'tst_cgctl require' exited

Description: Controller module below test cases are getting failed 
-------------
       cgroup - tst_cgroup.c:792: TBROK: 'rdma' controller is unknown to LTP cgroup_regression_test 7 TBROK: 'tst_cgctl require' exited
       memcontrol04 - memcontrol04.c:214: TFAIL: Expect: (F low events=419) == 0
       cpuset_inherit - cpuset_inherit 1 TFAIL: Could not mount cgroup filesystem with  cpuset on /dev/cpuset..Exiting test
       cpuset_hotplug - cpuset_hotplug 1 TFAIL: Could not mount cgroup filesystem with  cpuset on /dev/cpuset..Exiting test
       cpuset_regression_test - cpuset_regression_test 1 TBROK: Both cpuset.cpu_exclusive and cpu_exclusive do not exist

Config Details:
-----------------
	DISTRIB_RELEASE=22.04
	DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
	PRETTY_NAME="Ubuntu 22.04 LTS"
	NAME="Ubuntu"
	VERSION_ID="22.04"
	VERSION="22.04 (Jammy Jellyfish)"
	VERSION_CODENAME=jammy
	ID=ubuntu
	uname: Linux ubuntu 5.19.0-rpl-ww35bkc #1 SMP PREEMPT_DYNAMIC Fri Aug 19 12:03:14 IST 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
-----------------------
Clone the LTP---> git clone https://github.com/linux-test-project/ltp.git
Run ./runltp -f in /opt/ltp path

Host logs:
------------
[controllers.log](https://github.com/linux-test-project/ltp/files/9493447/controllers.log)

Name: Anilkumar
Mail id : [anilkumar@intel.com](mailto:anilkumar@intel.com)

**Comment by pevik** [comment]
I'd expect bcb7caa2458866dbe6806faf04fae5bf51d8a203 would fix this, are you sure you tested it with this commit?

**Comment by xuyang0410** [comment]
Close this issue. If still have problem, please reopen it.
