### ISSUE TITLE
LTP tests support for riscv64

### ISSUE THREAD

**Issue by Ankita-020696** [linux-test-project/ltp#970]
Hi,
Does LTP's all tests are supprted on RISCV64 platform?

Thanks

**Comment by metan-ucw** [comment]
About 99% of the testcases should not depend on a platform at all, there are a few tests that are platform specific but these should be skipped automatically.

**Comment by pevik** [comment]
@Ankita-020696 FYI there is some riscv package for openSUSE, i.e. a proof that it can be compiled:
https://build.opensuse.org/package/binaries/benchmark:ltp:devel/ltp/openSUSE_Factory_RISCV

Also embedded distros (which all support riscv) have LTP
* Buildroot
http://autobuild.buildroot.net/stats/master.html
https://git.busybox.net/buildroot/tree/package/ltp-testsuite/ltp-testsuite.mk

* Yoctoo
https://git.openembedded.org/openembedded-core/tree/meta/recipes-extended/ltp/ltp_20220527.bb

Also note, the only arch dependency I remember is [`include/tst_atomic.h`](https://github.com/linux-test-project/ltp/blob/master/include/tst_atomic.h), but this was problematic only on very old toolchains used on very old architectures. Risc is obviously new enough to be OK
