### ISSUE TITLE
Gcov Branch test coverage can not reach 100%(Single line statement is considered branch)

### ISSUE THREAD

**Issue by MelInfacte** [linux-test-project/ltp#98]
when I worked on my test coverage project, an issue was occured.my program lists below:
/**********************************************************/
qtDrwDbus::qtDrwDbus()
{
    qRegisterMetaType<InfoStruct>("InfoStruct");
}
/**********************************************************/
Gcov was used to test coverage of this program,however,the "qRegisterMetaType<InfoStruct>("InfoStruct");" be considered as a branch,so that the branch test coverage rate was decreased.

Please help explain the reason of the problem and how to solve the problem !Thank you

**Comment by metan-ucw** [comment]
The gcov binary is part of gcc project, you have to contact them.
