### ISSUE TITLE
The presence of "emmintrin.h" shouldn't be used for x86 detection.

### ISSUE THREAD

**Issue by ilyakurdyukov** [linux-test-project/ltp#980]
testcases/cve/meltdown.c:
```c
#ifdef HAVE_EMMINTRIN_H
#include <emmintrin.h>
```
And below this `ifdef` is the assembly code for x86/x86_64.

But `emmintrin.h` may exist for some non-x86 platforms (such as e2k) as an emulation of Intel SIMD intrinsics. So there's a compilation error here.

**Comment by metan-ucw** [comment]
Good catch, I had quick look into gcc sources and it looks like there is emulation for Power ISA as well.

I guess that the code should be ifdefed with `#if defined(HAVE_EMMINTRIN_H) && (defined(__x86_64__) || defined(__i386__))`

Will you send a patch to the LTP mailing list?

**Comment by ilyakurdyukov** [comment]
Don't want to figure out how to send a patch to the mailing list. Please accept this pull request or submit it yourself (I don't care about the patch authorship).
