### ISSUE TITLE
tst_cgroup: cgroup mount hardcodes /tmp directory

### ISSUE THREAD

**Issue by edliaw** [linux-test-project/ltp#986]
https://github.com/linux-test-project/ltp/blob/4e824f9db0dd8b78a4013ed0281fb9686aadb2b8/lib/tst_cgroup.c#L293

This causes a problem for Android, where the `/tmp` directory isn't writeable.  Should it use `TMPDIR` instead (or some other environment variable)?

**Comment by pevik** [comment]
Yep, that's obviously wrong. Would you please send a patch, which uses `TMPDIR` env?
@richiejp @wangli5665  FYI (added here in 310da3784a232d76af13fd2c09e26e6d10a94224, but it was there before in 3b716981bd5422c256e1bdf76fe55c653bd460fa).

**Comment by edliaw** [comment]
Sent https://lists.linux.it/pipermail/ltp/2022-October/031496.html
