### ISSUE TITLE
The testcase  ”ltp/testcases/kernel/syscalls/ipc/shmctl/shmctl06.c“  is unreasonable

### ISSUE THREAD

**Issue by luyuantaolll** [linux-test-project/ltp#992]
Test requires structure shmid64_ ds has time_ High field, but it seems that this field is only available in__ BITS_ PER_ LONG != 64.
Now the system seems to define the long field as 64bit, Maybe we need to modify the test case to test different shmid64_ ds.
![1668482413280](https://user-images.githubusercontent.com/52696697/201818645-be7ef6c6-d91b-4ace-aaaf-99f7132be48e.png)

**Comment by metan-ucw** [comment]
The test is guarded by `HAVE_SHMID64_DS_TIME_HIGH` that is defined in the `include/lapi/shmbuf.h` only if `__BITS_PER_LONG != 64` so as far as I can tell everything is working as expected.
