### ISSUE TITLE
fs-bench case can`t be used

### ISSUE THREAD

**Issue by yumdeer** [linux-test-project/ltp#994]
ltp/testcases/kernel/fs/fs-bench/  cant be used ， ReadME is so old , the code is died, i cant run the new case.

**Comment by metan-ucw** [comment]
There is a lot of historical baggage in LTP, we are going over them slowly, keeping and fixing useful parts and removing the rest. Quick look a the fs-bench suggests that it's horribly broken and there does not seem to be a lot of value in keeping it.

@pevik what do you think, should we remove fs-bench?

**Comment by pevik** [comment]
@metan-ucw I don't see much value either. I'll send RFC patch to ML.

**Comment by pevik** [comment]
FYI patch sent:
https://patchwork.ozlabs.org/project/ltp/patch/20221123115546.786-1-pvorel@suse.cz/
https://lore.kernel.org/ltp/20221123115546.786-1-pvorel@suse.cz/
