### ISSUE TITLE
Am I running test properly?

### ISSUE THREAD

**Issue by lucky33newman** [linux-test-project/ltp#995]
Hello guys,

I am running LTP in qemu, it has been installed to /opt/ltp.

I wanna run all the tests under this path:

root@qemux86-64:/opt/ltp/testcases/realtime/func# pwd
/opt/ltp/testcases/realtime/func

I can see a lot of folders here:

root@qemux86-64:/opt/ltp/testcases/realtime/func# ls
async_handler  gtod_latency  hrtimer-prio  matrix_mult  measurement  periodic_cpu_load  pi-tests  pi_perf  prio-preempt  prio-wake  pthread_kill_latency  rt-migrate  sched_football  sched_jitter  sched_latency  thread_clock

I think they are tests, and I want to run them.

Now, I enter the folder, take an example:

root@qemux86-64:/opt/ltp/testcases/realtime/func/async_handler# ls
async_handler  async_handler_jk  async_handler_tsc  run_auto.sh

I can see run_auto.sh, so I run command:

sh ./run_auto.sh

Latter on the test began, so, the question is, am I running the tests properly? Can I call such tests from the 'runltp'?

Thanks.

**Comment by lucky33newman** [comment]
Thanks for helping. 👍

**Comment by pevik** [comment]
If you care about realtime, run https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git

**Comment by lucky33newman** [comment]
Thanks, I'll check it out.

Best，
Yan

Petr Vorel ***@***.***> 于2022年11月24日周四 16:40写道：
