### ISSUE TITLE
html output not generated

### ISSUE THREAD

**Issue by canuradhadasarichartercom** [linux-test-project/ltp#999]
Tried to follow all the instructions as in README of this repo but yet html file doesn't get generated.

**Comment by pevik** [comment]
Talking about metadata html, or which html?

You need to install `asciidoc` or `asciidoctor`.
You can use package names specifies in scripts in https://github.com/linux-test-project/ltp/tree/master/ci

You can also learn from my ongoing work of automatic html build, where I use `asciidoctor`
https://github.com/pevik/ltp/blob/docparse-mirror.devel/.github/workflows/metadata-mirror.yml#L76
```
apt install -y --no-install-recommends asciidoctor autoconf automake libjson-perl libwww-perl make
make autotools && ./configure --with-metadata-generator=asciidoctor
cd metadata/
make -j$(nproc)
ls ../docparse/*.html
../docparse/metadata.html
```

**Comment by pevik** [comment]
No response, closing.
